export interface FormField { key:string; label:string; type?:'text'|'number'|'decimal'|'datetime-local'|'date'|'textarea'|'intervals'|'select'|'checkbox'; required?:boolean; source?:string; options?:[string,string][]; default?:string|number|boolean; help?:string }
export interface ActionForm { title:string; permission:string; path:string; fields:FormField[]; notice?:string; target?:boolean; method?:string }
const field=(key:string,label:string,type:FormField['type']='text',extra:Partial<FormField>={}):FormField=>({key,label,type,required:true,...extra})
const ref=(key:string,label:string,source:string,required=true)=>field(key,label,'select',{source,required})
const currency=field('currency','币种','select',{options:[['CNY','CNY 人民币'],['HKD','HKD 港币'],['USD','USD 美元'],['EUR','EUR 欧元']]})
const evidence=field('evidence','依据与说明','textarea')
const reason=field('reason','操作理由','textarea')
export const forms:Record<string,ActionForm>={
  machine:{title:'配置机台',permission:'master_write',path:'machines',fields:[field('code','机台编号'),field('name','机台名称'),field('model','品牌 / 型号','text',{required:false}),field('width_mm','有效幅宽（mm）','decimal',{required:false}),field('height_mm','有效幅高（mm）','decimal',{required:false}),field('ink_family','兼容墨材型号','text',{default:'unknown'}),field('capability_evidence','能力确认依据','textarea',{required:false})],notice:'未知能力不能用于自动排程；这里不会建立真实设备连接。'},
  fixture:{title:'新建治具版本',permission:'master_write',path:'fixtures',fields:[field('code','治具编号'),field('revision','版本','number',{default:1}),field('slots','槽位数','number'),field('width_mm','幅宽（mm）','decimal'),field('height_mm','幅高（mm）','decimal')]},
  product:{title:'新建产品',permission:'master_write',path:'products',fields:[field('code','稳定产品编号'),field('name','产品名称'),field('customer','客户名称','text',{required:false})]},
  process:{title:'新建工艺版本',permission:'master_write',path:'process-versions',fields:[ref('product_id','产品','products'),ref('fixture_id','治具版本','fixtures'),field('revision','版本','number',{default:1}),field('name','工艺名称'),field('ink_family','兼容墨材型号'),field('pieces_per_board','每板件数','number'),field('cycle_seconds','单板单遍节拍（秒）','decimal',{required:false}),field('width_mm','布局宽度（mm）','decimal'),field('height_mm','布局高度（mm）','decimal'),field('faces','计价面数','number',{default:1}),field('passes','实际工序遍数','number',{default:1})],notice:'新版本不会改变已有任务。首件确认绑定具体工艺及文件版本。'},
  fileConfirm:{title:'确认文件与首件',permission:'master_write',path:'file-versions/:id/confirm',target:true,fields:[field('first_article_evidence','首件结论或稳定重复工艺豁免依据','textarea')]},
  demand:{title:'新建生产需求',permission:'plan_write',path:'demands',fields:[field('code','需求编号'),ref('product_id','产品','products'),field('quantity','目标件数（pcs）','number'),field('due_at','交期（华康 A 时间）','datetime-local'),field('priority','优先级 0–10','number',{default:0})]},
  task:{title:'新建打印任务',permission:'plan_write',path:'tasks',fields:[field('code','任务编号'),ref('demand_id','来源需求','demands'),ref('process_version_id','工艺版本','process-versions'),ref('file_version_id','已确认生产文件','file-versions'),field('quantity','本任务件数（pcs）','number'),ref('price_policy_id','价格版本','pricing-policies',false),ref('wage_policy_id','工资规则','wage-policies',false)],notice:'任务保存时冻结工艺、文件、价格与工资规则。缺少核算规则的任务会标记为资料不完整。'},
  shift:{title:'新建班次',permission:'shift_write',path:'shifts',fields:[field('name','班次名称'),field('business_date','业务日期','date'),field('start_at','开始时间','datetime-local'),field('end_at','结束时间','datetime-local')]},
  participation:{title:'登记参与工时',permission:'shift_write',path:'participations',fields:[ref('shift_id','班次','shifts'),ref('task_id','任务','tasks'),field('employee_id','稳定员工编号'),field('employee_name','员工姓名'),field('start_at','实际开始','datetime-local'),field('end_at','实际结束','datetime-local'),field('role_coefficient','角色系数','decimal',{default:'1'})],notice:'同一员工跨机台的重叠时间由服务器分摊，不会重复累计整段工时。'},
  quality:{title:'处置待检数量',permission:'quality_write',path:'quality/resolve',fields:[ref('batch_id','实体批次','batches'),ref('shift_id','处置班次','shifts'),field('quantity','处置件数','number'),field('disposition','品质结论','select',{options:[['good','良品'],['rework','返工'],['scrap','报废']]}),evidence]},
  rework:{title:'建立返工任务',permission:'quality_write',path:'rework-tasks',fields:[ref('batch_id','原实体批次','batches'),field('code','返工任务编号'),field('quantity','返工件数','number')],notice:'返工消耗原批次的返工数量，保留来源，不重复增加实体产量。'},
  handover:{title:'发起良品交接',permission:'handover_write',path:'handovers',fields:[ref('batch_id','良品批次','batches'),field('target','收方 / 下工序'),field('receiver_id','指定收方账号 ID','text',{required:false,help:'留空表示本人负责现场签收，并会记录当前账号。'}),field('quantity','交接件数','number'),field('business_date','业务日期','date')]},
  receive:{title:'签收交接',permission:'handover_write',path:'handovers/:id/receive',target:true,fields:[field('quantity','本次签收件数','number'),field('business_date','业务日期','date'),evidence]},
  reject:{title:'拒收并释放预留',permission:'handover_write',path:'handovers/:id/reject',target:true,fields:[field('quantity','本次拒收件数','number'),field('business_date','业务日期','date'),evidence]},
  return:{title:'退回已签收良品',permission:'handover_write',path:'handovers/:id/return',target:true,fields:[field('quantity','退回件数','number'),field('business_date','业务日期','date'),evidence]},
  closeShift:{title:'核对并结班',permission:'shift_write',path:'shifts/:id/close',target:true,fields:[field('wip_handover','在制交班说明','textarea',{required:false})],notice:'有未匹配运行、待检或缺参与工时时，需先处理，或填写明确的在制交班说明。结班不会停止现场打印。'},
  reopenShift:{title:'重开班次',permission:'shift_write',path:'shifts/:id/reopen',target:true,fields:[reason]},
  advance:{title:'进入下一工序',permission:'production_write',path:'batches/:id/advance-pass',target:true,fields:[reason],notice:'本遍待加工、返工与待检需先结清。中间合格件进入下一遍，不增加实体数量。'},
  reverse:{title:'冲销已确认报产',permission:'production_write',path:'production/:id/reverse',target:true,fields:[reason],notice:'保留原始记录，新增反向凭证；已有工资或交接依赖时会阻止冲销。'},
  inkSku:{title:'新建墨水 SKU',permission:'inventory_write',path:'ink/skus',fields:[field('code','SKU 编号'),field('supplier','供应商'),field('model','产品型号'),field('ink_family','软 / 硬墨兼容型号'),field('color','颜色 / 通道'),field('capacity_ml','包装容量（ml）','decimal')]},
  ink:{title:'登记墨水流水',permission:'inventory_write',path:'ink/movements',fields:[ref('sku_id','墨水 SKU','ink/skus'),field('lot','批号','text',{default:'unbatched'}),field('location','当前库位'),field('kind','业务类型','select',{options:[['receipt','入库'],['transfer','库位转移'],['consume','实际耗用'],['return','耗用退回'],['reverse','完整冲销'],['stocktake_in','盘盈'],['stocktake_out','盘亏']]}),field('quantity_ml','数量（ml）','decimal'),field('cost_value','入库总成本','decimal',{required:false,help:'入库/盘盈必填，允许有依据的 0；耗用由服务器取原成本。'}),currency,field('target_location','转移目标库位','text',{required:false}),ref('task_id','关联任务','tasks',false),field('reversal_of','退回 / 冲销原流水 ID','text',{required:false}),field('business_date','业务日期','date'),evidence]},
  price:{title:'新建价格政策',permission:'cost_write',path:'pricing-policies',fields:[ref('product_id','产品','products'),field('basis','计价口径','select',{options:[['piece','按最终良品件数'],['area','按最终良品面积']]}),field('rate','单位价格（保留六位小数）','decimal'),currency,field('rectangle_area','使用明确的矩形面积计价','checkbox',{required:false}),field('measured_area_m2','每件实测面积（m²）','decimal',{required:false}),evidence]},
  wagePolicy:{title:'新建工资规则',permission:'payroll_write',path:'wage-policies',fields:[field('name','规则名称'),field('basis','工资口径','select',{options:[['piece','计件'],['hour','计时'],['base_bonus','计时基础 + 计件奖金']]}),field('rate','基础单价','decimal'),field('bonus_rate','计件奖金单价','decimal',{default:'0'}),currency,evidence]},
  wage:{title:'核准本班任务工资',permission:'payroll_write',path:'wages/confirm',fields:[ref('task_id','任务','tasks'),ref('shift_id','班次','shifts')],notice:'核准后冻结本任务本班的计薪依据，后续核数将被阻止。请先完成品质核对。'},
  expense:{title:'登记费用',permission:'cost_write',path:'expenses',fields:[field('category','费用性质','select',{options:[['direct','任务直接费用'],['department','部门费用'],['investment','投资（不计当期经营成本）']]}),ref('task_id','关联任务','tasks',false),field('cost_amount','总金额','decimal'),currency,field('business_date','发生 / 分摊开始日期','date'),field('allocation_end','分摊结束日期','date',{required:false}),evidence]},
  closePeriod:{title:'封存月度账期',permission:'close_period',path:'periods/:id/close',target:true,fields:[reason],notice:'服务端会检查未结班、待检、运行匹配与核算缺项；通过后冻结本月快照。'},
  reopenPeriod:{title:'重开月度账期',permission:'close_period',path:'periods/:id/reopen',target:true,fields:[reason]},
  agent:{title:'创建现场代理身份',permission:'agent_manage',path:'agents',fields:[field('name','代理名称')],notice:'保存后显示一次性配对码，15 分钟有效。代理主动出站连接，不开放现场入站端口。'},
  source:{title:'绑定机台采集源',permission:'agent_manage',path:'sources',fields:[ref('agent_id','已配对代理','agents'),ref('machine_id','机台','machines'),field('source_id','本地配置中的采集源 ID'),field('adapter_type','适配器','select',{options:[['generic_csv_log','指定格式日志（待现场验证）'],['simulator','合成模拟器']]}),reason],notice:'新绑定替换机台当前主源；旧版本证据保留。没有已验证的通用打印控制能力。'},
  revoke:{title:'撤销代理凭据',permission:'agent_manage',path:'agents/:id/revoke',target:true,fields:[reason]},
}
forms.machineEdit={...forms.machine!,title:'编辑机台能力与维护',path:'machines/:id',target:true,method:'PATCH',fields:[...forms.machine!.fields,field('maintenance','机台维护中','checkbox',{required:false})]}
forms.completeAccounting={title:'补齐任务核算规则',permission:'plan_write',path:'tasks/:id/complete-accounting',target:true,fields:[ref('price_policy_id','缺失的价格版本','pricing-policies',false),ref('wage_policy_id','缺失的工资规则','wage-policies',false),reason],notice:'只允许补齐原来为空的规则。已有快照不能覆盖；已封账业务需先有理由地重开。'}
forms.runCost={title:'按拼版份额分摊运行成本',permission:'cost_write',path:'run-costs',fields:[ref('run_id','已匹配运行','runs'),field('cost_amount','本次运行成本总额','decimal'),currency,field('business_date','业务日期','date'),evidence],notice:'同一运行只登记一次成本池，按已确认份额生成各任务直接费用，总额保持一致。该成本池不得包含已经独立登记的墨料耗用或人工工资。'}
forms.lateAcknowledge={title:'核对封账后迟到证据',permission:'close_period',path:'late-events/:id/acknowledge',target:true,fields:[reason],notice:'这里只登记差异结论，不改变冻结月报或工资。如需调整业务，请先有理由地重开账期，再按原始证据补录。'}
forms.cancelHandover={title:'取消未签收预留',permission:'handover_write',path:'handovers/:id/cancel',target:true,fields:[field('business_date','取消日期','date'),reason],notice:'只释放尚未签收的数量；已签收部分需由收方执行退回。'}
forms.cancelRework={title:'取消未开工返工任务',permission:'quality_write',path:'rework-tasks/:id/cancel',target:true,fields:[reason]}
forms.shift!.fields.push(field('breaks','休息区间','intervals',{required:false,help:'每行一组完整本地时间，逗号分隔。例如 2026-09-23T12:00,2026-09-23T13:00'}))

forms.unbind={title:'解除主采集源绑定',permission:'agent_manage',path:'sources/:id/unbind',target:true,fields:[reason],notice:'保留历史证据。解绑后可把同一采集源重新绑定至正确机台。'}

forms.splitBatch={title:"拆分未加工批次",permission:"plan_write",path:"batches/:id/split",target:true,fields:[field("quantity","拆出件数（其余为另一子批）","number"),reason],notice:"仅允许首遍尚未加工批次。两个子批保留同一任务与冻结工艺，原批保留谱系且不能再加工。"}
forms.mergeBatch={title:"合并未加工批次",permission:"plan_write",path:"batches/:id/merge",target:true,fields:[ref("other_batch_id","同一任务的另一未加工批次","batches"),reason],notice:"只合并同任务、未加工首遍批次；保留两个来源，不能合并不同产品或已加工数量。"}
