<script setup lang="ts">
import { nextTick, ref, watch } from 'vue'
import { X, Plus, Trash2 } from '@lucide/vue'
import { createRandomUuid } from '@/lib/randomUuid'
import { entities, str, type Entity } from '../contracts'
import CollectionFooter from './CollectionFooter.vue'
import { useUvWorkspace, UvError } from '../workspace'
const props=defineProps<{run:Entity|null}>(),emit=defineEmits<{close:[];saved:[]}>(),w=useUvWorkspace(),dialog=ref<HTMLDialogElement>()
const rows=ref<{task_id:string;batch_id:string;pass_index:number;slots:string;full_boards:number;tail_pieces:number;share:string}[]>([])
const evidence=ref(''),error=ref(''),saving=ref(false),uncertain=ref(false)
let op=createRandomUuid(),submitted:Record<string,unknown>|null=null
function add(){rows.value.push({task_id:'',batch_id:'',pass_index:1,slots:'',full_boards:0,tail_pieces:0,share:rows.value.length?'0':'1'})}
watch(()=>props.run,async value=>{if(!value){dialog.value?.close();return}rows.value=[];add();error.value='';evidence.value='';uncertain.value=false;submitted=null;op=createRandomUuid();await nextTick();dialog.value?.showModal();try{await w.load(['tasks','batches'])}catch(cause){error.value=w.explain(cause)}})
watch(w.contextVersion,()=>emit('close'))
async function submit(){if(!props.run)return;saving.value=true;error.value='';try{if(!uncertain.value)submitted={expected_version:props.run.version,evidence:evidence.value,allocations:rows.value.map(row=>({...row,slots:row.slots.split(/[,，\s]+/).filter(Boolean).map(Number)}))};await w.command('runs/'+props.run.id+'/match',submitted!,op);emit('saved')}catch(cause){error.value=w.explain(cause);uncertain.value=!(cause instanceof UvError)||cause.status>=500;if(!uncertain.value)op=createRandomUuid()}finally{saving.value=false}}
</script>
<template><dialog ref="dialog" class="uv-dialog uv-wide-dialog" @cancel.prevent="!saving&&emit('close')"><form @submit.prevent="submit"><header><div><span class="uv-context">运行证据 · {{str(run??undefined,'native_job_id')}}</span><h2>核对任务归属</h2></div><button type="button" class="uv-icon-button" aria-label="关闭运行核对" :disabled="saving" @click="emit('close')"><X :size="20"/></button></header><div class="uv-dialog-body"><p class="uv-notice">拼版分配按遍次检查槽位互斥，份额总和必须为 1。板数 × 槽位数 + 尾板件数只形成加工参考，不自动确认良品。</p><CollectionFooter name="tasks"/><fieldset :disabled="saving||uncertain" class="uv-match-fields"><section v-for="(row,index) in rows" :key="index" class="uv-allocation-row"><div class="uv-form-grid"><label><span>任务</span><select v-model="row.task_id" required @change="row.batch_id='' "><option value="">请选择任务</option><option v-for="task in w.items('tasks')" :key="task.id" :value="task.id">{{str(task,'code')}}</option></select></label><label><span>实体批次</span><select v-model="row.batch_id" required><option value="">请选择批次</option><option v-for="batch in entities(w.items('tasks').find(task=>task.id===row.task_id)?.batches)" :key="batch.id" :value="batch.id">{{batch.id.slice(0,8)}} · {{batch.quantity}} pcs</option></select></label><label><span>工序遍次</span><input v-model.number="row.pass_index" type="number" min="1" required/></label><label><span>槽位编号（逗号分隔）</span><input v-model="row.slots" required placeholder="1,2,3"/></label><label><span>完整板数</span><input v-model.number="row.full_boards" type="number" min="0" required/></label><label><span>尾板件数（pcs）</span><input v-model.number="row.tail_pieces" type="number" min="0" required/></label><label><span>分摊份额（0–1）</span><input v-model="row.share" inputmode="decimal" required/></label></div><button v-if="rows.length>1" type="button" class="uv-link" @click="rows.splice(index,1)"><Trash2 :size="14"/>删除此分配</button></section><button type="button" class="uv-button" @click="add"><Plus :size="15"/>追加拼版任务</button><label class="uv-block-label">核对依据<textarea v-model="evidence" required rows="3"/></label></fieldset><p v-if="error" class="uv-error" role="alert">{{error}}</p><p v-if="uncertain" class="uv-notice">请求结果不确定。已锁定输入，重试沿用原操作编号。</p></div><footer><button type="button" class="uv-button" :disabled="saving" @click="emit('close')">取消</button><button class="uv-button primary" :disabled="saving||!w.can('production_write')">{{saving?'保存中…':uncertain?'重试同一操作':'确认归属'}}</button></footer></form></dialog></template>
