from enum import StrEnum

DOCUMENT_CONTRACT_VERSION = "1"
MAX_DOCUMENT_PAGES = 200
MAX_BLOCK_TEXT_CHARS = 50_000


class DocumentExtractionRoute(StrEnum):
    NATIVE = "NATIVE"
    LOCAL_OCR = "LOCAL_OCR"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class DocumentExtractionSource(StrEnum):
    NATIVE_TEXT = "NATIVE_TEXT"
    LOCAL_OCR = "LOCAL_OCR"
    USER_REVIEW = "USER_REVIEW"


class DocumentKind(StrEnum):
    GENERAL = "GENERAL"
    ORDER_TABLE = "ORDER_TABLE"
    FORM = "FORM"
    REPORT = "REPORT"
    CONTRACT = "CONTRACT"


class DocumentBlockKind(StrEnum):
    TITLE = "TITLE"
    PARAGRAPH = "PARAGRAPH"
    LIST_ITEM = "LIST_ITEM"
    TABLE = "TABLE"
    IMAGE = "IMAGE"
    HEADER = "HEADER"
    FOOTER = "FOOTER"


class DocumentCellValueType(StrEnum):
    TEXT = "TEXT"
    IDENTIFIER = "IDENTIFIER"
    INTEGER = "INTEGER"
    DECIMAL = "DECIMAL"
    DATE = "DATE"
    BOOLEAN = "BOOLEAN"
    UNKNOWN = "UNKNOWN"


class DocumentReviewIssueKind(StrEnum):
    LOW_CONFIDENCE_BLOCK = "LOW_CONFIDENCE_BLOCK"
    LOW_CONFIDENCE_CELL = "LOW_CONFIDENCE_CELL"
    LEADING_ZERO_IDENTIFIER = "LEADING_ZERO_IDENTIFIER"
    AMBIGUOUS_READING_ORDER = "AMBIGUOUS_READING_ORDER"
    UNSUPPORTED_CONTENT = "UNSUPPORTED_CONTENT"
    OUTPUT_VALIDATION_FAILED = "OUTPUT_VALIDATION_FAILED"
    TRANSLATION_UNIT_MISMATCH = "TRANSLATION_UNIT_MISMATCH"
    PROTECTED_TOKEN_MISSING = "PROTECTED_TOKEN_MISSING"
    TEXT_OVERFLOW = "TEXT_OVERFLOW"
    FONT_MISSING = "FONT_MISSING"
