import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(join(process.cwd(), path), 'utf8')
const routerSource = read('src/router/index.ts')
const enterpriseSource = read('src/data/enterpriseMock.ts')
const viewSource = read('src/views/InternalQuoteDeskView.vue')
const workbenchSource = read('src/components/modules/sales/SalesModuleWorkbench.vue')
const homeSource = read('src/components/modules/sales/internal-quote/InternalQuoteHome.vue')
const createDialogSource = read('src/components/modules/sales/internal-quote/InternalQuoteCreateDialog.vue')
const baselineDialogSource = read('src/components/modules/sales/internal-quote/InternalQuoteBaselineDialog.vue')
const collaborationSource = read('src/components/modules/sales/internal-quote/InternalQuoteCollaboration.vue')
const activitySource = read('src/components/modules/sales/internal-quote/InternalQuoteActivityPanel.vue')
const sectionEditorSource = read('src/components/modules/sales/internal-quote/InternalQuoteSectionEditor.vue')
const sectionFormSource = read('src/components/modules/sales/internal-quote/InternalQuoteSectionForm.vue')
const summarySource = read('src/components/modules/sales/internal-quote/InternalQuoteSummary.vue')
const exportSource = read('src/components/modules/sales/internal-quote/InternalQuoteExportSummary.vue')
const apiSource = read('src/api/internalQuote.ts')
const storeSource = read('src/stores/internalQuoteDesk.ts')
const payloadSource = read('src/lib/internalQuoteSectionPayload.ts')

describe('internal quote desk frontend layout', () => {
  it('registers the new module under the business department without replacing customer conversion', () => {
    expect(enterpriseSource).toContain("id: 'internal-quote-desk'")
    expect(enterpriseSource).toContain("title: '内部报价台'")
    expect(enterpriseSource).toContain("route: '/modules/sales-business/internal-quote-desk'")
    expect(enterpriseSource).toContain('业务部与工程部建单')
    expect(enterpriseSource).toContain("id: 'customer-price-conversion'")
    expect(enterpriseSource).toContain("title: '客价转换台'")
    expect(viewSource).toContain('SalesModuleWorkbench')
    expect(viewSource).toContain('title="内部报价台"')
  })

  it('exposes the four staged frontend routes before the generic module route', () => {
    const internalQuoteRouteIndex = routerSource.indexOf("path: '/modules/sales-business/internal-quote-desk'")
    const genericModuleRouteIndex = routerSource.indexOf("path: '/modules/:department/:module'")
    expect(internalQuoteRouteIndex).toBeGreaterThan(-1)
    expect(internalQuoteRouteIndex).toBeLessThan(genericModuleRouteIndex)
    expect(routerSource).toContain("name: 'internal-quote-desk-home'")
    expect(routerSource).toContain("name: 'internal-quote-collaboration'")
    expect(routerSource).toContain("name: 'internal-quote-summary'")
    expect(routerSource).toContain("name: 'internal-quote-export-summary'")
    const routeSource = routerSource.slice(internalQuoteRouteIndex, genericModuleRouteIndex)
    expect(routeSource).not.toContain('requiresAuth: false')
    expect(routeSource).toContain("permissions: ['internal_quote:read']")
    expect(routeSource).toContain('enforcePermissions: true')
  })

  it('implements the confirmed creation, collaboration, browsing, release and export surfaces', () => {
    for (const text of ['新建内部报价', '复制报价', '业务部', '工程部', '搜索报价号']) expect(homeSource).toContain(text)
    for (const text of ['参与分段进度', '参考快照已冻结', '查看汇总与放行', '添加参与部门']) expect(collaborationSource).toContain(text)
    for (const text of ['业务部、工程部、装配部固定参与', '可选参与部门', '创建后仍可在协作页添加回来', '客人目标价', '没有请填无']) expect(createDialogSource).toContain(text)
    expect(homeSource).toContain('跨厂只读')
    expect(homeSource).toContain('canCreateCurrentFactory')
    expect(homeSource).toContain('canCloneQuote')
    for (const text of ['Excel 预览导入', '预览不会修改正式数据', '申请不适用', '合法重开', '分段附件']) expect(sectionEditorSource).toContain(text)
    for (const text of ['五金', '辅助材料', '五金 Excel 导入', '电子零件与子项', '注塑明细', '七类喷油工序', '搪胶成本明细', '车缝产品组', '装配与包装产品组']) expect(`${sectionFormSource}\n${sectionEditorSource}`).toContain(text)
    for (const text of ['模具资料', '模胚类型', '模具结构', '出模数', '净重 (g)', '周期 (秒)', '模具价格 RMB', '模价 HKD（自动）', '生产模具费用与分摊', '客户补贴模费 USD', '手板费总额 USD', '测试费总额 USD', 'RMB→USD 汇率', '每件分摊合计']) expect(sectionFormSource).toContain(text)
    for (const text of ['附加税与印尼运费', '减税分类', '出货场景']) expect(sectionFormSource).not.toContain(text)
    for (const text of ['纸箱计算与包装尺寸', '产品尺寸 (cm)', '彩盒尺寸 (cm)', '纸价系数（箱价基数）', '平卡纸价系数（默认同箱价）', '一箱装的个数', '平卡价 HKD（自动）']) expect(sectionFormSource).toContain(text)
    for (const text of ['包装材料', '零件名称', '规格', '用量', '单价 RMB', '单价 HKD（自动）', '成品金额 HKD（自动）', '税点 %', '备注', '吸塑', '彩盒/内卡', '利宝/说明书', '其他外购']) expect(sectionFormSource).toContain(text)
    for (const text of ['运费计算', '主纸箱 CU.FT', '柜/车容量 CUFT', '运费 + 吊柜费 HKD', '总箱数（自动）', '运费 + 吊柜 HKD/PCS（自动）', '不重复填写', '八个方案是备选参考', '客户自提', '暂时取消运费计算', 'CUFT，整数']) expect(sectionFormSource).toContain(text)
    for (const text of ['HK 40 柜', 'YT 5 吨车']) expect(payloadSource).toContain(text)
    expect(sectionFormSource).toContain('calculateSalesFreightOptions(sales.value.freight_calc, primaryCarton.value)')
    expect(sectionFormSource.indexOf('sales-packaging-materials')).toBeLessThan(sectionFormSource.indexOf('class="payload-block sales-packaging"'))
    const engineeringFormSource = sectionFormSource.slice(sectionFormSource.indexOf("props.code === 'engineering'"), sectionFormSource.indexOf("props.code === 'electronic'"))
    const hardwareFormSource = engineeringFormSource.slice(engineeringFormSource.indexOf('<strong>五金</strong>'), engineeringFormSource.indexOf('<strong>辅助材料</strong>'))
    for (const text of ['零件名称', '规格', '类别', '用量', '单价 RMB', '单价 HKD（自动）', '金额 HKD（自动）', '税点 %', '备注']) expect(hardwareFormSource).toContain(text)
    for (const text of ['配件用处', '单位', '材质', '表面处理', '供应商', '联系人/电话']) expect(hardwareFormSource).not.toContain(text)
    expect(hardwareFormSource).toContain('v-model="row.auxiliary_category"')
    expect(hardwareFormSource).toContain('模板列不作映射')
    expect(engineeringFormSource).not.toContain('<option value="packaging">包装材料</option>')
    expect(sectionEditorSource).toContain(':rmb-hkd-rate="quote.fxRmbHkd"')
    expect(sectionFormSource).toContain('const flatCardPriceFactor = computed<number>')
    expect(sectionFormSource).toContain('else delete sales.value.flat_card_price_factor')
    expect(sectionFormSource).not.toContain('engineering.cartons')
    expect(sectionFormSource).not.toContain('addEngineeringCarton')
    expect(sectionFormSource).toContain('统一填入格式：Huaxing Demo')
    expect(sectionFormSource).toContain('客户名称仅决定最终报客价的输出模板')
    for (const customerFlag of ['isBuzzBee', 'isDisney', 'isDickie', 'isCaixing']) {
      expect(sectionFormSource).toContain(`const ${customerFlag} = computed(() => false)`)
    }
    for (const text of ['协作评论', '业务操作时间线', '浏览记录', '短时间刷新会去重', '客人目标价', 'quote.targetCustomerPrice']) expect(activitySource).toContain(text)
    for (const text of ['调整汇率', '保存汇率', '保存会生成新 revision', 'updateFx']) expect(activitySource).toContain(text)
    expect(collaborationSource).toContain("internal_quote:sales_edit")
    expect(collaborationSource).toContain('updateReferenceFx')
    for (const text of ['汇总与最终放行', '分段放行状态', '最终提交人与最终放行人不得相同']) expect(summarySource).toContain(text)
    for (const text of ['内部报价导出汇总', '审批 revision 矩阵', '均由后端控制']) expect(exportSource).toContain(text)
    expect(exportSource).toContain('统一内部格式：Huaxing Demo')
    for (const text of ['调整报价基数', '初始材料价', '初始机型价', '业务主管可修改', '跟客只读查看']) {
      expect(`${homeSource}\n${baselineDialogSource}\n${storeSource}`).toContain(text)
    }
    expect(homeSource).toContain("internal_quote:baseline_read")
    expect(homeSource).toContain("internal_quote:baseline_manage")
  })

  it('matches the molding-sample interaction baseline for back navigation, motion and readable type', () => {
    expect(workbenchSource).toContain('sales-topbar-back')
    expect(workbenchSource).toContain('backTo?: string')
    expect(viewSource).toContain("label: '业务部模块'")
    expect(viewSource).toContain("label: '返回报价首页'")
    expect(viewSource).toContain("label: '返回协作页'")
    expect(viewSource).toContain("label: '返回汇总与放行'")
    expect(viewSource).toContain('name="quote-route"')
    expect(viewSource).toContain('quote-route-enter-active')
    expect(viewSource).toContain('button:not(:disabled):hover')
    expect(viewSource).toContain('transform: translateY(-2px)')
    expect(viewSource).toContain('font-size: 13px !important')
    expect(viewSource).toContain('font-size: 12px !important')
    expect(viewSource).toContain('@media (prefers-reduced-motion: reduce)')
    expect(createDialogSource).toContain('.quote-primary-button,.quote-secondary-button{font-size:13px}')
    expect(createDialogSource).toContain('.quote-segment-pills span{font-size:11px}')
    expect(createDialogSource).toContain('.quote-primary-button:hover,.quote-secondary-button:hover')
  })

  it('does not import external prototype CDNs and uses the protected internal-quote API adapter', () => {
    const combined = [viewSource, homeSource, collaborationSource, activitySource, sectionEditorSource, summarySource, exportSource].join('\n')
    expect(combined).not.toMatch(/cdn\.tailwindcss|fonts\.googleapis|material-symbols|lh3\.googleusercontent/)
    expect(apiSource).toContain("'/internal-quotes'")
    expect(apiSource).toContain("'/internal-quotes/business-owners'")
    expect(apiSource).toContain("'/internal-quotes/pricing-baseline'")
    expect(apiSource).toContain('include_sections: true')
    expect(apiSource).toContain('saveSection(quoteId')
    expect(apiSource).toContain('previewImport(quoteId')
    expect(apiSource).toContain('reviewFinal(quoteId')
    expect(apiSource).toContain('addParticipation(quoteId')
    expect(apiSource).toContain('/participation`')
    expect(storeSource).toContain('internalQuoteApi.list')
    expect(storeSource).not.toContain('createInitialInternalQuotes')
  })
})
