import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(join(process.cwd(), path), 'utf8')
const routerSource = read('src/router/index.ts')
const enterpriseSource = read('src/data/enterpriseMock.ts')
const viewSource = read('src/views/InternalQuoteDeskView.vue')
const workbenchSource = read('src/components/modules/sales/SalesModuleWorkbench.vue')
const homeSource = read('src/components/modules/sales/internal-quote/InternalQuoteHome.vue')
const comparisonDialogSource = read('src/components/modules/sales/internal-quote/InternalQuoteComparisonDialog.vue')
const createDialogSource = read('src/components/modules/sales/internal-quote/InternalQuoteCreateDialog.vue')
const baselineDialogSource = read('src/components/modules/sales/internal-quote/InternalQuoteBaselineDialog.vue')
const customerDialogSource = read('src/components/modules/sales/internal-quote/InternalQuoteCustomerDialog.vue')
const collaborationSource = read('src/components/modules/sales/internal-quote/InternalQuoteCollaboration.vue')
const activitySource = read('src/components/modules/sales/internal-quote/InternalQuoteActivityPanel.vue')
const sectionEditorSource = read('src/components/modules/sales/internal-quote/InternalQuoteSectionEditor.vue')
const sectionFormSource = read('src/components/modules/sales/internal-quote/InternalQuoteSectionForm.vue')
const summarySource = read('src/components/modules/sales/internal-quote/InternalQuoteSummary.vue')
const exportSource = read('src/components/modules/sales/internal-quote/InternalQuoteExportSummary.vue')
const apiSource = read('src/api/internalQuote.ts')
const storeSource = read('src/stores/internalQuoteDesk.ts')
const payloadSource = read('src/lib/internalQuoteSectionPayload.ts')
const comparisonSource = read('src/lib/internalQuoteComparison.ts')
const backendSummarySource = read('backend/app/services/internal_quote.py')

describe('internal quote desk frontend layout', () => {
  it('uses integer spin-button steps for quantity and usage inputs', () => {
    const quantityInputs = sectionFormSource.match(/<input\b[^>]*v-model\.number="[^"]*(?:quantity|usage)[^"]*"[^>]*>/g) ?? []

    expect(quantityInputs.length).toBeGreaterThanOrEqual(10)
    for (const input of quantityInputs) expect(input).toContain('step="1"')
  })

  it('uses one-decimal spin-button steps for loss-rate inputs', () => {
    const lossRateInputs = sectionFormSource.match(/<input\b[^>]*v-model\.number="[^"]*(?:loss_rate|LossRate)[^"]*"[^>]*>/g) ?? []

    expect(lossRateInputs).toHaveLength(4)
    for (const input of lossRateInputs) expect(input).toContain('step="0.1"')
  })

  it('registers the new module under the business department without replacing customer conversion', () => {
    expect(enterpriseSource).toContain("id: 'internal-quote-desk'")
    expect(enterpriseSource).toContain("title: '内部报价台'")
    expect(enterpriseSource).toContain("route: '/modules/sales-business/internal-quote-desk'")
    expect(enterpriseSource).toContain('业务部与工程部建单')
    expect(enterpriseSource).toContain("id: 'customer-price-conversion'")
    expect(enterpriseSource).toContain("title: '客价转换台'")
    expect(viewSource).toContain('SalesModuleWorkbench')
    expect(viewSource).toContain('title="内部报价台"')
    expect(viewSource).toContain('wide-layout')
    expect(workbenchSource).toContain('wideLayout?: boolean')
    expect(workbenchSource).toContain('--sales-workbench-max-width: 1840px')
    expect(collaborationSource).toContain('.quote-collaboration-grid{grid-template-columns:minmax(0,1fr);min-width:0;gap:0}')
    expect(collaborationSource).toContain('class="quote-head-image"')
    expect(collaborationSource).toContain('InternalQuoteProductActions')
    expect(collaborationSource).not.toContain('class="quote-product-navigation"')
    expect(collaborationSource.match(/<InternalQuoteProductActions/g)).toHaveLength(1)
  })

  it('exposes the four staged frontend routes before the generic module route', () => {
    const internalQuoteRouteIndex = routerSource.indexOf("path: '/modules/sales-business/internal-quote-desk'")
    const genericModuleRouteIndex = routerSource.indexOf("path: '/modules/:department/:module'")
    expect(internalQuoteRouteIndex).toBeGreaterThan(-1)
    expect(internalQuoteRouteIndex).toBeLessThan(genericModuleRouteIndex)
    expect(routerSource).toContain("name: 'internal-quote-desk-home'")
    expect(routerSource).toContain("name: 'internal-quote-collaboration'")
    expect(routerSource).toContain("name: 'internal-quote-summary'")
    expect(routerSource).toContain("name: 'internal-quote-export-summary'")
    const routeSource = routerSource.slice(internalQuoteRouteIndex, genericModuleRouteIndex)
    expect(routeSource).not.toContain('requiresAuth: false')
    expect(routeSource).toContain("permissions: ['internal_quote:read']")
    expect(routeSource).toContain('enforcePermissions: true')
  })

  it('implements the confirmed creation, collaboration, browsing, release and export surfaces', () => {
    for (const text of ['新建内部报价', '复制报价', '业务部', '工程部', '搜索报价号']) expect(homeSource).toContain(text)
    for (const text of ['报价经营概览', '总报价数', '进行中报价数', '已完成报价数', '已取消报价数', '本周统计', '本月统计', '本年统计', '报价状态占比', '各客户报价数量', '客户报价速度对比', '建单至最终放行的平均时长', '横向点图']) expect(homeSource).toContain(text)
    expect(homeSource).not.toContain('进行中报价进度')
    expect(homeSource).toContain('<th>部门完成进度</th>')
    expect(homeSource).toContain('statusDonutStyle')
    expect(homeSource).toContain('customerBarWidth')
    expect(homeSource).toContain('speedDotPosition')
    expect(homeSource).toContain('quoteStore.loadDashboard')
    for (const text of ['参与分段进度', '参考快照已冻结', '添加参与部门']) expect(collaborationSource).toContain(text)
    for (const text of ['整单审核人', '部门填写进度', '提交整单审核', '整单审核通过', '退回整单', '整单连续报价内容', 'quote-continuous-sections', 'scrollIntoView', 'whole-quote-review']) expect(collaborationSource).toContain(text)
    for (const text of ['baselineDifferentSections', 'baselineDifferenceLabel', '与基准款不同', '全部内容沿用基准款', ':different-section-codes="baselineDifferentSections"', ':differs-from-baseline="baselineDifferentSections.includes(section.code)"']) expect(collaborationSource).toContain(text)
    expect(sectionEditorSource).toContain('class="baseline-difference"')
    for (const text of ['整单操作', '查看汇总与输出', 'saveWholeProductDraft', 'quote-whole-product-actions', 'quote-whole-product-workflow']) expect(collaborationSource).toContain(text)
    expect(collaborationSource).toContain("<Save />{{ wholeProductSaving ? '保存中…' : '保存' }}")
    expect(collaborationSource).toContain("{{ quoteStore.submitting ? '提交中…' : '提交审核' }}")
    for (const text of ['rememberInternalQuoteProductScroll', 'consumeInternalQuoteProductScroll', 'loadSwitchedProduct', "window.scrollTo({ top: scrollTop, behavior: 'auto' })"]) expect(collaborationSource).toContain(text)
    expect(sectionEditorSource).not.toContain('section.formulaHint')
    expect(sectionEditorSource).toContain('<footer v-if="!wholeQuoteReview" class="quote-editor-actions">')
    expect(sectionEditorSource).toContain('saveWholeQuoteDraft')
    for (const text of ['页面导航', '悬停部门查看填写状态', '报价概览', '整单操作', '未填写', '填写中', '已完成', '需处理']) expect(read('src/components/modules/sales/internal-quote/InternalQuoteSectionRail.vue')).toContain(text)
    expect(storeSource).toContain("workflow_mode: 'whole_quote_review'")
    for (const text of ['removeParticipation', ':can-remove="canRemoveActive"', '@remove="removeParticipation"', '已不再计入进度、成本汇总和最终放行']) expect(collaborationSource).toContain(text)
    for (const text of ['quote-edge-panel-left', 'quote-edge-panel-right', 'quote-edge-handle', '鼠标移入展开页面导航', '鼠标移入展开报价与资料侧栏', ':hover,.quote-edge-panel:focus-within', 'table-layout:fixed', 'overflow:visible']) expect(collaborationSource).toContain(text)
    for (const text of ['focusEntryMode', '显示导航与侧栏', '切换为专注填报', 'class="focus-entry-float"']) expect(collaborationSource).not.toContain(text)
    for (const text of ['业务部、工程部、装配部固定参与', '可选参与部门', '创建后仍可在协作页添加回来', '客人目标价', '没有请填无']) expect(createDialogSource).toContain(text)
    expect(homeSource).toContain('跨厂只读')
    expect(homeSource).toContain('canCreateCurrentFactory')
    expect(homeSource).toContain('canCloneQuote')
    for (const text of ['每页 10 条', '内部报价分页', '上一页', '下一页', '切换页码时按需加载', 'loadQuotePage', 'quoteListTotalPages']) expect(homeSource).toContain(text)
    for (const text of ['报价对比', 'comparisonQuotes', 'comparisonLimit = 5', 'toggleQuoteComparison', '清空对比选择', 'InternalQuoteComparisonDialog']) expect(homeSource).toContain(text)
    for (const text of ['报价分段金额对比', '第一张为比较基准', 'HKD / PCS', '差距范围', '最高 − 最低', '未参与', '暂无有效计算']) expect(comparisonDialogSource).toContain(text)
    for (const text of ['deltaFromBaselineHkd', 'gapHkd', 'sectionDefinitions']) expect(comparisonSource).toContain(text)
    expect(apiSource).toContain('page_size: options.pageSize ?? 10')
    expect(apiSource).toContain('customer: options.customer')
    for (const text of ['自动识别', '预览不会修改正式数据', '申请不适用', '合法重开', '分段附件']) expect(sectionEditorSource).toContain(text)
    for (const text of ['移除该部门报价', 'v-if="props.canRemove"', '当前分段数据和未保存修改将不再生效', '历史 revision 和审计记录仍会保留', '以后可再次添加该部门']) expect(sectionEditorSource).toContain(text)
    for (const text of ['五金部分', '辅助材料/外购件部分', '五金报价单', '电子零件部分', '电子报价单', '注塑部分', '喷油/移印/UV部分', '喷油报价单', '搪胶部分', '搪胶报价单', '车缝部分', '车缝报价单', '总表部分', '组装部分', '包装部分']) expect(`${sectionFormSource}\n${sectionEditorSource}`).toContain(text)
    for (const text of ['电子快捷报价部分', '电子快捷报价零件名称', '电子快捷报价单价 RMB', '电子快捷报价税点', '电子快捷报价备注']) expect(sectionFormSource).toContain(text)
    expect(sectionEditorSource).toContain("['electronic', 'painting', 'sewing']")
    for (const title of ['五金部分', '辅助材料/外购件部分', '模具部分', '生产模具费用与分摊部分', '电子零件部分', '电子成本汇总部分', '注塑部分', '吹气部分', '喷油/移印/UV部分', '搪胶部分', '车缝部分', '总表部分', '组装部分', '包装部分', '包装材料部分', '纸箱计算与包装尺寸部分', '运费计算部分']) expect(sectionFormSource).toContain(`<strong>${title}</strong>`)
      expect(sectionFormSource).toContain('.electronicSummaryTable th,.electronicSummaryTable td')
      expect(sectionFormSource).toContain('width:14.2857%')
      expect(sectionFormSource).toContain('text-align:center;vertical-align:middle')
      expect(sectionFormSource).toContain('font-variant-numeric:tabular-nums')
      expect(sectionFormSource).toContain('function calculated(value: number) { return fixedDecimal(value, 3) }')
      expect(sectionFormSource).toContain('function measured(value: number) { return value.toFixed(4) }')
      expect(sectionEditorSource).toContain('detailAmount(line.amountHkd)')
      expect(sectionEditorSource).toContain('detailAmount(section.totalHkd)')
    for (const text of ['布料名称', '部位', '工艺', '裁片数', '用量/码', '物料价 (RMB)', '价钱 (RMB，自动)', '码点', '总价钱 (RMB，自动)', '含电绣', '<option value="丝印">丝印</option>']) expect(`${sectionFormSource}\n${payloadSource}`).toContain(text)
    for (const text of ['产品编号', '胶件名称', '材料', '料重 (g)', '日产量 24H', '用量 (PC)', '单价 HKD', '总价 HKD（自动）']) expect(`${sectionFormSource}\n${payloadSource}`).toContain(text)
    for (const text of ['图片 / 附件引用', '名称', '位置', '夹模', '移印', '散枪', '边模', '油色', '浸油', '抹油', '擦PP水', '报价 HKD', '备注', '二、喷油/移印/UV成本汇总']) expect(`${sectionFormSource}\n${payloadSource}`).toContain(text)
    for (const text of ['啤机报价单', '注塑部分', '模具名称', '料价 HKD/g（快照）', '原料单价 HKD（自动）', '啤价 HKD/啤（自动）', '出模数', '机型 A码', '目标数', '周期 (秒)', '重量汇总（含损耗）', '料价汇总 HKD', '啤工汇总 HKD', '吹气部分', '日产量 / 22H', '产品料价 HKD（自动）', '吹工 HKD', '披锋 HKD', '利润倍率', '出数', '模价 RMB']) expect(`${sectionFormSource}\n${sectionEditorSource}`).toContain(text)
    expect(sectionFormSource).not.toContain('<th>#</th><th>模具名称</th><th>模号</th><th>材质</th>')
    expect(sectionFormSource).not.toContain('<th>含损耗重量 (g，自动)</th>')
    expect(sectionFormSource).not.toContain('<th>机台</th><th>啤价')
    expect(sectionEditorSource).not.toContain('公式口径')
    expect(sectionEditorSource).not.toContain('公式：{{ quote.formulaVersion }}')
    expect(sectionEditorSource).toContain('class="primary-upload"')
    expect(sectionEditorSource).toContain('v-if="section.code !== \'sales\'" class="primary-upload"')
    expect(sectionEditorSource).toContain('v-if="section.code !== \'sales\'" ref="uploadInput"')
    expect(sectionEditorSource).toContain('button.primary-upload{border-color:#0f766e;background:#0f766e')
    expect(sectionEditorSource).toContain('class="template-download"')
    expect(sectionEditorSource).toContain('下载模板')
    expect(sectionEditorSource).toContain('downloadImportTemplate(props.quote.id, target.type, target.fileName)')
    for (const fileName of ['展兴模具--工模报价表.xlsx', '装工.xlsx', '五金1.xlsx', '喷油报价单.xlsx', '电子报价单.xlsx', '车缝报价单.xlsx']) {
      expect(sectionEditorSource).toContain(`fileName: '${fileName}'`)
    }
    expect(sectionEditorSource).toContain('handleUploadFile')
    expect(sectionEditorSource).toContain('detectImportPreview')
    expect(sectionEditorSource).toContain('for (const option of importOptions.value)')
    expect(sectionEditorSource).not.toContain('value="append">追加')
    expect(sectionEditorSource).not.toContain('value="replace">替换')
    expect(sectionEditorSource).toContain('重复导入不会累计金额')
    expect(sectionEditorSource).toContain('确认导入')
    expect(sectionEditorSource).toContain('deleteImportAttachment')
    expect(sectionEditorSource).toContain('删除导入附件和相关数据？')
    expect(sectionEditorSource).toContain('该文件导入生成的本部门明细、关联模具图片和计算结果会一起清除')
    expect(sectionEditorSource).toContain('未识别为本部门结构化报价单，已作为普通附件保存')
    for (const text of ['onBeforeRouteUpdate', 'onBeforeRouteLeave', 'beforeunload', '有未保存修改', '是否先保存为草稿', '不保存并切换', '继续填写', '保存草稿并切换', 'confirmUnsavedNavigation']) expect(sectionEditorSource).toContain(text)
    for (const text of ['isOwnPendingSubmission', 'canWithdraw', '返回修改', '内容没有变化，沿用 revision', '相同内容不会重复生成版本']) expect(sectionEditorSource).toContain(text)
    expect(apiSource).toContain('/withdraw')
    expect(storeSource).toContain('submittedById: section.submitted_by_id')
    expect(storeSource).toContain('withdrawSection')
    expect(backendSummarySource).toContain('def withdraw_section_submission')
    expect(backendSummarySource).toContain('next_payload_json == current_payload_json')
    expect(sectionEditorSource).not.toContain('v-for="option in importOptions"')
    expect(sectionEditorSource).not.toContain('buttonLabel')
    expect(sectionEditorSource).toContain(':calculation="section.calculation"')
    for (const text of ['模具部分', '模胚类型', '模具结构', '出模数', '净重 (g)', '周期 (秒)', '模具价格 RMB', '模价 HKD（自动）', '生产模具费用与分摊部分', '客户补贴模费 USD', '手板费总额 USD', '测试费总额 USD', 'RMB→USD 汇率', '每件分摊合计']) expect(sectionFormSource).toContain(text)
    expect(sectionFormSource).toContain('class="inline-fields seven mold-allocation-inputs"')
    expect(sectionFormSource).toContain('grid-template-columns:repeat(7,minmax(0,1fr))')
    for (const text of ['engineering.mold_allocation_enabled', '计算分摊', '暂不分摊', '暂时取消生产模具费用与分摊', '服务端分摊结果归零']) expect(sectionFormSource).toContain(text)
    for (const text of ['附加税与印尼运费', '减税分类', '出货场景']) expect(sectionFormSource).not.toContain(text)
    for (const text of ['纸箱计算与包装尺寸', '产品尺寸 (in，可不填)', '彩盒尺寸', '彩盒尺寸单位', '尺寸单位', '<option value="inch">inch</option>', '<option value="cm">cm</option>', '主纸箱系数（箱价基数）', '内纸箱系数（新增后可调）', '平卡报价系数（默认同箱价）', '新增纸箱', '一箱装的个数', '平卡价 HKD（自动）', '平卡 ${flatIndex + 1} 用量']) expect(sectionFormSource).toContain(text)
    expect(sectionFormSource.indexOf('产品尺寸 (in，可不填)')).toBeLessThan(sectionFormSource.indexOf('<strong>彩盒尺寸</strong>'))
    for (const text of ['产品长度 IN', '产品宽度 IN', '产品高度 IN', 'updateColorBoxDimension', 'updateCartonDimension', 'dimensionValueToInches']) expect(sectionFormSource).toContain(text)
    expect(sectionFormSource).toContain('.dimension-grid{display:grid;grid-template-columns:1fr;')
    for (const text of ['测试费部分', '启用测试费计算', '计算测试费', '不计测试费', '本单不计算测试费', '新增业务部测试费 MOQ', '新增 MOQ', 'sales.testing_fee_moqs', '业务部测试费用 USD', '业务部测试费 MOQ', '业务部测试费单价 USD']) expect(sectionFormSource).toContain(text)
    for (const text of ['包装材料', '零件名称', '规格', '用量', '单价 RMB', '单价 HKD（自动）', '成品金额 HKD（自动）', '税点 %', '备注', '吸塑', '彩盒/内卡', '利宝/说明书', '其他外购']) expect(sectionFormSource).toContain(text)
    for (const label of ['辅助材料/外购件原单价 HKD', '包装材料原单价 HKD']) expect(sectionFormSource).toContain(`aria-label="${label}"`)
    expect(sectionFormSource).toContain("setEngineeringMaterialUnitPrice(row, 'HKD', $event)")
    expect(sectionFormSource).toContain("setPackagingMaterialUnitPrice(row, 'HKD', $event)")
    for (const text of ['运费计算', '主纸箱 CU.FT', '柜/车容量 CUFT', '运费 HKD（报价基数）', '吊柜费 HKD（报价基数）', '总箱数（自动）', '运费 HKD/PCS（自动）', '吊柜费 HKD/PCS（自动）', '合计 HKD/PCS（自动）', '冻结的报价基数', '启用运费计算', '启用吊柜费计算', '本单不计算运费和吊柜费', 'CUFT，整数']) expect(sectionFormSource).toContain(text)
    expect(sectionFormSource).not.toContain('运费 + 吊柜费 HKD')
    for (const text of ['HK 40 柜', 'YT 5 吨车']) expect(payloadSource).toContain(text)
    expect(sectionFormSource).toContain('calculateSalesFreightOptions(sales.value.freight_calc, primaryCarton.value, referenceFreightRoutes.value)')
    expect(sectionFormSource.indexOf('sales-packaging-materials')).toBeLessThan(sectionFormSource.indexOf('class="payload-block sales-packaging"'))
    const engineeringFormSource = sectionFormSource.slice(sectionFormSource.indexOf("props.code === 'engineering'"), sectionFormSource.indexOf("props.code === 'electronic'"))
    const hardwareFormSource = engineeringFormSource.slice(engineeringFormSource.indexOf('<strong>五金部分</strong>'), engineeringFormSource.indexOf('<strong>辅助材料/外购件部分</strong>'))
    for (const text of ['零件名称', '规格', '类别', '用量', '单价 RMB', '单价 HKD（自动）', '金额 HKD（自动）', '税点 %', '备注']) expect(hardwareFormSource).toContain(text)
    for (const text of ['配件用处', '单位', '材质', '表面处理', '供应商', '联系人/电话']) expect(hardwareFormSource).not.toContain(text)
    expect(hardwareFormSource).toContain('class="fixed-field" aria-label="五金类别">五金</span>')
    expect(hardwareFormSource).toContain('class="fixed-field numeric" aria-label="五金税点">13%</span>')
    expect(hardwareFormSource).not.toContain('v-model="row.auxiliary_category"')
    expect(hardwareFormSource).not.toContain('v-model.number="row.tax_rate_percent"')
    expect(hardwareFormSource).toContain('仅导入原有对应字段')
    expect(engineeringFormSource).not.toContain('<option value="packaging">包装材料</option>')
    expect(sectionEditorSource).toContain(':rmb-hkd-rate="quote.fxRmbHkd"')
    expect(sectionFormSource).toContain('const flatCardPriceFactor = computed<number>')
    expect(sectionFormSource).toContain('const innerPaperPriceFactor = computed<number>')
    expect(sectionFormSource).toContain(':disabled="disabled || !hasInnerCarton"')
    expect(sectionFormSource).toContain('cartonPaperPriceFactor(index)')
    expect(sectionFormSource).toContain('data-testid="add-sales-carton"')
    expect(sectionFormSource).toContain(':disabled="disabled || index === 0"')
    expect(sectionFormSource).toContain('else delete sales.value.flat_card_price_factor')
    expect(sectionFormSource).not.toContain('engineering.cartons')
    expect(sectionFormSource).not.toContain('addEngineeringCarton')
    expect(sectionFormSource).toContain('统一填入格式：Huaxing Demo')
    expect(sectionFormSource).toContain('当前客户的报客模板专属字段只用于最终转换')
    expect(sectionFormSource).not.toContain('<aside class="form-block-navigator"')
    expect(sectionFormSource).not.toContain('form-block-tooltip')
    for (const text of ['block-progress', 'getInternalQuoteFormBlocks']) expect(sectionFormSource).toContain(text)
    const sectionRailSource = read('src/components/modules/sales/internal-quote/InternalQuoteSectionRail.vue')
    for (const text of ['页面导航', '报价概览', '整单操作', '悬停部门查看填写状态', 'quote-section-block-progress', 'internalQuoteBlockStatusLabels']) expect(sectionRailSource).toContain(text)
    for (const text of ['grid-template-columns:minmax(0,1fr)', 'grid-column:1;grid-row:2', 'completion now lives in page navigation']) expect(sectionFormSource).toContain(text)
    expect(sectionFormSource).toContain('content:"";pointer-events:none')
    expect(sectionFormSource).toContain('.payload-block>header>.freight-toggle-group')
    expect(sectionFormSource).toContain('position:relative;z-index:1')
    for (const text of ['backdrop-filter:blur(10px)', 'width:42px', 'border-radius:999px;background:rgb(255 255 255/.46)']) expect(sectionFormSource).not.toContain(text)
    expect(sectionFormSource).toContain('linear-gradient(105deg,#134e4a')
    expect(sectionFormSource).toContain('class="section-payload-blocks"')
    expect(sectionFormSource).not.toContain('grid-row:2/span 80')
    expect(sectionEditorSource).toContain('.quote-section-editor{position:relative;min-width:0;overflow:clip')
    expect(sectionEditorSource).not.toContain('.quote-section-editor{min-width:0;overflow:hidden')
    expect(sectionFormSource).toContain("const isBuzzBee = computed(() => normalizedCustomer.value === 'buzzbee')")
    expect(sectionFormSource).toContain("const isDisney = computed(() => ['disney', '迪士尼'].includes(normalizedCustomer.value))")
    expect(sectionFormSource).toContain("const isCaixing = computed(() => ['caixing', '彩星'].includes(normalizedCustomer.value))")
    expect(sectionFormSource).toContain("const isThreeSixty = computed(() => ['360', 'threesixty'].includes(normalizedCustomer.value))")
    for (const customerFlag of ['isDickie']) {
      expect(sectionFormSource).toContain(`const ${customerFlag} = computed(() => false)`)
    }
    for (const text of ['迪士尼采购件客户字段部分', '迪士尼模具客户字段部分', '迪士尼注塑客户参数部分', '迪士尼包装件客户字段部分', 'row.disney_unit_price_usd', 'carton.disney_unit_price_usd']) expect(sectionFormSource).toContain(text)
    for (const text of ['协作评论', '业务操作时间线', '浏览记录', '短时间刷新会去重', '客人目标价', 'quote.targetCustomerPrice']) expect(activitySource).toContain(text)
    for (const text of ['调整汇率', '保存汇率', '保存会生成新 revision', 'updateFx']) expect(activitySource).toContain(text)
    for (const text of ['保存分段码数与杂项', '选择此档', '本单采用', 'select-quote-markup-tier-', 'save-quote-markup', 'live-quote-markup-moq-', 'live-quote-misc', 'live-quote-settlement', '报表找数系数', 'updateMarkup', 'MOQ 区间必须由小到大排列', '码数最多保留 2 位小数', '杂项率最多保留 2 位小数']) expect(activitySource).toContain(text)
    for (const text of ['updateQuoteMarkup', 'saveSalesMarkup', 'salesSettlementDivisorForMiscRatio', '在协作侧栏保存分段 MOQ 码数与杂项系数', '请先重开业务部分段']) expect(`${collaborationSource}\n${sectionEditorSource}`).toContain(text)
    expect(collaborationSource).toContain('divisor: salesSettlementDivisorForMiscRatio(miscRatio)')
    expect(sectionEditorSource).toContain('divisor: salesSettlementDivisorForMiscRatio(miscRatio)')
    for (const text of ['markup_x?: number', 'markup_tiers?: SalesMarkupTier[]', 'selected_markup_moq?: number', 'misc_ratio?: number', 'divisor?: number']) expect(payloadSource).toContain(text)
    for (const permission of ['internal_quote:sales_edit', 'internal_quote:engineering_edit']) expect(collaborationSource).toContain(permission)
    expect(collaborationSource).toContain('updateReferenceFx')
    for (const text of ['汇总与最终放行', '权威成本分布', '部门金额分布', '成本项目分布', 'departmentEntries', 'InternalQuoteInteractiveDonut', 'display-total', '悬停扇区或部门明细可联动高亮', '出货价算价', '已启用：', '减税明细 / 成本汇总', '一、出厂货价核', '二、包装 / 外购', '三、人工 &amp; 成本汇总', '四、减税明细', '减税后成本', '分段放行状态', '业务跟客最终放行', '由业务部分段的提交跟客一人确认放行', 'canResponsibleRelease', '负责跟客确认放行', 'finalRejectError', '退回中…']) expect(summarySource).toContain(text)
    for (const text of [
      "quote.value.regionCode === 'indonesia'",
      'canEditAllInternalQuoteSections',
      'data-testid="indonesia-freight-panel"',
      'data-testid="indonesia-freight-input"',
      'data-testid="save-indonesia-freight"',
      "cloneInternalQuotePayload('sales'",
      'quoteStore.saveSection(',
      'section.revision,',
      '在汇总页修改印尼价运费',
      '本项仅用于印尼价，作为直接成本单独计入，不属于杂项率金额。',
      '杂项金额 = 货价 × 杂项率；附加税独立计入；仅印尼价另计印尼运费',
    ]) expect(summarySource).toContain(text)
    expect(summarySource).toContain("item.key !== 'indonesia_freight_hkd' || isIndonesiaQuote.value")
    expect(summarySource).not.toContain('杂项包含印尼运费和附加税')
    for (const text of ['等待第二名业务主管复核', '另一名业务主管批准放行', '最终提交人与最终放行人不得相同']) expect(summarySource).not.toContain(text)
    for (const text of ['含税13%类成本', '人工类13%', '纸箱类', '含税1%', '搪胶类3%', '车发类13%', '车衣物料退税（仅华康C/D）', '吸塑类6%', '运费类9%', '含税13%类']) expect(backendSummarySource).toContain(text)
    expect(summarySource).toContain('v-if="shippingPricing.enabled"')
    expect(summarySource).toContain('金额、税率、减税额及减税后成本均由系统统一计算')
    expect(summarySource).not.toContain('减税额 = 金额 × 税率')
    expect(summarySource).not.toContain('<th>项目</th>')
    for (const text of ['rr2T1Fields', 'rr2T2Fields', 'rr2T3Fields', 'rr2T4Fields', "['glue_bag', '胶袋']", "['misc', '杂项']", "['total_cost', '总成本'", "['tax13b', '含税13%类'"]) expect(storeSource).toContain(text)
    expect(summarySource).not.toContain('责任分段成本汇总')
    for (const text of ['报价与工程资料导出汇总', '审批 revision 矩阵', '内部报价继续受 SHA-256']) expect(exportSource).toContain(text)
    expect(exportSource).toContain('统一内部格式：Huaxing Demo')
    for (const text of ['批次产品正式输出切换', '逐款独立输出', '整批共用一次审核结果', 'batchOutputReadyCount', 'switchOutputProduct', 'quoteStore.loadBatchProducts']) expect(exportSource).toContain(text)
    for (const text of ['调整报价基数', '初始材料价', '初始机型价', '运费与吊柜费 HKD 默认值', '吊柜费 HKD', '业务主管可修改', '跟客只读查看']) {
      expect(`${homeSource}\n${baselineDialogSource}\n${storeSource}`).toContain(text)
    }
    expect(homeSource).toContain("internal_quote:baseline_read")
    expect(homeSource).toContain("internal_quote:baseline_manage")
    for (const text of ['客户资料', '仅本厂业务主管或工程主管可新增、修改和删除', '删除只会从后续建单选项中移除']) {
      expect(`${homeSource}\n${customerDialogSource}`).toContain(text)
    }
    expect(homeSource).toContain("internal_quote:customer_manage")
    expect(createDialogSource).toContain('v-for="customer in customerOptions"')
  })

  it('matches the molding-sample interaction baseline for back navigation, motion and readable type', () => {
    expect(workbenchSource).toContain('sales-topbar-back')
    expect(workbenchSource).toContain('backTo?: string')
    expect(viewSource).toContain("label: '业务部模块'")
    expect(viewSource).toContain("label: '返回报价首页'")
    expect(viewSource).toContain("label: '返回协作页'")
    expect(viewSource).toContain("label: '返回汇总与放行'")
    expect(viewSource).toContain('name="quote-route"')
    expect(viewSource).toContain('quote-route-enter-active')
    expect(viewSource).toContain('button:not(:disabled):hover')
    expect(viewSource).toContain('transform: translateY(-2px)')
    expect(viewSource).toContain('font-size: 13px !important')
    expect(viewSource).toContain('font-size: 12px !important')
    expect(viewSource).toContain('@media (prefers-reduced-motion: reduce)')
    expect(createDialogSource).toContain('.quote-primary-button,.quote-secondary-button{font-size:13px}')
    expect(createDialogSource).toContain('.quote-segment-pills span{font-size:11px}')
    expect(createDialogSource).toContain('.quote-primary-button:hover,.quote-secondary-button:hover')
  })

  it('keeps the active factory through sales and every internal-quote navigation level', () => {
    expect(workbenchSource).toMatch(/const scopedBackTo = computed\(\(\) => props\.backTo\.startsWith\('\/'\)[\s\S]{0,100}getFactoryScopedRoute\(props\.backTo, activeFactory\.value\.id\)/)
    expect(workbenchSource).toMatch(/const salesDepartmentRoute = computed\(\(\) => getFactoryScopedRoute\([\s\S]{0,80}'\/modules\/sales-business',[\s\S]{0,60}activeFactory\.value\.id/)
    expect(workbenchSource).toContain(':to="scopedBackTo"')
    expect(workbenchSource).toContain(':to="salesDepartmentRoute"')

    expect(homeSource).toMatch(/function getQuoteRoute\(path: string, factoryId: string = activeFactory\.value\.id\)[\s\S]{0,100}getFactoryScopedRoute\(path, factoryId as FactoryContextId\)/)
    expect(homeSource).toMatch(/router\.push\(getQuoteRoute\([\s\S]{0,120}`\/modules\/sales-business\/internal-quote-desk\/\$\{quote\.id\}\/collaboration`,[\s\S]{0,80}quote\.factoryId/)
    expect(homeSource).toMatch(/router\.push\(getQuoteRoute\(`\/modules\/sales-business\/internal-quote-desk\/\$\{quote\.id\}\/\$\{target\}`\)\)/)

    for (const detailSource of [collaborationSource, summarySource, exportSource]) {
      expect(detailSource).toMatch(/const getQuoteRoute = \(path: string\) => getFactoryScopedRoute\([\s\S]{0,100}isFactoryContextId\(quote\.value\.factoryId\) \? quote\.value\.factoryId : 'huaxing'/)
      expect(detailSource).not.toMatch(/<RouterLink[^>]+to="\/modules\/sales-business\/internal-quote-desk/)
    }

    expect(collaborationSource).toContain(':to="getQuoteRoute(\'/modules/sales-business/internal-quote-desk\')"')
    expect(collaborationSource).toContain(':to="getQuoteRoute(`/modules/sales-business/internal-quote-desk/${quote.id}/summary`)"')
    expect(summarySource).toContain(':to="getQuoteRoute(`/modules/sales-business/internal-quote-desk/${quote.id}/collaboration`)"')
    expect(summarySource).toContain('router.push(getQuoteRoute(`/modules/sales-business/internal-quote-desk/${quote.value.id}/export`))')
    expect(exportSource).toContain(':to="getQuoteRoute(`/modules/sales-business/internal-quote-desk/${quote.id}/summary`)"')
  })

  it('does not import external prototype CDNs and uses the protected internal-quote API adapter', () => {
    const combined = [viewSource, homeSource, collaborationSource, activitySource, sectionEditorSource, summarySource, exportSource].join('\n')
    expect(combined).not.toMatch(/cdn\.tailwindcss|fonts\.googleapis|material-symbols|lh3\.googleusercontent/)
    expect(apiSource).toContain("'/internal-quotes'")
    expect(apiSource).toContain("'/internal-quotes/business-owners'")
    expect(apiSource).toContain("'/internal-quotes/dashboard'")
    expect(apiSource).toContain("'/internal-quotes/pricing-baseline'")
    expect(apiSource).toContain("'/internal-quotes/customers'")
    expect(apiSource).toContain('include_sections: true')
    expect(apiSource).toContain('saveSection(quoteId')
    expect(apiSource).toContain('previewImport(quoteId')
    expect(apiSource).toContain('reviewFinal(quoteId')
    expect(apiSource).toContain('addParticipation(quoteId')
    expect(apiSource).toContain('/participation`')
    expect(storeSource).toContain('internalQuoteApi.list')
    expect(storeSource).toContain('internalQuoteApi.getDashboard')
    expect(storeSource).not.toContain('createInitialInternalQuotes')
  })

  it('exports internal quote and engineering data as two independent workbooks', () => {
    expect(exportSource).toContain('生成内部报价 XLSX')
    expect(exportSource).toContain('生成工程资料 XLSX')
    expect(exportSource).toContain('confirmEngineeringExport')
    expect(exportSource).toContain('quoteStore.downloadEngineeringWorkbook')
    expect(exportSource).toContain("const engineeringWorkbookSheets = ['排摸表', '外购清单']")
    expect(exportSource).toContain('工程资料单独按原模板即时生成，不进入客价转换和内部报价历史')
    expect(apiSource).toContain('/engineering-data/export')
    expect(storeSource).toContain('internalQuoteApi.downloadEngineeringWorkbook')
  })
})
