<script setup lang="ts">
import { RouterLink } from 'vue-router'
import { DialogRoot, DialogPortal, DialogOverlay, DialogContent, DialogTitle, DialogDescription } from 'reka-ui'
import { ArrowUpRight, Check, X } from '@lucide/vue'
import { Button } from '@/components/ui/button'
import { formatBusinessDateTime } from '@/lib/dateTime'
import { materialCategoryLabels, type FabricReceipt } from '@/api/fabricReceiving'

defineProps<{ record: FabricReceipt }>()
const emit = defineEmits<{ close: [] }>()
</script>

<template>
  <DialogRoot :open="true" @update:open="open => { if (!open) emit('close') }">
    <DialogPortal>
      <DialogOverlay class="receipt-detail-overlay" />
      <DialogContent class="receipt-detail-panel">
        <header class="receipt-detail-header"><div><div class="receipt-detail-title"><DialogTitle>入库单详情</DialogTitle><span><Check :size="13" aria-hidden="true" />已入库</span></div><DialogDescription>原始实收凭据 · {{ record.receipt_date }}</DialogDescription></div><button type="button" class="receipt-detail-close" aria-label="关闭入库详情" @click="emit('close')"><X :size="20" aria-hidden="true" /></button></header>
        <div class="receipt-detail-body">
          <section class="receipt-detail-material"><span>{{ materialCategoryLabels[record.material_category] }} · {{ record.facts.material_code || '未填编码' }}</span><h3>{{ record.facts.material_name || '未填物料名称' }}</h3><div><p>本次实收<strong>{{ record.quantity }} <small>{{ record.unit }}</small></strong></p><p>实物明细<strong>{{ record.batches.length }} <small>项</small></strong></p></div></section>
          <section class="receipt-detail-section"><div class="receipt-detail-section-title"><h3>实物批次明细</h3><span>保留收货时的分仓信息</span></div><div class="receipt-detail-table-scroll" tabindex="0" role="region" aria-label="入库批次明细"><table><thead><tr><th scope="col">仓位</th><th v-if="record.material_category === 'FABRIC'" scope="col">缸号 / 卷号</th><th scope="col" class="numeric">实收数量</th><th scope="col">入库时质量</th></tr></thead><tbody><tr v-for="batch in record.batches" :key="batch.id"><td><strong>{{ batch.location }}</strong></td><td v-if="record.material_category === 'FABRIC'">{{ batch.dye_lot || '—' }}<small>卷号 {{ batch.roll_no || '—' }}</small></td><td class="numeric"><strong>{{ batch.quantity }}</strong> {{ record.unit }}</td><td><span class="receipt-detail-quality">待检</span></td></tr></tbody></table></div><p class="receipt-detail-hint">这里显示入库当时的记录，后续质检与收发请在库存台账中查看。</p></section>
          <section class="receipt-detail-section"><h3>收货与采购来源</h3><dl><div><dt>采购单号</dt><dd>{{ record.facts.order_no || '—' }}</dd></div><div><dt>采购类型</dt><dd>{{ record.facts.source_category === 'SUPPLEMENT' ? '补数追货' : '正常采购' }}</dd></div><div class="wide"><dt>供应商</dt><dd>{{ record.facts.supplier || '—' }}</dd></div><div><dt>送货依据</dt><dd>{{ record.delivery_reference || '—' }}</dd></div><div><dt>记账月份</dt><dd>{{ record.accounting_month }}</dd></div><div v-if="record.facts.production_no"><dt>生产 / 放产单号</dt><dd>{{ record.facts.production_no }}</dd></div><div v-if="record.facts.contract_no"><dt>合同号</dt><dd>{{ record.facts.contract_no }}</dd></div></dl></section>
          <section v-if="record.difference_reason || record.note" class="receipt-detail-section"><h3>补充说明</h3><dl><div v-if="record.difference_reason" class="wide"><dt>超收说明</dt><dd>{{ record.difference_reason }}</dd></div><div v-if="record.note" class="wide"><dt>备注</dt><dd>{{ record.note }}</dd></div></dl></section>
          <section class="receipt-detail-section"><h3>登记与追溯</h3><dl><div><dt>登记人</dt><dd>{{ record.actor_name }}</dd></div><div><dt>登记时间</dt><dd>{{ formatBusinessDateTime(record.occurred_at) }}</dd></div><div class="wide"><dt>完整入库单号</dt><dd class="receipt-detail-code">{{ record.id }}</dd></div><div class="wide"><dt>来源明细编号</dt><dd class="receipt-detail-code">{{ record.source_line_id }}</dd></div><div><dt>来源版本</dt><dd>第 {{ record.source_revision }} 版</dd></div></dl></section>
        </div>
        <footer class="receipt-detail-footer"><RouterLink :to="{ path: '/modules/pmc-warehouse/fabric-warehouse/inventory', query: { factory: 'huakang-c', view: 'stock' } }">查看当前库存<ArrowUpRight :size="15" aria-hidden="true" /></RouterLink><Button variant="outline" @click="emit('close')">关闭详情</Button></footer>
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>

<style scoped>
.receipt-detail-overlay{position:fixed;inset:0;z-index:140;background:#0f172a59}
.receipt-detail-panel{position:fixed;inset:0 0 0 auto;z-index:150;display:flex;flex-direction:column;width:min(720px,100vw);height:100dvh;background:#fff;color:#0f172a;box-shadow:-12px 0 48px #0f172a24;outline:0}
.receipt-detail-header{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;padding:24px 28px 20px;border-bottom:1px solid #e2e8f0}.receipt-detail-title{display:flex;align-items:center;gap:12px}.receipt-detail-title h2{font-size:21px;line-height:1.4;font-weight:700}.receipt-detail-title>span{display:flex;align-items:center;gap:4px;background:#f0fdfa;border:1px solid #ccfbf1;border-radius:5px;color:#0f766e;font-size:11px;padding:2px 7px}.receipt-detail-header p{color:#64748b;font-size:12px;margin-top:7px}.receipt-detail-close{padding:6px;border-radius:6px;color:#64748b}.receipt-detail-close:hover{background:#f1f5f9}
.receipt-detail-body{flex:1;min-height:0;overflow:auto;padding:24px 28px}.receipt-detail-material{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:20px}.receipt-detail-material>span{font-size:12px;color:#64748b}.receipt-detail-material h3{font-size:18px;line-height:1.6;font-weight:600;margin-top:6px;overflow-wrap:anywhere}.receipt-detail-material>div{display:flex;gap:40px;margin-top:18px}.receipt-detail-material p{font-size:12px;color:#64748b}.receipt-detail-material strong{display:block;font-size:28px;font-weight:650;line-height:1.6;color:#0f766e;font-variant-numeric:tabular-nums}.receipt-detail-material small{font-size:13px;font-weight:400;color:#64748b}
.receipt-detail-section{padding-top:24px}.receipt-detail-section h3{font-size:14px;font-weight:650;margin-bottom:14px}.receipt-detail-section dl{display:grid;grid-template-columns:1fr 1fr;gap:16px 24px}.receipt-detail-section dl>div{min-width:0}.receipt-detail-section dt{font-size:12px;color:#94a3b8;margin-bottom:5px}.receipt-detail-section dd{font-size:13px;color:#334155;line-height:1.7;white-space:pre-wrap;overflow-wrap:anywhere}.receipt-detail-section .wide{grid-column:1/-1}.receipt-detail-section-title{display:flex;justify-content:space-between;align-items:baseline;gap:12px}.receipt-detail-section-title>span{font-size:11px;color:#94a3b8}.receipt-detail-code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}
.receipt-detail-table-scroll{overflow-x:auto;border:1px solid #e2e8f0;border-radius:8px}.receipt-detail-table-scroll table{width:100%;min-width:440px;text-align:left;border-collapse:collapse;font-size:13px}.receipt-detail-table-scroll th{padding:11px 14px;color:#64748b;background:#f8fafc;font-size:11px;font-weight:500;white-space:nowrap}.receipt-detail-table-scroll td{padding:14px;border-top:1px solid #f1f5f9;vertical-align:top;overflow-wrap:anywhere}.receipt-detail-table-scroll .numeric{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}.receipt-detail-table-scroll strong{font-weight:550}.receipt-detail-table-scroll small{display:block;font-size:11px;color:#94a3b8;margin-top:5px}.receipt-detail-quality{display:inline-block;padding:1px 7px;border-radius:4px;color:#b45309;background:#fffbeb;font-size:11px;white-space:nowrap}.receipt-detail-hint{font-size:11px;color:#94a3b8;line-height:1.8;margin-top:10px}
.receipt-detail-footer{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:16px 28px;border-top:1px solid #e2e8f0;background:#fff}.receipt-detail-footer a{display:flex;align-items:center;gap:5px;font-size:13px;color:#0f766e}
.receipt-detail-panel :is(a,button,[tabindex]):focus-visible{outline:2px solid #14b8a6;outline-offset:3px}
@media(max-width:600px){.receipt-detail-table-scroll table{min-width:0;table-layout:fixed}.receipt-detail-table-scroll th,.receipt-detail-table-scroll td{padding:10px 8px}.receipt-detail-table-scroll .numeric{white-space:normal}.receipt-detail-header{padding:20px 16px 16px}.receipt-detail-body{padding:16px}.receipt-detail-material{padding:16px}.receipt-detail-footer{padding:14px 16px}.receipt-detail-section dl{gap:14px 16px}.receipt-detail-section-title{display:block}.receipt-detail-section-title>span{display:block;margin-top:-8px;margin-bottom:12px}.receipt-detail-title h2{font-size:19px}}
</style>
