"""Bounded, disposable processes for customer-order workbook/PDF computation."""
from __future__ import annotations

import asyncio
import pickle
import sys
import tempfile
import time
from contextvars import ContextVar
from dataclasses import dataclass, field
from pathlib import Path
from threading import BoundedSemaphore, Event

from fastapi import HTTPException, Request
from app.services.customer_order_ocr import _run_worker

JOB_SECONDS = 240.0
MAX_RESULT_BYTES = 128 * 1024 * 1024
LOCK_PATH = Path(tempfile.gettempdir()) / "rr-customer-order-job.lock"
_local_slot = BoundedSemaphore(1)
OPERATIONS = frozenset({
    "_create_unified_single_preview", "_export_unified_single_schedule",
    "_create_special_batch_preview", "_export_special_batch_schedule",
    "_create_mapped_customer_preview", "_export_mapped_customer_schedule",
    "parse_workbook",
})


@dataclass
class JobBudget:
    deadline: float = field(default_factory=lambda: time.monotonic() + JOB_SECONDS)
    cancelled: Event = field(default_factory=Event)

    def check(self):
        if self.cancelled.is_set():
            raise HTTPException(499, "订单处理已取消，任务已停止。")
        if time.monotonic() >= self.deadline:
            raise HTTPException(504, "订单处理超时，任务已停止。请缩小批次或整理排期后重试。")


_budget: ContextVar[JobBudget | None] = ContextVar("customer_order_job_budget", default=None)


async def order_job_request(request: Request):
    budget = JobBudget()
    token = _budget.set(budget)

    async def monitor():
        while not budget.cancelled.is_set():
            if await request.is_disconnected():
                budget.cancelled.set()
                return
            await asyncio.sleep(0.2)

    watcher = asyncio.create_task(monitor())
    try:
        yield
    finally:
        budget.cancelled.set()
        watcher.cancel()
        try:
            await watcher
        except asyncio.CancelledError:
            pass
        _budget.reset(token)


def _execute(operation, args, kwargs, budget):
    budget.check()
    # Reject duplicate submissions before spooling another large workbook or
    # launching a child. The worker file lock also covers other API processes.
    if not _local_slot.acquire(blocking=False):
        raise HTTPException(429, "已有订单文件正在处理，请稍后重试，勿重复提交。")
    try:
        return _execute_owned(operation, args, kwargs, budget)
    finally:
        _local_slot.release()


def _execute_owned(operation, args, kwargs, budget):
    with tempfile.TemporaryDirectory(prefix="rr-order-job-") as folder:
        source, result = Path(folder) / "input.pkl", Path(folder) / "result.pkl"
        # Pickles are private IPC generated by this process, never uploaded files.
        with source.open("wb") as stream:
            pickle.dump((operation, args, kwargs), stream, protocol=5)
        code = _run_worker([
            sys.executable, "-m", "app.workers.customer_order_job", str(source),
            str(result), str(budget.deadline), str(LOCK_PATH),
        ], budget)
        budget.check()
        if not result.is_file() or result.stat().st_size > MAX_RESULT_BYTES:
            raise HTTPException(422, "订单文件处理超出资源限制或未完成，请缩小批次后重试。")
        with result.open("rb") as stream:
            payload = pickle.load(stream)
        if code or "error" in payload:
            raise HTTPException(payload.get("status", 422), payload.get("error", "订单文件处理失败，请检查文件。"))
        return payload["value"]


async def run_order_job(function, *args, db=None, **kwargs):
    operation = function.__name__
    if operation not in OPERATIONS:
        raise RuntimeError("Unsupported customer-order job")
    budget = _budget.get() or JobBudget()
    budget.check()
    if db is not None:
        # Authorization reads opened a transaction. No business writes precede
        # this call; do not hold a pooled DB connection while processing files.
        if db.new or db.dirty or db.deleted:
            raise RuntimeError("Cannot start a file job with pending database writes")
        db.rollback()
    task = asyncio.create_task(asyncio.to_thread(_execute, operation, args, kwargs, budget))
    try:
        return await asyncio.shield(task)
    except asyncio.CancelledError:
        budget.cancelled.set()
        try:
            await asyncio.shield(task)
        except (HTTPException, asyncio.CancelledError):
            pass
        raise
