<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { Button } from '@/components/ui/button'
import { useSprayWorkspace } from '../workspace'
import { number,dateTime,utc,type Demand,type RouteVersion,type Resource,type Entity,type Stock } from '../contracts'
import WorkspaceDialog from './WorkspaceDialog.vue'
const w=useSprayWorkspace(),open=ref(false),selected=ref<Entity|null>(null),error=ref(''),busy=ref(false)
const form=reactive({line_id:'',step_id:'',resource_id:'',quantity:'',start:'',end:'',ready:'',condition:''}),allocations=reactive<Record<string,string>>({})
const lines=computed(()=>w.items<Demand>('demands').filter(d=>d.status==='confirmed').flatMap(d=>d.lines)),route=computed(()=>w.items<RouteVersion>('routes').find(r=>r.id===lines.value.find(l=>l.id===form.line_id)?.route_id))
async function show(){open.value=true;selected.value=null;error.value='';await w.load(['forecasts'])}
async function save(){busy.value=true;try{await w.command('forecasts',{line_id:form.line_id,step_id:form.step_id,resource_id:form.resource_id,quantity:form.quantity,start_at:utc(form.start),end_at:utc(form.end),expected_ready_at:utc(form.ready),condition:form.condition});await w.load(['forecasts']);form.quantity='';form.condition=''}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
async function convert(){if(!selected.value)return;busy.value=true;try{await w.command(`forecasts/${selected.value.id}/convert`,{allocations:Object.entries(allocations).filter(([,q])=>Number(q)>0).map(([stock_id,quantity])=>({stock_id,quantity}))},selected.value.version);selected.value=null;await w.load(['forecasts','tasks','stock'])}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
async function cancel(plan:Entity){const reason=await w.promptReason('取消条件计划的依据');if(!reason)return;try{await w.command(`forecasts/${plan.id}/cancel`,{business_date:w.businessDate.value,reason},plan.version);await w.load(['forecasts'])}catch(cause){error.value=w.explain(cause)}}
function choose(plan:Entity){selected.value=plan;for(const key of Object.keys(allocations))delete allocations[key]}
async function close(){if(w.dirty.value&&!(await w.confirmDiscard('放弃尚未保存的条件计划填写？')))return;open.value=false;w.dirty.value=false}
</script>
<template><Button v-if="w.can('plan')" variant="outline" @click="show">条件计划</Button><WorkspaceDialog :open="open" title="条件计划 · 预计来料与转序" wide @close="close"><p class="spray-alert">只安排条件产能，不生成实际库存。兑现时必须匹配真实合格批次，并重新核对前序、准备和资源。</p><p v-if="error" class="spray-alert" role="alert">{{error}}</p><section v-for="plan in w.items('forecasts').filter(p=>p.status==='conditional')" :key="plan.id" class="spray-import-review"><div><strong>{{lines.find(l=>l.id===plan.line_id)?.item_no}} · {{number(plan.quantity)}}</strong><p>{{dateTime(plan.start_at)}} — {{dateTime(plan.end_at)}}</p><small>{{plan.condition}}</small></div><div class="spray-actions"><Button variant="outline" @click="choose(plan)">匹配实物兑现</Button><button class="spray-text-button" @click="cancel(plan)">取消计划</button></div></section><form v-if="selected" class="spray-form" @submit.prevent="convert"><h3 class="wide">匹配实际可用批次</h3><label v-for="stock in w.items<Stock>('stock').filter(s=>s.line_id===selected?.line_id&&Number(s.quantity)>0)" :key="stock.id">{{stock.batch_id.slice(0,8)}} · {{number(stock.quantity)}} {{stock.unit}}<input v-model="allocations[stock.id]" inputmode="decimal" placeholder="本次分配数"/></label><div class="wide spray-actions"><Button :disabled="busy">核对并转为待开工任务</Button><Button type="button" variant="outline" @click="selected=null">返回</Button></div></form><form v-else class="spray-form" @submit.prevent="save" @input="w.dirty.value=true"><h3 class="wide">新增条件计划</h3><label>需求部位<select v-model="form.line_id" required><option value="">选择需求</option><option v-for="line in lines" :key="line.id" :value="line.id">{{line.item_no}} · {{line.part}}</option></select></label><label>预计工序<select v-model="form.step_id" required><option value="">选择工序</option><option v-for="step in route?.steps" :key="step.id" :value="step.id">{{step.name}}</option></select></label><label>资源<select v-model="form.resource_id" required><option value="">选择资源</option><option v-for="resource in w.items<Resource>('resources').filter(r=>['manual','automatic','pad'].includes(r.kind))" :key="resource.id" :value="resource.id">{{resource.name}}</option></select></label><label>预计数量<input v-model="form.quantity" inputmode="decimal" required/></label><label>预计条件齐备<input v-model="form.ready" type="datetime-local" required/></label><label>安排开始<input v-model="form.start" type="datetime-local" required/></label><label>安排结束<input v-model="form.end" type="datetime-local" required/></label><label class="wide">来料 / 前序 / 准备条件<textarea v-model="form.condition" required placeholder="明确预计齐备的条件和责任来源，不代表实际完成"/></label><Button type="submit" :disabled="busy">保存条件计划</Button></form></WorkspaceDialog></template>
