<script setup lang="ts">
import { computed, ref, watch, onMounted } from 'vue'
import { Button } from '@/components/ui/button'
import { sprayProductionApi as api, type SprayResult } from '@/api/sprayProduction'
import { useSprayWorkspace, errorText, type Entity } from '../workspace'
import VirtualList from './VirtualList.vue'
import TemplateOutput from './TemplateOutput.vue'
const props=defineProps<{source:Entity;sheets:string[];sheet:string}>()
const s=useSprayWorkspace(),kind=ref('shipment'),role=ref('source'),start=ref('2'),end=ref('200'),reason=ref(''),preview=ref<SprayResult|null>(null),busy=ref(false)
const fieldNames=[['business_date','业务日期'],['document_no','单据唯一编号'],['customer','客户 / 供应商'],['product_no','原始货号'],['part_name','实体部件 / 材料'],['operation','工序 / 活动'],['source_line','单据行 / 重复列标识'],['quantity','数量'],['unit','原单位'],['price','原单价'],['amount','原金额'],['currency','原币种'],['wage','工资'],['difference','有符号工资差额'],['regular_hours','正班小时'],['overtime_hours','加班小时']] as const
const fields=ref<Record<string,string>>({}),selected=ref<string[]>([]),accepted=ref<string[]>([]),dates=ref('')
const kinds=[['order','接单'],['receipt','来料'],['report','生产日报'],['shipment','送货'],['settlement','月结对照'],['payroll','工资'],['purchase','采购'],['material','油漆收发耗用'],['returnable','容器往来'],['expense','收支费用'],['production_summary','生产汇总'],['price','工价报价']]
function fieldSpec(value:string){return value.startsWith('=')?{value:value.slice(1),reason:reason.value}:value.endsWith('↓')?{column:value.slice(0,-1),fill_down:true}:value}
function payload(){const mapped=Object.fromEntries(Object.entries(fields.value).filter(([,v])=>v).map(([k,v])=>[k,fieldSpec(v)]));const variants=dates.value.trim()?dates.value.trim().split(/\r?\n/).map(line=>{const [column,date,ident]=line.split(/\t/);return {quantity:column,business_date:fieldSpec(date??''),source_line:{value:ident||column}}}):undefined;return {import_id:props.source.id,sheets:[{sheet:props.sheet||props.sheets[0],kind:kind.value,role:role.value,start_row:Number(start.value),end_row:Number(end.value),fields:mapped,variants}]}}
const rows=computed<Entity[]>(()=>((preview.value?.rows??[]) as Entity[]).map(r=>({...r,id:String(r.row_id)+':'+String(r.variant)})))
watch(()=>[props.source.id,props.sheet],()=>{preview.value=null;selected.value=[];accepted.value=[];const mapping=props.source.mapping as {sheets?:Array<Record<string,unknown>>}|undefined;const saved=mapping?.sheets?.find(v=>v.sheet===(props.sheet||props.sheets[0]));if(saved){kind.value=String(saved.kind);role.value=String(saved.role);start.value=String(saved.start_row);end.value=String(saved.end_row);fields.value=Object.fromEntries(Object.entries(saved.fields as Record<string,unknown>).map(([key,value])=>[key,typeof value==='object'&&value!==null?('column' in value?String((value as {column:string}).column)+'↓':'='+String((value as {value:unknown}).value)):String(value)]))}},{immediate:true})
onMounted(async()=>{await s.loadPreferences();const old=s.preferences.find(v=>v.kind==='import_draft'&&v.name===props.source.id+':'+(props.sheet||props.sheets[0]));if(old){const p=old.payload as Record<string,unknown>;kind.value=String(p.kind);role.value=String(p.role);start.value=String(p.start);end.value=String(p.end);reason.value=String(p.reason);fields.value=p.fields as Record<string,string>;dates.value=String(p.dates??'')}})
async function saveMapping(){await s.savePreference('import_draft',props.source.id+':'+(props.sheet||props.sheets[0]),{kind:kind.value,role:role.value,start:start.value,end:end.value,reason:reason.value,fields:fields.value,dates:dates.value,sheet:props.sheet})}
async function check(){busy.value=true;const scope=s.factory;try{const result=await api.historyPreview(scope,payload());if(s.factory!==scope)return;preview.value=result;selected.value=rows.value.filter(r=>['added','linked'].includes(String(r.decision))).map(r=>r.id);accepted.value=[]}catch(e){s.error=errorText(e)}finally{busy.value=false}}
async function recognize(){try{const p=await api.mappingSuggestion(s.factory,props.source.id,props.sheet||props.sheets[0]||'');kind.value=String(p.kind);role.value=String(p.role);start.value=String(p.start_row);end.value=String(p.end_row);fields.value=p.fields as Record<string,string>;s.notice=String(p.reason)+'；待映射 '+(p.pending_fields as string[]).join('、')}catch(e){s.error=errorText(e)}}
async function apply(){if(!preview.value)return;const result=await s.command('history-apply',{...payload(),fingerprint:preview.value.fingerprint,selected:selected.value,accept_differences:accepted.value,reason:reason.value});if(result){s.notice='历史事实已应用，当前库存未变化：'+JSON.stringify(result.counts);preview.value=null}}
async function exportTemplate(){try{const blob=await api.template(s.factory,props.source.id);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='历史复刻-'+String(props.source.filename);a.click();URL.revokeObjectURL(url)}catch(e){s.error=errorText(e)}}
const decisionName=(key:unknown)=>({added:'新增历史事实',linked:'关联同一业务',different:'数量 / 金额差异',pending:'待核',ignored:'忽略',comparison_only:'未匹配对照'}[String(key)]??String(key))
</script>
<template><section class="spray-panel"><h3 class="font-semibold">业务映射与跨表差异</h3><p class="spray-help">表页 {{ sheet||sheets[0] }}。填列字母（A）、固定单元格（B2）、向下沿用（A↓）或确认常量（=2020-08-11）。保留原年份、单号与单位；没有依据的字段保持待核。</p><Button variant="outline" class="mb-3" @click="recognize">按原表表头生成映射候选</Button><div class="spray-entry"><label class="spray-field">业务类型<select v-model="kind"><option v-for="k in kinds" :key="k[0]" :value="k[0]">{{ k[1] }}</option></select></label><label class="spray-field">表页角色<select v-model="role"><option value="source">业务源事实</option><option value="comparison">汇总 / 月结对照（不重复入账）</option><option value="ignore">空模板 / 忽略</option></select></label><label class="spray-field">起始行<input v-model="start" inputmode="numeric" /></label><label class="spray-field">结束行<input v-model="end" inputmode="numeric" /></label><label v-for="[key,label] in fieldNames" :key="key" class="spray-field">{{ label }}<input v-model="fields[key]" :aria-label="'映射'+label" placeholder="列 / 单元格 / =确认常量" /></label></div><details class="my-3"><summary>日期横向矩阵 / 重复日期列</summary><p class="spray-help">每行三列，以 Tab 分隔：数量列、日期单元格或 =完整日期、单据行/来源列标识。重复日期保留不同来源列，未给标识时使用列名。</p><textarea v-model="dates" rows="3" class="w-full" aria-label="日期列展开映射" /></details><label class="spray-field">执行厂区、客户及字段确认依据<input v-model="reason" /></label><div class="spray-actions mt-3"><Button :disabled="busy||s.busy||!sheet&&!sheets.length" @click="check">预览逐行映射与差异</Button><Button variant="outline" :disabled="s.busy" @click="saveMapping">保存映射草稿</Button><Button variant="outline" :disabled="!s.can('export')" @click="exportTemplate">下载原格式历史复刻</Button><Button variant="outline" :disabled="s.busy||!reason" @click="s.command('history-reverse',{import_id:source.id,reason})">有依据地撤回此次映射</Button></div>
<template v-if="preview"><p class="spray-message">新增 {{ (preview.counts as Record<string,number>).added }} · 关联 {{ (preview.counts as Record<string,number>).linked }} · 差异 {{ (preview.counts as Record<string,number>).different }} · 待核 {{ (preview.counts as Record<string,number>).pending }} · 库存影响 0</p><VirtualList :items="rows" :row-height="116" label="历史导入差异列表"><template #default="{item}"><input v-model="selected" type="checkbox" :value="item.id" :aria-label="'选择来源行 '+item.row_number" :disabled="item.decision==='pending'" /><div class="min-w-0 flex-1"><strong>{{ item.sheet }}!第 {{ item.row_number }} 行 · {{ decisionName(item.decision) }}</strong><p class="spray-help truncate">{{ item.reason || (item.values as Record<string,unknown>)?.document_no }} {{ (item.values as Record<string,unknown>)?.product_no }} {{ (item.values as Record<string,unknown>)?.amount }}</p><details v-if="item.decision==='different'"><summary>查看差异并确认</summary><pre class="spray-code">{{ item.differences }}</pre></details></div><label v-if="item.decision==='different'&&role==='source'"><input v-model="accepted" type="checkbox" :value="item.id" />明确采用更正</label></template></VirtualList><Button class="mt-3" :disabled="s.busy||!reason||!selected.length" @click="apply">应用所选 {{ selected.length }} 条历史事实 / 关联</Button><p class="spray-help">对照表只关联证据；正式库存通过独立的切换日期初确认建立。应用后撤回会留下反向记录。</p></template></section><TemplateOutput :source="source" :sheets="sheets" /></template>
