<script setup lang="ts">
import { computed,ref } from 'vue'
import { Button } from '@/components/ui/button'
import { sprayProductionApi as api } from '@/api/sprayProduction'
import { useSprayWorkspace, str, localDate, errorText, type Entity } from '../workspace'
const s=useSprayWorkspace(),facts=ref<Entity[]>([]),line=ref(''),selected=ref<string[]>([]),cutover=ref(localDate()),document=ref(''),reason=ref('')
const counts=ref([{state:'finished',quantity:''}])
const matches=computed(()=>facts.value.filter(f=>f.status==='active'&&f.product_no===s.find('lines',line.value)?.product_no&&f.part_name===s.find('lines',line.value)?.part_name))
const states=computed(()=>[{value:'finished',label:'合格待交付'},{value:'receipt-held',label:'来料待检'},{value:'scrap',label:'已盘点报废'},...(s.find('lines',line.value)?.graph_route?[{value:'route:',label:'工艺起点待投入'}]:s.items('steps').filter(v=>v.line_id===line.value).map(v=>({value:'ready:'+v.id,label:'待 '+str(v,'name')})))])
async function load(){try{const all:Entity[]=[];for(let page=1;;page++){const r=await api.collection(s.factory,'history-facts',undefined,page);all.push(...r.items);if(all.length>=r.total||!r.items.length)break}facts.value=all}catch(e){s.error=errorText(e)}}
async function confirm(){const balances:Record<string,string>={};for(const row of counts.value){if(balances[row.state]){s.error='同一盘点状态只能填写一次';return}balances[row.state]=row.quantity}const result=await s.command('opening',{line_id:line.value,history_ids:selected.value,cutover_date:cutover.value,document_no:document.value,reason:reason.value,balances});if(result){selected.value=[];await load()}}
</script>
<template><details v-if="s.can('logistics')&&s.can('cost_read')" class="spray-panel"><summary @click="load">上线切换日期初 · 用实际盘点建立库存</summary><p class="spray-help">先在历史导入关联事实，再选择对应的新工单部件与实际盘点量。历史累计来料不会自动变为现存库存，同一历史依据不能重复建立期初。</p><div class="spray-entry"><label class="spray-field">切换日期<input v-model="cutover" type="date" /></label><label class="spray-field">期初盘点凭据<input v-model="document" /></label><label class="spray-field">当前工单部件<select v-model="line" @change="selected=[]"><option value="">选择部件</option><option v-for="l in s.items('lines')" :key="l.id" :value="l.id">{{ s.lineLabel(l) }} · {{ str(s.find('orders',l.order_id),'document_no') }}</option></select></label></div><div class="spray-actions my-3"><label v-for="fact in matches" :key="fact.id"><input v-model="selected" type="checkbox" :value="fact.id" /> {{ fact.document_no }} · {{ fact.business_date }} · {{ (fact.values as Record<string,unknown>).quantity }} {{ (fact.values as Record<string,unknown>).unit }}</label></div><p v-if="line&&!matches.length" class="spray-help">没有同货号、同实体部件的已映射历史依据，请先完成映射。</p><div v-for="(row,i) in counts" :key="i" class="spray-actions my-3"><select v-model="row.state" aria-label="期初库存状态"><option v-for="state in states" :key="state.value" :value="state.value">{{ state.label }}</option></select><input v-model="row.quantity" aria-label="实际盘点数量" inputmode="decimal" /><Button v-if="counts.length>1" variant="ghost" @click="counts.splice(i,1)">移除</Button></div><Button variant="outline" @click="counts.push({state:'receipt-held',quantity:''})">增加盘点状态</Button><label class="spray-field my-3">盘点人、实物核对与切换依据<input v-model="reason" /></label><Button :disabled="s.busy||!selected.length||!reason||!document" @click="confirm">确认切换日期初库存</Button></details></template>
