<script setup lang="ts">
import { computed, ref } from 'vue'
import { Button } from '@/components/ui/button'
import { sprayProductionApi as api, type SprayResult } from '@/api/sprayProduction'
import { useSprayWorkspace, str, localDate, amount, errorText, type Entity } from '../workspace'
import EntryForm from './EntryForm.vue'
const s=useSprayWorkspace(),preview=ref<SprayResult|null>(null),history=ref<SprayResult|null>(null),period=ref(localDate().slice(0,7))
const policies=computed(()=>s.items('rates').filter(r=>r.rule_code==='employee_shift_guarantee').map(r=>({value:r.id,label:str(r,'name')+' · '+str(r,'status')})))
async function calculate(p:Record<string,string>){const scope=s.factory;try{const result=await api.payrollPreview(scope,p);if(scope===s.factory)preview.value=result}catch(e){s.error=errorText(e)}}
async function confirm(){if(preview.value){const r=await s.command('payroll-confirm',preview.value);if(r)preview.value=null}}
async function reconcile(){const scope=s.factory;try{const r=await api.reconcile(scope,period.value);if(scope===s.factory)history.value=r}catch(e){s.error=errorText(e)}}
</script>
<template><section class="spray-panel"><h3 class="font-semibold">员工班次工资 · 多任务汇总后补差</h3><p class="spray-help">将同一员工同日同班的全部任务、调机和非生产工时合并；有符号差额与实际补贴分别列出。未核工资或未正式采用的策略不能确认应付。</p><details v-if="s.can('cost_write')" class="my-3"><summary>建立班次保底策略（先暂算）</summary><EntryForm :fields="[{key:'name',label:'策略版本名称'},{key:'regular_hour_rate',label:'正班每小时保底',type:'decimal'},{key:'overtime_hour_rate',label:'加班每小时保底',type:'decimal'},{key:'currency',label:'币种',options:[{value:'CNY',label:'人民币'},{value:'HKD',label:'港币'}]},{key:'effective_date',label:'生效日期',type:'date',value:localDate()},{key:'evidence',label:'负责人及适用规则依据'}]" @submit="v=>s.command('rates',{...v,rule_code:'employee_shift_guarantee',quantity_basis:'good',parameters:{regular_hour_rate:v.regular_hour_rate,overtime_hour_rate:v.overtime_hour_rate}})" :busy="s.busy" /></details><EntryForm :fields="[{key:'business_date',label:'工资业务日期',type:'date',value:localDate()},{key:'shift',label:'工资班次',value:'白班'},{key:'policy_id',label:'班次保底策略',options:policies}]" submit-label="汇总本班员工工资" :busy="s.busy" @submit="calculate" /><section v-if="preview" class="mt-4"><div class="spray-table-wrap"><table class="spray-table"><thead><tr><th>员工</th><th>任务数</th><th>正 / 加班小时</th><th>已赚工资</th><th>保底</th><th>有符号差额</th><th>实际补贴</th><th>应付</th></tr></thead><tbody><tr v-for="e in (preview.employees as Entity[])" :key="String(e.employee)"><td>{{ e.name }}</td><td>{{ (e.tasks as Entity[]).length }}</td><td>{{ e.regular_hours }} / {{ e.overtime_hours }}</td><td>{{ amount(e.earned) }}</td><td>{{ amount(e.guarantee) }}</td><td>{{ amount(e.signed_difference) }}</td><td>{{ amount(e.subsidy) }}</td><td>{{ amount(e.payable) }} {{ preview.currency }}</td></tr></tbody></table></div><p v-for="(p,i) in (preview.pending as Entity[])" :key="i" class="spray-message">{{ p.employee }} {{ p.reason }}</p><Button class="mt-3" :disabled="!preview.confirmable||s.busy||!s.can('cost_write')" @click="confirm">确认本班应付 {{ amount(preview.amount) }} {{ preview.currency }}</Button></section><div v-for="payroll in s.items('payrolls')" :key="payroll.id" class="spray-row"><span>{{ payroll.business_date }} {{ payroll.shift }} · 已确认</span><strong>{{ amount(payroll.amount) }} {{ payroll.currency }}</strong></div></section>
<section class="spray-panel"><h3 class="font-semibold">历史表复刻 / 跨表对账</h3><div class="spray-actions my-3"><input v-model="period" type="month" aria-label="历史对账月份" /><Button variant="outline" @click="reconcile">读取历史事实与差异</Button></div><template v-if="history"><p class="spray-help">历史覆盖 {{ (history.coverage_dates as string[]).join('、') || '未映射数据' }}。按币种与原单位分别汇总；未核费用不自动归入利润。</p><div v-for="(total,i) in (history.totals as Entity[])" :key="i" class="spray-row"><span>{{ total.kind }} · {{ total.rows }} 条来源事实</span><span>{{ amount(total.quantity) }} {{ total.unit }} · {{ amount(total.amount) }} {{ total.currency }}</span></div><p v-if="!(history.differences as Entity[]).length" class="spray-help">已关联对照中没有数值差异；未映射、未关联来源仍须在导入工作区处理。</p><details v-for="(difference,i) in (history.differences as Entity[])" :key="i"><summary>{{ difference.document_no }} · 源事实与对照差异</summary><pre>{{ difference.differences }}</pre></details></template></section>
<details v-if="s.can('settlement')" class="spray-panel"><summary>已月结差额 · 新期间调整凭据</summary><EntryForm class="mt-3" :fields="[{key:'settlement_id',label:'原月结单',options:s.items('settlements').map(v=>({value:v.id,label:str(v,'customer')+' '+str(v,'period')+' '+str(v,'currency')}))},{key:'document_no',label:'调整凭据号'},{key:'business_date',label:'调整日期（后续开放月份）',type:'date',value:localDate()},{key:'amount',label:'调整金额（减少填写负数）',type:'decimal'},{key:'reason',label:'差额说明与原凭据引用'}]" @submit="v=>s.command('settlement-adjust',v)" :busy="s.busy" submit-label="登记调整凭据" /><div v-for="a in s.items('adjustments')" :key="a.id" class="spray-row"><span>{{ a.document_no }} {{ a.business_date }} · {{ a.reason }}</span><strong>{{ amount(a.amount) }}</strong></div></details></template>
