<script setup lang="ts">
import { ref, watch } from 'vue'
import { useSprayWorkspace, localDate, str } from '../workspace'
import { Button } from '@/components/ui/button'
import EntryForm from './EntryForm.vue'
const s=useSprayWorkspace(),selected=ref(''),windows=ref(localDate()+'T08:00\t'+localDate()+'T12:00\n'+localDate()+'T13:00\t'+localDate()+'T17:00'),requirements=ref<string[]>([])
const quantities=ref<Record<string,number>>({})
watch(selected,id=>{const resource=s.find('resources',id);if(!resource)return;const needs=(resource.shared_requirements||[]) as {id:string;quantity:number}[];requirements.value=needs.map(v=>v.id);quantities.value=Object.fromEntries(needs.map(v=>[v.id,v.quantity]));windows.value=(resource.calendar as {start:string;end:string}[]).map(w=>[w.start,w.end].map(v=>new Date(new Date(v).getTime()+8*3600000).toISOString().slice(0,16)).join('\t')).join('\n')})
const calendar=()=>windows.value.trim().split(/\r?\n/).map(v=>{const [a,b]=v.split('\t');return {start:a+'+08:00',end:b+'+08:00'}})
</script>
<template><section class="spray-panel"><h3 class="font-semibold">共享人员 / 工装与多班次日历</h3><p class="spray-help">同一人员在各机台共用一个身份；工装按可用套数约束。下面每行填写开始和结束时间，以 Tab 分隔，午休、跨日和请假直接体现为可用时段。</p><textarea v-model="windows" class="w-full" rows="4" aria-label="多班次工作日历" /><details v-if="s.can('master_write')" class="my-3"><summary>新增共享人员或工装</summary><EntryForm :fields="[{key:'name',label:'人员 / 工装名称'},{key:'kind',label:'共享类型',options:[{value:'person',label:'人员（单人同时只占一处）'},{value:'tool',label:'工装（按套数）'}]},{key:'capacity',label:'工装套数（人员固定 1）',value:'1'}]" :busy="s.busy" @submit="v=>s.command('shared-resources',{...v,calendar:calendar()})" /></details><div v-for="r in s.items('shared-resources')" :key="r.id" class="spray-row"><span>{{ r.name }} · {{ r.kind==='person'?'共享人员':'共享工装' }}</span><span>{{ r.capacity }} · {{ (r.calendar as unknown[]).length }} 个时段</span></div><template v-if="s.can('master_write')"><label class="spray-field mt-3">更新机台班次与必需共享资源<select v-model="selected"><option value="">选择现有机台 / 工位</option><option v-for="r in s.items('resources')" :key="r.id" :value="r.id">{{ r.name }}</option></select></label><div class="spray-actions my-3"><label v-for="r in s.items('shared-resources')" :key="r.id"><input v-model="requirements" type="checkbox" :value="r.id" /> {{ r.name }} <input v-if="requirements.includes(r.id)" v-model.number="quantities[r.id]" type="number" min="1" :max="Number(r.capacity)" :aria-label="r.name+' 需求数量'" placeholder="1" class="w-20" /></label></div><Button :disabled="s.busy||!selected" @click="s.command('resource-update',{id:selected,expected_revision:s.find('resources',selected)?.revision,calendar:calendar(),shared_requirements:requirements.map(id=>({id,quantity:quantities[id]||1})),reason:'更新已确认班次与共享人员工装'})">更新此资源的日历与共享需求</Button><p class="spray-help">已有任务保留占用快照；变更若影响现有预留会拒绝并提示先改排。</p></template></section></template>
