<script setup lang="ts">
import { computed,ref } from 'vue'
import { Button } from '@/components/ui/button'
import { sprayProductionApi as api } from '@/api/sprayProduction'
import { useSprayWorkspace,str,errorText,type Entity } from '../workspace'
const props=defineProps<{source:Entity;sheets:string[]}>(),s=useSprayWorkspace()
const kind=ref('shipment_line'),record=ref(''),field=ref('quantity'),cell=ref(''),sheet=ref(''),bindings=ref<Record<string,unknown>[]>([])
const types=[['order','orders','工单'],['order_line','lines','部件'],['shipment','shipments','送货单'],['shipment_line','shipment-lines','送货数量金额'],['settlement','settlements','月结'],['payroll','payrolls','班次应付'],['report_line','report-lines','报工'],['purchase','purchases','采购'],['material_event','material-events','油漆收发'],['returnable','returnables','容器']]
const records=computed(()=>s.items(types.find(v=>v[0]===kind.value)?.[1]??'shipments'))
const fields=computed(()=>Object.entries(records.value.find(v=>v.id===record.value)??{}).filter(([key,value])=>!['id','factory_id','created_by','revision'].includes(key)&&typeof value!=='object').map(([key])=>key))
async function output(){try{const blob=await api.renderTemplate(s.factory,props.source.id,bindings.value);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='业务填报-'+String(props.source.filename);a.click();URL.revokeObjectURL(url)}catch(e){s.error=errorText(e)}}
</script>
<template><details class="spray-panel"><summary>用真实业务填充原表模板</summary><p class="spray-help">保留原表格式、合并单元格和打印布局。仅填入下方明确绑定的单元格，其他区域保留模板内容；先使用空白业务模板，避免混入旧单。原始文件始终不变。</p><div class="spray-entry"><label class="spray-field">业务类型<select v-model="kind" @change="record=''"><option v-for="t in types" :key="t[0]" :value="t[0]">{{ t[2] }}</option></select></label><label class="spray-field">实际单据<select v-model="record"><option value="">选择记录</option><option v-for="r in records" :key="r.id" :value="r.id">{{ r.document_no||r.business_date||r.period||s.batchLabel(s.find('batches',r.batch_id)) }} · {{ r.customer||r.amount||r.activity||r.product_no }}</option></select></label><label class="spray-field">来源字段<select v-model="field"><option v-for="f in fields" :key="f" :value="f">{{ f }} · {{ records.find(v=>v.id===record)?.[f] }}</option></select></label><label class="spray-field">目标表页<select v-model="sheet"><option value="">选择表页</option><option v-for="name in sheets" :key="name">{{ name }}</option></select></label><label class="spray-field">目标单元格<input v-model="cell" placeholder="例如 E8" /></label></div><div class="spray-actions my-3"><Button variant="outline" :disabled="!record||!sheet||!cell" @click="bindings.push({kind,record_id:record,field,sheet,cell:cell.toUpperCase()})">增加填充项</Button><Button :disabled="!bindings.length||!s.can('export')" @click="output">生成原模板文件</Button></div><div v-for="(b,i) in bindings" :key="i" class="spray-row"><span>{{ b.sheet }}!{{ b.cell }} ← {{ b.field }}</span><Button variant="ghost" @click="bindings.splice(i,1)">移除</Button></div></details></template>
