<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import { Sparkles, Save, Star, ArrowUpRight, Settings2, Layers, Heart, ArrowUp } from '@lucide/vue'
import { useMessagingStore } from '@/stores/messaging'
import { useAuthStore } from '@/stores/auth'
import { useWorkCenterStore } from '@/stores/workCenter'
import { directoryApi, type DirectoryMember } from '@/api/directory'
import { collaborationApi, type MemberProfile, type Preferences, type Appreciation, type Page } from '@/api/collaboration'
import { useVisibleModules } from '@/composables/useVisibleModules'
import { isModuleDepartmentId } from '@/data/enterpriseMock'
import { getApiErrorMessage } from '@/lib/http'
import MemberCard from '@/features/collaboration/MemberCard.vue'
const messaging = useMessagingStore(), auth = useAuthStore(), center = useWorkCenterStore(), route = useRoute()
const edit = ref<MemberProfile | null>(null), pref = ref<Preferences | null>(null), official = ref<DirectoryMember | null>(null), contacts = ref<DirectoryMember[]>([]), thanks = ref<Appreciation[]>([]), unseen = ref(0), nextThanks = ref<string | null>(null)
const skillInput = ref(''), saved = ref(''), error = ref(''), busy = ref(false), prefBusy = ref(false), showHidden = ref(false), openedThanks = ref(''), expiry = ref('120')
const department = computed(() => { const value = auth.currentUser?.profile?.primary_department; return isModuleDepartmentId(value || '') ? value as Parameters<typeof isModuleDepartmentId>[0] & import('@/data/enterpriseMock').ModuleDepartmentId : 'engineering' })
const visibleModules = useVisibleModules(department)
const availableModules = computed(() => visibleModules.value.filter(m => m.route && m.detailPage !== false))
const shortcuts = computed(() => (pref.value?.module_shortcuts ?? []).flatMap(id => availableModules.value.filter(m => m.id === id)))
const preview = computed(() => official.value && edit.value ? { ...official.value, self_profile: edit.value } : null)
const collected = computed(() => thanks.value.filter(t => showHidden.value || !t.hidden_at).sort((a,b) => b.private_pin_order-a.private_pin_order || b.created_at.localeCompare(a.created_at)))
const themes = [{ id: 'celadon', name: '青瓷', note: '柔光树脂' }, { id: 'jade', name: '翡翠', note: '细磨砂金属' }, { id: 'dusk', name: '暮蓝', note: '柔网格折光' }, { id: 'champagne', name: '香槟', note: '温暖纸面' }] as const
const categories: Record<string,string> = { timely_help: '及时协助', careful_check: '认真核对', patient_explanation: '耐心讲解', problem_solved: '解决问题' }
const thanksBusy = ref(new Set<string>())
let controller = new AbortController(), thanksSequence = 0
async function loadThanks(more = false) { const request = controller, sequence = ++thanksSequence; try { const result = await collaborationApi.get<Page<Appreciation> & { unseen: number }>('/me/appreciations', request.signal, more && nextThanks.value ? { cursor: nextThanks.value } : undefined); if (request.signal.aborted || sequence !== thanksSequence) return; const rows = result.items.map(item => { const old = thanks.value.find(t => t.id === item.id); return old && (old.version ?? 0) > (item.version ?? 0) ? old : item }); thanks.value = more ? [...thanks.value, ...rows.filter(item => !thanks.value.some(t => t.id === item.id))] : rows; unseen.value = result.unseen; nextThanks.value = result.next_cursor } catch (caught) { if (!request.signal.aborted) error.value = getApiErrorMessage(caught) } }
async function load() { if (!messaging.ready || !auth.currentUser) return; const request = controller; try { const [person, people] = await Promise.all([directoryApi.getMember(auth.currentUser.id, request.signal), collaborationApi.get<{ items: DirectoryMember[] }>('/me/contacts', request.signal)]); if (request.signal.aborted) return; official.value = person; contacts.value = people.items; await loadThanks(); await scrollSection(); if (typeof route.query.item === 'string') { let item = thanks.value.find(t => t.id === route.query.item); if (!item) { item = await collaborationApi.get<Appreciation>(`/appreciations/${encodeURIComponent(route.query.item)}`, request.signal); if (request.signal.aborted) return; if (item.receiver_id === auth.currentUser?.id) thanks.value.unshift(item); else item = undefined }; if (item) await openThanks(item) } } catch (caught) { if (!request.signal.aborted) error.value = getApiErrorMessage(caught) } }
async function scrollSection() { await nextTick(); const section = route.query.section; if (typeof section === 'string' && ['profile','preferences','appreciations'].includes(section)) document.getElementById(section)?.scrollIntoView({ block: 'start' }) }
watch([() => route.query.section, () => route.query.item], () => void load())
function clone<T>(value: T): T { return JSON.parse(JSON.stringify(value)) as T }
function resetEditor() { if (messaging.profile) { edit.value = clone(messaging.profile); skillInput.value = messaging.profile.skill_tags.join('、') }; if (messaging.preferences) pref.value = clone(messaging.preferences) }
watch(() => messaging.ready, ready => { if (ready) { resetEditor(); void load() } }, { immediate: true })
watch(() => messaging.profile, value => { if (!edit.value && value) resetEditor() })
watch(() => messaging.identityKey, () => { controller.abort(); controller = new AbortController(); official.value = null; edit.value = null; pref.value = null; contacts.value = []; thanks.value = []; busy.value = false; prefBusy.value = false; error.value = ''; saved.value = ''; openedThanks.value = ''; thanksBusy.value.clear(); thanksSequence++ })
function expires() { if (expiry.value === 'today') { const today = new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()); return `${today}T23:59:59+08:00` }; return new Date(Date.now()+Number(expiry.value)*60000).toISOString() }
async function save() { if (!edit.value || busy.value) return; busy.value = true; saved.value = ''; error.value = ''; const key = messaging.identityKey; try { edit.value.skill_tags = skillInput.value.split(/[、,，]/).map(t => t.trim()).filter(Boolean); const result = await messaging.saveProfile({ ...edit.value, status_expires_at: edit.value.status_text || edit.value.availability !== 'available' ? expires() : null }); if (result && key === messaging.identityKey) { edit.value = clone(result); saved.value = '名片已保存，其他成员现在可以看到。' } } catch (caught) { if (key === messaging.identityKey) error.value = getApiErrorMessage(caught) } finally { if (key === messaging.identityKey) busy.value = false } }
async function savePref() {
  if (!pref.value || prefBusy.value) return
  const key = messaging.identityKey, request = controller, submitted = clone(pref.value)
  prefBusy.value = true; error.value = ''; saved.value = ''
  try {
    await messaging.savePreferences(submitted)
    if (!request.signal.aborted && key === messaging.identityKey && messaging.preferences && pref.value) {
      const changed = JSON.stringify(pref.value) !== JSON.stringify(submitted)
      pref.value = changed ? { ...pref.value, version: messaging.preferences.version } : clone(messaging.preferences)
      saved.value = changed ? '已保存提交的偏好，新修改尚未保存' : '偏好已保存'
    }
  } catch (caught) { if (!request.signal.aborted && key === messaging.identityKey) error.value = getApiErrorMessage(caught) }
  finally { if (!request.signal.aborted && key === messaging.identityKey) prefBusy.value = false }
}
async function updateThanks(item: Appreciation, patch: { seen?: boolean; private_pin_order?: number; hidden?: boolean }) {
  if (thanksBusy.value.has(item.id)) return
  const request = controller
  thanksBusy.value.add(item.id); error.value = ''
  try {
    const result = await collaborationApi.patch<Appreciation>(`/appreciations/${item.id}`, { expected_version: item.version, seen: !!item.receiver_seen_at, private_pin_order: item.private_pin_order, hidden: !!item.hidden_at, ...patch }, request.signal)
    if (!request.signal.aborted) {
      thanks.value = thanks.value.map(t => t.id === result.id ? result : t)
      unseen.value = Math.max(0, unseen.value + Number(!result.receiver_seen_at && !result.hidden_at) - Number(!item.receiver_seen_at && !item.hidden_at))
    }
  } catch (caught) { if (!request.signal.aborted) { error.value = getApiErrorMessage(caught); await loadThanks() } }
  finally { if (!request.signal.aborted) thanksBusy.value.delete(item.id) }
}
async function openThanks(item: Appreciation) { openedThanks.value = item.id; if (!item.receiver_seen_at) await updateThanks(item, { seen: true }) }
function toggleShortcut(id: string) { if (!pref.value) return; const list = pref.value.module_shortcuts; pref.value.module_shortcuts = list.includes(id) ? list.filter(x => x !== id) : [...list, id].slice(0,6) }
function moveShortcut(id: string) { if (!pref.value) return; const list = [...pref.value.module_shortcuts], index = list.indexOf(id); if (index > 0) { [list[index-1], list[index]] = [list[index]!, list[index-1]!]; pref.value.module_shortcuts = list } }
function refreshThanks() { void loadThanks() }
onMounted(() => window.addEventListener('collaboration-appreciations-changed', refreshThanks))
onBeforeUnmount(() => { controller.abort(); window.removeEventListener('collaboration-appreciations-changed', refreshThanks) })
</script>
<template><main class="rr-connect connect-page" :data-motion="messaging.preferences?.motion || 'rich'"><header class="connect-hero"><div><p class="connect-eyebrow">MY SPACE · 属于你的工作一隅</p><h1>{{ auth.currentUser?.display_name }}，欢迎回到我的空间。</h1><p>表达专长，整理协作，收藏每一份真诚的感谢。</p></div><Sparkles :size="44" /><div class="connect-hero-orbit" /></header><p v-if="!messaging.ready" class="connect-empty">{{ messaging.error || '当前身份尚未开启个人空间。原账号头像与退出操作仍可使用。' }}</p><p v-if="error" class="connect-error" role="alert">{{ error }}</p><p v-if="saved" class="connect-saved" role="status">{{ saved }}</p>
<div v-if="edit && pref" class="connect-space-layout"><div class="connect-space-main"><section class="connect-space-section" id="profile"><div class="connect-section-heading"><h2><Layers :size="20" />我的名片</h2><span>自述由你填写，正式任职保持只读</span></div><div class="connect-theme-options"><button v-for="theme in themes" :key="theme.id" :data-theme="theme.id" :aria-pressed="edit.theme === theme.id" @click="edit.theme = theme.id"><i /><strong>{{ theme.name }}</strong><small>{{ theme.note }}</small></button></div><label>可以找我的事<input v-model="edit.help_topics" maxlength="80" placeholder="例如：试模协调、模具资料、啤办跟进"></label><label>专长标签 <small>最多 6 项，每项 20 字，用顿号分隔</small><input v-model="skillInput" placeholder="试模、资料核对、Excel"></label><label>关于我<textarea v-model="edit.bio" rows="3" maxlength="280" placeholder="写下你的协作方式，或方便联系的时段。" /></label><div class="connect-form-row"><label>联系偏好<select v-model="edit.availability"><option value="available">可联系</option><option value="busy">忙碌</option><option value="leave_message">请留言</option></select></label><label>状态到期<select v-model="expiry"><option value="30">30 分钟后</option><option value="120">2 小时后</option><option value="today">今天结束（上海时间）</option></select></label></div><label>短状态<input v-model="edit.status_text" maxlength="60" placeholder="现场处理，稍后回复"></label><button class="connect-button connect-button--primary" :disabled="busy" @click="save"><Save :size="16" />{{ busy ? '正在保存…' : '保存名片' }}</button></section>
<section class="connect-space-section" id="preferences"><div class="connect-section-heading"><h2><Settings2 :size="20" />外观与消息偏好</h2></div><div class="connect-form-row"><label>动效<select v-model="pref.motion"><option value="rich">丰富</option><option value="simple">简约</option><option value="off">关闭</option></select></label><label>密度<select v-model="pref.density"><option value="comfortable">舒适</option><option value="compact">紧凑</option></select></label><label>发送快捷键<select v-model="pref.send_key"><option value="enter">Enter 发送</option><option value="ctrl_enter">Ctrl+Enter 发送</option></select></label></div><label class="connect-check"><input v-model="pref.sound_enabled" type="checkbox">启用私信与感谢提示音</label><label class="connect-check"><input v-model="pref.read_receipts_enabled" type="checkbox">允许对方看到我的已读回执</label><label class="connect-check"><input type="checkbox" :checked="!!pref.dnd_until && Date.parse(pref.dnd_until) > Date.now()" @change="pref.dnd_until = ($event.target as HTMLInputElement).checked ? new Date(Date.now()+2*3600000).toISOString() : null">免打扰 2 小时（继续保留未读）</label><button class="connect-button" :disabled="prefBusy" @click="savePref">保存偏好</button></section>
<section class="connect-space-section" id="appreciations"><div class="connect-section-heading"><h2><Heart :size="20" />我的感谢收藏 <small>{{ unseen }} 张未查看</small></h2><button class="connect-text-button" @click="showHidden = !showHidden">{{ showHidden ? '收起已隐藏' : '查看已隐藏' }}</button></div><p class="connect-muted">仅双方可见。你可以私下置顶三张，把具体的帮助好好留下。</p><div class="connect-thanks-grid"><article v-for="item in collected" :key="item.id" class="connect-thanks-card" :class="{ 'is-opened': openedThanks === item.id }"><div class="connect-thanks-medal"><Sparkles :size="26" /></div><p class="connect-eyebrow">{{ categories[item.category] }}</p><button class="connect-thanks-open" @click="openThanks(item)"><h3>{{ item.sender_name }} 的感谢</h3><span v-if="!item.receiver_seen_at">未查看 · 点击展开</span></button><p v-if="openedThanks === item.id || item.receiver_seen_at" class="connect-thanks-text">{{ item.text }}</p><time>{{ new Date(item.created_at).toLocaleDateString('zh-CN', { timeZone: 'Asia/Shanghai' }) }}</time><footer><button :disabled="thanksBusy.has(item.id)" @click="updateThanks(item, { private_pin_order: item.private_pin_order ? 0 : 1 })"><Star :size="14" />{{ item.private_pin_order ? '取消置顶' : '私人置顶' }}</button><button :disabled="thanksBusy.has(item.id)" @click="updateThanks(item, { hidden: !item.hidden_at })">{{ item.hidden_at ? '恢复' : '隐藏' }}</button></footer></article></div><p v-if="!collected.length" class="connect-empty">真实的帮助，会在这里留下温暖的回声。</p><button v-if="nextThanks" class="connect-button" @click="loadThanks(true)">更早的感谢</button></section></div>
<aside class="connect-space-aside"><p class="connect-preview-label">你的名片 · 实时预览</p><MemberCard v-if="preview" :member="preview" detailed /><section class="connect-space-section"><h2>我的常用入口</h2><div class="connect-shortcuts"><RouterLink v-for="module in shortcuts" :key="module.id" :to="module.route!">{{ module.title }}<ArrowUpRight :size="15" /></RouterLink></div><details><summary>选择并排序入口</summary><label v-for="module in availableModules" :key="module.id" class="connect-check"><input type="checkbox" :checked="pref.module_shortcuts.includes(module.id)" @change="toggleShortcut(module.id)">{{ module.title }}<button v-if="pref.module_shortcuts.includes(module.id)" class="connect-icon-button" :aria-label="`上移${module.title}`" @click.prevent="moveShortcut(module.id)"><ArrowUp :size="13" /></button></label><button class="connect-button" :disabled="prefBusy" @click="savePref">保存入口</button></details></section><section class="connect-space-section"><h2>我的重点事项</h2><p v-if="center.error || (center.bell && center.bell.health.status !== 'fresh')" class="connect-muted">部分事项暂不可用</p><RouterLink v-for="item in (center.bell?.items ?? []).slice(0,3)" :key="item.id" class="connect-work-item" :to="{ name: 'notification-center', query: { entry: item.id } }"><strong>{{ item.title }}</strong><small>{{ item.reference_label }}</small></RouterLink><RouterLink to="/notifications" class="connect-text-button">进入事项工作台</RouterLink></section><section class="connect-space-section"><h2>常联系</h2><button v-for="member in contacts" :key="member.id" class="connect-contact-link" @click="messaging.openPeer(member.id)"><span>{{ member.display_name }}</span><small>{{ member.org_name }}</small><ArrowUpRight :size="14" /></button><RouterLink v-if="!contacts.length" to="/people">从成员目录添加常联系人</RouterLink></section></aside></div></main></template>
