<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { RouterLink } from 'vue-router'
import { ArrowLeft, ArrowDown, Send, Paperclip, X, Search, Maximize2, MessageCircle, FileText, Quote, Link2, Sparkles } from '@lucide/vue'
import { useMessagingStore } from '@/stores/messaging'
import { collaborationApi, type Message, type MessagePage, type Reference } from '@/api/collaboration'
import { directoryApi, type DirectoryMember } from '@/api/directory'
import { useDialogFocus } from '@/composables/useDialogFocus'
import { acquireBodyScrollLock, type BodyScrollLockRelease } from '@/lib/bodyScrollLock'
import { businessPreempted, foregroundSurface } from './panelCoordinator'
import { getApiErrorMessage } from '@/lib/http'
import { createRandomUuid } from '@/lib/randomUuid'
import AppreciationDialog from './AppreciationDialog.vue'
const props = defineProps<{ fullPage?: boolean }>(), emit = defineEmits<{ close: [] }>()
const messaging = useMessagingStore(), root = ref<HTMLElement | null>(null), scroll = ref<HTMLElement | null>(null), fileInput = ref<HTMLInputElement | null>(null)
const draft = computed(() => messaging.drafts[messaging.selectedId]), rows = computed(() => messaging.visibleMessages)
const showList = ref(true), search = ref(''), searchResults = ref<Message[]>([]), searchOpen = ref(false), referenceOpen = ref(false), imagePreview = ref(''), previewRoot = ref<HTMLElement | null>(null), thanks = ref<DirectoryMember | null>(null)
const reference = ref<Reference>({ resource_type: 'molding_sample', resource_id: '', factory_id: 'huakang-a' }), localError = ref(''), uploadRows = ref<{ key: string; cid: string; file: File; progress: number; error: string; done: boolean }[]>([])
const showArchived = ref(false)
const ordered = computed(() => [...messaging.conversations].filter(c => showArchived.value ? !!c.archived_at : !c.archived_at).sort((a,b) => b.pin_order-a.pin_order || b.updated_at.localeCompare(a.updated_at)))
const controller = new AbortController(); let releasePreview: BodyScrollLockRelease | undefined, readTimer: ReturnType<typeof setTimeout> | undefined, readInFlight = false, readingIntent = false, atBottom = true
const composing = ref(false)
const newlyArrived = ref(0), seen = new Set<number>()
let readingGeneration = 0
useDialogFocus(() => !!imagePreview.value, previewRoot, { inertBackground: true, onEscape: () => imagePreview.value = '' })
watch(imagePreview, value => { if (value) releasePreview ??= acquireBodyScrollLock(); else { releasePreview?.(); releasePreview = undefined } })
function time(value: string) { return new Intl.DateTimeFormat('zh-CN', { timeZone: 'Asia/Shanghai', month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) }
async function choose(cid: string) { showList.value = false; seen.clear(); readingIntent = false; newlyArrived.value = 0; localError.value = ''; await messaging.select(cid); await nextTick(); if (messaging.selected?.unread) await unread(); else bottom() }
function bottom() { scroll.value?.scrollTo({ top: scroll.value.scrollHeight }); newlyArrived.value = 0; atBottom = true }
async function jump(seq: number) { try { await messaging.locate(messaging.selectedId, seq); await nextTick(); scroll.value?.querySelector(`[data-message-seq="${seq}"]`)?.scrollIntoView({ block: 'center' }) } catch (caught) { localError.value = getApiErrorMessage(caught) } }
async function unread() { await messaging.firstUnread(messaging.selectedId); await nextTick(); const first = rows.value.find(m => m.message_seq > (messaging.selected?.last_read_seq ?? 0) && m.sender_user_id !== messaging.capabilities?.owner.user_id && !m.retracted_at); if (first) await jump(first.message_seq) }
async function older() {
  const element = scroll.value, cid = messaging.selectedId, generation = readingGeneration
  if (!element) return
  const top = element.getBoundingClientRect().top
  const anchor = [...element.querySelectorAll<HTMLElement>('[data-message-seq]')].find(node => node.getBoundingClientRect().bottom > top)
  const seq = anchor?.dataset.messageSeq, offset = anchor ? anchor.getBoundingClientRect().top - top : 0
  await messaging.loadMessages(cid, true); await nextTick()
  if (readingGeneration !== generation || messaging.selectedId !== cid || scroll.value !== element || !seq) return
  const restored = element.querySelector<HTMLElement>(`[data-message-seq="${seq}"]`)
  if (restored) element.scrollTop += restored.getBoundingClientRect().top - element.getBoundingClientRect().top - offset
}
function observed() {
  const element = scroll.value
  if (!element) return
  atBottom = element.scrollHeight - element.scrollTop - element.clientHeight < 70
  if (!readingIntent || document.hidden || !document.hasFocus() || imagePreview.value || thanks.value || businessPreempted.value || (!props.fullPage && foregroundSurface.value !== 'messages') || !root.value?.contains(document.activeElement)) return
  const bounds = element.getBoundingClientRect()
  for (const node of element.querySelectorAll<HTMLElement>('[data-message-seq]')) { const r = node.getBoundingClientRect(); if (r.top >= bounds.top && r.bottom <= bounds.bottom) seen.add(Number(node.dataset.messageSeq)) }
  let through = messaging.selected?.last_read_seq ?? 0
  for (const row of rows.value) { if (row.message_seq <= through) continue; if (row.message_seq !== through + 1) break; if (!seen.has(row.message_seq) && row.sender_user_id !== messaging.capabilities?.owner.user_id && !row.retracted_at) break; through = row.message_seq }
  if (through <= (messaging.selected?.last_read_seq ?? 0) || readInFlight) return
  clearTimeout(readTimer); const cid = messaging.selectedId
  readTimer = setTimeout(async () => { if (cid !== messaging.selectedId || document.hidden || !document.hasFocus() || !root.value?.contains(document.activeElement) || imagePreview.value || businessPreempted.value) return; readInFlight = true; try { await messaging.markRead(cid, through) } finally { readInFlight = false } }, 600)
}
function scrolled() { readingGeneration++; observed() }
function intent() { readingIntent = true; observed() }
function key(event: KeyboardEvent) { if (event.key !== 'Enter' || event.shiftKey || event.isComposing || composing.value || event.keyCode === 229) return; const allowed = messaging.preferences?.send_key === 'ctrl_enter' ? event.ctrlKey || event.metaKey : !event.ctrlKey && !event.metaKey; if (allowed) { event.preventDefault(); void messaging.send(messaging.selectedId) } }
async function upload(item: typeof uploadRows.value[number]) { const owner = messaging.identityKey; item.error = ''; try { const result = await messaging.upload(item.cid, item.file, item.key, n => item.progress = n); if (result && owner === messaging.identityKey) item.done = true } catch (caught) { if (owner === messaging.identityKey) item.error = getApiErrorMessage(caught) } }
function files(list: FileList | File[]) { if (!draft.value || !messaging.selectedId) return; if (draft.value.reference) { localError.value = '当前草稿已有业务引用，请先发送或移除后再添加附件。'; return }; for (const file of Array.from(list)) { if ((draft.value.attachment_ids.length + uploadRows.value.filter(r => !r.done && r.cid === messaging.selectedId).length) >= 6) { localError.value = '每条消息最多 6 个附件'; break }; const item = { key: createRandomUuid(), cid: messaging.selectedId, file, progress: 0, error: '', done: false }; uploadRows.value.push(item); void upload(item) } }
function paste(event: ClipboardEvent) { if (event.clipboardData?.files.length) { event.preventDefault(); files(event.clipboardData.files) } }
async function find() { const cid = messaging.selectedId, owner = messaging.identityKey, query = search.value; try { const page = await collaborationApi.get<MessagePage>(`/conversations/${cid}/search`, controller.signal, { q: query }); if (cid === messaging.selectedId && owner === messaging.identityKey && query === search.value) searchResults.value = page.items } catch (caught) { if (cid === messaging.selectedId && owner === messaging.identityKey) localError.value = getApiErrorMessage(caught) } }
async function attachReference() {
  const cid = messaging.selectedId, owner = messaging.identityKey, value = { ...reference.value }
  const isCurrent = () => cid === messaging.selectedId && owner === messaging.identityKey && !controller.signal.aborted
  const hasAttachments = () => messaging.drafts[cid]?.attachment_ids.length || uploadRows.value.some(item => item.cid === cid && !item.done)
  if (hasAttachments()) { localError.value = '当前草稿还有附件，请先发送或移除后再分享业务记录。'; return }
  try {
    const result = await collaborationApi.post<{ reference: { available: boolean }; peer_can_view: boolean }>(`/references/preview?peer_user_id=${encodeURIComponent(messaging.selected?.peer.id ?? '')}`, value, controller.signal)
    if (!isCurrent()) return
    if (!result.reference.available) { localError.value = '该业务记录当前不可分享'; return }
    if (hasAttachments()) { localError.value = '当前草稿还有附件，请先发送或移除后再分享业务记录。'; return }
    messaging.edit(cid, { reference: value }); referenceOpen.value = false
    localError.value = result.peer_can_view ? '' : '对方当前无权查看，将看到不可查看提示。'
  } catch (caught) { if (isCurrent()) localError.value = getApiErrorMessage(caught) }
}
async function appreciate() { const cid = messaging.selectedId, owner = messaging.identityKey; try { const member = await directoryApi.getMember(messaging.selected!.peer.id, controller.signal); if (cid === messaging.selectedId && owner === messaging.identityKey && !controller.signal.aborted) thanks.value = member } catch (caught) { if (cid === messaging.selectedId && owner === messaging.identityKey && !controller.signal.aborted) localError.value = getApiErrorMessage(caught) } }
async function action(type: 'pin' | 'mute' | 'archive') { if (!messaging.selected) return; try { await messaging.changeConversation(messaging.selected, type === 'pin' ? { pin_order: messaging.selected.pin_order ? 0 : 1 } : type === 'mute' ? { mute_until: messaging.selected.mute_until ? null : new Date(Date.now()+86400000).toISOString() } : { archived: !messaging.selected.archived_at }); if (type === 'archive') showList.value = true } catch (caught) { localError.value = getApiErrorMessage(caught) } }
watch(() => [messaging.selectedId, rows.value.at(-1)?.message_seq ?? 0] as const, async ([cid, seq], [oldCid, oldSeq]) => {
  if (cid !== oldCid || seq <= oldSeq) return
  const generation = readingGeneration
  await nextTick(); if (readingGeneration !== generation) return
  if (atBottom) bottom(); else newlyArrived.value += rows.value.filter(row => row.message_seq > oldSeq).length
  observed()
})
watch(() => messaging.selectedId, id => { readingGeneration++; if (id) showList.value = false; seen.clear(); readingIntent = false; searchResults.value = []; uploadRows.value = uploadRows.value.filter(r => !r.done) }, { immediate: true, flush: 'sync' })
onBeforeUnmount(() => { controller.abort(); clearTimeout(readTimer); releasePreview?.() })
</script>
<template><section ref="root" class="connect-chat" :class="{ 'connect-chat--full': fullPage, 'connect-chat--conversation': !showList && messaging.selectedId }" aria-label="私信" @focusin="intent" @pointerdown="intent">
  <aside class="connect-conversation-list"><header><div><p class="connect-eyebrow">NEXUS CONNECT</p><h2>私信 <small>{{ messaging.unread }} 未读</small></h2></div><button v-if="!fullPage" class="connect-icon-button" aria-label="收起私信" @click="emit('close')"><X /></button></header><p class="connect-connection" role="status">{{ messaging.status }}</p><label class="connect-check" style="padding:6px 18px"><input v-model="showArchived" type="checkbox">已归档会话</label><div class="connect-conversations"><button v-for="conv in ordered" :key="conv.id" :aria-pressed="conv.id === messaging.selectedId" @click="choose(conv.id)"><span class="connect-initial">{{ conv.peer.display_name.slice(0,1) }}</span><span><strong>{{ conv.peer.display_name }}<i v-if="conv.pin_order">置顶</i><i v-if="conv.mute_until">静音</i></strong><small>{{ conv.last_message?.retracted_at ? '消息已撤回' : conv.last_message?.body || (conv.last_message ? '附件或业务卡片' : '开始新的协作') }}</small></span><b v-if="conv.unread">{{ conv.unread }}</b></button><p v-if="!ordered.length" class="connect-empty">还没有会话<br><RouterLink to="/people" @click="emit('close')">从成员目录找一位同事</RouterLink></p><button v-if="messaging.nextConversationCursor" class="connect-button" @click="messaging.moreConversations">更多会话</button></div><RouterLink v-if="!fullPage" class="connect-full-link" to="/messages" @click="emit('close')"><Maximize2 :size="15" />打开完整消息页</RouterLink></aside>
  <div class="connect-chat-main" v-if="messaging.selected && draft"><header class="connect-chat-header"><button class="connect-icon-button connect-back-to-list" aria-label="返回会话列表" @click="showList = true"><ArrowLeft :size="20" /></button><div><h2>{{ messaging.selected.peer.display_name }}</h2><p>{{ messaging.selected.peer.available ? '可留言 · 按对方方便的时间继续' : '成员当前不可联系，仍可查看历史' }}</p></div><button class="connect-icon-button" aria-label="搜索会话" @click="searchOpen = !searchOpen"><Search :size="18" /></button><button v-if="!fullPage" class="connect-icon-button" aria-label="收起私信" @click="emit('close')"><X :size="19" /></button></header>
  <div class="connect-chat-actions"><button @click="action('pin')">{{ messaging.selected.pin_order ? '取消置顶' : '置顶' }}</button><button @click="action('mute')">{{ messaging.selected.mute_until ? '取消静音' : '静音 24 小时' }}</button><button @click="action('archive')">{{ messaging.selected.archived_at ? '恢复会话' : '归档' }}</button><button @click="messaging.markRead(messaging.selectedId, messaging.selected.last_message_seq)">标为已读</button><button @click="appreciate">感谢</button></div>
  <form v-if="searchOpen" class="connect-chat-search" @submit.prevent="find"><input v-model="search" type="search" placeholder="搜索当前会话" maxlength="100"><button class="connect-button" :disabled="!search.trim()">搜索</button><ul v-if="searchResults.length"><li v-for="result in searchResults" :key="result.id"><button @click.prevent="jump(result.message_seq); searchOpen = false">{{ result.body.slice(0,100) }}</button></li></ul></form>
  <div ref="scroll" class="connect-message-scroll" tabindex="0" aria-label="消息阅读区" @scroll="scrolled" @paste="paste" @dragover.prevent @drop.prevent="files($event.dataTransfer?.files || [])"><button v-if="messaging.hasMore[messaging.selectedId]" class="connect-history-button" :disabled="messaging.loading[messaging.selectedId]" @click="older">加载更早消息</button><button v-if="messaging.selected.unread" class="connect-unread-button" @click="unread">{{ messaging.selected.unread }} 条未读 · 跳到首条</button>
    <article v-for="message in rows" :key="message.id" class="connect-message" :class="{ own: message.sender_user_id === messaging.capabilities?.owner.user_id, retracted: message.retracted_at }" :data-message-seq="message.message_seq"><time>{{ time(message.created_at) }}</time><div v-if="message.retracted_at" class="connect-tombstone">消息已撤回</div><template v-else><button v-if="message.reply" class="connect-reply" @click="jump(message.reply.message_seq)"><Quote :size="12" />{{ message.reply.body || '附件或业务卡片' }}</button><div class="connect-bubble"><p v-if="message.body">{{ message.body }}</p><template v-for="asset in message.attachments" :key="asset.id"><button v-if="asset.mime.startsWith('image/')" class="connect-image" :aria-label="`预览 ${asset.filename}`" @click="imagePreview = asset.url"><img :src="asset.url" :alt="asset.filename" loading="lazy"></button><a v-else class="connect-file" :href="asset.url"><FileText :size="24" /><span>{{ asset.filename }}<small>{{ (asset.size/1024).toFixed(1) }} KB · 下载</small></span></a></template><RouterLink v-if="message.reference?.available && message.reference.url" class="connect-reference" :to="message.reference.url"><Link2 :size="20" /><span>{{ message.reference.label }}<strong>{{ message.reference.title }}</strong><small>{{ message.reference.status }}</small></span></RouterLink><p v-else-if="message.reference">该业务记录当前不可查看</p></div><div class="connect-message-tools"><button @click="messaging.edit(messaging.selectedId, { reply_to_id: message.id })">引用</button><template v-if="message.sender_user_id === messaging.capabilities?.owner.user_id"><span>{{ messaging.selected.peer_read_seq !== null && messaging.selected.peer_read_seq >= message.message_seq ? '已读' : '已发送' }}</span><button v-if="Date.now()-new Date(message.created_at).getTime() < 120000" @click="messaging.retract(message)">撤回</button></template></div></template></article>
    <article v-for="entry in messaging.pending[messaging.selectedId] || []" :key="entry.payload.client_message_id" class="connect-message own"><div class="connect-bubble"><p>{{ entry.payload.body || '附件或业务卡片' }}</p></div><small>{{ entry.state === 'sending' ? '发送中…' : '结果待核对' }}</small><p v-if="entry.error" class="connect-error">{{ entry.error }}</p><button v-if="entry.state === 'failed'" class="connect-button" @click="messaging.transmit(messaging.selectedId, entry)">使用原标识核对并重试</button></article><p v-if="!rows.length" class="connect-empty"><MessageCircle :size="36" />把事情接着往前推<br>发一句问候，或带上具体的业务记录。</p>
  </div><button v-if="newlyArrived" class="connect-new-messages" @click="bottom"><ArrowDown :size="14" />{{ newlyArrived }} 条新消息</button>
  <div class="connect-composer" @paste="paste" @dragover.prevent @drop.prevent="files($event.dataTransfer?.files || [])"><p v-if="localError || messaging.error" class="connect-error" role="alert">{{ localError || messaging.error }}</p><div v-if="draft.reply_to_id" class="connect-composer-note">引用消息 <button aria-label="取消引用" @click="messaging.edit(messaging.selectedId, { reply_to_id: null })"><X :size="14" /></button></div><div v-if="draft.reference" class="connect-composer-note">业务引用：{{ draft.reference.resource_id }}<button aria-label="取消业务引用" @click="messaging.edit(messaging.selectedId, { reference: null })"><X :size="14" /></button></div><div v-for="item in uploadRows.filter(r => r.cid === messaging.selectedId && !r.done)" :key="item.key" class="connect-upload-progress">{{ item.file.name }} · {{ item.progress }}% <button v-if="item.error" @click="upload(item)">重试上传</button><p v-if="item.error">{{ item.error }}</p></div><div v-for="id in draft.attachment_ids" :key="id" class="connect-composer-note">{{ draft.unavailable_attachment_ids?.includes(id) ? '附件已过期，请移除并重新选择' : '已暂存附件' }} {{ id.slice(0,6) }}<button aria-label="移除附件" @click="messaging.edit(messaging.selectedId, { attachment_ids: draft.attachment_ids.filter(a => a !== id) })"><X :size="14" /></button></div>
  <textarea :value="draft.text" rows="3" maxlength="4000" aria-label="输入私信" placeholder="写下消息…" :disabled="!messaging.selected.peer.available" @input="messaging.edit(messaging.selectedId, { text: ($event.target as HTMLTextAreaElement).value })" @keydown="key" @compositionstart="composing = true" @compositionend="composing = false" /><div class="connect-composer-toolbar"><input ref="fileInput" type="file" multiple accept=".jpg,.jpeg,.png,.webp,.pdf,.doc,.docx,.xls,.xlsx" hidden @change="files(($event.target as HTMLInputElement).files || []); ($event.target as HTMLInputElement).value = ''"><button class="connect-icon-button" aria-label="上传图片或文档" @click="fileInput?.click()"><Paperclip :size="20" /></button><button class="connect-icon-button" aria-label="分享业务记录" @click="referenceOpen = !referenceOpen"><Link2 :size="20" /></button><span>{{ draft.text.length }}/4000 · {{ messaging.preferences?.send_key === 'ctrl_enter' ? 'Ctrl+Enter' : 'Enter' }} 发送</span><button class="connect-button connect-button--primary" :disabled="!messaging.selected.peer.available || (!draft.text.trim() && !draft.attachment_ids.length && !draft.reference)" @click="messaging.send(messaging.selectedId)"><Send :size="16" />发送</button></div><p v-if="draft.error" class="connect-error">草稿未同步：{{ draft.error }}<button @click="messaging.loadDraft(messaging.selectedId)">采用云端草稿</button><button @click="messaging.keepLocalDraft(messaging.selectedId)">保留本机并覆盖云端</button></p><p v-else class="connect-draft-status">{{ draft.saving ? '正在同步草稿…' : draft.revision === draft.savedRevision ? '草稿已同步' : '草稿保留在当前会话' }}</p>
  <form v-if="referenceOpen" class="connect-reference-form" @submit.prevent="attachReference"><select v-model="reference.resource_type" aria-label="业务类型"><option value="molding_sample">啤办单</option><option value="internal_quote">内部报价</option></select><input v-model="reference.resource_id" placeholder="业务记录 ID" aria-label="业务记录 ID" required><select v-model="reference.factory_id" aria-label="业务来源厂区"><option v-for="[id,name] in [['huakang-a','华康A'],['huakang-b','华康B'],['huakang-c','华康C'],['huakang-d','华康D'],['huadeng','华登'],['huaxing','华兴']]" :key="id" :value="id">{{ name }}</option></select><button class="connect-button">核验并添加</button></form></div></div>
  <div v-else class="connect-chat-welcome"><Sparkles :size="40" /><h2>让沟通有个落点</h2><p>选择会话，继续未完的协作。</p></div>
  <Teleport to="body"><div v-if="imagePreview" class="rr-connect connect-backdrop" data-connect-overlay @click.self="imagePreview = ''"><section ref="previewRoot" class="connect-image-preview" role="dialog" aria-modal="true" aria-label="图片预览" tabindex="-1"><button class="connect-icon-button" aria-label="关闭图片预览" @click="imagePreview = ''"><X /></button><img :src="imagePreview" alt="私信图片预览"></section></div></Teleport><AppreciationDialog v-if="thanks" :member="thanks" @close="thanks = null" />
</section></template>
