<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Factory, Building2, Search, Users, Star, X, LayoutGrid, Rows3, ChevronLeft, ChevronRight } from '@lucide/vue'
import { directoryApi, type DirectoryMember, type DirectoryOrganization, type PresenceFilter } from '@/api/directory'
import { useDirectoryQuery } from '@/composables/useDirectoryQuery'
import { useAuthStore } from '@/stores/auth'
import { useAppStore } from '@/stores/app'
import { useMessagingStore } from '@/stores/messaging'
import MemberCard from './MemberCard.vue'
import AppreciationDialog from './AppreciationDialog.vue'
import './connect.css'
const route = useRoute(), router = useRouter(), auth = useAuthStore(), app = useAppStore(), messaging = useMessagingStore()
const query = (key: string) => typeof route.query[key] === 'string' ? route.query[key] as string : ''
const q = computed(() => query('q')), searchText = ref(q.value), organizations = ref<DirectoryOrganization[]>([]), catalogError = ref(''), selected = ref<DirectoryMember | null>(null), thanks = ref<DirectoryMember | null>(null), compact = ref(false), panorama = ref(true)
const params = computed(() => ({ page: Math.max(1, Number(query('page')) || 1), page_size: 36, q: q.value, presence: (['online', 'away', 'offline'].includes(query('presence')) ? query('presence') : 'all') as PresenceFilter, org_unit_id: query('org_unit_id') || query('factory_id'), department: query('department'), contacts_only: query('contacts') === '1' }))
const { items, total, totalPages, counts, loading, error, stale, load } = useDirectoryQuery(params)
const myOrg = computed(() => auth.currentUser?.identity?.primary_assignment?.org_unit_id || auth.currentUser?.profile?.primary_factory_id || '')
let debounce: ReturnType<typeof setTimeout> | undefined, detailController: AbortController | undefined, catalogController: AbortController | undefined
function filter(patch: Record<string, string | undefined>) { void router.push({ query: { ...route.query, page: undefined, ...patch } }) }
const composing = ref(false)
function compositionStart() { composing.value = true; clearTimeout(debounce) }
function input() { clearTimeout(debounce); if (!composing.value) debounce = setTimeout(() => filter({ q: searchText.value.trim() || undefined }), 250) }
async function catalog() { catalogController?.abort(); const request = catalogController = new AbortController(); try { const result = await directoryApi.getCatalog(request.signal); if (!request.signal.aborted) { organizations.value = result.organizations; catalogError.value = '' } } catch { if (!request.signal.aborted) catalogError.value = '组织统计暂不可用' } }
async function show(id: string) { detailController?.abort(); selected.value = items.value.find(m => m.id === id) ?? null; if (!id) return; const request = detailController = new AbortController(); try { const member = await directoryApi.getMember(id, request.signal); if (!request.signal.aborted) selected.value = member } catch { if (!request.signal.aborted) catalogError.value = '这位成员当前不可查看' } }
watch(q, value => { clearTimeout(debounce); searchText.value = value })
watch(() => query('member'), id => void show(id), { immediate: true })
watch(() => messaging.identityKey, () => { selected.value = null; detailController?.abort(); organizations.value = []; void catalog() })
onMounted(() => { void catalog() })
onBeforeUnmount(() => { clearTimeout(debounce); detailController?.abort(); catalogController?.abort() })
</script>
<template><main class="rr-connect connect-page" :data-motion="messaging.preferences?.motion || 'rich'" :data-density="messaging.preferences?.density || 'comfortable'">
  <header class="connect-hero"><div><p class="connect-eyebrow">同频 · NEXUS CONNECT</p><h1>找到同事，连接每一份专长。</h1><p>成员目录 / {{ total }} 位匹配成员 · {{ counts.online }} 位近期在线</p></div><div class="connect-hero-orbit" aria-hidden="true" /><label class="connect-search"><Search :size="20" /><input v-model="searchText" type="search" maxlength="64" placeholder="找姓名、岗位、组织或专长" @input="input" @compositionstart="compositionStart" @compositionend="composing = false; input()"></label></header>
  <div class="connect-section-heading"><span>组织全景 <small>正式任职来自组织档案</small></span><button class="connect-text-button" @click="panorama = !panorama">{{ panorama ? '收起全景' : '展开全景' }}</button></div>
  <div v-if="panorama" class="connect-panorama"><button v-for="org in organizations" :key="org.id" :aria-pressed="params.org_unit_id === org.id" @click="filter({ org_unit_id: org.id, factory_id: undefined, department: undefined, contacts: undefined })"><component :is="org.kind === 'functional_unit' ? Building2 : Factory" :size="25" /><strong>{{ org.name }}</strong><span>{{ org.total }} 位成员 <i />{{ org.online }} 在线</span></button></div><p v-if="catalogError" class="connect-error">{{ catalogError }}</p>
  <div class="connect-directory-layout" :class="{ 'has-detail': selected }"><nav class="connect-org-nav" aria-label="成员组织"><button :aria-pressed="!params.org_unit_id && !params.contacts_only" @click="filter({ org_unit_id: undefined, factory_id: undefined, department: undefined, contacts: undefined })"><Users :size="18" />全部成员</button><button v-if="messaging.ready" :aria-pressed="params.contacts_only" @click="filter({ contacts: '1' })"><Star :size="18" />常联系</button><button @click="filter({ org_unit_id: myOrg || undefined, factory_id: undefined, department: undefined })"><Building2 :size="18" />我的组织</button><button @click="filter({ org_unit_id: app.activeFactoryId === 'group' ? undefined : app.activeFactoryId, factory_id: undefined, department: undefined })"><Factory :size="18" />浏览范围 · {{ app.activeFactoryId === 'group' ? '集团' : app.activeFactory.shortName }}</button><hr><template v-for="org in organizations" :key="org.id"><button :aria-pressed="params.org_unit_id === org.id" @click="filter({ org_unit_id: org.id, factory_id: undefined, department: undefined })">{{ org.name }}<span>{{ org.total }}</span></button><select v-if="params.org_unit_id === org.id" aria-label="组织部门" :value="params.department" @change="filter({ department: ($event.target as HTMLSelectElement).value || undefined })"><option value="">全部部门</option><option v-for="dept in org.departments" :key="dept.id" :value="dept.id">{{ dept.name }}</option></select></template></nav>
  <section class="connect-member-results"><div class="connect-results-toolbar"><select aria-label="连接状态" :value="params.presence" @change="filter({ presence: ($event.target as HTMLSelectElement).value })"><option value="all">全部状态</option><option value="online">在线</option><option value="away">最近在线</option><option value="offline">离线 · 可留言</option></select><span>{{ total }} 位成员</span><button class="connect-icon-button" :aria-label="compact ? '切换名片视图' : '切换紧凑视图'" @click="compact = !compact"><component :is="compact ? LayoutGrid : Rows3" :size="19" /></button><button class="connect-text-button" @click="router.push({ query: {} })">清除筛选</button></div><p v-if="loading" role="status">正在查找成员…</p><p v-if="error" class="connect-error" role="alert">{{ error }} <button @click="load()">重试</button></p><p v-if="stale">更新暂缓，显示最近一次结果</p><div class="connect-member-grid" :class="{ compact }"><MemberCard v-for="member in items" :key="member.id" :member="member" :compact="compact" @select="filter({ member: $event.id, page: query('page') || undefined })" @chat="messaging.openPeer($event.id)" @contact="load(true)" /></div><p v-if="!loading && !items.length" class="connect-empty">没有符合条件的成员。试试清除筛选，或先添加常联系人。</p><footer class="connect-pagination"><button class="connect-button" :disabled="params.page <= 1" @click="filter({ page: String(params.page - 1) })"><ChevronLeft :size="16" />上一页</button><span>{{ params.page }} / {{ Math.max(1, totalPages) }}</span><button class="connect-button" :disabled="params.page >= totalPages" @click="filter({ page: String(params.page + 1) })">下一页<ChevronRight :size="16" /></button></footer></section>
  <aside v-if="selected" class="connect-directory-detail" aria-label="选中成员名片"><button class="connect-icon-button connect-detail-close" aria-label="关闭名片" @click="filter({ member: undefined, page: query('page') || undefined })"><X :size="18" /></button><MemberCard :member="selected" detailed @chat="messaging.openPeer($event.id)" @appreciate="thanks = $event" @contact="show(selected.id); load(true)" /></aside></div><AppreciationDialog v-if="thanks" :member="thanks" @close="thanks = null" /></main></template>
