"""Batch-scoped UV plans and explicit manual duration; preserve existing plans."""
from alembic import op
import sqlalchemy as sa

revision = "20260929_0127"
down_revision = "20260928_0126"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    if bind.dialect.name == 'sqlite' and bind.exec_driver_sql('PRAGMA foreign_keys').scalar():
        raise RuntimeError('Run this reviewed SQLite rebuild on a dedicated connection with foreign_keys=OFF, then verify foreign_key_check and row preservation before enabling UV.')
    def preserved_checks(name):
        # Alembic drops reflected anonymous SQLite checks during batch copies.
        return tuple(sa.CheckConstraint(row['sqltext'], name=f'ck_{name}_preserved_{index}')
                     for index, row in enumerate(sa.inspect(bind).get_check_constraints(name)) if not row['name'])
    previous = next(row for row in sa.inspect(bind).get_unique_constraints("uv_ops_schedule_blocks")
                    if row["column_names"] == ["factory_id", "task_id"])
    convention = {"uq": "uq_%(table_name)s_%(column_0_name)s_%(column_1_name)s"}
    with op.batch_alter_table("uv_ops_schedule_blocks", naming_convention=convention, table_args=preserved_checks('uv_ops_schedule_blocks')) as batch:
        batch.drop_constraint(previous["name"] or "uq_uv_ops_schedule_blocks_factory_id_task_id", type_="unique")
        batch.add_column(sa.Column("batch_id", sa.String(64)))
        batch.add_column(sa.Column("fixture_id", sa.String(64)))
        batch.add_column(sa.Column("fixture_evidence", sa.Text()))
        batch.add_column(sa.Column("estimate_basis", sa.String(24), nullable=False, server_default="standard"))
        batch.add_column(sa.Column("estimated_seconds", sa.Numeric(18, 6)))
        batch.add_column(sa.Column("estimate_reason", sa.Text()))
        batch.create_foreign_key("fk_uv_ops_schedule_batch", "uv_ops_batches", ["factory_id", "batch_id"], ["factory_id", "id"])
        batch.create_foreign_key("fk_uv_ops_schedule_fixture", "uv_ops_fixtures", ["factory_id", "fixture_id"], ["factory_id", "id"])
        batch.create_unique_constraint("uq_uv_ops_schedule_task_batch", ["factory_id", "task_id", "batch_id"])
        batch.create_check_constraint("ck_uv_ops_schedule_estimate_basis", "estimate_basis IN ('standard','manual')")
        batch.create_check_constraint("ck_uv_ops_schedule_estimated_seconds", "estimated_seconds IS NULL OR estimated_seconds > 0")
    # Preserve old whole-task rows verbatim. Runtime resolves a single batch;
    # ambiguous split plans require explicit cancellation, never guessed history.


    for name, key in [('uv_ops_participations', None), ('uv_ops_quality_entries', None), ('uv_ops_expenses', None), ('uv_ops_wage_accruals', ['factory_id','shift_id','task_id']), ('uv_ops_run_costs', ['factory_id','run_id'])]:
        old = next((row for row in sa.inspect(bind).get_unique_constraints(name) if row['column_names'] == key), None) if key else None
        convention = {'uq': 'uq_%(table_name)s_%(column_0_name)s_%(column_1_name)s'}
        with op.batch_alter_table(name, naming_convention=convention, table_args=preserved_checks(name)) as batch:
            batch.add_column(sa.Column('active_key', sa.Integer(), nullable=True, server_default='1'))
            if key:
                batch.drop_constraint(old['name'] or f'uq_{name}_{key[0]}_{key[1]}', type_='unique')
                batch.create_unique_constraint('uq_'+name+'_active', key+['active_key'])
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uv_ops_reversals',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.CheckConstraint("factory_id = 'huakang-a'"),
    sa.CheckConstraint("kind IN ('quality','expense','wage','run_cost','participation')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'id'),
    sa.UniqueConstraint('factory_id', 'kind', 'entity_id')
    )
    op.create_index(op.f('ix_uv_ops_reversals_factory_id'), 'uv_ops_reversals', ['factory_id'], unique=False)
    op.create_table('uv_ops_executions',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('machine_id', sa.String(length=64), nullable=False),
    sa.Column('schedule_id', sa.String(length=64), nullable=False),
    sa.Column('fixture_code', sa.String(length=64), nullable=False),
    sa.Column('shift_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.String(length=40), nullable=False),
    sa.Column('ended_at', sa.String(length=40), nullable=True),
    sa.Column('start_evidence', sa.Text(), nullable=False),
    sa.Column('end_evidence', sa.Text(), nullable=True),
    sa.Column('ended_shift_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['factory_id', 'ended_shift_id'], ['uv_ops_shifts.factory_id', 'uv_ops_shifts.id']),
    sa.Column('active_key', sa.Integer(), server_default='1', nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.CheckConstraint("factory_id = 'huakang-a'"),
    sa.CheckConstraint('(active_key = 1 AND ended_at IS NULL) OR (active_key IS NULL AND ended_at IS NOT NULL)'),
    sa.CheckConstraint('ended_at IS NULL OR ended_at > started_at'),
    sa.ForeignKeyConstraint(['factory_id', 'batch_id'], ['uv_ops_batches.factory_id', 'uv_ops_batches.id'], ),
    sa.ForeignKeyConstraint(['factory_id', 'machine_id'], ['uv_ops_machines.factory_id', 'uv_ops_machines.id'], ),
    sa.ForeignKeyConstraint(['factory_id', 'schedule_id'], ['uv_ops_schedule_blocks.factory_id', 'uv_ops_schedule_blocks.id'], ),
    sa.ForeignKeyConstraint(['factory_id', 'shift_id'], ['uv_ops_shifts.factory_id', 'uv_ops_shifts.id'], ),
    sa.ForeignKeyConstraint(['factory_id', 'task_id'], ['uv_ops_tasks.factory_id', 'uv_ops_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'batch_id', 'active_key'),
    sa.UniqueConstraint('factory_id', 'fixture_code', 'active_key'),
    sa.UniqueConstraint('factory_id', 'id'),
    sa.UniqueConstraint('factory_id', 'machine_id', 'active_key')
    )
    op.create_index(op.f('ix_uv_ops_executions_factory_id'), 'uv_ops_executions', ['factory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError("UV batch plans carry business history; retain the additive schema during rollback.")
