"""Explicit supplier membership, paper commitments, shipment and attachment evidence."""
from alembic import op
import sqlalchemy as sa
revision = "20260921_0118"
down_revision = "20260917_0117"
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carton_supplier_attachments',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=96), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.CheckConstraint('version >= 1 AND size > 0 AND size <= 10485760', name='ck_carton_supplier_attachment_size'),
    sa.ForeignKeyConstraint(['order_id', 'factory_id'], ['carton_orders.id', 'carton_orders.factory_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'filename', 'version', name='uq_carton_supplier_attachment_version')
    )
    op.create_index(op.f('ix_carton_supplier_attachments_factory_id'), 'carton_supplier_attachments', ['factory_id'], unique=False)
    op.create_index(op.f('ix_carton_supplier_attachments_order_id'), 'carton_supplier_attachments', ['order_id'], unique=False)
    op.create_table('carton_supplier_members',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.String(length=96), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE') AND revision >= 1", name='ck_carton_supplier_member_state'),
    sa.ForeignKeyConstraint(['supplier_id', 'factory_id'], ['carton_suppliers.id', 'carton_suppliers.factory_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'factory_id', name='uq_carton_supplier_member_user_factory')
    )
    op.create_index(op.f('ix_carton_supplier_members_factory_id'), 'carton_supplier_members', ['factory_id'], unique=False)
    op.create_index(op.f('ix_carton_supplier_members_user_id'), 'carton_supplier_members', ['user_id'], unique=False)
    op.create_table('carton_supplier_shipments',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.String(length=96), nullable=False),
    sa.Column('delivery_note_no', sa.String(length=128), nullable=False),
    sa.Column('delivery_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('receipt_id', sa.String(length=96), nullable=True),
    sa.Column('confirmation_request_id', sa.String(length=128), nullable=False),
    sa.Column('confirmation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('confirmed_by', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', sa.String(length=40), nullable=False),
    sa.Column('acceptance_json', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('SENT','RECEIVED','NOT_RECEIVED') AND revision >= 1", name='ck_carton_supplier_shipment_status'),
    sa.ForeignKeyConstraint(['receipt_id'], ['carton_receipts.id'], ),
    sa.ForeignKeyConstraint(['supplier_id', 'factory_id'], ['carton_suppliers.id', 'carton_suppliers.factory_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'created_by', 'request_id', name='uq_carton_supplier_shipment_request'),
    sa.UniqueConstraint('factory_id', 'supplier_id', 'delivery_note_no', name='uq_carton_supplier_shipment_note'),
    sa.UniqueConstraint('id', 'factory_id', name='uq_carton_supplier_shipment_factory')
    )
    op.create_index(op.f('ix_carton_supplier_shipments_factory_id'), 'carton_supplier_shipments', ['factory_id'], unique=False)
    op.create_index(op.f('ix_carton_supplier_shipments_status'), 'carton_supplier_shipments', ['status'], unique=False)
    op.create_index(op.f('ix_carton_supplier_shipments_supplier_id'), 'carton_supplier_shipments', ['supplier_id'], unique=False)
    op.create_table('carton_supplier_commitments',
    sa.Column('order_line_id', sa.String(length=96), nullable=False),
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('issue_id', sa.String(length=96), nullable=False),
    sa.Column('promised_date', sa.String(length=10), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('accepted_by', sa.String(length=64), nullable=False),
    sa.Column('accepted_at', sa.String(length=40), nullable=False),
    sa.CheckConstraint('revision >= 1', name='ck_carton_supplier_commitment_revision'),
    sa.ForeignKeyConstraint(['issue_id'], ['carton_purchase_order_issues.id'], ),
    sa.ForeignKeyConstraint(['order_line_id', 'factory_id'], ['carton_order_lines.id', 'carton_order_lines.factory_id'], ),
    sa.PrimaryKeyConstraint('order_line_id')
    )
    op.create_index(op.f('ix_carton_supplier_commitments_factory_id'), 'carton_supplier_commitments', ['factory_id'], unique=False)
    op.create_table('carton_supplier_shipment_lines',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('shipment_id', sa.String(length=96), nullable=False),
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('order_line_id', sa.String(length=96), nullable=False),
    sa.Column('issue_id', sa.String(length=96), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_carton_supplier_shipment_quantity'),
    sa.ForeignKeyConstraint(['issue_id'], ['carton_purchase_order_issues.id'], ),
    sa.ForeignKeyConstraint(['order_line_id', 'factory_id'], ['carton_order_lines.id', 'carton_order_lines.factory_id'], ),
    sa.ForeignKeyConstraint(['shipment_id', 'factory_id'], ['carton_supplier_shipments.id', 'carton_supplier_shipments.factory_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'order_line_id', name='uq_carton_supplier_shipment_line')
    )
    op.create_index(op.f('ix_carton_supplier_shipment_lines_factory_id'), 'carton_supplier_shipment_lines', ['factory_id'], unique=False)
    op.create_index(op.f('ix_carton_supplier_shipment_lines_order_line_id'), 'carton_supplier_shipment_lines', ['order_line_id'], unique=False)
    op.create_index(op.f('ix_carton_supplier_shipment_lines_shipment_id'), 'carton_supplier_shipment_lines', ['shipment_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("供应商接单、发货与附件为业务证据，禁止自动删除；请使用已验证备份恢复")
