"""Create injection V3 after retirement, without touching historical business tables."""

import json

import sqlalchemy as sa
from alembic import op

revision = "20260905_0100"
down_revision = "20260904_0099"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "injection_v3_calendar_event",
        sa.Column("factory_id", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "factory_id IN ('huaxing','huadeng','huakang-a','huakang-b')",
            name="ck_iv3_calendar_factory",
        ),
        sa.CheckConstraint(
            "end_at IS NULL OR end_at > start_at", name="ck_iv3_calendar_interval"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_injection_v3_calendar_event_factory_id"),
        "injection_v3_calendar_event",
        ["factory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_injection_v3_calendar_event_resource_id"),
        "injection_v3_calendar_event",
        ["resource_id"],
        unique=False,
    )
    op.create_table(
        "injection_v3_factory_settings",
        sa.Column("factory_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("factory_id"),
    )
    op.create_table(
        "injection_v3_import_batch",
        sa.Column("factory_id", sa.String(length=64), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("sheet_name", sa.String(length=100), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "factory_id IN ('huaxing','huadeng','huakang-a','huakang-b')",
            name="ck_iv3_import_factory",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "factory_id",
            "file_sha256",
            "sheet_name",
            "parser_version",
            name="uq_iv3_import_source",
        ),
    )
    op.create_index(
        op.f("ix_injection_v3_import_batch_factory_id"),
        "injection_v3_import_batch",
        ["factory_id"],
        unique=False,
    )
    op.create_table(
        "injection_v3_machine",
        sa.Column("factory_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("workshop", sa.String(length=100), nullable=False),
        sa.Column("machine_a", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("clamp_ton", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("machine_family", sa.String(length=32), nullable=False),
        sa.Column("speed_class", sa.String(length=32), nullable=False),
        sa.Column("manipulator", sa.String(length=200), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("restrictions", sa.JSON(), nullable=False),
        sa.Column("operating_status", sa.String(length=32), nullable=False),
        sa.Column("recovery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(length=4000), nullable=False),
        sa.Column("current_setup", sa.JSON(), nullable=False),
        sa.Column("raw_header_cells", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "factory_id IN ('huaxing','huadeng','huakang-a','huakang-b')",
            name="ck_iv3_machine_factory",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("factory_id", "code", name="uq_iv3_machine_code"),
        sa.UniqueConstraint("id", "factory_id", name="uq_iv3_machine_factory"),
    )
    op.create_index(
        op.f("ix_injection_v3_machine_factory_id"),
        "injection_v3_machine",
        ["factory_id"],
        unique=False,
    )
    op.create_table(
        "injection_v3_mold_master",
        sa.Column("normalized_code", sa.String(length=200), nullable=False),
        sa.Column("mold_code", sa.String(length=200), nullable=False),
        sa.Column("part_name", sa.String(length=255), nullable=False),
        sa.Column("alias_codes", sa.JSON(), nullable=False),
        sa.Column(
            "required_machine_a", sa.Numeric(precision=12, scale=3), nullable=True
        ),
        sa.Column("requirement_raw", sa.String(length=1000), nullable=False),
        sa.Column("requirements", sa.JSON(), nullable=False),
        sa.Column("defaults", sa.JSON(), nullable=False),
        sa.Column("notes", sa.String(length=4000), nullable=False),
        sa.Column("created_from_factory_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalized_code"),
    )
    op.create_table(
        "injection_v3_operation",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("factory_id", sa.String(length=64), nullable=False),
        sa.Column("client_operation_id", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("before", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_operation_id"),
    )
    op.create_index(
        op.f("ix_injection_v3_operation_factory_id"),
        "injection_v3_operation",
        ["factory_id"],
        unique=False,
    )
    op.create_table(
        "injection_v3_saved_view",
        sa.Column("factory_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("view_type", sa.String(length=32), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_injection_v3_saved_view_factory_id"),
        "injection_v3_saved_view",
        ["factory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_injection_v3_saved_view_user_id"),
        "injection_v3_saved_view",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "injection_v3_shared_revision",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "injection_v3_demand",
        sa.Column("factory_id", sa.String(length=64), nullable=False),
        sa.Column("order_no", sa.String(length=255), nullable=True),
        sa.Column("item_no", sa.String(length=255), nullable=True),
        sa.Column("part_name", sa.String(length=255), nullable=True),
        sa.Column("mold_master_id", sa.String(length=64), nullable=True),
        sa.Column("mold_code", sa.String(length=200), nullable=False),
        sa.Column(
            "required_machine_a", sa.Numeric(precision=12, scale=3), nullable=True
        ),
        sa.Column("requirements_snapshot", sa.JSON(), nullable=False),
        sa.Column("demand_sets", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("planned_shots", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("opening_shots", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column(
            "adjustment_shots", sa.Numeric(precision=20, scale=4), nullable=False
        ),
        sa.Column("completed_shots", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("remaining_shots", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column(
            "overproduced_shots", sa.Numeric(precision=20, scale=4), nullable=False
        ),
        sa.Column("required_units", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("good_units", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("remaining_units", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("pieces_per_set", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "effective_outputs_per_shot",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column("allocation_mode", sa.String(length=32), nullable=False),
        sa.Column("quantity_basis", sa.String(length=64), nullable=False),
        sa.Column("opening_cutoff_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "target_shots_per_day", sa.Numeric(precision=20, scale=4), nullable=True
        ),
        sa.Column(
            "target_basis_hours", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column("net_weight_g", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("gross_weight_g", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("weight_basis", sa.String(length=64), nullable=False),
        sa.Column("allowance_rate", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("price_per_shot", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column(
            "remaining_material_kg", sa.Numeric(precision=24, scale=8), nullable=True
        ),
        sa.Column(
            "remaining_processing_amount",
            sa.Numeric(precision=24, scale=8),
            nullable=True,
        ),
        sa.Column("color_name", sa.String(length=255), nullable=True),
        sa.Column("colorant_code", sa.String(length=255), nullable=True),
        sa.Column("color_depth_rank", sa.Integer(), nullable=True),
        sa.Column("material_raw", sa.String(length=255), nullable=True),
        sa.Column("resin", sa.String(length=100), nullable=True),
        sa.Column("material_grade", sa.String(length=200), nullable=True),
        sa.Column("priority_level", sa.Integer(), nullable=False),
        sa.Column("dispatch_state", sa.String(length=32), nullable=False),
        sa.Column("ordered_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "downstream_lead_days", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column("earliest_available_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("planned_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("planned_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_stock_ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "delivery_slack_hours", sa.Numeric(precision=20, scale=6), nullable=True
        ),
        sa.Column("machine_code", sa.String(length=100), nullable=True),
        sa.Column("order_note", sa.String(length=4000), nullable=True),
        sa.Column("production_note", sa.String(length=4000), nullable=True),
        sa.Column("warehouse_note", sa.String(length=1000), nullable=True),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("source_document", sa.String(length=255), nullable=True),
        sa.Column("source_line_id", sa.String(length=255), nullable=True),
        sa.Column("source_row", sa.Integer(), nullable=True),
        sa.Column("import_batch_id", sa.String(length=64), nullable=True),
        sa.Column("stable_sequence", sa.Integer(), nullable=False),
        sa.Column("extras", sa.JSON(), nullable=False),
        sa.Column("field_sources", sa.JSON(), nullable=False),
        sa.Column("unplaced_reason", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "factory_id IN ('huaxing','huadeng','huakang-a','huakang-b')",
            name="ck_iv3_demand_factory",
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["injection_v3_import_batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mold_master_id"],
            ["injection_v3_mold_master.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "factory_id", name="uq_iv3_demand_factory"),
    )
    op.create_index(
        "ix_iv3_demand_item",
        "injection_v3_demand",
        ["factory_id", "item_no"],
        unique=False,
    )
    op.create_index(
        "ix_iv3_demand_mold",
        "injection_v3_demand",
        ["factory_id", "mold_code"],
        unique=False,
    )
    op.create_index(
        "ix_iv3_demand_order",
        "injection_v3_demand",
        ["factory_id", "order_no"],
        unique=False,
    )
    op.create_index(
        "ix_iv3_demand_state_due",
        "injection_v3_demand",
        ["factory_id", "dispatch_state", "delivery_due_at", "id"],
        unique=False,
    )
    op.create_table(
        "injection_v3_mold_asset",
        sa.Column("master_id", sa.String(length=64), nullable=False),
        sa.Column("asset_code", sa.String(length=200), nullable=False),
        sa.Column("current_factory_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location_source", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["injection_v3_mold_master.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("master_id", "asset_code", name="uq_iv3_asset_code"),
    )
    op.create_index(
        op.f("ix_injection_v3_mold_asset_current_factory_id"),
        "injection_v3_mold_asset",
        ["current_factory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_injection_v3_mold_asset_master_id"),
        "injection_v3_mold_asset",
        ["master_id"],
        unique=False,
    )
    op.create_table(
        "injection_v3_import_row",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("batch_id", sa.String(length=64), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=False),
        sa.Column("row_role", sa.String(length=64), nullable=False),
        sa.Column("demand_id", sa.String(length=64), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("issues", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["injection_v3_import_batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["demand_id"],
            ["injection_v3_demand.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "source_row", name="uq_iv3_import_row"),
    )
    op.create_index(
        op.f("ix_injection_v3_import_row_batch_id"),
        "injection_v3_import_row",
        ["batch_id"],
        unique=False,
    )
    op.create_table(
        "injection_v3_run",
        sa.Column("factory_id", sa.String(length=64), nullable=False),
        sa.Column("machine_id", sa.String(length=64), nullable=False),
        sa.Column("mold_asset_id", sa.String(length=64), nullable=False),
        sa.Column("parent_run_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("setup_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("planned_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("planned_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "planned_physical_shots", sa.Numeric(precision=20, scale=4), nullable=False
        ),
        sa.Column("physical_shots", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("segments", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.JSON(), nullable=False),
        sa.Column("execution_events", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "factory_id IN ('huaxing','huadeng','huakang-a','huakang-b')",
            name="ck_iv3_run_factory",
        ),
        sa.ForeignKeyConstraint(
            ["machine_id", "factory_id"],
            ["injection_v3_machine.id", "injection_v3_machine.factory_id"],
            name="fk_iv3_run_machine",
        ),
        sa.ForeignKeyConstraint(
            ["mold_asset_id"],
            ["injection_v3_mold_asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_run_id"],
            ["injection_v3_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "factory_id", name="uq_iv3_run_factory"),
    )
    op.create_index(
        "ix_iv3_run_asset_start",
        "injection_v3_run",
        ["mold_asset_id", "planned_start_at"],
        unique=False,
    )
    op.create_index(
        "ix_iv3_run_machine_start",
        "injection_v3_run",
        ["factory_id", "machine_id", "planned_start_at"],
        unique=False,
    )
    op.create_table(
        "injection_v3_historical_output",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("demand_id", sa.String(length=64), nullable=False),
        sa.Column("import_row_id", sa.String(length=64), nullable=False),
        sa.Column("production_date", sa.Date(), nullable=False),
        sa.Column("shift_code", sa.String(length=16), nullable=False),
        sa.Column("source_key", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("counts_toward_demand", sa.Boolean(), nullable=False),
        sa.Column("allocation_mode", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["demand_id"],
            ["injection_v3_demand.id"],
        ),
        sa.ForeignKeyConstraint(
            ["import_row_id"],
            ["injection_v3_import_row.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "demand_id",
            "production_date",
            "shift_code",
            "source_key",
            name="uq_iv3_history_key",
        ),
    )
    op.create_index(
        op.f("ix_injection_v3_historical_output_demand_id"),
        "injection_v3_historical_output",
        ["demand_id"],
        unique=False,
    )
    op.create_table(
        "injection_v3_run_demand",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("factory_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("demand_id", sa.String(length=64), nullable=False),
        sa.Column("allocation_mode", sa.String(length=32), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "planned_quantity", sa.Numeric(precision=20, scale=4), nullable=False
        ),
        sa.Column(
            "outputs_per_shot", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column("product_code", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["demand_id", "factory_id"],
            ["injection_v3_demand.id", "injection_v3_demand.factory_id"],
            name="fk_iv3_rd_demand",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "factory_id"],
            ["injection_v3_run.id", "injection_v3_run.factory_id"],
            name="fk_iv3_rd_run",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "demand_id", name="uq_iv3_run_demand"),
    )
    op.create_index(
        op.f("ix_injection_v3_run_demand_demand_id"),
        "injection_v3_run_demand",
        ["demand_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_injection_v3_run_demand_run_id"),
        "injection_v3_run_demand",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "injection_v3_shift_report",
        sa.Column("factory_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("production_date", sa.Date(), nullable=False),
        sa.Column("shift_code", sa.String(length=16), nullable=False),
        sa.Column("segment_key", sa.String(length=64), nullable=False),
        sa.Column("physical_shots", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("good_units", sa.JSON(), nullable=False),
        sa.Column("scrap_units", sa.JSON(), nullable=False),
        sa.Column("client_operation_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("physical_shots >= 0", name="ck_iv3_report_nonnegative"),
        sa.ForeignKeyConstraint(
            ["run_id", "factory_id"],
            ["injection_v3_run.id", "injection_v3_run.factory_id"],
            name="fk_iv3_report_run",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_operation_id", name="uq_iv3_report_operation"),
        sa.UniqueConstraint(
            "run_id",
            "production_date",
            "shift_code",
            "segment_key",
            name="uq_iv3_shift_key",
        ),
    )
    op.create_index(
        op.f("ix_injection_v3_shift_report_factory_id"),
        "injection_v3_shift_report",
        ["factory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_injection_v3_shift_report_run_id"),
        "injection_v3_shift_report",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "injection_v3_report_allocation",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("report_id", sa.String(length=64), nullable=False),
        sa.Column("run_demand_id", sa.String(length=64), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["injection_v3_shift_report.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_demand_id"],
            ["injection_v3_run_demand.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id", "run_demand_id", name="uq_iv3_allocation"),
    )
    op.create_index(
        op.f("ix_injection_v3_report_allocation_report_id"),
        "injection_v3_report_allocation",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_injection_v3_report_allocation_run_demand_id"),
        "injection_v3_report_allocation",
        ["run_demand_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    settings = sa.table(
        "injection_v3_factory_settings",
        sa.column("factory_id", sa.String),
        sa.column("revision", sa.Integer),
        sa.column("parameters", sa.JSON),
    )
    parameters = json.loads(
        '{"business_timezone": "Asia/Shanghai", "target_basis_hours": 24, "downstream_lead_days": 3, "allowance_rate": 0.01, "material_change_minutes": 60, "day_start": "08:00", "night_start": "20:00", "working_days": [0, 1, 2, 3, 4, 5, 6], "daily_breaks": [], "setup_interruptible": false, "allowed_upsize": {"4": [5, 7], "5": [5, 7], "7": [7, 10, 12], "10": [10, 12, 14], "12": [12, 14, 18], "14": [14, 18, 24], "18": [18, 24], "24": [24, 32, 35], "32": [32, 35, 40, 50], "35": [35, 40, 50], "40": [40, 50, 60], "50": [50, 60, 80], "60": [60, 80], "80": [80, 100, 104], "100": [100, 104, 120], "104": [104, 120], "120": [120]}, "changeover_reference": {"5": ["43.20", "24.48"], "7": ["50.40", "24.48"], "12": ["64.80", "36"], "14": ["86.40", "36"], "18": ["86.40", "36"], "24": ["100.80", "48.24"], "32": ["122.40", "48.24"], "60": ["144", "60.48"], "80": ["194.40", "72"], "104": ["237.60", "72"], "120": ["288", "78.48"]}, "cleaning_matrix": {}, "color_ranks": {"透明": 0, "白色": 1, "浅色": 2, "中色": 3, "深色": 4, "黑色": 5}, "defaults_note": "班制与允许上放为可编辑建议；24小时目标、3天准备期、1%材料系数与转换参考来自原表。"}'
    )
    op.bulk_insert(
        settings,
        [
            {"factory_id": f, "revision": 0, "parameters": parameters}
            for f in ("huaxing", "huadeng", "huakang-a", "huakang-b")
        ],
    )
    op.execute(
        "INSERT INTO injection_v3_shared_revision (id, revision) VALUES ('shared', 0)"
    )
    _register_permissions()


def _register_permissions():
    """Freeze the V3 catalog; fixed-position grants reconcile at app startup.

    Do not restore retired grants, copy custom roles, or change existing denies.
    Typed insert/select expressions also avoid untyped PostgreSQL bind values.
    """
    permissions = sa.table(
        "auth_permissions",
        sa.column("id", sa.String(96)),
        sa.column("code", sa.String(128)),
        sa.column("name", sa.String(128)),
        sa.column("description", sa.Text()),
    )
    metadata = sa.table(
        "auth_permission_metadata",
        sa.column("permission_id", sa.String(96)),
        sa.column("module_code", sa.String(64)),
        sa.column("action", sa.String(64)),
        sa.column("risk_level", sa.String(32)),
        sa.column("access_kind", sa.String(16)),
        sa.column("scope_type", sa.String(32)),
        sa.column("status", sa.String(32)),
        sa.column("sort_order", sa.Integer()),
        sa.column("created_at", sa.String(32)),
        sa.column("updated_at", sa.String(32)),
    )
    # 0095 already removed the former generations. These are four new business
    # capabilities, without the retired approval/publish/profile permissions.
    for index, action in enumerate(("read", "plan", "report", "master_write")):
        code = f"injection_scheduling:{action}"
        permission_id = f"perm-injection_scheduling-{action}"
        op.execute(
            permissions.insert().from_select(
                ["id", "code", "name", "description"],
                sa.select(
                    sa.literal(permission_id, type_=sa.String(96)),
                    sa.literal(code, type_=sa.String(128)),
                    sa.literal(code, type_=sa.String(128)),
                    sa.literal("", type_=sa.Text()),
                ).where(~sa.exists(sa.select(1).where(permissions.c.code == code))),
            )
        )
        op.execute(
            metadata.insert().from_select(
                [
                    "permission_id",
                    "module_code",
                    "action",
                    "risk_level",
                    "access_kind",
                    "scope_type",
                    "status",
                    "sort_order",
                    "created_at",
                    "updated_at",
                ],
                sa.select(
                    permissions.c.id,
                    sa.literal("injection_scheduling", type_=sa.String(64)),
                    sa.literal(action, type_=sa.String(64)),
                    sa.literal("normal", type_=sa.String(32)),
                    sa.literal(
                        "read" if action == "read" else "operate", type_=sa.String(16)
                    ),
                    sa.literal("factory_department", type_=sa.String(32)),
                    sa.literal("active", type_=sa.String(32)),
                    sa.literal(800 + index, type_=sa.Integer()),
                    sa.literal("2026-09-05 00:00:00", type_=sa.String(32)),
                    sa.literal("2026-09-05 00:00:00", type_=sa.String(32)),
                ).where(
                    permissions.c.code == code,
                    ~sa.exists(
                        sa.select(1).where(metadata.c.permission_id == permissions.c.id)
                    ),
                ),
            )
        )


def downgrade():
    raise RuntimeError(
        "V3 contains business history; restore a verified backup instead of discarding it"
    )
