<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { RouterLink } from 'vue-router'
import { ArrowUpRight, Download, Plus, Calculator, ShieldCheck, CircleAlert, Check, FileCheck } from '@lucide/vue'
import { Button } from '@/components/ui/button'
import { useSprayPage } from '../usePage'
import { SPRAY_BASE, documentNo, number, stateLabel, type Entity, type Rule, type Employee } from '../contracts'
import WorkspaceDialog from '../components/WorkspaceDialog.vue'
import WorkspaceState from '../components/WorkspaceState.vue'
import RecordTable from '../components/RecordTable.vue'
interface Economics {month:string;currency:string;coverage:Record<string,string>;operating_value:string|null;material_cost:string|null;payroll_amount?:string|null;expense_amount:string|null;surplus:string|null;is_partial:boolean;label:string;missing:Record<string,number>}
interface Payroll extends Entity {document_no:string;business_date:string;status:string;currency:string;lines:(Entity&{employee_id:string;payroll_amount:string;base_amount:string;guarantee:string;subsidy:string;adjustment:string})[]}
const w=useSprayPage(['rules','reports','employees'])
const tab=ref('economics'), month=ref(w.businessDate.value.slice(0,7)), currency=ref('CNY'), summary=ref<Economics|null>(null), error=ref(''), busy=ref(false)
const dialog=ref(''), selected=ref<Payroll|null>(null), closure=ref<{month:string;fingerprint:string;blockers:{code:string;message:string;entity_id?:string}[]}|null>(null)
const form=reactive({document_no:documentNo('工资核对'),rule_id:'',category:'',kind:'expense',amount:'',included:'unknown',evidence:'',reason:'',report_id:''})
const rowRules=reactive<Record<string,string>>({})
const adjustments=ref<{employee_id:string;subsidy:string;adjustment:string;evidence:string}[]>([])
const reportRows=computed(()=>w.items('reports').filter(r=>r.business_date===w.businessDate.value&&r.status==='confirmed').flatMap(r=>(r.rows as Entity[]).map(row=>({...row,document_no:String(r.document_no)}))))
const wageRules=computed(()=>w.items<Rule>('rules').filter(r=>r.kind==='wage'))
const costRules=computed(()=>w.items<Rule>('rules').filter(r=>r.kind==='operation_price'&&r.status==='confirmed'))
const employeeName=(id:string)=>w.items<Employee>('employees').find(e=>e.id===id)?.name??id.slice(0,8)
async function refresh(){error.value='';if(w.can('cost_read'))try{summary.value=(await w.query<Economics>('finance/economics',{month:month.value,currency:currency.value})).data;await w.load(['expenses','valuations'])}catch(cause){error.value=w.explain(cause)}if(w.can('payroll_read'))await w.load(['payroll']);if(w.can('settle')&&w.can('cost_read')&&w.can('payroll_read'))await w.load(['periods'])}
watch(()=>[w.ready.value,month.value,currency.value],()=>{if(w.ready.value)void refresh()},{immediate:true})
function open(kind:string){if(kind==='payroll'){adjustments.value=[];Object.keys(rowRules).forEach(k=>delete rowRules[k])}dialog.value=kind;error.value='';form.document_no=documentNo(kind==='payroll'?'工资核对':'费用');form.evidence='';form.amount='';form.rule_id=kind==='payroll'?wageRules.value[0]?.id??'':costRules.value[0]?.id??''}
async function save(){busy.value=true;error.value='';try{
 if(dialog.value==='payroll'){selected.value=await w.command<Payroll>('payroll/trial',{document_no:form.document_no,business_date:w.businessDate.value,rule_id:form.rule_id,row_rules:Object.fromEntries(Object.entries(rowRules).filter(([,value])=>!!value)),adjustments:adjustments.value});dialog.value='payroll-detail'}
 else if(dialog.value==='expense'){await w.command('expenses',{document_no:form.document_no,business_date:w.businessDate.value,category:form.category,kind:form.kind,amount:form.amount,currency:currency.value,included:form.included==='unknown'?null:form.included==='yes',evidence:form.evidence});dialog.value=''}
 else if(dialog.value==='valuation'){const report=w.items('reports').find(r=>r.id===form.report_id);if(!report)throw new Error('请选择已确认日报');await w.command('valuations',{business_date:w.businessDate.value,report_id:report.id,rule_id:form.rule_id},report.version);dialog.value=''}
 await refresh()
}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
async function confirmExpense(item:Entity,included:boolean){const reason=await w.promptReason(included?'确认此费用纳入经营成本的依据':'确认此费用不纳入经营成本的依据');if(!reason)return;try{await w.command(`expenses/${item.id}/confirm`,{business_date:w.businessDate.value,included,reason},item.version);await refresh()}catch(cause){error.value=w.explain(cause)}}
async function confirmPayroll(){if(!selected.value)return;busy.value=true;try{selected.value=await w.command<Payroll>(`payroll/${selected.value.id}/confirm`,{},selected.value.version);await refresh()}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
async function reopen(){const period=w.items('periods').find(p=>p.month===month.value&&p.status==='closed');if(!period)return;const reason=await w.promptReason('重开期间原因（保留上次冻结核对表）');if(!reason)return;try{await w.command(`periods/${period.id}/reopen`,{business_date:w.businessDate.value,reason},period.version);await refresh()}catch(cause){error.value=w.explain(cause)}}
async function previewClose(){error.value='';try{closure.value=(await w.query<NonNullable<typeof closure.value>>('periods/preview',{month:month.value})).data;form.reason='';dialog.value='close'}catch(cause){error.value=w.explain(cause)}}
async function closePeriod(){if(!closure.value)return;busy.value=true;try{const period=w.items('periods').find(p=>p.month===month.value);await w.command('periods/close',{business_date:w.businessDate.value,month:month.value,reason:form.reason,fingerprint:closure.value.fingerprint},period?.version??0);dialog.value='';await refresh()}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
const completeCount=computed(()=>Object.values(summary.value?.coverage??{}).filter(v=>v==='complete').length)
const coverageLabels:Record<string,string>={production:'生产实绩',pricing:'工序价格',payroll:'员工工资',material_cost:'材料实际成本'}
async function closeDialog(){if(w.dirty.value&&!(await w.confirmDiscard('放弃未保存的核对内容？')))return;dialog.value='';w.dirty.value=false}
</script>
<template>
 <div class="spray-page"><header class="spray-page-heading"><div><span class="spray-eyebrow">ECONOMICS / 经营与月结</span><h1>看清收入依据，也看清缺项</h1><p>工序产值、交收收入和材料成本采用独立口径，不互相叠加。</p></div><div class="spray-actions"><RouterLink v-if="w.can('settle')" class="spray-secondary" :to="{path:`${SPRAY_BASE}/finance/settlements`,query:{factory:w.factory.value}}"><FileCheck :size="15" />委托方月结</RouterLink><Button v-if="w.items('periods').some(p=>p.month===month&&p.status==='closed')" variant="outline" @click="reopen">重开期间</Button><Button v-if="w.can('export')&&w.can('cost_read')&&w.can('payroll_read')" variant="outline" @click="w.download('operating',{month,currency})"><Download :size="15" />导出核对表</Button></div></header><WorkspaceState /><p v-if="error&&!dialog" class="spray-alert" role="alert">{{ error }}</p>
 <div class="spray-finance-filters"><div class="spray-tabs"><button :class="{active:tab==='economics'}" @click="tab='economics'">经营收支</button><button v-if="w.can('payroll_read')" :class="{active:tab==='payroll'}" @click="tab='payroll'">工资核对</button><button v-if="w.can('cost_read')" :class="{active:tab==='expenses'}" @click="tab='expenses'">费用与回收</button></div><label>期间<input v-model="month" type="month" aria-label="经营期间" /></label><label>币种<select v-model="currency"><option>CNY</option><option>HKD</option><option>USD</option></select></label></div>
 <template v-if="tab==='economics'"><div v-if="!w.can('cost_read')" class="spray-empty spray-panel"><strong>经营金额需要成本查看权限</strong><p>生产实绩仍可在现场执行工作区查看。</p></div><template v-else><div class="spray-economics-layout"><section class="spray-panel"><div class="spray-panel__header"><div><h3>{{ month }} · 经营结构</h3><p class="spray-muted">{{ currency }} · 管理口径</p></div><span class="spray-badge" :class="{'spray-badge--amber':summary?.is_partial}">{{ !summary?'正在核对':summary.is_partial?'资料尚未齐备':'依据已齐备' }}</span></div><div class="spray-economics-rows"><div class="spray-economics-row income"><span>工序产值<small>正常生产合格数 × 确认工序价格</small></span><strong>{{ number(summary?.operating_value) }}</strong></div><div class="spray-economics-row"><span>材料实际耗用<small>按原始批次成本确认，仅计实际耗用</small></span><strong>{{ number(summary?.material_cost) }}</strong></div><div v-if="w.can('payroll_read')" class="spray-economics-row"><span>已确认工资<small>按员工 / 日汇总保底与补贴</small></span><strong>{{ number(summary?.payroll_amount) }}</strong></div><div v-else class="spray-economics-row"><span>员工工资</span><span class="spray-badge spray-badge--gray">权限受限</span></div><div class="spray-economics-row"><span>费用净额<small>已确认纳入口径的支出与回收</small></span><strong>{{ number(summary?.expense_amount) }}</strong></div><div class="spray-economics-result"><div><span>经营结余</span><small>完整成本口径后才形成可比结余</small></div><strong>{{ summary?.surplus == null ? '待核对' : number(summary.surplus) }}</strong></div></div><div class="spray-panel__body"><Button v-if="w.can('cost_write')" variant="outline" @click="open('valuation')"><Plus :size="14" />登记工序产值依据</Button></div></section><aside class="spray-panel spray-coverage"><div class="spray-panel__header"><h3>资料覆盖度</h3><span>{{ completeCount }} / 4</span></div><div class="spray-panel__body"><p class="spray-muted">缺少的数据保留为空，不当作零成本或零工资。</p><div v-for="(label,key) in coverageLabels" :key="key" class="spray-coverage-row"><Check v-if="summary?.coverage[key]==='complete'" :size="16" /><CircleAlert v-else :size="16" /><span>{{ label }}</span><small>{{ stateLabel[summary?.coverage[key]??'unknown'] }}</small></div><div v-if="w.can('settle')&&w.can('payroll_read')" class="spray-period-box"><h3>期间核对与锁月</h3><p>先检查未定价、未核工资、来源差异与退货贷项。</p><Button variant="outline" @click="previewClose">查看锁月核对清单</Button></div></div></aside></div><section class="spray-panel"><div class="spray-panel__header"><h3>已登记工序产值来源</h3><span class="spray-muted">返工不重复登记正常产值</span></div><RecordTable :rows="w.items('valuations').filter(v=>String(v.business_date).startsWith(month))" :columns="[{key:'business_date',label:'实绩日期'},{key:'report_allocation_id',label:'日报分摊来源'},{key:'quantity',label:'合格数量',numeric:true},{key:'price',label:'确认单价',numeric:true},{key:'amount',label:'工序产值',numeric:true},{key:'currency',label:'币种'}]" /></section></template></template>
 <section v-else-if="tab==='payroll'" class="spray-panel"><div class="spray-panel__header"><div><h3>按实际报工核对员工工资</h3><p class="spray-muted">试算与正式确认分开，未确认规则无法正式入账。</p></div><Button v-if="w.can('payroll_write')" @click="open('payroll')"><Calculator :size="15" />按日试算</Button></div><RecordTable :rows="w.items<Payroll>('payroll').filter(p=>p.business_date.startsWith(month))" :columns="[{key:'document_no',label:'核对单'},{key:'business_date',label:'生产日期'},{key:'status',label:'状态'},{key:'currency',label:'币种'}]" @select="selected=$event as Payroll;dialog='payroll-detail';error=''"><template #actions="{row}"><button class="spray-text-button" @click.stop="selected=row as Payroll;dialog='payroll-detail';error=''">查看员工分摊</button></template></RecordTable></section>
 <section v-else class="spray-panel"><div class="spray-panel__header"><h3>费用归集</h3><Button v-if="w.can('cost_write')" variant="outline" @click="open('expense')"><Plus :size="15" />登记费用 / 回收</Button></div><RecordTable :rows="w.items('expenses').filter(e=>String(e.business_date).startsWith(month))" :columns="[{key:'document_no',label:'单据'},{key:'business_date',label:'日期'},{key:'category',label:'类别'},{key:'kind',label:'方向'},{key:'amount',label:'金额',numeric:true},{key:'currency',label:'币种'},{key:'evidence',label:'归集依据'}]"><template #actions="{row}"><template v-if="row.included==null&&w.can('cost_write')"><button class="spray-text-button" @click="confirmExpense(row,true)">确认纳入 · </button><button class="spray-text-button" @click="confirmExpense(row,false)">确认不纳入</button></template><span v-else>{{row.included==null?'待核对':row.included?'已纳入':'不纳入'}}</span></template></RecordTable></section>
 <WorkspaceDialog :open="!!dialog" :title="dialog==='payroll-detail'?'员工工资分摊':dialog==='close'?'期间关闭核对':dialog==='payroll'?'按日生成工资试算':dialog==='valuation'?'登记工序产值':'登记费用与回收'" :wide="dialog==='payroll-detail'" @close="closeDialog">
  <template v-if="dialog==='payroll-detail'&&selected"><div class="spray-actions"><strong>{{ selected.document_no }}</strong><span class="spray-badge" :class="{'spray-badge--amber':selected.status==='trial'}">{{ stateLabel[selected.status] }}</span><span class="spray-muted">{{ selected.business_date }} · {{ selected.currency }}</span></div><div class="spray-table-wrap"><table class="spray-table"><thead><tr><th>员工</th><th class="numeric">基础工资</th><th class="numeric">补足保底</th><th class="numeric">补贴</th><th class="numeric">调整</th><th class="numeric">当日合计</th></tr></thead><tbody><tr v-for="line in selected.lines" :key="line.id"><td>{{ employeeName(line.employee_id) }}</td><td class="numeric">{{ number(line.base_amount) }}</td><td class="numeric">{{ number(line.guarantee) }}</td><td class="numeric">{{ number(line.subsidy) }}</td><td class="numeric">{{ number(line.adjustment) }}</td><td class="numeric"><strong>{{ number(line.payroll_amount) }}</strong></td></tr></tbody></table></div><p class="spray-muted">分摊到分，尾差按稳定员工记录分配；同一天的保底只计算一次。</p></template>
  <template v-else-if="dialog==='close'&&closure"><p>{{ month }} · {{ closure.blockers.length ? `仍有 ${closure.blockers.length} 项待处理` : '核对清单没有阻塞项' }}</p><ul class="spray-close-list"><li v-for="(item,index) in closure.blockers" :key="index"><CircleAlert :size="16" /><span>{{ item.message }}</span><small>{{ item.entity_id?.slice(0,8) }}</small></li></ul><div class="spray-form"><label class="wide">关闭依据<textarea v-model="form.reason" required /></label></div><p class="spray-muted">锁月会冻结当前证据；新的本期业务登记将被阻止。</p></template>
  <form v-else id="spray-finance-form" class="spray-form" @submit.prevent="save" @input="w.dirty.value=true"><template v-if="dialog==='payroll'"><label>核对单号<input v-model="form.document_no" required /></label><label>生产日期<input v-model="w.businessDate.value" type="date" required /></label><label class="wide">工资规则版本<select v-model="form.rule_id" required><option value="">选择明确规则</option><option v-for="rule in wageRules" :key="rule.id" :value="rule.id">{{ rule.label }} · V{{ rule.revision }} · {{ stateLabel[rule.status] }}</option></select></label><fieldset class="wide spray-form"><legend>逐行指定规则（留空沿用上方规则）</legend><label v-for="row in reportRows" :key="row.id">{{row.document_no}} · 行 {{row.id.slice(0,8)}}<select v-model="rowRules[row.id]"><option value="">沿用默认规则</option><option v-for="rule in wageRules" :key="rule.id" :value="rule.id">{{rule.label}} · V{{rule.revision}}</option></select></label></fieldset><fieldset class="wide spray-form"><legend>员工当日补贴与调整</legend><section v-for="(adjust,index) in adjustments" :key="index" class="wide spray-form"><label>员工<select v-model="adjust.employee_id" required><option value="">选择员工</option><option v-for="employee in w.items<Employee>('employees')" :key="employee.id" :value="employee.id">{{employee.name}}</option></select></label><label>补贴<input v-model="adjust.subsidy" inputmode="decimal" required/></label><label>调整金额（允许负数）<input v-model="adjust.adjustment" inputmode="decimal" required/></label><label>调整依据<input v-model="adjust.evidence" required/></label><button type="button" class="spray-text-button" @click="adjustments.splice(index,1)">移除调整</button></section><Button type="button" variant="outline" @click="adjustments.push({employee_id:'',subsidy:'0',adjustment:'0',evidence:''})">增加员工调整</Button></fieldset><p class="wide spray-alert">草稿规则可以试算；确认工资前必须核对并确认规则。</p></template>
  <template v-else-if="dialog==='valuation'"><label class="wide">已确认日报<select v-model="form.report_id" required><option value="">选择实绩来源</option><option v-for="report in w.items('reports').filter(r=>r.status==='confirmed')" :key="report.id" :value="report.id">{{ report.document_no }} · {{ report.business_date }}</option></select></label><label class="wide">确认的工序价格<select v-model="form.rule_id" required><option value="">选择价格版本</option><option v-for="rule in costRules" :key="rule.id" :value="rule.id">{{ rule.label }} · V{{ rule.revision }}</option></select></label></template>
  <template v-else><label>单据编号<input v-model="form.document_no" required /></label><label>费用类别<input v-model="form.category" required /></label><label>业务类型<select v-model="form.kind"><option value="expense">费用支出</option><option value="recovery">回收 / 冲减</option><option value="investment">投入 / 投资</option><option value="memo">参考备忘</option></select></label><label>金额（{{ currency }}）<input v-model="form.amount" inputmode="decimal" required /></label><label class="wide">是否纳入经营成本<select v-model="form.included"><option value="unknown">尚未确认</option><option value="yes">已确认纳入</option><option value="no">已确认不纳入</option></select></label><label class="wide">来源与归集依据<textarea v-model="form.evidence" required /></label></template></form>
  <p v-if="error" class="spray-alert" role="alert">{{ error }}</p><template #footer><Button variant="outline" @click="closeDialog">返回核对</Button><Button v-if="dialog==='payroll-detail'&&selected?.status==='trial'&&w.can('payroll_write')" :disabled="busy" @click="confirmPayroll">确认正式工资</Button><Button v-else-if="dialog==='close'" :disabled="busy||!!closure?.blockers.length||!form.reason.trim()" @click="closePeriod">确认锁定本期</Button><Button v-else-if="!['payroll-detail','close'].includes(dialog)" form="spray-finance-form" type="submit" :disabled="busy">{{ dialog==='payroll'?'生成试算':'确认登记' }}</Button></template>
 </WorkspaceDialog></div>
</template>
