<script setup lang="ts">
import { computed, ref } from 'vue'
import { Banknote, Coins, Receipt, Scale, TrendingUp } from '@lucide/vue'
import { Button } from '@/components/ui/button'
import { sprayProductionApi } from '@/api/sprayProduction'
import { useSprayWorkspace, localDate, str, amount, statusName, errorText, type Entity } from '../workspace'
import EntryForm from '../components/EntryForm.vue'
import PayrollWorkspace from '../components/PayrollWorkspace.vue'
import SpraySegmentedControl from '../components/ui/SpraySegmentedControl.vue'
import SprayStatusPill from '../components/ui/SprayStatusPill.vue'
const s=useSprayWorkspace(),tab=ref('settlements'),preview=ref<Entity|null>(null),formKey=ref(0)
const tabs=[{value:'payroll',label:'员工工资与历史对账',icon:Coins},{value:'rates',label:'工价与预算',icon:Scale},{value:'purchases',label:'采购与耗用',icon:Receipt},{value:'operating',label:'收支分析',icon:TrendingUp},{value:'settlements',label:'月结对账',icon:Banknote}]
const rateFields=[{key:'name',label:'工价版本名称'},{key:'rule_code',label:'策略',options:[{value:'piece_direct',label:'直接计件'},{value:'time_based',label:'计时/非生产活动'}]},{key:'rate',label:'计件/每小时金额',type:'decimal'},{key:'currency',label:'币种',options:[{value:'CNY',label:'人民币 CNY'},{value:'HKD',label:'港币 HKD'}]},{key:'quantity_basis',label:'计件口径',options:[{value:'good',label:'合格数量'},{value:'attempt',label:'加工尝试次数'}]},{key:'effective_date',label:'生效日期',type:'date',value:localDate()},{key:'evidence',label:'来源与适用正加班规则说明',type:'textarea'}]
const purchaseFields=[{key:'document_no',label:'采购单号'},{key:'supplier',label:'供应商'},{key:'material',label:'物料名称/规格'},{key:'quantity',label:'采购数量',type:'decimal'},{key:'unit',label:'采购单位'},{key:'base_unit',label:'基本库存单位'},{key:'conversion',label:'每采购单位对应基本数量',value:'1',type:'decimal'},{key:'conversion_evidence',label:'包装换算依据',optional:true},{key:'price',label:'每采购单位价格',type:'decimal'},{key:'currency',label:'币种',options:[{value:'CNY',label:'人民币 CNY'},{value:'HKD',label:'港币 HKD'}]}]
const customers=computed(()=>[...new Set(s.items('orders').map(o=>str(o,'customer')))].map(value=>({value,label:value})))
async function saveRate(v:Record<string,string>){if(await s.command('rates',{...v,parameters:{rate:v.rate,adjustment:'0'}}))formKey.value++}
async function savePurchase(v:Record<string,string>){if(await s.command('purchases',v))formKey.value++}
async function showPreview(v:Record<string,string>){try{preview.value=await sprayProductionApi.settlementPreview(s.factory,v)}catch(e){s.error=errorText(e)}}
async function confirm(){if(!preview.value)return;const lines=preview.value.lines as Entity[];if(await s.command('settlements',{...preview.value,line_ids:lines.map(v=>v.id).sort()}))preview.value=null}
const wages=computed(()=>s.items('report-lines').filter(r=>s.find('reports',r.report_id)?.status==='confirmed'))
function totalWage(currency:string){return wages.value.reduce((sum,r)=>{const c=r.calculation as Record<string,unknown>|undefined;return sum+(c?.currency===currency?Number(c.amount):0)},0)}
</script>
<template><div class="spray-toolbar"><div><h2>经营核算</h2><p>原币、原凭据、采用版本可追溯；暂算与正式金额分开。</p></div><div class="spray-toolbar-actions"><span class="spray-badge" :class="s.can('cost_read') ? 'done' : 'warn'">成本权限：{{ s.can('cost_read') ? '已下发' : '未授权' }}</span></div></div><div v-if="!s.can('cost_read')" class="spray-empty"><h3>经营数据未授权</h3><p>当前账号可继续生产业务；工资与成本没有下发到浏览器。如需核对成本，请联系厂区管理员开通成本读取权限。</p></div><template v-else><SpraySegmentedControl v-model="tab" :options="tabs" label="经营核算分区" tone="bar" />
  <PayrollWorkspace v-if="tab==='payroll'" /><template v-if="tab==='settlements'"><div class="spray-split"><div class="spray-panel"><h3 class="font-semibold mb-4">客户 / 月份</h3><EntryForm :fields="[{key:'customer',label:'委托客户',options:customers},{key:'period',label:'结算月份',type:'month',value:localDate().slice(0,7)},{key:'currency',label:'计价币种',options:[{value:'HKD',label:'港币 HKD'},{value:'CNY',label:'人民币 CNY'}]}]" submit-label="预览净送货对账" :busy="s.busy" @submit="showPreview" /></div><aside class="spray-panel"><h3 class="font-semibold">对账提示</h3><p class="spray-help">只纳入尚未结算的送货与退货行。请款、加工明细和送货明细引用同一来源。冻结后旧账保留，退货贷项进入新期间。</p></aside></div><section v-if="preview" class="spray-panel"><div class="spray-section-title"><h3>{{ preview.customer }} · {{ preview.period }}</h3><strong class="spray-figure">{{ amount(preview.amount) }} {{ preview.currency }}</strong></div><div v-for="line in (preview.lines as Entity[])" :key="line.id" class="spray-row"><span>{{ str(s.find('shipments',line.shipment_id),'document_no') }} · {{ amount(line.quantity) }} × {{ line.price }}</span><strong>{{ amount(line.amount) }}</strong></div><div v-for="a in (preview.adjustments as Entity[] || [])" :key="a.id" class="spray-row"><span>{{ a.document_no }} · {{ a.reason }}</span><strong>{{ amount(a.amount) }}</strong></div><Button v-if="s.can('settlement') && ((preview.lines as Entity[]).length||(preview.adjustments as Entity[]|undefined)?.length)" class="mt-4" :disabled="s.busy" @click="confirm">确认并冻结本期对账</Button><p v-else class="spray-help">没有当前可确认的结算行，或无确认权限。</p></section><h3 class="font-semibold my-4">已冻结对账</h3><div v-for="r in s.items('settlements')" :key="r.id" class="spray-row"><span>{{ r.customer }} · {{ r.period }}</span><strong>{{ amount(r.amount) }} {{ r.currency }}</strong></div><p v-if="!s.items('settlements').length" class="spray-help">本厂尚无已冻结对账。冻结后旧账保留，退货贷项进入新期间。</p></template>
  <template v-if="tab==='rates'"><section v-if="s.can('cost_write')" class="spray-panel spray-enter"><h3 class="font-semibold mb-4">新增工价版本 · 初始为暂算</h3><EntryForm :key="formKey" :fields="rateFields" :busy="s.busy" @submit="saveRate" /></section><section v-for="(r,rateIndex) in s.items('rates')" :key="r.id" class="spray-panel spray-enter" :style="{ '--spray-enter-delay': Math.min(300, rateIndex * 50) + 'ms' }"><h3 class="font-semibold flex items-center gap-2 flex-wrap">{{ r.name }} <SprayStatusPill :status="r.status" :spinning="str(r,'status')==='provisional'" /></h3><p class="spray-help">{{ r.evidence }} · {{ r.effective_date }}</p><EntryForm v-if="r.status!=='active' && s.can('cost_write')" :fields="[{key:'reason',label:'正式采用依据（负责人、适用范围、正加班口径）'}]" :busy="s.busy" submit-label="明确确认采用" @submit="v=>s.command('rate-activate',{...v,rate_id:r.id})" /></section><p v-if="!s.items('rates').length" class="spray-help">本厂尚无工价版本。新增版本先计入暂算，明确采用依据后才作为正式规则。</p></template>
  <template v-if="tab==='purchases'"><details v-if="s.can('cost_write')" class="spray-panel"><summary>登记采购</summary><EntryForm :key="formKey" class="mt-4" :fields="purchaseFields" :busy="s.busy" @submit="savePurchase" /></details><section v-if="s.can('cost_write')" class="spray-panel"><h3 class="font-semibold mb-4">收货 / 领用 / 退回 / 实耗</h3><EntryForm :fields="[{key:'purchase_id',label:'采购物料',options:s.items('purchases').map(p=>({value:p.id,label:str(p,'document_no')+' · '+str(p,'material')+' ['+str(p,'base_unit')+']'}))},{key:'kind',label:'业务类型',options:[{value:'receipt',label:'采购收货'},{value:'issue',label:'车间领用'},{value:'return',label:'余料退回'},{value:'consume',label:'实际耗用'}]},{key:'document_no',label:'本次物料凭据号'},{key:'business_date',label:'业务日期',type:'date',value:localDate()},{key:'quantity',label:'基本单位数量',type:'decimal'},{key:'order_id',label:'归属工单',optional:true,options:s.items('orders').map(o=>({value:o.id,label:str(o,'document_no')}))},{key:'reason',label:'实测/分摊依据',optional:true}]" :busy="s.busy" @submit="v=>s.command('material-events',v)" /><p class="spray-help">采购金额不直接计耗用。未知“卡”可按同单位记账，不能自动转 KG。</p></section><div v-for="p in s.items('purchases')" :key="p.id" class="spray-panel"><h3 class="font-semibold">{{ p.document_no }} · {{ p.material }}</h3><p class="spray-help">{{ p.supplier }} · 采购 {{ amount(p.quantity) }} {{ p.unit }} · 单价 {{ p.price }} {{ p.currency }}</p><div v-for="e in s.items('material-events').filter(e=>e.purchase_id===p.id)" :key="e.id" class="spray-row"><span>{{ e.document_no }} · {{ ({receipt:'收货',issue:'领用',return:'退回',consume:'实耗'}[str(e,'kind')]) }}</span><span>{{ amount(e.quantity) }} {{ p.base_unit }} · 计耗用 {{ amount(e.cost) }} {{ p.currency }}</span></div></div><p v-if="!s.items('purchases').length" class="spray-help">本厂尚无采购记录。采购金额在收货、领用、实耗后按凭据计入耗用。</p></template>
  <template v-if="tab==='operating'"><div class="spray-note"><p class="spray-help">标准经营口径 · 当前展示已记录覆盖；不称完整月度净利润。</p></div><section v-for="currency in ['HKD','CNY']" :key="currency" class="spray-panel"><h3 class="font-semibold">{{ currency }} 原币凭据</h3><div class="spray-row"><span>已记送货净结算金额</span><strong class="spray-figure">{{ amount(s.items('shipment-lines').filter(l=>l.currency===currency).reduce((sum,l)=>sum+Number(l.amount),0)) }}</strong></div><div class="spray-row"><span>工资已算金额（含暂算，未作为应付总额）</span><strong class="spray-figure">{{ amount(totalWage(currency)) }}</strong></div><div class="spray-row"><span>实际耗用</span><strong class="spray-figure">{{ amount(s.items('material-events').filter(e=>s.find('purchases',e.purchase_id)?.currency===currency).reduce((sum,e)=>sum+Number(e.cost),0)) }}</strong></div></section><p class="spray-help">{{ wages.filter(r=>r.wage_status!=='verified').length }} 条报工工资待核。未归属费用、社保、样板工资和设备投资不自动补扣。</p></template>
</template></template>
