<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { Plus, PackageCheck, Truck, Download, ArrowDownLeft, ArrowUpRight, ClipboardCheck } from '@lucide/vue'
import { Button } from '@/components/ui/button'
import { useSprayPage } from '../usePage'
import { documentNo, number, utc, stateLabel, type Stock, type Batch, type Demand, type RouteVersion, type Delivery, type DeliveryLine, type Entity } from '../contracts'
import WorkspaceDialog from '../components/WorkspaceDialog.vue'
import WorkspaceState from '../components/WorkspaceState.vue'
import RecordTable from '../components/RecordTable.vue'
const w=useSprayPage(['stock','batches','demands','routes','preparations','deliveries','containers','returns'])
const tab=ref('white'), dialog=ref(''), error=ref(''), busy=ref(false), selectedBatch=ref<Batch|null>(null), selectedDelivery=ref<Delivery|null>(null), selectedReturn=ref<DeliveryLine|null>(null)
const tabs=[{key:'white',label:'白件接收'},{key:'wip',label:'在制库存'},{key:'finished',label:'合格成品'},{key:'deliveries',label:'交货验收'},{key:'containers',label:'包材与周转物'},{key:'returns',label:'退货记录'}]
const lines=computed(()=>w.items<Demand>('demands').flatMap(order=>order.lines.map(line=>({...line,order}))))
const stock=computed(()=>w.items<Stock>('stock').filter(stock=>stock.state===tab.value&&Number(stock.quantity)>0))
const lineLabel=(id:string|null)=>{const line=lines.value.find(l=>l.id===id);return line?`${line.item_no} / ${line.part} · ${line.order.document_no}`:'未匹配订单'}
const batchLabel=(id:string)=>w.items<Batch>('batches').find(batch=>batch.id===id)?.document_no??id.slice(0,8)
const receipt=reactive({document_no:documentNo('来料'),line_id:'',item_no:'',part:'',quantity:'',held:'0',rejected:'0',unit:'件',source_ref:''})
function selectLine(){const line=lines.value.find(l=>l.id===receipt.line_id);if(line){receipt.item_no=line.item_no;receipt.part=line.part;receipt.unit=line.unit}}
const prep=reactive({step_id:'',ready:'',expires:'',evidence:''})
const batchRoute=computed(()=>w.items<RouteVersion>('routes').find(route=>route.id===lines.value.find(line=>line.id===selectedBatch.value?.line_id)?.route_id))
function prepare(batch:Batch){selectedBatch.value=batch;prep.step_id=batchRoute.value?.steps[0]?.id??'';prep.ready=new Date(Date.now()+8*3600000).toISOString().slice(0,16);prep.expires='';prep.evidence='';open('prep')}
const delivery=reactive({document_no:documentNo('送货'),counterparty:'',warehouse_ref:''})
const selectedStock=reactive<Record<string,string>>({}), acceptances=reactive<Record<string,{accepted:string;rejected:string;reason:string}>>({})
const eligible=computed(()=>w.items<Stock>('stock').filter(stock=>stock.state==='finished'&&Number(stock.quantity)>0))
function accept(item:Delivery){selectedDelivery.value=item;Object.keys(acceptances).forEach(key=>delete acceptances[key]);item.lines.forEach(line=>{acceptances[line.id]={accepted:'',rejected:'0',reason:''}});open('accept')}
const returned=reactive({quantity:'',reason:''})
const container=reactive({counterparty:'',item:'',owner:'ours',direction:'out',recoverable:true,quantity:'',source_ref:''})
const returnCandidates=computed(()=>w.items<Delivery>('deliveries').flatMap(d=>d.lines.map(l=>({...l,document_no:d.document_no,counterparty:d.counterparty}))).filter(l=>Number(l.accepted)>Number(l.returned)))
function open(kind:string){dialog.value=kind;error.value='';if(kind==='receipt')receipt.document_no=documentNo('来料');if(kind==='delivery'){delivery.document_no=documentNo('送货');Object.keys(selectedStock).forEach(k=>delete selectedStock[k])}}
async function save(){busy.value=true;error.value='';try{
  if(dialog.value==='match'&&selectedBatch.value)await w.command(`batches/${selectedBatch.value.id}/match`,{line_id:matchLine.value},selectedBatch.value.version)
  else if(dialog.value==='receipt')await w.command('batches',{...receipt,line_id:receipt.line_id||null,business_date:w.businessDate.value,accepted:String(Number(receipt.quantity)-Number(receipt.held)-Number(receipt.rejected))})
  else if(dialog.value==='prep'&&selectedBatch.value){const previous=w.items('preparations').find(p=>p.batch_id===selectedBatch.value!.id&&p.step_id===prep.step_id);await w.command('preparations',{batch_id:selectedBatch.value.id,step_id:prep.step_id,ready_at:utc(prep.ready),expires_at:prep.expires?utc(prep.expires):null,evidence:prep.evidence},previous?.version??0)}
  else if(dialog.value==='delivery')await w.command('deliveries',{...delivery,business_date:w.businessDate.value,lines:Object.entries(selectedStock).filter(([,qty])=>Number(qty)>0).map(([stock_id,quantity])=>({stock_id,quantity}))})
  else if(dialog.value==='accept'&&selectedDelivery.value)await w.command(`deliveries/${selectedDelivery.value.id}/accept`,{business_date:w.businessDate.value,lines:Object.entries(acceptances).filter(([,v])=>Number(v.accepted)+Number(v.rejected)>0).map(([delivery_line_id,v])=>({delivery_line_id,accepted:v.accepted||'0',rejected:v.rejected||'0',reason:v.reason}))},selectedDelivery.value.version)
  else if(dialog.value==='return'&&selectedReturn.value)await w.command('returns',{business_date:w.businessDate.value,delivery_line_id:selectedReturn.value.id,...returned},selectedReturn.value.version)
  else if(dialog.value==='container')await w.command('containers',{business_date:w.businessDate.value,...container})
  dialog.value='';await w.load(['stock','batches','demands','preparations','deliveries','containers','returns'])
}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
async function close(){if(w.dirty.value&&!(await w.confirmDiscard('放弃未保存的业务登记？')))return;dialog.value='';w.dirty.value=false}
function unitTotals(item:Delivery, kind:string){const values:Record<string,number>={};for(const row of item.lines){const qty=kind==='pending'?Number(row.quantity)-Number(row.accepted)-Number(row.rejected):Number(row[kind]);values[row.unit]=(values[row.unit]??0)+qty}return Object.entries(values).map(([unit,qty])=>`${number(qty)} ${unit}`).join(' · ')}
const matchLine=ref('')
function matchBatch(batch:Batch){selectedBatch.value=batch;matchLine.value='';open('match')}
const title=computed(()=>({match:'匹配来料与订单',receipt:'接收一批白件',prep:'确认工序准备',delivery:'从合格库存登记交货',accept:'登记交货验收',return:'登记实物退货',container:'登记包材与周转物'})[dialog.value]??'业务登记')
</script>
<template>
  <div class="spray-page"><header class="spray-page-heading"><div><span class="spray-eyebrow">MATERIAL FLOW / 胶件与交收</span><h1>每一批货，都有清楚的去向</h1><p>白件、在制、合格库存和在途分别记录；验收与退货保留原单关联。</p></div><div class="spray-actions"><Button v-if="w.can('export')" variant="outline" @click="w.download(tab==='deliveries'?'delivery':'stock')"><Download :size="15" />导出</Button><Button v-if="w.can('stock_write')" variant="outline" @click="open('delivery')"><Truck :size="16" />登记交货</Button><Button v-if="w.can('stock_write')" @click="open('receipt')"><Plus :size="16" />接收白件</Button></div></header><WorkspaceState /><div class="spray-tabs"><button v-for="item in tabs" :key="item.key" :class="{active:tab===item.key}" @click="tab=item.key">{{ item.label }}</button></div>
    <div v-if="['white','wip','finished'].includes(tab)" class="spray-panel"><div class="spray-panel__header"><h3>{{ tabs.find(t=>t.key===tab)?.label }} · 实时物理库存</h3><span class="spray-muted">预留与已消耗分开记录</span></div><div class="spray-table-wrap"><table class="spray-table"><thead><tr><th>批次 / 来源订单</th><th>状态</th><th class="numeric">库存数量</th><th class="numeric">已预留</th><th class="numeric">可安排</th><th>单位</th><th>操作</th></tr></thead><tbody><tr v-for="lot in stock" :key="lot.id"><td><strong>{{ batchLabel(lot.batch_id) }}</strong><button class="spray-text-button" @click="w.passportId.value=lines.find(l=>l.id===lot.line_id)?.demand_id??null">{{ lineLabel(lot.line_id) }}</button></td><td><span class="spray-badge">{{ stateLabel[lot.state] }}</span></td><td class="numeric">{{ number(lot.quantity) }}</td><td class="numeric">{{ number(lot.reserved) }}</td><td class="numeric">{{ number(Number(lot.quantity)-Number(lot.reserved)) }}</td><td>{{ lot.unit }}</td><td><button v-if="!lot.line_id&&w.can('stock_write')" class="spray-text-button" @click="matchBatch(w.items<Batch>('batches').find(b=>b.id===lot.batch_id)!)">匹配订单</button><button v-if="w.can('plan')&&lot.state!=='finished'&&lot.line_id" class="spray-text-button" @click="prepare(w.items<Batch>('batches').find(b=>b.id===lot.batch_id)!)">确认准备</button></td></tr></tbody></table></div><div v-if="!stock.length" class="spray-empty"><strong>当前没有{{ tabs.find(t=>t.key===tab)?.label }}记录</strong><p>来料和生产实绩确认后，库存会按实际流转更新。</p></div></div>
    <div v-else-if="tab==='deliveries'" class="spray-panel"><div class="spray-panel__header"><h3>交货与验收台账</h3><button v-if="w.can('stock_write')" class="spray-text-button" @click="open('return')">登记退货</button></div><div class="spray-table-wrap"><table class="spray-table"><thead><tr><th>送货单</th><th>日期</th><th>委托方</th><th>状态</th><th class="numeric">交货数量</th><th class="numeric">已验收</th><th class="numeric">在途</th><th>操作</th></tr></thead><tbody><tr v-for="item in w.items<Delivery>('deliveries')" :key="item.id"><td><strong>{{ item.document_no }}</strong><small>{{ item.warehouse_ref||'仓库单号待关联' }}</small></td><td>{{ item.business_date }}</td><td>{{ item.counterparty }}</td><td><span class="spray-badge">{{ stateLabel[item.status] }}</span></td><td class="numeric">{{ unitTotals(item,'quantity') }}</td><td class="numeric">{{ unitTotals(item,'accepted') }}</td><td class="numeric">{{ unitTotals(item,'pending') }}</td><td><button v-if="['dispatched','partial_accepted'].includes(item.status)&&w.can('stock_write')" class="spray-text-button" @click="accept(item)">验收 / 拒收</button></td></tr></tbody></table></div><div v-if="!w.items('deliveries').length" class="spray-empty"><strong>尚无交货单</strong><p>可选择合格成品登记交货，签收后再进入月结核对。</p></div></div>
    <div v-else-if="tab==='containers'" class="spray-panel"><div class="spray-panel__header"><h3>包材与周转物往来</h3><Button v-if="w.can('stock_write')" variant="outline" @click="open('container')"><Plus :size="15" />登记往来</Button></div><RecordTable :rows="w.items('containers')" :columns="[{key:'counterparty',label:'往来方'},{key:'item',label:'物品'},{key:'owner',label:'所有权'},{key:'direction',label:'方向'},{key:'quantity',label:'数量',numeric:true},{key:'business_date',label:'日期'}]" /></div>
    <RecordTable v-else :rows="w.items('returns')" :columns="[{key:'id',label:'退货记录'},{key:'business_date',label:'日期'},{key:'quantity',label:'数量',numeric:true},{key:'reason',label:'退货原因'}]" />
    <WorkspaceDialog :open="!!dialog" :title="title" :wide="['delivery','accept'].includes(dialog)" @close="close"><form id="spray-handover-form" class="spray-form" @input="w.dirty.value=true" @submit.prevent="save">
      <template v-if="dialog==='match'"><p class="wide">{{ selectedBatch?.document_no }} · {{ selectedBatch?.item_no }} / {{ selectedBatch?.part }}</p><label class="wide">确认对应订单<select v-model="matchLine" required><option value="">选择匹配订单</option><option v-for="line in lines" :key="line.id" :value="line.id">{{line.order.document_no}} · {{line.item_no}} / {{line.part}} · {{line.unit}}</option></select></label></template><template v-if="dialog==='receipt'"><label>来料单号<input v-model="receipt.document_no" required /></label><label>匹配订单部位<select v-model="receipt.line_id" @change="selectLine"><option value="">暂不匹配，保留待核</option><option v-for="line in lines" :key="line.id" :value="line.id">{{ line.item_no }} / {{ line.part }} · {{ line.order.document_no }}</option></select></label><label>货号<input v-model="receipt.item_no" required :readonly="!!receipt.line_id" /></label><label>部位<input v-model="receipt.part" required :readonly="!!receipt.line_id" /></label><label>本批总数<input v-model="receipt.quantity" inputmode="numeric" required /></label><label>单位<input v-model="receipt.unit" required /></label><label>待判数量<input v-model="receipt.held" inputmode="numeric" /></label><label>拒收数量<input v-model="receipt.rejected" inputmode="numeric" /></label><p class="wide spray-alert">合格接收 {{ number(Number(receipt.quantity)-Number(receipt.held)-Number(receipt.rejected)) }} {{ receipt.unit }}；本次只登记这一批，不代表全部齐料。</p><label class="wide">来源单号 / 备注<input v-model="receipt.source_ref" /></label></template>
      <template v-if="dialog==='prep'"><label class="wide">准备对应工序<select v-model="prep.step_id" required><option v-for="step in batchRoute?.steps" :key="step.id" :value="step.id">{{ step.name }}</option></select></label><label>准备完成时间<input v-model="prep.ready" type="datetime-local" required /></label><label>有效期截止（可选）<input v-model="prep.expires" type="datetime-local" /></label><label class="wide">备料 / 调机 / 颜色确认依据<textarea v-model="prep.evidence" required /></label></template>
      <template v-if="dialog==='delivery'"><label>送货单号<input v-model="delivery.document_no" required /></label><label>委托方<input v-model="delivery.counterparty" required list="spray-counterparties" /><datalist id="spray-counterparties"><option v-for="name in [...new Set(lines.map(l=>l.order.counterparty))]" :key="name">{{ name }}</option></datalist></label><label class="wide">仓库关联单号<input v-model="delivery.warehouse_ref" placeholder="人工关联原仓库单号" /></label><fieldset class="wide spray-stock-picker"><legend>选择合格库存及本次交货数</legend><label v-for="lot in eligible" :key="lot.id"><span>{{ lineLabel(lot.line_id) }}<small>{{ batchLabel(lot.batch_id) }} · 可交 {{ number(lot.quantity) }} {{ lot.unit }}</small></span><input v-model="selectedStock[lot.id]" inputmode="numeric" aria-label="本次交货数量" placeholder="本次交货数" /></label><p v-if="!eligible.length" class="spray-muted">没有可交合格库存。</p></fieldset></template>
      <template v-if="dialog==='accept'"><p class="wide spray-muted">{{ selectedDelivery?.document_no }} · {{ selectedDelivery?.counterparty }}</p><section v-for="line in selectedDelivery?.lines" :key="line.id" class="wide spray-accept-line"><h3>送货行 {{ line.id.slice(0,8) }} · 在途 {{ number(Number(line.quantity)-Number(line.accepted)-Number(line.rejected)) }}</h3><div v-if="acceptances[line.id]" class="spray-form"><label>本次合格验收<input v-model="acceptances[line.id]!.accepted" inputmode="numeric" /></label><label>本次拒收<input v-model="acceptances[line.id]!.rejected" inputmode="numeric" /></label><label class="wide">拒收原因<input v-model="acceptances[line.id]!.reason" /></label></div></section></template>
      <template v-if="dialog==='return'"><label class="wide">原验收送货行<select :value="selectedReturn?.id??''" required @change="selectedReturn=returnCandidates.find(l=>l.id===($event.target as HTMLSelectElement).value)??null"><option value="">选择原送货行</option><option v-for="line in returnCandidates" :key="line.id" :value="line.id">{{ line.document_no }} · {{ line.counterparty }} · 可退 {{ number(Number(line.accepted)-Number(line.returned)) }}</option></select></label><label>本次退货数量<input v-model="returned.quantity" inputmode="numeric" required /></label><label class="wide">退货原因<textarea v-model="returned.reason" required /></label><p class="wide spray-alert">实物退货进入待判库存；已结算部分须另行登记贷项。</p></template>
      <template v-if="dialog==='container'"><label>往来方<input v-model="container.counterparty" required /></label><label>包材 / 周转物名称<input v-model="container.item" required /></label><label>所有权<select v-model="container.owner"><option value="ours">我方物品</option><option value="theirs">对方物品</option></select></label><label>流转方向<select v-model="container.direction"><option value="out">发出</option><option value="in">收到 / 收回</option></select></label><label>数量<input v-model="container.quantity" inputmode="numeric" required /></label><label class="check"><input v-model="container.recoverable" type="checkbox" />需要回收核对</label><label class="wide">来源单号<input v-model="container.source_ref" /></label></template>
      <p v-if="error" class="spray-alert wide" role="alert">{{ error }}</p></form><template #footer><Button variant="outline" @click="close">取消</Button><Button form="spray-handover-form" type="submit" :disabled="busy">{{ busy?'保存中…':'确认登记' }}</Button></template></WorkspaceDialog>
  </div>
</template>
