<script setup lang="ts">
import { ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { Button } from '@/components/ui/button'
import { sprayProductionApi as api } from '@/api/sprayProduction'
import { useSprayWorkspace, str, errorText, type Entity } from '../workspace'
import HistoryMapping from '../components/HistoryMapping.vue'
const route=useRoute()
const s=useSprayWorkspace(),selected=ref(String(route.params.id ?? '')),sheet=ref(''),page=ref(1),source=ref<Awaited<ReturnType<typeof api.source>>|null>(null),busy=ref(false),reason=ref('')
let generation=0
async function read(){if(!selected.value)return;const current=++generation;try{const result=await api.source(s.factory,selected.value,sheet.value,page.value);if(current===generation)source.value=result}catch(e){s.error=errorText(e)}}
watch([selected,sheet,page],read,{immediate:true})
watch(()=>route.params.id,value=>{selected.value=String(value ?? '');sheet.value='';page.value=1})
async function upload(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;busy.value=true;try{const result=await api.upload(s.factory,file);await s.load();selected.value=result.id;sheet.value='';page.value=1;await read()}catch(e){s.error=errorText(e)}finally{busy.value=false}}
async function archive(){if(await s.command('import-apply',{import_id:selected.value,mode:'historical_evidence',reason:reason.value}))await read()}
function cells(row:Entity){return Object.entries(row.cells as Record<string,Record<string,unknown>>)}
</script>
<template><div class="spray-toolbar"><div><h2>历史资料导入</h2><p>文件识别 → 表页映射 → 逐行差异 → 历史事实与对照关联。</p></div><label v-if="s.can('import')&&s.can('cost_read')" class="spray-pill">{{ busy?'正在识别…':'选择原始 Excel / ET / PDF' }}<input :disabled="busy" type="file" accept=".xlsx,.xls,.et,.pdf" aria-label="上传喷油原始资料" @change="upload" /></label></div><div v-if="!s.can('cost_read')||!s.can('import')" class="spray-empty">原始文件可能包含薪酬，需同时具备资料导入及成本读取权限。</div><template v-else><div class="spray-message">历史证据模式 · 不创建当前库存，不自动确定部件或工资规则。</div><div class="spray-import-layout"><aside class="spray-panel"><h3 class="font-semibold mb-3">来源文件</h3><button v-for="f in s.items('imports')" :key="f.id" class="spray-source" :class="{active:selected===f.id}" @click="selected=f.id;sheet='';page=1"><strong>{{ f.filename }}</strong><small>{{ f.format }} · {{ f.status==='archived'?'已归档':'待核对' }}</small></button><p v-if="!s.items('imports').length" class="spray-help">上传原文件开始预览。原件只读保存。</p><template v-if="source"><h3 class="font-semibold mt-5 mb-2">工作表</h3><button v-for="name in source.sheets" :key="name" class="spray-source" :class="{active:sheet===name}" @click="sheet=name;page=1">{{ name }}</button></template></aside><section v-if="source" class="min-w-0"><div class="spray-panel"><h3 class="font-semibold break-all">{{ source.source.filename }}</h3><p class="spray-code mt-2">SHA-256 {{ source.source.sha256 }}</p><p class="spray-help">数值保留原缓存；错误不当成 0。BIFF 的公式仅交叉核对缓存，未宣称完整公式重算。</p></div><div class="spray-table-wrap"><table class="spray-table"><thead><tr><th>来源坐标</th><th>原值 / 缓存</th><th>公式 / 差异</th><th>分类</th></tr></thead><tbody><template v-for="row in source.rows" :key="row.id"><tr v-for="[address,cell] in cells(row)" :key="row.id+address"><td>{{ row.sheet }}!{{ address }}</td><td>{{ cell.raw_value ?? '无缓存' }}</td><td class="spray-code">{{ cell.raw_formula || cell.validation_status }}</td><td>{{ row.role==='comparison'?'汇总对照':'历史待核' }}</td></tr></template></tbody></table></div><div class="spray-actions my-4"><Button variant="outline" :disabled="page===1" @click="page--">上一页</Button><span>第 {{ page }} 页 · {{ source.total }} 个来源行（含表页说明）</span><Button variant="outline" :disabled="page*30>=source.total" @click="page++">下一页</Button></div><HistoryMapping :key="source.source.id + (sheet || source.sheets[0])" :source="source.source" :sheets="source.sheets" :sheet="sheet" /><section class="spray-panel"><h3 class="font-semibold">归属确认与应用范围</h3><p class="spray-help">当前执行厂区 {{ s.factory }}。本次只关联历史证据；业务建单映射和上线期初仍需分别确认。</p><label class="spray-field">确认来源归属的依据<input v-model="reason" placeholder="例如：表页标题及负责人确认；不确定部分保持待核" /></label><Button class="mt-3" :disabled="!reason||s.busy||source.source.status==='archived'" @click="archive">确认归档历史证据</Button></section></section><div v-else class="spray-empty">选择来源文件查看原值和公式。</div></div></template></template>
<style scoped>.spray-import-layout{display:grid;grid-template-columns:240px minmax(0,1fr);gap:20px}.spray-source{display:block;width:100%;text-align:left;padding:10px;border-radius:8px;overflow-wrap:anywhere}.spray-source.active{background:var(--accent);color:var(--primary)}.spray-source strong,.spray-source small{display:block}.spray-source small{color:var(--muted-foreground);margin-top:4px}.spray-table td{max-width:400px;white-space:normal;overflow-wrap:anywhere}@media(max-width:1000px){.spray-import-layout{grid-template-columns:1fr}}</style>
