<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { Upload, FileSpreadsheet, ChevronRight, Check, Plus, X, ShieldCheck } from '@lucide/vue'
import { Button } from '@/components/ui/button'
import { http } from '@/lib/http'
import { useSprayPage } from '../usePage'
import { type Entity, type Envelope, documentNo, stateLabel, type RouteVersion } from '../contracts'
import { importFields, importLabels, importValues } from '../importFields'
import WorkspaceDialog from '../components/WorkspaceDialog.vue'
import WorkspaceState from '../components/WorkspaceState.vue'
import HistoryPolicyDialog from '../components/HistoryPolicyDialog.vue'
interface Profile {id:string;label:string;targets:string[];sources:string[];payroll:boolean}
interface Cell {coordinate:string;row:number;column:number;raw_value:unknown;value:unknown;cached_value:unknown;formula:string|null;number_format:string;flags:string[]}
interface SourceView {source:Entity&{name:string;sha256:string;format:string};sheets:{name:string;state:string;cells:number}[];sheet:string;rows:{row:number;cells:Cell[]}[];total:number;warnings:{code?:string;message?:string}[];pages?:number}
interface Document {document_key:string;sheet:string;coordinates:string[];target:string;values:Record<string,unknown>;reason:string;primary_source_confirmation:string;mode:string;flags?:string[];conflict_id?:string}
interface Job extends Entity {fingerprint:string;status:string;snapshot:{documents:Document[]};confirmed:{document_key:string;target_id:string}[]}
const w=useSprayPage([]),profiles=ref<Profile[]>([]),profile=ref(''),source=ref<SourceView|null>(null),sheet=ref(''),page=ref(1),error=ref(''),busy=ref(false),job=ref<Job|null>(null),fileInput=ref<HTMLInputElement|null>(null),pendingFile=ref<File|null>(null),uploadId=ref(''),stage=ref('source')
const documents=ref<Document[]>([]),selectedCells=ref<string[]>([]),mappings=reactive<Record<string,string>>({}),edit=ref(false),target=ref('reference'),values=reactive<Record<string,string>>({}),reason=ref(''),primary=ref(''),mode=ref('current'),key=ref(''),month=ref(w.businessDate.value.slice(0,7)),pdfPage=ref('1')
const active=computed(()=>profiles.value.find(p=>p.id===profile.value)),fields=computed(()=>importFields[target.value]??[]),cells=computed(()=>source.value?.rows.flatMap(r=>r.cells)??[])
watch(()=>w.ready.value,async ready=>{if(ready&&w.can('import'))try{profiles.value=(await w.query<Profile[]>('import-profiles')).data.filter(p=>!p.payroll||w.can('payroll_read'));profile.value=profiles.value[0]?.id??'';if(w.can('cost_read'))await w.load(['imports'])}catch(cause){error.value=w.explain(cause)}},{immediate:true})
async function upload(event?:Event){if(event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;pendingFile.value=file;uploadId.value=crypto.randomUUID()}if(!pendingFile.value)return;busy.value=true;error.value='';const generation=w.contextVersion.value;try{const data=new FormData();data.append('file',pendingFile.value);data.append('options',JSON.stringify({factory_id:w.factory.value,operation_id:uploadId.value,expected_version:0,profile:profile.value}));const response=await http.post<Envelope<Entity>>('/spray-operations/imports/upload',data,{headers:{'Content-Type':undefined}});if(generation!==w.contextVersion.value)return;pendingFile.value=null;source.value=(await w.query<SourceView>('sources/'+response.data.data.id)).data;sheet.value=source.value.sheet;page.value=1;documents.value=[];job.value=null;stage.value='source'}catch(cause){error.value=w.explain(cause)+'；重试会使用原上传编号'}finally{busy.value=false}}
async function loadSheet(delta=0){if(!source.value)return;page.value=Math.max(1,page.value+delta);try{source.value=(await w.query<SourceView>('sources/'+source.value.source.id,{sheet:sheet.value,page:page.value})).data}catch(cause){error.value=w.explain(cause)}}
function toggle(cell:Cell){const idx=selectedCells.value.indexOf(cell.coordinate);if(idx>=0)selectedCells.value.splice(idx,1);else selectedCells.value.push(cell.coordinate)}
function newDoc(){if(!source.value)return;target.value=active.value?.targets[0]??'reference';key.value=documentNo('来源');reason.value='';primary.value='';mode.value='current';resetValues();edit.value=true;void loadOptions()}
function resetValues(){for(const k of Object.keys(values))delete values[k];for(const field of fields.value){values[field.key]=field.type==='date'?w.businessDate.value:field.key==='currency'?'CNY':field.key==='unit'?'件':field.key==='month'?month.value:''}}
async function loadOptions(){resetValues();const collections=[...new Set(fields.value.flatMap(f=>f.collection?[f.collection]:[]))];if(target.value==='opening')collections.push('routes');if(collections.length)await w.load(collections)}
function applyCell(field:string){const cell=cells.value.find(c=>c.coordinate===mappings[field]);if(!cell)return;if(cell.formula&&cell.cached_value==null){error.value='公式缓存为空，请输入经人工核对的值并说明依据';return}values[field]=String(cell.formula?cell.cached_value??'':cell.value??cell.raw_value??'');if(!selectedCells.value.includes(cell.coordinate))selectedCells.value.push(cell.coordinate);w.dirty.value=true}
function addDocument(){try{const coords=source.value?.source.format==='PDF'?['page:'+pdfPage.value]:[...selectedCells.value];if(!coords.length)throw new Error('请先选择来源单元格或 PDF 页码');const linked=target.value==='opening'?w.items<RouteVersion>('routes').find(r=>r.id===w.items('demand-lines').find(l=>l.id===values.line_id)?.route_id):target.value==='report'?w.items('tasks').find(r=>r.id===values.task_id):target.value==='return'?w.items('delivery-lines').find(r=>r.id===values.delivery_line_id):undefined;documents.value.push({document_key:key.value,sheet:source.value?.source.format==='PDF'?'PDF':sheet.value,coordinates:coords,target:target.value,values:importValues(target.value,values,linked),reason:reason.value,primary_source_confirmation:primary.value,mode:target.value==='opening'?'opening':mode.value});edit.value=false;selectedCells.value=[];w.dirty.value=true}catch(cause){error.value=w.explain(cause)}}
async function preview(){if(!source.value)return;busy.value=true;error.value='';try{job.value=await w.command<Job>('imports/preview',{source_id:source.value.source.id,profile:profile.value,business_month:month.value,mappings:{...mappings},documents:documents.value});stage.value='confirm';await w.load(['imports'])}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
async function confirm(doc:Document){if(!job.value)return;busy.value=true;error.value='';try{job.value=await w.command<Job>(`imports/${job.value.id}/confirm`,{fingerprint:job.value.fingerprint,document_key:doc.document_key},job.value.version);await w.load(['imports'])}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
async function cancelJob(){if(!job.value)return;const reason=await w.promptReason('结束此预览的原因，已成功的单据仍会保留');if(!reason)return;try{job.value=await w.command<Job>(`imports/${job.value.id}/cancel`,{business_date:w.businessDate.value,reason},job.value.version);await w.load(['imports'])}catch(cause){error.value=w.explain(cause)}}
async function resume(row:Entity){try{job.value=(await w.query<Job>('imports/'+row.id)).data;stage.value='confirm'}catch(cause){error.value=w.explain(cause)}}
function label(row:Entity){return String(row.document_no??row.name??row.code??row.item_no??row.id.slice(0,8))+(row.quantity?' · '+row.quantity:'')}
async function close(){if(w.dirty.value&&!(await w.confirmDiscard('放弃此条尚未加入预览的填写？')))return;edit.value=false;w.dirty.value=documents.value.length>0}
</script>
<template><div class="spray-page"><header class="spray-page-heading"><div><span class="spray-eyebrow">SOURCE DESK / 导入中心</span><h1>先核对来源，再形成业务事实</h1><p>保留原始坐标、公式和缓存值。每张业务单据单独确认，可从成功位置继续。</p></div><div class="spray-actions"><HistoryPolicyDialog/><span class="spray-badge"><ShieldCheck :size="14"/>当前执行工厂独立导入</span></div></header><WorkspaceState/><p v-if="error" class="spray-alert" role="alert">{{error}}</p><div class="spray-import-steps"><button :class="{active:stage==='source'}" @click="stage='source'">01 来源与映射</button><ChevronRight :size="14"/><button :class="{active:stage==='confirm'}" :disabled="!job" @click="stage='confirm'">02 逐单确认</button><ChevronRight :size="14"/><button :class="{active:stage==='history'}" @click="stage='history'">03 导入记录</button></div>
 <template v-if="stage==='source'"><section class="spray-panel"><div class="spray-panel__body spray-import-upload"><FileSpreadsheet :size="32"/><div><h3>{{source?.source.name??'选择需要核对的来源文件'}}</h3><p class="spray-muted">Excel / WPS 表格或 PDF · 20 MB 以内</p></div><select v-model="profile" :disabled="!!source" aria-label="资料配置"><option v-for="p in profiles" :key="p.id" :value="p.id">{{p.sources.join('/')}} · {{p.label}}</option></select><input ref="fileInput" type="file" class="sr-only" @change="upload"/><Button :disabled="busy||!w.can('cost_read')" @click="fileInput?.click()"><Upload :size="15"/>{{busy?'读取中…':'选择文件'}}</Button><Button v-if="pendingFile" variant="outline" @click="upload()">重试上传</Button><button v-if="source" class="spray-text-button" @click="source=null;documents=[];job=null;w.dirty.value=false">开始另一份资料</button></div></section>
 <template v-if="source"><p v-if="source.warnings.length" class="spray-alert">{{source.warnings.map(warn=>typeof warn==='string'?warn:warn.message??warn.code).join('；')}}</p><div class="spray-import-layout"><section class="spray-panel"><div class="spray-panel__header"><h3>来源单元格</h3><select v-if="source.sheets.length" v-model="sheet" aria-label="来源工作表" @change="page=1;selectedCells=[];loadSheet()"><option v-for="s in source.sheets" :key="s.name" :value="s.name">{{s.name}} · {{s.state==='visible'?'可见':'隐藏'}} · {{s.cells}} 格</option></select></div><div v-if="source.source.format==='PDF'" class="spray-panel__body"><p>PDF 共 {{source.pages}} 页，请人工阅读原文后登记来源页码。</p><label>证据页码 <input v-model="pdfPage" type="number" min="1" :max="source.pages"/></label></div><div v-else class="spray-source-grid"><div v-for="row in source.rows" :key="row.row" class="spray-source-row"><span>{{row.row}}</span><button v-for="cell in row.cells" :key="cell.coordinate" :class="{selected:selectedCells.includes(cell.coordinate),warning:cell.flags.length}" :title="`${cell.coordinate}\n${cell.formula??cell.raw_value??''}\n格式 ${cell.number_format}\n${cell.flags.join(' / ')}`" @click="toggle(cell)"><small>{{cell.coordinate}}{{cell.formula?' ƒ':''}}</small><strong>{{cell.value??cell.cached_value??cell.raw_value??'无缓存'}}</strong><em v-if="cell.flags.length">需复核</em></button></div></div><div class="spray-panel__body spray-actions"><button class="spray-secondary" :disabled="page===1" @click="loadSheet(-1)">上一页</button><span class="spray-muted">第 {{page}} 页 · {{source.total}} 行</span><button class="spray-secondary" :disabled="page*50>=source.total" @click="loadSheet(1)">下一页</button><span class="spray-muted">已选 {{selectedCells.length}} 个证据单元格</span></div></section><aside class="spray-panel"><div class="spray-panel__header"><h3>待导入单据</h3><button class="spray-icon-button" aria-label="添加业务单据" @click="newDoc"><Plus :size="18"/></button></div><div v-if="!documents.length" class="spray-empty"><strong>逐条建立映射</strong><p>选择来源单元格，再填写业务含义、主事实来源和差异说明。</p><Button variant="outline" @click="newDoc">添加第一张单据</Button></div><div v-for="(doc,index) in documents" :key="doc.document_key" class="spray-import-doc"><strong>{{doc.document_key}}</strong><span>{{importLabels[doc.target]}} · {{doc.sheet}}</span><small>{{doc.coordinates.join('、')}}</small><button class="spray-icon-button" aria-label="移除待导入单据" @click="documents.splice(index,1)"><X :size="14"/></button></div><div class="spray-panel__body spray-form"><label class="wide">归属业务月份<input v-model="month" type="month"/></label><Button class="wide" :disabled="busy||!documents.length" @click="preview">冻结核对预览 <ChevronRight :size="15"/></Button></div></aside></div><p class="spray-muted spray-hash">来源指纹 {{source.source.sha256}}</p></template></template>
 <section v-else-if="stage==='confirm'&&job" class="spray-panel"><div class="spray-panel__header"><h3>逐单确认 · {{job.confirmed.length}} / {{job.snapshot.documents.length}}</h3><button v-if="['review','partial'].includes(job.status)" class="spray-text-button" @click="cancelJob">结束剩余预览</button><span class="spray-badge">{{stateLabel[job.status]??job.status}}</span></div><article v-for="doc in job.snapshot.documents" :key="doc.document_key" class="spray-import-review"><div><strong>{{doc.document_key}} · {{importLabels[doc.target]}}</strong><p>{{doc.sheet}} / {{doc.coordinates.join('、')}}</p><small>核对依据：{{doc.reason}}</small><small>主事实来源：{{doc.primary_source_confirmation}}</small><p v-if="doc.flags?.length" class="spray-alert">{{doc.flags.join(' · ')}}</p><p v-if="doc.conflict_id" class="spray-alert">已有相同业务事实，请核对主来源，不能重复确认。</p></div><span v-if="job.confirmed.some(c=>c.document_key===doc.document_key)" class="spray-badge"><Check :size="14"/>已入账</span><Button v-else :disabled="busy||!!doc.conflict_id||job.status==='cancelled'" @click="confirm(doc)">确认此单</Button></article><div class="spray-panel__body"><p class="spray-muted">修改任何字段须重新生成预览；已确认单据保留原回执，重试不会重复入账。</p></div></section>
 <section v-else-if="stage==='history'" class="spray-panel"><div v-if="!w.items('imports').length" class="spray-empty">暂无导入记录</div><button v-for="row in w.items('imports')" :key="row.id" class="spray-queue-row" @click="resume(row)"><div><strong>{{profiles.find(p=>p.id===row.profile)?.label??row.profile}}</strong><small>{{row.created_at}}</small></div><span class="spray-badge">{{stateLabel[String(row.status)]??row.status}}</span><ChevronRight :size="16"/></button></section>
 <WorkspaceDialog :open="edit" title="核对来源与业务映射" wide @close="close"><p v-if="error" class="spray-alert" role="alert">{{error}}</p><form class="spray-form" @input="w.dirty.value=true" @submit.prevent="addDocument"><label>业务含义<select v-model="target" @change="loadOptions"><option v-for="kind in active?.targets" :key="kind" :value="kind">{{importLabels[kind]}}</option></select></label><label>来源业务单据键<input v-model="key" required/></label><label v-for="field in fields" :key="field.key">{{field.label}}<select v-if="field.collection" v-model="values[field.key]" :required="!field.optional"><option value="">{{field.optional?'尚未关联':'请选择'}}</option><option v-for="row in w.items(field.collection)" :key="row.id" :value="row.id">{{label(row)}}</option></select><select v-else-if="field.options" v-model="values[field.key]" required><option value="">请选择</option><option v-for="opt in field.options" :key="opt.value" :value="opt.value">{{opt.label}}</option></select><input v-else v-model="values[field.key]" :type="field.type==='date'?'date':'text'" :inputmode="field.type==='number'?'decimal':undefined" :required="!field.optional"/><select v-if="!field.collection&&!field.options&&cells.length" v-model="mappings[field.key]" :aria-label="`映射${field.label}`" @change="applyCell(field.key)"><option value="">手工核对填写 / 选择来源格</option><option v-for="cell in cells" :key="cell.coordinate" :value="cell.coordinate">{{cell.coordinate}} · {{String(cell.value??cell.cached_value??cell.raw_value??'无缓存').slice(0,45)}}</option></select></label><label v-if="target==='reference'">资料用途<select v-model="mode"><option value="current">本期参考证据</option><option value="historical_reference">历史参考，不生成实绩</option><option value="opening">期初核对依据</option></select></label><label class="wide">差异 / 公式 / 人工核对说明<textarea v-model="reason" required placeholder="记录实际业务含义、公式缓存错误的处理和金额差异确认依据"/></label><label class="wide">主事实来源确认<textarea v-model="primary" required placeholder="确认此来源是主单据，与其他跟踪表、日报、入库表如何去重"/></label><p class="wide spray-muted">证据 {{selectedCells.join('、')||`PDF 第 ${pdfPage} 页`}}。负数必须匹配退货或保留参考，不可直接形成正常生产。</p><div class="wide spray-actions"><Button type="submit">加入待核对单据</Button><Button type="button" variant="outline" @click="close">取消</Button></div></form></WorkspaceDialog>
 </div></template>
