<script setup lang="ts">
import { computed, ref } from 'vue'
import EntryForm from '../components/EntryForm.vue'
import OpeningBalances from '../components/OpeningBalances.vue'
import { useSprayWorkspace, localDate, str, amount } from '../workspace'
const s=useSprayWorkspace(),tab=ref('receipt'),formKey=ref(0)
const tabs=[['receipt','胶件接收'],['shipment','成品送货'],['return','客户退回'],['containers','容器往来']]
const lineOptions=computed(()=>s.items('lines').map(l=>({value:l.id,label:s.lineLabel(l)})))
const batchOptions=computed(()=>s.items('batches').map(b=>({value:b.id,label:s.batchLabel(b)+' · 可交 '+amount(s.balances[b.id]?.finished)})))
const fields=computed(()=>tab.value==='receipt'?[{key:'document_no',label:'来源送货单号'},{key:'business_date',label:'实际来料日期',type:'date',value:localDate()},{key:'line_id',label:'工单部件',options:lineOptions.value},{key:'source_line',label:'原送货单行号',value:'1'},{key:'accepted',label:'接受数量',type:'decimal'},{key:'held',label:'待检数量',type:'decimal',value:'0'},{key:'rejected',label:'拒收数量',type:'decimal',value:'0'}]:tab.value==='shipment'?[{key:'document_no',label:'送货单号'},{key:'business_date',label:'送货日期',type:'date',value:localDate()},{key:'customer',label:'收货客户',options:[...new Set(s.items('orders').map(o=>str(o,'customer')))].map(v=>({value:v,label:v}))},{key:'batch_id',label:'成品批次',options:batchOptions.value},{key:'quantity',label:'送出件数',type:'decimal'}]:tab.value==='return'?[{key:'document_no',label:'退货凭据号'},{key:'business_date',label:'退货业务日期',type:'date',value:localDate()},{key:'shipment_line_id',label:'原送货明细',options:s.items('shipment-lines').filter(l=>Number(l.quantity)>0).map(l=>({value:l.id,label:str(s.find('shipments',l.shipment_id),'document_no')+' · '+s.batchLabel(s.find('batches',l.batch_id))}))},{key:'quantity',label:'退回件数',type:'decimal'},{key:'reason',label:'退回原因'}]:[{key:'customer',label:'往来客户'},{key:'document_no',label:'关联凭据号'},{key:'name',label:'容器名称'},{key:'unit',label:'容器单位',value:'个'},{key:'quantity',label:'往来数量（发出正数、收回负数）',type:'decimal'},{key:'reason',label:'说明',optional:true}])
async function save(v:Record<string,string>){let result;if(tab.value==='receipt')result=await s.command('receipts',{document_no:v.document_no,business_date:v.business_date,lines:[v]});else if(tab.value==='shipment')result=await s.command('shipments',{document_no:v.document_no,customer:v.customer,business_date:v.business_date,lines:[v]});else result=await s.command(tab.value==='return'?'returns':'returnables',v);if(result)formKey.value++}
</script>
<template><div class="spray-toolbar"><div><h2>收发交接</h2><p>每张凭据只记一次；历史累计不代替今日实存，来料、送出与退回分别登记。</p></div><div class="spray-toolbar-actions"><span class="spray-badge">登记权限：{{ s.can('logistics') ? '可登记' : '只读查看' }}</span></div></div>
  <OpeningBalances /><div class="spray-tabs" role="toolbar" aria-label="收发交接分区"><button v-for="t in tabs" :key="t[0]" :aria-pressed="tab===t[0]" :class="{active:tab===t[0]}" @click="tab=t[0]??'receipt'">{{ t[1] }}</button></div>
  <div class="spray-split"><section v-if="s.can('logistics')" class="spray-panel"><h3 class="font-semibold mb-4">{{ tabs.find(t=>t[0]===tab)?.[1] }}登记</h3><EntryForm :key="tab+formKey" :fields="fields" :busy="s.busy" :submit-label="tab==='receipt'?'确认实收':tab==='shipment'?'确认送出':tab==='return'?'登记退货待判':'登记容器往来'" @submit="save" /></section><aside class="spray-panel"><h3 class="font-semibold">数量核对</h3><p class="spray-help" v-if="tab==='receipt'">来料总数 = 接受 + 待检 + 拒收。仅接受量进入首工序可用库存；同单多行可使用不同原行号继续登记。</p><p class="spray-help" v-else-if="tab==='shipment'">从末工序合格库存送出。采用工单结算价快照，待定价时不能记正式月结金额。</p><p class="spray-help" v-else-if="tab==='return'">保留原送货凭据，另记退货并转入待判。已月结期间的退货须登记到开放期间。</p><p class="spray-help" v-else>容器与加工件数分开。发出记正数，收回记负数；不自动收费。</p></aside></div>
  <div class="spray-table-wrap"><p class="spray-table-caption">{{ tabs.find(t=>t[0]===tab)?.[1] }}凭据 · 共 {{ tab==='receipt' ? s.items('batches').length : tab==='containers' ? s.items('returnables').length : s.items('shipments').length }} 行</p><table v-if="tab==='receipt'" class="spray-table"><thead><tr><th>来源单</th><th>部件</th><th>日期</th><th>总来料</th><th>检查</th></tr></thead><tbody><tr v-for="b in s.items('batches')" :key="b.id"><td>{{ b.document_no }} / {{ b.source_line }}</td><td>{{ s.lineLabel(s.find('lines',b.line_id)) }}</td><td>{{ b.business_date }}</td><td class="num">{{ amount(b.received) }}</td><td><button class="spray-pill" @click="s.selection=b.id">查看流转</button></td></tr></tbody></table><table v-else-if="tab==='containers'" class="spray-table"><thead><tr><th>客户</th><th>容器</th><th>发出/收回</th><th>凭据</th></tr></thead><tbody><tr v-for="r in s.items('returnables')" :key="r.id"><td>{{ r.customer }}</td><td>{{ r.name }}</td><td class="num">{{ amount(r.quantity) }} {{ r.unit }}</td><td>{{ r.document_no }}</td></tr></tbody></table><table v-else class="spray-table"><thead><tr><th>凭据号</th><th>客户</th><th>日期</th><th>类型</th></tr></thead><tbody><tr v-for="r in s.items('shipments')" :key="r.id"><td>{{ r.document_no }}</td><td>{{ r.customer }}</td><td>{{ r.business_date }}</td><td>{{ r.kind==='return'?'退货贷项':'送货' }}</td></tr></tbody></table></div>
  <p v-if="tab==='receipt'&&!s.items('batches').length" class="spray-help">尚无来料批次。登记实际来料后，接受量才进入可用库存。</p><p v-else-if="tab==='containers'&&!s.items('returnables').length" class="spray-help">尚无容器往来记录。发出记正数、收回记负数，不自动收费。</p><p v-else-if="tab!=='receipt'&&tab!=='containers'&&!s.items('shipments').length" class="spray-help">尚无送退货凭据。从末工序合格库存送出并保留原凭据。</p>
</template>
