<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { Plus, ArrowDownToLine, PaintBucket, Download, ArrowRight, Package } from '@lucide/vue'
import { Button } from '@/components/ui/button'
import { useSprayPage } from '../usePage'
import { documentNo, number, type Entity, type Rule } from '../contracts'
import WorkspaceDialog from '../components/WorkspaceDialog.vue'
import WorkspaceState from '../components/WorkspaceState.vue'
import RecordTable from '../components/RecordTable.vue'
interface PurchaseLine extends Entity { purchase_id:string;material_id:string;quantity:string;unit:string;price?:string|null;received:string;cancelled:string;due_date:string }
interface Purchase extends Entity {document_no:string;supplier:string;business_date:string;currency:string;status:string;lines:PurchaseLine[]}
interface Lot extends Entity {material_id:string;quantity:string;warehouse:string;floor:string;consumed:string;unit:string;unit_cost?:string|null;currency:string;purchase_line_id:string}
const w=useSprayPage(['materials','purchases','material-lots','material-movements','rules','demands'])
const tab=ref('purchases'), dialog=ref(''), error=ref(''), busy=ref(false), selected=ref<Lot|null>(null)
const purchases=computed(()=>w.items<Purchase>('purchases')), lots=computed(()=>w.items<Lot>('material-lots'))
const purchaseLines=computed(()=>purchases.value.flatMap(p=>p.lines.map(line=>({...line,purchase:p}))))
const materialName=(id:string)=>{const material=w.items('materials').find(m=>m.id===id);return material?`${material.code} ${material.name}`:id.slice(0,8)}
const form=reactive({document_no:documentNo('采购'),supplier:'',currency:'CNY',tax_basis:'',source_ref:'',material_id:'',quantity:'',unit:'',price:'',due_date:'',purchase_line_id:'',conversion_rule_id:'',kind:'issue',issue_id:'',reason:'',old_price:'',new_price:'',unit_cost:''})
const newLines=ref<{material_id:string;quantity:string;unit:string;price:string;due_date:string}[]>([])
function open(kind:string,lot?:Lot){dialog.value=kind;error.value='';selected.value=lot??null;form.document_no=documentNo(kind==='receipt'?'材料入库':'采购');form.quantity='';form.reason='';form.issue_id='';form.kind='issue';newLines.value=[]}
function selectPurchase(){const line=purchaseLines.value.find(l=>l.id===form.purchase_line_id);if(line){form.supplier=line.purchase.supplier;form.unit=line.unit;form.material_id=line.material_id}}
function addLine(){if(!form.material_id||!form.quantity||!form.unit||!form.due_date){error.value='请填写物料、数量、单位和交货期';return}newLines.value.push({material_id:form.material_id,quantity:form.quantity,unit:form.unit,price:form.price,due_date:form.due_date});form.quantity='';form.price='';error.value=''}
async function save(){busy.value=true;error.value='';try{
 if(dialog.value==='purchase'){if(form.quantity)addLine();if(!newLines.value.length)throw new Error('至少添加一项采购物料');await w.command('purchases',{document_no:form.document_no,supplier:form.supplier,currency:form.currency,tax_basis:form.tax_basis,source_ref:form.source_ref,business_date:w.businessDate.value,lines:newLines.value.map(l=>({...l,price:l.price||null}))})}
 else if(dialog.value==='cancel'){const line=purchaseLines.value.find(l=>l.id===form.purchase_line_id);if(!line)throw new Error('请选择采购行');await w.command(`purchases/${line.purchase.id}/cancel`,{line_id:line.id,quantity:form.quantity,reason:form.reason,business_date:w.businessDate.value},line.purchase.version)}
 else if(dialog.value==='receipt')await w.command('material-receipts',{document_no:form.document_no,supplier:form.supplier,source_ref:form.source_ref,business_date:w.businessDate.value,lines:[{purchase_line_id:form.purchase_line_id,quantity:form.quantity,unit:form.unit,conversion_rule_id:form.conversion_rule_id||null}]})
 else if(dialog.value==='move'&&selected.value)await w.command(`material-lots/${selected.value.id}/move`,{business_date:w.businessDate.value,kind:form.kind,quantity:form.quantity,issue_id:form.kind==='issue'?null:form.issue_id,reason:form.reason},selected.value.version)
 else if(dialog.value==='cost'&&selected.value)await w.command(`material-lots/${selected.value.id}/cost`,{business_date:w.businessDate.value,unit_cost:form.unit_cost,evidence:form.reason},selected.value.version)
 else if(dialog.value==='saving')await w.command('savings',{business_date:w.businessDate.value,purchase_line_id:form.purchase_line_id||null,quantity:form.quantity,old_price:form.old_price,new_price:form.new_price,currency:form.currency,source_ref:form.source_ref})
 await w.load(['purchases','material-lots','material-movements',...(w.can('cost_read')?['savings']:[])]);dialog.value='';w.dirty.value=false
}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
async function refreshLot(){if(!selected.value)return;try{const latest=await w.query<Lot>('material-lots/'+selected.value.id);selected.value=latest.data;error.value='已更新批次库存与版本，请核对上方余量后再次确认；当前填写保留'}catch(cause){error.value=w.explain(cause)}}
const selectedIssues=computed(()=>w.items('material-movements').filter(m=>m.kind==='issue'&&m.lot_id===selected.value?.id))
function changeTab(key:string){tab.value=key;if(key==='savings'&&w.can('cost_read'))void w.load(['savings'])}
async function close(){if(w.dirty.value&&!(await w.confirmDiscard('放弃当前未保存的登记？')))return;dialog.value='';w.dirty.value=false}
const title=computed(()=>({cost:'确认原始批次成本',cancel:'取消未到货采购数量',purchase:'登记油漆采购单',receipt:'匹配采购并接收到货',move:'登记领料、退回或实际耗用',saving:'登记采购节约分析'})[dialog.value]??'材料登记')
</script>
<template>
 <div class="spray-page"><header class="spray-page-heading"><div><span class="spray-eyebrow">PAINT & PROCUREMENT / 油漆与采购</span><h1>从采购到每一笔实际耗用</h1><p>保留采购原价、实收批次与原领料关联，未知成本持续标记待确认。</p></div><div class="spray-actions"><Button v-if="w.can('export')&&w.can('cost_read')" variant="outline" @click="w.download(tab==='purchases'?'purchase':'material')"><Download :size="15" />导出</Button><Button v-if="w.can('procure')" variant="outline" @click="open('receipt')"><ArrowDownToLine :size="16" />登记到货</Button><Button v-if="w.can('procure')&&w.can('cost_write')" @click="open('purchase')"><Plus :size="16" />新建采购</Button></div></header><WorkspaceState />
 <div class="spray-tabs"><button :class="{active:tab==='purchases'}" @click="changeTab('purchases')">采购与到货</button><button :class="{active:tab==='lots'}" @click="changeTab('lots')">批次库存</button><button :class="{active:tab==='movements'}" @click="changeTab('movements')">领退与耗用</button><button v-if="w.can('cost_read')" :class="{active:tab==='savings'}" @click="changeTab('savings')">采购节约分析</button></div>
 <div v-if="tab==='purchases'" class="spray-panel"><div class="spray-panel__header"><h3>采购跟进</h3><span class="spray-muted">采购单 → 匹配到货 → 批次库存</span></div><div class="spray-table-wrap"><table class="spray-table"><thead><tr><th>采购单 / 供应商</th><th>物料</th><th class="numeric">采购数量</th><th class="numeric">已收数量</th><th v-if="w.can('cost_read')" class="numeric">原单价</th><th>交货期</th><th>收货进度</th><th>操作</th></tr></thead><tbody><tr v-for="line in purchaseLines" :key="line.id"><td><strong>{{ line.purchase.document_no }}</strong><small>{{ line.purchase.supplier }}</small></td><td>{{ materialName(line.material_id) }}</td><td class="numeric">{{ number(line.quantity) }} {{ line.unit }}</td><td class="numeric">{{ number(line.received) }}</td><td v-if="w.can('cost_read')" class="numeric">{{ number(line.price) }} {{ line.purchase.currency }}</td><td>{{ line.due_date }}</td><td><span class="spray-badge" :class="{'spray-badge--amber':Number(line.received)<Number(line.quantity)-Number(line.cancelled)}">{{ Number(line.received)>=Number(line.quantity)-Number(line.cancelled)?'收货完成':'等待到货' }}</span></td><td><button v-if="w.can('procure')" class="spray-text-button" @click="open('receipt');form.purchase_line_id=line.id;selectPurchase()">接收本单</button><button v-if="w.can('procure')&&Number(line.quantity)>Number(line.received)+Number(line.cancelled)" class="spray-text-button" @click="open('cancel');form.purchase_line_id=line.id;form.quantity=String(Number(line.quantity)-Number(line.received)-Number(line.cancelled));form.reason=''"> · 取消余量</button></td></tr></tbody></table></div><div v-if="!purchaseLines.length" class="spray-empty"><strong>尚无采购记录</strong><p>登记供应商、原单号及物料明细，再按实收到货建立批次。</p></div></div>
 <div v-else-if="tab==='lots'" class="spray-panel"><div class="spray-table-wrap"><table class="spray-table"><thead><tr><th>物料 / 批次</th><th class="numeric">仓库</th><th class="numeric">车间余料</th><th class="numeric">已耗用</th><th>单位</th><th v-if="w.can('cost_read')" class="numeric">原批次单位成本</th><th>操作</th></tr></thead><tbody><tr v-for="lot in lots" :key="lot.id"><td><strong>{{ materialName(lot.material_id) }}</strong><small>{{ lot.id.slice(0,8) }}</small></td><td class="numeric">{{ number(lot.warehouse) }}</td><td class="numeric">{{ number(lot.floor) }}</td><td class="numeric">{{ number(lot.consumed) }}</td><td>{{ lot.unit }}</td><td v-if="w.can('cost_read')" class="numeric">{{ number(lot.unit_cost) }} {{ lot.currency }}</td><td><button v-if="w.can('stock_write')" class="spray-text-button" @click="open('move',lot)">领料 / 退回 / 耗用</button><button v-if="lot.unit_cost==null&&w.can('cost_write')&&w.can('cost_read')" class="spray-text-button" @click="open('cost',lot)">确认原批成本</button></td></tr></tbody></table></div><div v-if="!lots.length" class="spray-empty"><strong>材料批次为空</strong><p>在采购到货核对后建立真实库存，单位换算须有 SKU 专属确认版本。</p></div></div>
 <RecordTable v-else-if="tab==='movements'" :rows="w.items('material-movements')" :columns="[{key:'business_date',label:'日期'},{key:'kind',label:'业务类型'},{key:'lot_id',label:'批次'},{key:'quantity',label:'数量',numeric:true},...(w.can('cost_read')?[{key:'cost',label:'本次耗用成本',numeric:true}]:[]),{key:'reason',label:'依据'}]" />
 <div v-else class="spray-panel"><div class="spray-panel__header"><div><h3>采购减价分析</h3><p class="spray-muted">节约是比较指标，实际成本使用现价，不重复扣减。</p></div><Button v-if="w.can('cost_write')" variant="outline" @click="open('saving')"><Plus :size="15" />新增分析</Button></div><RecordTable :rows="w.items('savings')" :columns="[{key:'business_date',label:'日期'},{key:'quantity',label:'数量',numeric:true},{key:'old_price',label:'原单价',numeric:true},{key:'new_price',label:'现单价',numeric:true},{key:'saving',label:'节约金额',numeric:true},{key:'signed_difference',label:'原表差额',numeric:true},{key:'source_ref',label:'来源'}]" /></div>
 <WorkspaceDialog :open="!!dialog" :title="title" @close="close"><form id="spray-material-form" class="spray-form" @submit.prevent="save" @input="w.dirty.value=true" @change="w.dirty.value=true">
  <template v-if="dialog==='cost'"><p class="wide spray-alert">仅确认原采购批次的真实成本，不采用今日新价。既有未知成本耗用会另记补价凭据，原记录保留。</p><label>原批次单位成本（{{selected?.currency}} / {{selected?.unit}}）<input v-model="form.unit_cost" inputmode="decimal" required/></label><label class="wide">原合同、发票与核对依据<textarea v-model="form.reason" required/></label></template><template v-if="dialog==='cancel'"><label>本次取消数量<input v-model="form.quantity" inputmode="decimal" required/></label><label>取消依据<input v-model="form.reason" required/></label><p class="wide spray-muted">只减少尚未收货的余量，已入库的批次及原始成本保留。</p></template><template v-if="dialog==='purchase'"><label>采购单号<input v-model="form.document_no" required /></label><label>供应商<input v-model="form.supplier" required /></label><label>币种<select v-model="form.currency"><option>CNY</option><option>HKD</option><option>USD</option></select></label><label>税口径<input v-model="form.tax_basis" required placeholder="如含税 / 未税，按合同填写" /></label><label class="wide">物料<select v-model="form.material_id"><option value="">选择已登记材料</option><option v-for="material in w.items('materials')" :key="material.id" :value="material.id">{{ material.code }} · {{ material.name }}</option></select></label><label>采购数量<input v-model="form.quantity" inputmode="decimal" /></label><label>采购单位<input v-model="form.unit" placeholder="原单据单位，例如 桶 / KG / 卡" /></label><label>采购单价<input v-model="form.price" inputmode="decimal" placeholder="未知可留空" /></label><label>约定交货日期<input v-model="form.due_date" type="date" /></label><button type="button" class="spray-secondary wide" @click="addLine"><Plus :size="14" />加入采购明细</button><div v-if="newLines.length" class="wide spray-purchase-lines"><p v-for="(line,index) in newLines" :key="index">{{ materialName(line.material_id) }} · {{ line.quantity }} {{ line.unit }} · 单价 {{ line.price||'待确认' }}<button type="button" class="spray-text-button" @click="newLines.splice(index,1)">移除</button></p></div></template>
  <template v-if="dialog==='receipt'"><label class="wide">明确匹配采购行<select v-model="form.purchase_line_id" required @change="selectPurchase"><option value="">选择采购明细</option><option v-for="line in purchaseLines" :key="line.id" :value="line.id">{{ line.purchase.document_no }} · {{ materialName(line.material_id) }} · 剩余 {{ number(Number(line.quantity)-Number(line.received)-Number(line.cancelled)) }} {{ line.unit }}</option></select></label><label>入库单号<input v-model="form.document_no" required /></label><label>供应商<input v-model="form.supplier" required /></label><label>实收数量<input v-model="form.quantity" inputmode="decimal" required /></label><label>实收单位<input v-model="form.unit" required /></label><label class="wide">SKU 单位换算版本<select v-model="form.conversion_rule_id"><option value="">同单位，不换算</option><option v-for="rule in w.items<Rule>('rules').filter(r=>r.kind==='unit'&&r.status==='confirmed'&&r.material_id===form.material_id)" :key="rule.id" :value="rule.id">{{ rule.label }} · V{{ rule.revision }}</option></select></label></template>
  <template v-if="dialog==='move'"><p class="wide spray-alert">{{ materialName(selected?.material_id??'') }} · 批次 {{ selected?.id.slice(0,8) }} · 仓库 {{ number(selected?.warehouse) }} / 车间 {{ number(selected?.floor) }} {{ selected?.unit }}</p><label>业务类型<select v-model="form.kind"><option value="issue">仓库 → 车间领料</option><option value="return">车间 → 原批次退料</option><option value="consume">登记实际耗用</option></select></label><label>本次数量（{{ selected?.unit }}）<input v-model="form.quantity" inputmode="decimal" required /></label><label v-if="form.kind!=='issue'" class="wide">原领料记录<select v-model="form.issue_id" required><option value="">选择原领料</option><option v-for="issue in selectedIssues" :key="issue.id" :value="issue.id">{{ issue.business_date }} · 领 {{ issue.quantity }} · {{ issue.id.slice(0,8) }}</option></select></label><label class="wide">实际用途 / 原因<textarea v-model="form.reason" required /></label><p class="wide spray-muted">领料和退料保留原批次成本；只有实际耗用进入成本。</p></template>
  <template v-if="dialog==='saving'"><label>比较数量<input v-model="form.quantity" inputmode="decimal" required /></label><label>币种<select v-model="form.currency"><option>CNY</option><option>HKD</option><option>USD</option></select></label><label>原单价<input v-model="form.old_price" inputmode="decimal" required /></label><label>现单价<input v-model="form.new_price" inputmode="decimal" required /></label><p class="wide spray-alert">节约 {{ number((Number(form.old_price)-Number(form.new_price))*Number(form.quantity)) }}；现价采购金额 {{ number(Number(form.new_price)*Number(form.quantity)) }}。</p></template>
  <label v-if="!['move','cost'].includes(dialog)" class="wide">来源单号与依据<input v-model="form.source_ref" :required="dialog==='saving'" /></label><p v-if="error" class="wide spray-alert" role="alert">{{ error }}<button v-if="dialog==='move'" type="button" class="spray-text-button" @click="refreshLot">刷新批次并保留填写</button></p>
 </form><template #footer><Button variant="outline" @click="close">取消</Button><Button type="submit" form="spray-material-form" :disabled="busy">{{ busy?'保存中…':'确认登记' }}</Button></template></WorkspaceDialog>
 </div>
</template>
