<script setup lang="ts">
import { computed, ref } from 'vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import { Button } from '@/components/ui/button'
import { useSprayWorkspace, str, amount, capabilities, localDate, type Entity } from '../workspace'
import EntryForm from '../components/EntryForm.vue'
const s = useSprayWorkspace(), route = useRoute(), router = useRouter()
const editing = ref(false), search = ref(String(route.query.q ?? ''))
const head = ref({ document_no: '', customer: '', customer_factory_id: '', due_date: localDate(), source_ref: '', expected_material_date: '' })
const newPart = () => ({ product_no: '', part_name: '', quantity: '', price: '', currency: 'HKD', price_reference: '', steps: [{ name: '', capability: 'manual', color: '', wait_hours: '0' }] })
const parts = ref([newPart()])
const selected = computed(() => s.find('orders', route.params.id))
const filtered = computed(() => s.items('orders').filter(o => `${o.document_no} ${o.customer} ${s.items('lines').filter(l => l.order_id === o.id).map(l => l.product_no).join(' ')}`.includes(search.value)))
function totals(order: Entity) {
  const lines = s.items('lines').filter(l => l.order_id === order.id), ids = new Set(lines.map(l=>l.id))
  const batches = s.items('batches').filter(b => ids.has(str(b,'line_id')))
  let received = 0, good = 0, shipped = 0
  batches.forEach(b => { received += Number(b.received); good += Number(s.balances[b.id]?.finished ?? 0) + Number(s.balances[b.id]?.shipped ?? 0); shipped += Number(s.balances[b.id]?.shipped ?? 0) })
  return { ordered: lines.reduce((a,l)=>a+Number(l.quantity),0), received, good, shipped }
}
async function save() { const result = await s.command('orders', { ...head.value, lines: parts.value.map(v => ({ ...v, price: v.price || null })) }); if(result) { editing.value = false; head.value.document_no = ''; parts.value = [newPart()] } }
async function prepare(v: Record<string,string>) { await s.command('prepare', { ...v, ready_at: v.ready_at + '+08:00' }) }
function updateSearch() { void router.replace({ query: { ...route.query, q: search.value || undefined } }) }
</script>
<template>
  <div class="spray-toolbar"><div><h2>{{ selected ? str(selected,'document_no') : '工单交付' }}</h2><p>执行厂区与委托客户分开；来料、生产、交付独立计量。</p></div><Button v-if="s.can('order_write')" @click="editing = !editing">{{ editing ? '收起建单' : '新建工单' }}</Button></div>
  <section v-if="editing" class="spray-panel"><form @submit.prevent="save"><div class="spray-entry"><label class="spray-field">工单号<input v-model="head.document_no" required /></label><label class="spray-field">委托客户<input v-model="head.customer" required /></label><label class="spray-field">喷油交期<input v-model="head.due_date" type="date" required /></label><label class="spray-field">预计胶件期<input v-model="head.expected_material_date" type="date" /></label><label class="spray-field">上游单据/来源引用<input v-model="head.source_ref" /></label></div>
    <section v-for="(part, index) in parts" :key="index" class="spray-panel mt-4"><div class="spray-section-title"><h3>实体部件 {{ index + 1 }}</h3><Button v-if="parts.length > 1" type="button" variant="ghost" @click="parts.splice(index,1)">移除此部件</Button></div><div class="spray-entry"><label class="spray-field">货号<input v-model="part.product_no" required /></label><label class="spray-field">实体部件<input v-model="part.part_name" required /></label><label class="spray-field">订单件数<input v-model="part.quantity" inputmode="decimal" required /></label><label v-if="s.can('cost_write')" class="spray-field">每件结算价 · 可留空<input v-model="part.price" inputmode="decimal" /></label><label v-if="s.can('cost_write')" class="spray-field">币种<select v-model="part.currency"><option>HKD</option><option>CNY</option><option>USD</option></select></label><label v-if="s.can('cost_write')" class="spray-field">采用价格依据<input v-model="part.price_reference" :required="!!part.price" /></label></div>
      <h3 class="mt-4 mb-2 font-semibold">此部件的串行工艺 · 可分批转序</h3><div v-for="(step,si) in part.steps" :key="si" class="spray-actions mb-2"><span>{{ si+1 }}</span><input v-model="step.name" aria-label="工序名称" placeholder="工序名称" required /><select v-model="step.capability" aria-label="工序能力"><option v-for="c in capabilities" :key="c.value" :value="c.value">{{ c.label }}</option></select><input v-model="step.color" aria-label="部位或颜色" placeholder="部位或颜色" /><Button v-if="part.steps.length > 1" type="button" variant="ghost" @click="part.steps.splice(si,1)">移除</Button></div><Button type="button" variant="outline" @click="part.steps.push({ name: '', capability: 'manual', color: '', wait_hours: '0' })">增加后工序</Button>
    </section><div class="spray-form-actions"><Button type="button" variant="outline" @click="parts.push(newPart())">增加独立部件</Button><Button type="submit" :disabled="s.busy">保存工单</Button></div></form></section>
  <template v-if="selected"><details v-if="s.can('order_write')" class="spray-panel"><summary>调整交期与优先级</summary><EntryForm :key="String(selected.revision)" class="mt-4" :fields="[{key:'due_date',label:'喷油交期',type:'date',value:str(selected,'due_date')},{key:'priority',label:'优先级（数值越高越优先）',value:str(selected,'priority')}]" :busy="s.busy" @submit="v=>s.command('order-update',{...v,id:selected!.id,expected_revision:selected!.revision})" /></details><RouterLink :to="{ path:'/modules/production/spray-production/orders', query:route.query }" class="spray-pill">返回工单列表</RouterLink><div class="spray-metrics"><div><strong>{{ amount(totals(selected).received) }}</strong><span>实收总数（含拒收待检）</span></div><div><strong>{{ amount(totals(selected).good) }}</strong><span>合格可交付及净送出</span></div><div><strong>{{ amount(totals(selected).shipped) }}</strong><span>净已送货</span></div></div>
    <section v-for="line in s.items('lines').filter(l=>l.order_id===selected?.id)" :key="line.id" class="spray-panel"><h3 class="font-semibold">{{ s.lineLabel(line) }} · {{ amount(line.quantity) }} 件</h3><details v-if="s.can('cost_write')" class="mt-4"><summary>结算价格 · {{ line.price == null ? '尚未确认' : amount(line.price)+' '+line.currency }}</summary><EntryForm :key="line.id+String(line.revision)" class="mt-4" :fields="[{key:'price',label:'每件结算价',type:'decimal',value:line.price == null ? '' : str(line,'price')},{key:'currency',label:'计价币种',value:str(line,'currency'),options:[{value:'HKD',label:'港币 HKD'},{value:'CNY',label:'人民币 CNY'},{value:'USD',label:'美元 USD'}]},{key:'reason',label:'本次采用价格依据'}]" :busy="s.busy" submit-label="确认新价格版本" @submit="v=>s.command('price-set',{...v,line_id:line.id,expected_revision:line.revision})" /><p class="spray-help">已送货与已冻结账单保留原价；新价格仅供之后送货采用。</p></details><div class="spray-actions my-4"><span v-for="step in s.items('steps').filter(v=>v.line_id===line.id).sort((a,b)=>Number(a.sequence)-Number(b.sequence))" :key="step.id" class="spray-pill">{{ step.sequence }} · {{ step.name }}</span></div><p class="spray-help">备产：{{ line.prep_ready_at ? str(line,'prep_reason') : '尚未登记完成；默认建议提前两自然日备产，实际开工以完成依据为准' }}</p><EntryForm v-if="s.can('plan')" :key="line.id" :fields="[{key:'line_id',label:'部件',value:line.id,options:[{value:line.id,label:s.lineLabel(line)}]},{key:'ready_at',label:'实际备妥时间',type:'datetime-local'},{key:'reason',label:'领料/调油/调机及首件依据'}]" submit-label="登记备产完成" :busy="s.busy" @submit="prepare" /><div v-for="batch in s.items('batches').filter(b=>b.line_id===line.id)" :key="batch.id" class="spray-row"><span>{{ s.batchLabel(batch) }}</span><Button variant="outline" size="sm" @click="s.selection=batch.id">检查批次</Button></div></section>
  </template>
  <template v-else><input v-model="search" aria-label="搜索工单货号客户" placeholder="搜索工单 / 完整货号 / 客户" class="mb-4" @input="updateSearch" /><div class="spray-table-wrap"><table class="spray-table"><thead><tr><th>工单 / 客户</th><th>交期</th><th class="num">订单件数</th><th class="num">实收</th><th class="num">合格及已送出</th><th class="num">净送货</th></tr></thead><tbody><tr v-for="order in filtered" :key="order.id"><td><RouterLink :to="{ path:'/modules/production/spray-production/orders/'+order.id,query:route.query }"><strong>{{ order.document_no }}</strong>{{ order.customer }}</RouterLink></td><td>{{ order.due_date }}</td><td v-for="key in (['ordered','received','good','shipped'] as const)" :key="key" class="num">{{ amount(totals(order)[key]) }}</td></tr></tbody></table></div><div v-if="!filtered.length" class="spray-empty">没有匹配工单。可从真实订单建立首张工单。</div></template>
</template>
