<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { Play, ClipboardPen, Download, ClipboardPaste, Check, AlertTriangle, ArrowUpRight } from '@lucide/vue'
import { Button } from '@/components/ui/button'
import { useSprayPage } from '../usePage'
import { number, dateTime, documentNo, type Task, type Resource, type RouteVersion, type Demand, type Stock, type Entity } from '../contracts'
import WorkspaceState from '../components/WorkspaceState.vue'
import WorkspaceDialog from '../components/WorkspaceDialog.vue'
import ReportEditor from '../components/ReportEditor.vue'
import DraftReportEditor from '../components/DraftReportEditor.vue'
import LaborEditor from '../components/LaborEditor.vue'
import RecordTable from '../components/RecordTable.vue'
const w=useSprayPage(['tasks','resources','routes','demands','stock','reports'])
const laborReport=ref<Entity|null>(null)
const tab=ref('tasks'), selected=ref<Task|null>(null), error=ref(''), busy=ref(false)
const tasks=computed(()=>w.items<Task>('tasks').filter(task=>['planned','started','paused'].includes(task.status)))
const held=computed(()=>w.items<Stock>('stock').filter(stock=>stock.state==='hold' && Number(stock.quantity)>0))
const stepName=(id:string)=>w.items<RouteVersion>('routes').flatMap(r=>r.steps).find(s=>s.id===id)?.name ?? '工序'
const resourceName=(id:string)=>w.items<Resource>('resources').find(r=>r.id===id)?.name ?? '资源待核对'
const lineFor=(task:Task)=>w.items<Demand>('demands').flatMap(d=>d.lines).find(line=>task.allocations.some(a=>a.line_id===line.id))
async function start(task:Task) { busy.value=true; try {await w.command(`tasks/${task.id}/start`,{business_date:w.businessDate.value,actual_start:new Date().toISOString()},task.version); await w.load(['tasks'])}catch(cause){error.value=w.explain(cause)}finally{busy.value=false} }
async function pauseTask(task:Task){const reason=await w.promptReason(task.status==='paused'?'恢复生产依据':'暂停原因');if(!reason)return;try{await w.command(`tasks/${task.id}/${task.status==='paused'?'resume':'pause'}`,{business_date:w.businessDate.value,reason},task.version);await w.load(['tasks'])}catch(cause){error.value=w.explain(cause)}}
async function afterReport() { await w.load(['tasks','stock','reports','demands']) }
const quality=ref<Stock|null>(null), disposition=reactive({good:'0',rework:'0',scrap:'0',reason:'',rework_step_id:''})
function chooseQuality(stock:Stock) { quality.value=stock; Object.assign(disposition,{good:'0',rework:'0',scrap:'0',reason:'',rework_step_id:''}); error.value='' }
async function closeQuality(){if(w.dirty.value&&!(await w.confirmDiscard('放弃尚未保存的质量处置？')))return;quality.value=null;w.dirty.value=false}
async function closePaste(){if(w.dirty.value&&!(await w.confirmDiscard('放弃尚未确认的批量日报？')))return;pasteOpen.value=false;w.dirty.value=false}
async function saveQuality(){ if(!quality.value)return;busy.value=true;try{await w.command(`stock/${quality.value.id}/quality`,{business_date:w.businessDate.value,...disposition,rework_step_id:disposition.rework_step_id||null},quality.value.version);quality.value=null;await w.load(['stock'])}catch(cause){error.value=w.explain(cause)}finally{busy.value=false} }
const editingDraft=ref<Entity|null>(null)
const pasteOpen=ref(false), pasteText=ref(''), pasteShift=ref('')
const pasted=computed(()=>pasteText.value.split(/\r?\n/).filter(line=>line.trim()).map((line,index)=>{const cells=line.split('\t');const matches=tasks.value.filter(task=>task.id.startsWith(cells[0]?.trim()??'')&&task.status==='started');return{index:index+1,task:matches.length===1?matches[0]:undefined,values:{processed:cells[1]??'',good:cells[2]??'',hold:cells[3]??'0',scrap:cells[4]??'0',normal:cells[5]??'',overtime:cells[6]??'0'},reason:cells[7]??''}}))
async function savePasted(){busy.value=true;error.value='';try{if(pasted.value.some(row=>!row.task||row.task.allocations.length!==1))throw new Error('请定位唯一已开工任务；多订单合并任务需逐单填写分摊');await w.command('reports',{document_no:documentNo('批量日报'),business_date:w.businessDate.value,shift:pasteShift.value,rows:pasted.value.map(row=>({task_id:row.task!.id,...row.values,reason:row.reason,allocations:[{task_allocation_id:row.task!.allocations[0]!.id,...row.values}],labor:[]}))});pasteOpen.value=false;await afterReport()}catch(cause){error.value=w.explain(cause)}finally{busy.value=false} }
async function confirmDraft(report:Entity){try{await w.command(`reports/${report.id}/confirm`,{},report.version);await afterReport()}catch(cause){error.value=w.explain(cause)}}
async function reverseDaily(report:Entity){const reason=await w.promptReason('冲销保留原日报与原因；产出已有下游使用时不能冲销。请输入原因：');if(!reason?.trim())return;try{await w.command(`reports/${report.id}/reverse`,{business_date:w.businessDate.value,reason},report.version);await afterReport()}catch(cause){error.value=w.explain(cause)}}
</script>
<template>
  <div class="spray-page"><header class="spray-page-heading"><div><span class="spray-eyebrow">SHOP FLOOR / 现场执行</span><h1>把今天的实绩记录清楚</h1><p>{{ w.businessDate.value }} · 先确认任务，再记录数量、质量和实际工时。</p></div><div class="spray-actions"><Button v-if="w.can('export')" variant="outline" @click="w.download('daily',{from_date:w.businessDate.value,to_date:w.businessDate.value})"><Download :size="15" />打印日报</Button><Button v-if="w.can('report')" variant="outline" @click="pasteOpen=true;error='' "><ClipboardPaste :size="15" />批量粘贴</Button></div></header><WorkspaceState /><p v-if="error&&!quality&&!pasteOpen" class="spray-alert" role="alert">{{ error }}</p>
    <div class="spray-tabs"><button :class="{active:tab==='tasks'}" @click="tab='tasks'">当前任务 <span>{{ tasks.length }}</span></button><button :class="{active:tab==='daily'}" @click="tab='daily'">日报记录</button><button :class="{active:tab==='quality'}" @click="tab='quality'">质量待办 <span>{{ held.length }}</span></button></div>
    <div v-if="tab==='tasks'" class="spray-production-list"><article v-for="task in tasks" :key="task.id" class="spray-production-task"><div class="spray-production-resource"><span class="spray-status-dot" /><strong>{{ resourceName(task.resource_id) }}</strong><span class="spray-badge" :class="{'spray-badge--gray':task.status==='planned'}">{{ task.status==='started'?'正在执行':task.status==='paused'?'已暂停':'已排待开' }}</span></div><div class="spray-production-identity"><button class="spray-text-button" @click="w.passportId.value=lineFor(task)?.demand_id??null">{{ lineFor(task)?.item_no }} · {{ lineFor(task)?.part }}<ArrowUpRight :size="13" /></button><h3>{{ stepName(task.step_id) }}</h3><p>{{ dateTime(task.start_at) }} — {{ dateTime(task.end_at) }} · 任务 {{ task.id.slice(0,8) }}</p></div><div class="spray-production-progress"><span><b>{{ number(task.reported) }}</b> / {{ number(task.quantity) }} {{ w.items<RouteVersion>('routes').flatMap(r=>r.steps).find(s=>s.id===task.step_id)?.input_unit }}</span><div><i :style="{width:`${Number(task.reported)/Number(task.quantity)*100}%`}" /></div><small>已报 / 本任务目标</small></div><div class="spray-actions"><Button v-if="['started','paused'].includes(task.status)&&w.can('report')" variant="outline" @click="pauseTask(task)">{{task.status==='paused'?'恢复':'暂停'}}</Button><Button v-if="task.status==='planned'&&w.can('report')" variant="outline" :disabled="busy" @click="start(task)"><Play :size="15" />开始生产</Button><Button v-if="task.status==='started'&&w.can('report')" @click="selected=task"><ClipboardPen :size="16" />报工</Button></div></article><div v-if="!tasks.length" class="spray-empty spray-panel"><strong>当前没有待执行任务</strong><p>发布排期后，任务会出现在这里；正在执行和已完成实绩会分别保留。</p></div></div>
    <RecordTable v-else-if="tab==='daily'" :rows="w.items('reports')" :columns="[{key:'document_no',label:'日报编号'},{key:'business_date',label:'生产日期'},{key:'shift',label:'班次'},{key:'status',label:'状态'},{key:'source_ref',label:'来源'}]"><template #actions="{row}"><button v-if="['draft','confirmed'].includes(String(row.status))&&w.can('report')" class="spray-text-button" @click="laborReport=row">核对工时 · </button><button v-if="row.status==='draft'&&w.can('report')" class="spray-text-button" @click="editingDraft=row">修改草稿 · </button><button v-if="row.status==='draft'&&w.can('report')" class="spray-text-button" @click="confirmDraft(row)">确认草稿</button><button v-if="row.status==='confirmed'&&w.can('report')" class="spray-text-button" @click="reverseDaily(row)">冲销更正</button></template></RecordTable>
    <RecordTable v-else :rows="held" :columns="[{key:'id',label:'待判批次'},{key:'quantity',label:'待判数量',numeric:true},{key:'unit',label:'单位'},{key:'ready_at',label:'可转序时间'}]"><template #actions="{row}"><button v-if="w.can('quality')" class="spray-text-button" @click="chooseQuality(row as Stock)">复检 / 返工 / 报废</button></template></RecordTable>
    <DraftReportEditor :report="editingDraft" @close="editingDraft=null" @saved="afterReport"/><LaborEditor :report="laborReport" @close="laborReport=null" @saved="afterReport"/><ReportEditor :task="selected" @close="selected=null" @saved="afterReport" />
    <WorkspaceDialog :open="!!quality" title="登记质量处置" @close="closeQuality"><p class="spray-muted">待判 {{ number(quality?.quantity) }} {{ quality?.unit }} · 按本次处置数量分配，余量继续待判。</p><form id="spray-quality-form" class="spray-form" @input="w.dirty.value=true" @submit.prevent="saveQuality"><label>复检合格<input v-model="disposition.good" inputmode="numeric" required /></label><label>转入返工<input v-model="disposition.rework" inputmode="numeric" required /></label><label v-if="Number(disposition.rework)>0">返工起始工序<select v-model="disposition.rework_step_id"><option value="">沿用当前失败工序</option><optgroup v-for="r in w.items<RouteVersion>('routes')" :key="r.id" :label="r.label"><option v-for="step in r.steps" :key="step.id" :value="step.id">{{step.name}}</option></optgroup></select></label><label>确认报废<input v-model="disposition.scrap" inputmode="numeric" required /></label><label class="wide">判定依据与原因<textarea v-model="disposition.reason" required /></label><p v-if="error" class="spray-alert wide" role="alert">{{ error }}</p></form><template #footer><Button variant="outline" @click="closeQuality">取消</Button><Button form="spray-quality-form" type="submit" :disabled="busy">确认处置</Button></template></WorkspaceDialog>
    <WorkspaceDialog :open="pasteOpen" title="粘贴日报并逐行预览" wide @close="closePaste"><p class="spray-muted">列顺序：任务编号、加工、合格、待判、报废、正班、加班、原因。支持从表格复制制表符分隔内容；不自动推断员工工资。</p><div class="spray-form" @input="w.dirty.value=true"><label class="wide">实际班次<input v-model="pasteShift" required /></label><label class="wide">粘贴数据<textarea v-model="pasteText" rows="5" placeholder="粘贴到这里，预览后确认" /></label></div><div class="spray-table-wrap"><table class="spray-table"><thead><tr><th>行</th><th>任务</th><th>加工</th><th>合格</th><th>待判</th><th>报废</th><th>正班</th><th>加班</th></tr></thead><tbody><tr v-for="row in pasted" :key="row.index"><td>{{ row.index }}</td><td>{{ row.task?stepName(row.task.step_id):'无法唯一匹配，请核对' }}</td><td v-for="(value,key) in row.values" :key="key">{{ value }}</td></tr></tbody></table></div><p v-if="error" class="spray-alert" role="alert">{{ error }}</p><template #footer><Button variant="outline" @click="closePaste">返回</Button><Button :disabled="busy||!pasted.length||!pasteShift" @click="savePasted">确认这批实绩</Button></template></WorkspaceDialog>
  </div>
</template>
