<script setup lang="ts">
import { computed, ref, onMounted } from 'vue'
import { Button } from '@/components/ui/button'
import { createRandomUuid } from '@/lib/randomUuid'
import { useSprayWorkspace, str, amount, statusName, localDate } from '../workspace'
const s=useSprayWorkspace(), date=ref(localDate()), shift=ref('白班'),team=ref(''), people=ref(''),paste=ref(''),pasteError=ref('')
const fresh=()=>({task_id:'',activity:'',regular_qty:'',overtime_qty:'0',regular_hours:'',overtime_hours:'0',good:'',held:'0',rework:'0',scrap:'0',rate_id:''})
const lines=ref([fresh()]), selected=ref(0), draftStatus=ref(''), operationId=ref(createRandomUuid())
async function saveDraft(){ const r=await s.savePreference('report_draft','现场快录',{operation_id:operationId.value,date:date.value,shift:shift.value,team:team.value,people:people.value,lines:lines.value,cost_data:lines.value.some(l=>!!l.rate_id)});if(r)draftStatus.value='草稿已保存在本厂区、当前账号；刷新可恢复';return r }
onMounted(async()=>{await s.loadPreferences();const saved=s.preferences.find(v=>v.kind==='report_draft'&&v.name==='现场快录');if(saved){const p=saved.payload as {operation_id?:string;date:string;shift:string;team:string;people:string;lines:ReturnType<typeof fresh>[]};operationId.value=p.operation_id??createRandomUuid();date.value=p.date;shift.value=p.shift;team.value=p.team;people.value=p.people;lines.value=p.lines.length?p.lines:[fresh()];draftStatus.value='已恢复上次保存的快录草稿，尚未确认生产'}})

const tasks=computed(()=>s.items('tasks').filter(t=>['running','paused'].includes(str(t,'status'))))
const totals=computed(()=>lines.value.reduce((a,l)=>({regular:a.regular+Number(l.regular_qty||0),overtime:a.overtime+Number(l.overtime_qty||0),good:a.good+Number(l.good||0)}),{regular:0,overtime:0,good:0}))
function pasteRows(){const parsed=paste.value.trim().split(/\r?\n/).map(row=>row.split('\t'));if(!parsed.length||parsed.some(r=>r.length!==8||r.some(v=>v.trim()===''||!Number.isFinite(Number(v))||Number(v)<0))){pasteError.value='每行需 8 个非负数字：正班数量、正班小时、加班数量、加班小时、合格、待判、返工、报废。不会跳过错误行。';return}lines.value=parsed.map(r=>({...fresh(),regular_qty:r[0]!,regular_hours:r[1]!,overtime_qty:r[2]!,overtime_hours:r[3]!,good:r[4]!,held:r[5]!,rework:r[6]!,scrap:r[7]!}));pasteError.value='已预览 '+parsed.length+' 行，请逐行选择任务。尚未入账。'}
async function confirm(){if(!await saveDraft())return;const result=await s.command('reports',{operation_id:operationId.value,business_date:date.value,shift:shift.value,team:team.value,lines:lines.value.map(l=>({...l,regular_hours:l.regular_hours||'0',regular_qty:l.regular_qty||'0',good:l.good||'0',people:people.value.split(/[，,、]/).filter(Boolean).map(name=>({name:name.trim(),weight:'1'})),rate_id:l.rate_id||undefined}))});if(result){operationId.value=createRandomUuid();lines.value=[fresh()];await saveDraft();draftStatus.value='报工已确认，已清空草稿产量'}}
function next(event:KeyboardEvent){if(event.key==='Enter'&&(event.target as HTMLElement).tagName==='INPUT'){event.preventDefault();const controls=[...((event.currentTarget as HTMLElement).querySelectorAll<HTMLInputElement>('input,select'))];const i=controls.indexOf(event.target as HTMLInputElement);controls[i+1]?.focus()}}
</script>
<template><div class="spray-toolbar"><div><h2>现场报工</h2><p>一次记录同步生产与在制；工资未定价不阻塞生产确认，金额由后端计算。</p></div><div class="spray-toolbar-actions"><span class="spray-badge">增量报工 · 不复制上班产量</span></div></div>
  <template v-if="s.can('report')"><p v-if="draftStatus" role="status" class="spray-message">{{ draftStatus }}</p><div class="spray-actions mb-4"><label class="spray-field-label"><span>业务日期</span><input v-model="date" type="date" /></label><label class="spray-field-label"><span>班次</span><select v-model="shift" aria-label="班次"><option>白班</option><option>夜班</option></select></label><label class="spray-field-label"><span>班组</span><input v-model="team" placeholder="例如：喷油一组" aria-label="班组" required /></label><label class="spray-field-label"><span>人员 / 历史别名</span><input v-model="people" placeholder="多人以逗号分隔" aria-label="人员或历史别名" required /></label></div>
    <details class="spray-note"><summary>Excel 范围粘贴与预览 · 先预览再关联任务</summary><p class="spray-help">列顺序：正班数、正班小时、加班数、加班小时、合格、待判、返工、报废。整批替换当前行，不会跳过错误行。</p><textarea v-model="paste" aria-label="粘贴报工数字" rows="3" class="w-full" /><div class="spray-actions mt-3"><Button variant="outline" @click="pasteRows">检查粘贴</Button><p role="status" class="spray-help">{{ pasteError }}</p></div></details>
    <div class="spray-report-layout"><div><form @submit.prevent="confirm"><div class="spray-table-wrap" @keydown="next"><p class="spray-table-caption">第 {{ lines.length }} 行待确认 · Tab / Enter 连续录入，合格数按工序推进，加工次数不计入成品数</p><table class="spray-table spray-report-table"><thead><tr><th>任务 / 活动</th><th>正班数</th><th>正班小时</th><th>加班数</th><th>加班小时</th><th>合格</th><th>待判</th><th>返工</th><th>报废</th><th>操作</th></tr></thead><tbody><tr v-for="(line,i) in lines" :key="i" @focusin="selected=i"><td data-label="任务 / 活动"><select v-model="line.task_id" aria-label="报工任务"><option value="">非生产活动</option><option v-for="t in tasks" :key="t.id" :value="t.id">{{ s.taskLabel(t) }}</option></select><input v-if="!line.task_id" v-model="line.activity" aria-label="非生产活动说明" placeholder="调机、样板等说明" required /></td><td v-for="key in (['regular_qty','regular_hours','overtime_qty','overtime_hours','good','held','rework','scrap'] as const)" :key="key" :data-label="{regular_qty:'正班数',regular_hours:'正班小时',overtime_qty:'加班数',overtime_hours:'加班小时',good:'合格',held:'待判',rework:'返工',scrap:'报废'}[key]"><input v-model="line[key]" :aria-label="'第'+(i+1)+'行 '+{regular_qty:'正班数',regular_hours:'正班小时',overtime_qty:'加班数',overtime_hours:'加班小时',good:'合格',held:'待判',rework:'返工',scrap:'报废'}[key]" inputmode="decimal" /></td><td><Button v-if="lines.length>1" type="button" variant="ghost" @click="lines.splice(i,1)">移除行</Button></td></tr></tbody></table></div><div class="spray-actions my-4"><Button type="button" variant="outline" @click="lines.push(fresh())">增加空白行</Button><p class="spray-muted">当前 {{ lines.length }} 行</p></div><div class="spray-report-footer"><span>正班 {{ amount(totals.regular) }} · 加班 {{ amount(totals.overtime) }} · 合格 {{ amount(totals.good) }}</span><Button type="button" variant="outline" :disabled="s.busy" @click="saveDraft">保存草稿</Button><Button type="submit" :disabled="s.busy || !team || !people">确认本班记录</Button></div></form></div>
    <aside class="spray-panel"><h3 class="font-semibold">当前行检查</h3><p class="spray-help">正班 + 加班 = 合格 + 待判 + 返工 + 报废。合格数按工序推进，不把加工次数当成品数。</p><template v-if="s.can('cost_read')"><label class="spray-field">工价/工资策略<select v-if="lines[selected]" v-model="lines[selected]!.rate_id"><option value="">未定价 · 生产先确认</option><option v-for="rate in s.items('rates').filter(r=>r.rule_code!=='employee_shift_guarantee')" :key="rate.id" :value="rate.id">{{ rate.name }} · {{ statusName(rate.status) }}</option></select></label><p class="spray-help">金额由后端计算并留存版本快照。历史系数不自动成为正式规则。</p></template><p v-else class="spray-help">当前为现场基础视图，接口未下发工资金额。</p></aside></div>
  </template>
  <div class="spray-section-title mt-6"><h3>已保存报工<span class="spray-muted"> · {{ s.items('reports').length }} 条</span></h3><span class="spray-muted">按业务日期与班组登记，确认后不覆盖上班产量</span></div><div class="spray-table-wrap"><table class="spray-table"><thead><tr><th>业务日期 / 班组</th><th>班次</th><th>状态</th><th>记录时间</th></tr></thead><tbody><tr v-for="r in s.items('reports')" :key="r.id"><td><strong>{{ r.business_date }}</strong>{{ r.team }}</td><td>{{ r.shift }}</td><td>{{ statusName(r.status) }}</td><td>{{ new Date(str(r,'created_at')).toLocaleString('zh-CN') }}</td></tr></tbody></table></div><p v-if="!s.items('reports').length" class="spray-help">本厂尚无已确认报工。确认本班记录后会出现在这里。</p>
</template>
<style scoped>.spray-report-layout{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:16px}.spray-report-table select{max-width:240px}.spray-report-footer{display:flex;gap:12px 16px;flex-wrap:wrap;align-items:center;justify-content:space-between;padding:14px 16px;background:var(--card);border:1px solid var(--border);border-radius:10px;position:sticky;bottom:0}@media(max-width:1500px){.spray-report-layout{grid-template-columns:1fr}}@media(max-width:700px){.spray-report-table,.spray-report-table tbody{display:block;white-space:normal}.spray-report-table thead{display:none}.spray-report-table tr{display:grid;grid-template-columns:1fr 1fr;padding:12px;border-bottom:2px solid var(--border)}.spray-report-table td{display:flex;flex-direction:column;padding:8px;border:0}.spray-report-table td:first-child{grid-column:1/-1}.spray-report-table td:before{content:attr(data-label);font-size:12px;color:var(--muted-foreground);margin-bottom:4px}.spray-report-table td input,.spray-report-table select{width:100%;max-width:100%}.spray-report-footer{flex-direction:column;align-items:stretch;position:static}.spray-table-caption{display:none}}</style>
