<script setup lang="ts">
import { computed, ref } from 'vue'
import { Button } from '@/components/ui/button'
import { useSprayWorkspace, str, amount, statusName, localDate } from '../workspace'
import type { SprayResult } from '@/api/sprayProduction'
const s=useSprayWorkspace(), draft=ref<SprayResult|null>(null), day=ref(localDate()), zoom=ref('day')
const form=ref({ batch_id:'',step_id:'',resource_id:'',quantity:'',workers:'1',start_at:localDate()+'T08:00',manual_hours:'',duration_reason:'',rework:false })
const backlog=computed(()=>s.items('batches').flatMap(b=>Object.entries(s.balances[b.id]??{}).filter(([k,q])=>(k.startsWith('ready:')||k.startsWith('rework:'))&&Number(q)>0).map(([state,qty])=>({batch:b,state,qty,step:state.split(':')[1]??''}))))
const windowStart=computed(()=>new Date(day.value+'T00:00:00+08:00').getTime())
const hours=computed(()=>zoom.value==='week'?168:24)
const bars=computed(()=>s.items('tasks').filter(t=>t.status!=='cancelled'&&new Date(str(t,'end_at')).getTime()>windowStart.value&&new Date(str(t,'start_at')).getTime()<windowStart.value+hours.value*3600000))
function choose(batch:string,state:string,qty:string,resource='') { form.value.batch_id=batch;form.value.step_id=state.split(':')[1]??'';form.value.quantity=qty;form.value.rework=state.startsWith('rework:');if(resource)form.value.resource_id=resource;s.selection=batch }
function drop(event:DragEvent,resource:string) { const raw=event.dataTransfer?.getData('text/plain');const item=backlog.value.find(b=>b.batch.id+'|'+b.state===raw);if(item)choose(item.batch.id,item.state,item.qty,resource) }
async function preview() { const r=await s.command('schedule-preview',{changes:[{...form.value,workers:Number(form.value.workers),start_at:form.value.start_at+'+08:00'}]});if(r)draft.value=r }
async function apply() { if(draft.value){const r=await s.command('schedule-apply',{scenario_id:draft.value.id});if(r)draft.value=null} }
async function suggest() { const r=await s.command('schedule-suggest',{start_at:day.value+'T08:00:00+08:00'});if(r)draft.value=r }
function barStyle(task:Record<string,unknown>) { const start=Math.max(0,(new Date(String(task.start_at)).getTime()-windowStart.value)/3600000);const end=Math.min(hours.value,(new Date(String(task.end_at)).getTime()-windowStart.value)/3600000);return {left:start/hours.value*100+'%',width:Math.max(1,(end-start)/hours.value*100)+'%'} }
</script>
<template>
  <div class="spray-toolbar"><div><h2>排产画布</h2><p>实线为正式预留；表单和拖放均先生成草案。</p></div><div class="spray-actions"><input v-model="day" type="date" aria-label="排产日期" /><select v-model="zoom" aria-label="时间轴跨度"><option value="day">日视图</option><option value="week">周视图</option></select><Button v-if="s.can('plan')" :disabled="s.busy" @click="suggest">生成排产建议</Button></div></div>
  <div class="spray-schedule-layout"><aside class="spray-backlog"><h3>待排批次 <span class="spray-muted">{{ backlog.length }}</span></h3><button v-for="item in backlog" :key="item.batch.id+item.state" class="spray-task" draggable="true" @dragstart="($event.dataTransfer?.setData('text/plain',item.batch.id+'|'+item.state))" @click="choose(item.batch.id,item.state,item.qty)"><h4>{{ s.lineLabel(s.find('lines',item.batch.line_id)) }}</h4><p>{{ s.stateName(item.state) }}</p><footer><span>{{ amount(item.qty) }} 件可用</span><span>选择安排</span></footer></button><p v-if="!backlog.length" class="spray-help">暂无可排批次。先登记实际来料或前工序放行。</p></aside>
    <div class="spray-schedule-scroll"><div class="spray-time-axis"><span>资源 / 班组</span><div><span v-for="i in (zoom==='day'?8:7)" :key="i" :style="{left:(i-1)/(zoom==='day'?8:7)*100+'%'}">{{ zoom==='day' ? (i-1)*3+':00' : '第 '+i+' 天' }}</span></div></div><div v-for="resource in s.items('resources')" :key="resource.id" class="spray-resource-row" @dragover.prevent @drop.prevent="drop($event,resource.id)"><strong>{{ resource.name }}<small>{{ resource.workers }} 人</small></strong><div class="spray-track"><button v-for="task in bars.filter(t=>t.resource_id===resource.id)" :key="task.id" class="spray-plan-bar" :style="barStyle(task)" :title="s.taskLabel(task)+' '+str(task,'start_at')+' 至 '+str(task,'end_at')" @click="s.selection=str(task,'batch_id')">{{ str(s.find('steps',task.step_id),'name') }} · {{ amount(task.quantity) }}<small>{{ statusName(task.status) }}</small></button></div></div><p v-if="!s.items('resources').length" class="spray-empty">资料中心配置真实资源后显示时间轴。</p></div>
  </div>
  <section v-if="s.can('plan')" class="spray-panel mt-5"><div class="spray-section-title"><h3>批次安排 · 键盘与触摸操作</h3><span class="spray-muted">拖入资源只填写草稿，不直接占库存</span></div><form @submit.prevent="preview"><div class="spray-entry"><label class="spray-field">批次<select v-model="form.batch_id" required><option value="">请选择来料批次</option><option v-for="b in s.items('batches')" :key="b.id" :value="b.id">{{ s.batchLabel(b) }}</option></select></label><label class="spray-field">工序<select v-model="form.step_id" required><option value="">请选择工序</option><option v-for="step in s.items('steps').filter(v=>v.line_id===s.find('batches',form.batch_id)?.line_id)" :key="step.id" :value="step.id">{{ step.name }}</option></select></label><label class="spray-field">资源<select v-model="form.resource_id" required><option value="">请选择资源</option><option v-for="r in s.items('resources')" :key="r.id" :value="r.id">{{ r.name }}</option></select></label><label class="spray-field">开始时间<input v-model="form.start_at" type="datetime-local" required /></label><label class="spray-field">安排数量<input v-model="form.quantity" inputmode="decimal" required /></label><label class="spray-field">投入人数<input v-model="form.workers" inputmode="numeric" required /></label><label class="spray-field">确认占用小时 · 节拍缺失时填写<input v-model="form.manual_hours" inputmode="decimal" /></label><label class="spray-field">手填时长依据<input v-model="form.duration_reason" :required="!!form.manual_hours" /></label></div><label class="spray-actions mt-3"><input v-model="form.rework" type="checkbox" /> 使用原批次的返工量</label><div class="spray-form-actions"><Button :disabled="s.busy">预览这项安排</Button></div></form></section>
  <section v-if="draft" class="spray-panel spray-draft"><h3 class="font-semibold">草案预览 · 尚未应用</h3><p class="spray-help">{{ draft.strategy || '手动调整；应用时再次核对库存、资源与版本。' }}</p><div v-for="change in (draft.changes as Record<string,unknown>[])" :key="String(change.batch_id)+String(change.step_id)" class="spray-row"><span>{{ s.batchLabel(s.find('batches',change.batch_id)) }} · {{ str(s.find('resources',change.resource_id),'name') }}</span><span>{{ amount(change.quantity) }} 件 · {{ new Date(String(change.start_at)).toLocaleString('zh-CN') }}</span></div><div v-for="skip in (draft.skipped as Record<string,unknown>[] || [])" :key="String(skip.batch_id)" class="spray-help">{{ s.batchLabel(s.find('batches',skip.batch_id)) }}：{{ skip.reason }}</div><div class="spray-actions mt-3"><Button :disabled="s.busy" @click="apply">应用安排</Button><Button variant="outline" @click="draft=null">放弃草案</Button></div></section>
  <section class="spray-panel"><h3 class="font-semibold mb-3">任务执行</h3><div v-for="task in s.items('tasks').filter(t=>!['completed','cancelled'].includes(str(t,'status')))" :key="task.id" class="spray-row"><div><strong>{{ s.taskLabel(task) }}</strong><p class="spray-muted">{{ new Date(str(task,'start_at')).toLocaleString('zh-CN') }} · {{ statusName(task.status) }}</p></div><Button v-if="task.status==='planned' && s.can('report')" :disabled="s.busy" @click="s.command('task-state',{task_id:task.id,action:'start'})">开工</Button></div></section>
</template>
<style scoped>
.spray-schedule-layout{display:grid;grid-template-columns:245px minmax(0,1fr);gap:16px}.spray-backlog{max-height:450px;overflow:auto}.spray-backlog h3{font-weight:650;margin-bottom:12px}.spray-backlog .spray-task{width:100%;min-width:0;margin-bottom:10px}.spray-schedule-scroll{overflow:auto;border:1px solid var(--border);border-radius:10px;background:var(--card)}.spray-time-axis,.spray-resource-row{display:grid;grid-template-columns:140px minmax(600px,1fr);min-width:740px}.spray-time-axis{height:42px;background:var(--secondary);font-size:12px}.spray-time-axis>span{padding:12px}.spray-time-axis>div{position:relative}.spray-time-axis>div>span{position:absolute;top:50%;transform:translateY(-50%);white-space:nowrap}.spray-resource-row{min-height:88px;border-top:1px solid var(--border)}.spray-resource-row>strong{position:sticky;left:0;z-index:2;background:var(--card);padding:18px 12px;font-weight:550;border-right:1px solid var(--border)}.spray-resource-row small{display:block;font-size:12px;font-weight:400}.spray-track{position:relative;background:repeating-linear-gradient(to right,transparent,transparent calc(12.5% - 1px),var(--border) calc(12.5% - 1px),var(--border) 12.5%)}.spray-plan-bar{position:absolute;top:12px;height:62px;border:1px solid var(--primary);border-radius:6px;background:var(--accent);padding:6px;text-align:left;overflow:hidden;font-size:12px;color:var(--primary);white-space:nowrap;text-overflow:ellipsis}.spray-plan-bar small{overflow:hidden;text-overflow:ellipsis}.spray-draft{border:1px dashed #3476b5;background:#f1f7fc}@media(max-width:1100px){.spray-schedule-layout{grid-template-columns:1fr}.spray-backlog{display:flex;gap:8px;max-height:150px}.spray-backlog .spray-task{min-width:230px}.spray-backlog h3{min-width:70px}}@media(max-width:700px){.spray-schedule-scroll{display:none}.spray-backlog{max-height:200px}}
</style>
