<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import { ArrowLeft, Download, Plus, FileCheck, CircleAlert } from '@lucide/vue'
import { Button } from '@/components/ui/button'
import { useSprayPage } from '../usePage'
import { SPRAY_BASE, number, documentNo, type Delivery, type DeliveryLine, type Settlement, type Entity } from '../contracts'
import RecordTable from '../components/RecordTable.vue'
import WorkspaceDialog from '../components/WorkspaceDialog.vue'
import WorkspaceState from '../components/WorkspaceState.vue'
const w=useSprayPage(['deliveries','returns','containers']), route=useRoute(), router=useRouter()
const month=ref(w.businessDate.value.slice(0,7)), currency=ref('CNY'), counterparty=ref(''), error=ref(''), busy=ref(false), dialog=ref(''), selected=ref<Settlement|null>(null)
const quantities=reactive<Record<string,string>>({})
const form=reactive({document_no:documentNo('月结'),return_id:'',settlement_line_id:'',quantity:'',reason:'',price:'',line_id:''})
const parties=computed(()=>[...new Set(w.items<Delivery>('deliveries').map(d=>d.counterparty))])
const eligible=computed(()=>w.items<Delivery>('deliveries').filter(d=>d.status!=='draft'&&(!counterparty.value||d.counterparty===counterparty.value)).flatMap(d=>d.lines.filter(l=>l.currency===currency.value).map(l=>({...l,document_no:d.document_no,counterparty:d.counterparty,balance:Math.max(0,Math.min(Number(l.accepted)-Number(l.returned)-Number(l.settled),(l.acceptances??[]).filter(e=>e.business_date.slice(0,7)<=month.value).reduce((s,e)=>s+Number(e.quantity),0)-Number(l.settled)))})).filter(l=>l.balance>0)))
const chosen=computed(()=>eligible.value.filter(l=>Number(quantities[l.id])>0))
async function refresh(){if(w.can('settle')&&w.can('cost_read'))await w.load(['settlements','credits'])}
watch(()=>w.ready.value,ready=>{if(ready)void refresh()},{immediate:true})
watch(()=>[route.params.id,w.ready.value] as const,async([id,ready])=>{selected.value=null;if(id&&ready)try{selected.value=(await w.query<Settlement>('settlements/'+id)).data}catch(cause){error.value=w.explain(cause)}},{immediate:true})
async function create(){busy.value=true;error.value='';try{const row=await w.command<Settlement>('settlements',{document_no:form.document_no,business_date:w.businessDate.value,month:month.value,currency:currency.value,counterparty:counterparty.value,lines:chosen.value.map(l=>({delivery_line_id:l.id,quantity:quantities[l.id]}))});dialog.value='';w.dirty.value=false;await w.load(['deliveries']);await refresh();await router.push({path:`${SPRAY_BASE}/finance/settlements/${row.id}`,query:{factory:w.factory.value}})}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
async function credit(){busy.value=true;error.value='';try{const ret=w.items('returns').find(r=>r.id===form.return_id);if(!ret)throw new Error('请选择实物退货');await w.command('credits',{business_date:w.businessDate.value,return_id:ret.id,settlement_line_id:form.settlement_line_id,quantity:form.quantity,reason:form.reason});dialog.value='';w.dirty.value=false;await w.load(['deliveries']);await refresh()}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
async function price(){busy.value=true;error.value='';try{const line=eligible.value.find(l=>l.id===form.line_id);if(!line)return;await w.command(`delivery-lines/${line.id}/price`,{business_date:w.businessDate.value,price:form.price,evidence:form.reason},line.version);dialog.value='';await w.load(['deliveries'])}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
function view(row:Entity){void router.push({path:`${SPRAY_BASE}/finance/settlements/${row.id}`,query:{factory:w.factory.value}})}
async function close(){if(w.dirty.value&&!(await w.confirmDiscard('放弃尚未保存的填写？')))return;dialog.value='';w.dirty.value=false}
</script>
<template>
 <div class="spray-page"><header class="spray-page-heading"><div><RouterLink class="spray-back" :to="{path:`${SPRAY_BASE}/finance`,query:{factory:w.factory.value}}"><ArrowLeft :size="14"/>经营与月结</RouterLink><h1>{{selected?selected.document_no:'委托方交收月结'}}</h1><p>按已验收净数量选单，允许部分结算；历史结算单价和金额保持冻结。</p></div><div class="spray-actions"><Button v-if="selected&&w.can('export')" variant="outline" @click="w.download('settlement',{entity_id:selected.id})"><Download :size="15"/>月结明细</Button><Button v-if="selected&&w.can('export')" variant="outline" @click="w.download('request',{entity_id:selected.id})">请款单</Button><Button v-if="!selected&&w.can('settle')" @click="dialog='create';form.document_no=documentNo('月结')"><Plus :size="15"/>选单结算</Button></div></header><WorkspaceState/><p v-if="error" class="spray-alert" role="alert">{{error}}</p>
 <template v-if="selected"><div class="spray-metrics"><div class="spray-metric"><small>委托方</small><strong class="spray-metric__text">{{selected.counterparty}}</strong><span>{{selected.month}}</span></div><div class="spray-metric"><small>冻结金额</small><strong>{{number(selected.total_amount)}}</strong><span>{{selected.currency}}</span></div><div class="spray-metric"><small>交收来源</small><strong>{{selected.lines.length}}</strong><span>条验收记录</span></div><div class="spray-metric"><small>结算版本</small><strong>V{{selected.version}}</strong><span>已冻结 · 后续退货另记贷项</span></div></div><section class="spray-panel"><div class="spray-panel__header"><h3>验收来源与部分结算明细</h3><Button v-if="w.can('settle')" variant="outline" @click="dialog='credit'">登记退货贷项</Button></div><RecordTable :rows="selected.lines" :columns="[{key:'delivery_document_no',label:'送货来源'},{key:'order_document_no',label:'订单'},{key:'item_part',label:'货号 / 部件'},{key:'unit',label:'单位'},{key:'quantity',label:'本次结算数量',numeric:true},{key:'price',label:'冻结单价',numeric:true},{key:'amount',label:'结算金额',numeric:true}]" @select="row=>w.passportId.value=String(row.demand_id)"/></section><section class="spray-panel"><div class="spray-panel__header"><h3>后续贷项</h3><span class="spray-muted">不改写原月结</span></div><RecordTable :rows="w.items('credits').filter(c=>selected?.lines.some(l=>l.id===c.settlement_line_id))" :columns="[{key:'business_date',label:'贷项日期'},{key:'quantity',label:'数量',numeric:true},{key:'amount',label:'贷项金额',numeric:true},{key:'reason',label:'依据'}]"/></section><RouterLink class="spray-text-button" :to="{path:`${SPRAY_BASE}/finance/settlements`,query:{factory:w.factory.value}}">返回全部月结</RouterLink></template>
 <template v-else><div class="spray-finance-filters"><label>验收月份<input v-model="month" type="month"/></label><label>委托方<select v-model="counterparty"><option value="">全部委托方</option><option v-for="party in parties" :key="party">{{party}}</option></select></label><label>币种<select v-model="currency"><option>CNY</option><option>HKD</option><option>USD</option></select></label></div><section class="spray-panel"><div class="spray-panel__header"><h3>待结验收明细</h3><span class="spray-badge">{{eligible.length}} 条可选来源</span></div><RecordTable :rows="eligible" :columns="[{key:'document_no',label:'送货单'},{key:'counterparty',label:'委托方'},{key:'accepted_date',label:'验收日'},{key:'accepted',label:'已验收',numeric:true},{key:'returned',label:'实物退货',numeric:true},{key:'settled',label:'已结',numeric:true},{key:'balance',label:'待结',numeric:true},{key:'price',label:'交收单价',numeric:true}]"><template #actions="{row}"><button v-if="w.can('cost_write')&&!Number(row.settled)" class="spray-text-button" @click="form.line_id=row.id;form.price=String(row.price??'');form.reason='';dialog='price'">核对价格</button></template></RecordTable></section><section class="spray-panel"><div class="spray-panel__header"><h3>已冻结月结</h3><span class="spray-muted">点开追溯原始来源</span></div><RecordTable :rows="w.items('settlements')" :columns="[{key:'document_no',label:'月结单'},{key:'counterparty',label:'委托方'},{key:'month',label:'月份'},{key:'currency',label:'币种'},{key:'total_amount',label:'冻结金额',numeric:true}]" @select="view"/></section></template>
 <WorkspaceDialog :open="!!dialog" :wide="dialog==='create'" :title="dialog==='create'?'核对本次结算范围':dialog==='price'?'确认交收单价':'退货贷项'" @close="close"><p v-if="error" class="spray-alert" role="alert">{{error}}</p><form class="spray-form" @input="w.dirty.value=true" @submit.prevent="dialog==='create'?create():dialog==='price'?price():credit()"><template v-if="dialog==='create'"><label>月结单号<input v-model="form.document_no" required/></label><label>委托方<select v-model="counterparty" required><option value="">请选择</option><option v-for="party in parties" :key="party">{{party}}</option></select></label><label>验收月份<input v-model="month" type="month" required/></label><label>币种<select v-model="currency"><option>CNY</option><option>HKD</option><option>USD</option></select></label><p class="wide spray-alert"><CircleAlert :size="16"/>逐行填入本次结算数量，留空不结；金额由已确认单价在服务器计算。</p><div class="wide spray-table-wrap"><table class="spray-table"><thead><tr><th>送货来源</th><th>待结数量</th><th>单价</th><th>本次结算</th></tr></thead><tbody><tr v-for="line in eligible" :key="line.id"><td>{{line.document_no}}<small>{{line.id.slice(0,8)}}</small></td><td>{{number(line.balance)}}</td><td>{{number(line.price)}}</td><td><input v-model="quantities[line.id]" :aria-label="`结算数量 ${line.document_no}`" inputmode="decimal" :disabled="line.price==null"/></td></tr></tbody></table><p v-if="!eligible.length" class="spray-empty">该月份暂无可结算验收记录。</p></div></template><template v-else-if="dialog==='price'"><label>单价<input v-model="form.price" inputmode="decimal" required/></label><label>确认依据<input v-model="form.reason" required/></label></template><template v-else><label class="wide">实物退货记录<select v-model="form.return_id" required><option value="">请选择</option><option v-for="ret in w.items('returns')" :key="ret.id" :value="ret.id">{{ret.business_date}} · {{ret.quantity}} · {{ret.reason}}</option></select></label><label class="wide">原月结行<select v-model="form.settlement_line_id" required><option value="">请选择</option><option v-for="line in selected?.lines" :key="line.id" :value="line.id">{{line.delivery_document_no}} · {{line.item_part}} · 已结 {{number(line.quantity)}} · 单价 {{number(line.price)}}</option></select></label><label>本次贷项数量<input v-model="form.quantity" inputmode="decimal" required/></label><label>依据<input v-model="form.reason" required/></label></template><div class="wide spray-actions"><Button type="submit" :disabled="busy||(dialog==='create'&&(!counterparty||!chosen.length))"><FileCheck :size="15"/>{{busy?'正在核对…':dialog==='create'?'确认并冻结月结':'保存确认'}}</Button><Button type="button" variant="outline" @click="close">取消</Button></div></form></WorkspaceDialog>
 </div>
</template>
