import type {
  BusinessDate,
  CreateUvReport,
  Id,
  IsoInstant,
  ShiftCode,
  UvAssignment,
  UvEntity,
  UvExpense,
  UvFactoryId,
  UvHandoverRecord,
  UvInkMovement,
  UvInkSku,
  UvMachine,
  UvMonthlyPolicy,
  UvPricingQuote,
  UvPrintJob,
  UvProcessVersion,
  UvProduct,
  UvRateVersion,
  UvReport,
  UvShiftTemplate,
  UvSourceAllocation,
  UvWorkerRef,
  UvQuality,
} from '../contracts'
import { DEFAULT_SHIFT_TEMPLATES, shanghaiInstant } from '../domain/businessTime'
import { emptyQuality } from '../domain/quality'
import { computePricing, defaultPricingInput } from '../domain/pricing'

/**
 * 合成样例（docs/uv-printing/UV_PRINT_SHARED_SPEC.md 18.1）。
 *
 * - 全部使用显式 `DEMO-` 标记与固定日期，不复制旧客户/员工真实行；
 * - 覆盖打印中/待机/维修/停用/心跳过期/从未连接机台、有价/未定价/同名不同货号/前导零货号、
 *   60 秒内两次合法完成/重复事件/跨午夜/跨班次/取消/推断时间/两条候选产品、
 *   全部待判/全合格/部分不良半成品/已更正报工、同色不同供应商与材质/500ml 包装/低库/零库、
 *   未排班/三人均分/跨机兼岗/已离职历史、零与缺失金额/缺工价/分摊舍入；
 * - 生产构建不静态引入本文件。
 */

// 基准值定义在轻量模块 ./constants，这里导入后原样再导出，
// 避免任何静态引用把整套合成记录带进生产包。
import {
  SAMPLE_AS_OF,
  SAMPLE_BUSINESS_DATE,
  SAMPLE_CURRENCY,
  SAMPLE_DEMO_TAG,
  SAMPLE_FACTORY_ID,
  SAMPLE_MONTH,
  SAMPLE_TODAY,
} from './constants'

export {
  SAMPLE_AS_OF,
  SAMPLE_BUSINESS_DATE,
  SAMPLE_CURRENCY,
  SAMPLE_DEMO_TAG,
  SAMPLE_FACTORY_ID,
  SAMPLE_MONTH,
  SAMPLE_TODAY,
}

function entity(id: string, createdAt: IsoInstant, version = 1): UvEntity {
  return {
    id,
    factory_id: SAMPLE_FACTORY_ID,
    version,
    created_at: createdAt,
    updated_at: createdAt,
  }
}

function at(businessDate: BusinessDate, localTime: string): IsoInstant {
  return shanghaiInstant(businessDate, localTime)
}

const SEED_CREATED = at('2026-08-01', '08:00')

/* ------------------------------------------------------------------ *
 * 机台：行政状态 / 遥测状态 / 采集新鲜度
 * ------------------------------------------------------------------ */

export const sampleMachines: UvMachine[] = [
  {
    ...entity('DEMO-M01', SEED_CREATED),
    code: 'UV-01',
    name: 'UV 平板机 1 号',
    brand: 'Honson',
    model: 'HS-2513G',
    ink_material: 'hard',
    admin_status: 'normal',
    runtime_status: 'printing',
    freshness: 'fresh',
    last_heartbeat_at: at(SAMPLE_BUSINESS_DATE, '14:19'),
    current_task_name: 'DEMO-8801-面板',
    progress_pct: 62,
    connector_id: 'DEMO-CONN-A1',
    connector_mode: 'PrintExp',
    capabilities: { progress: true, exact_completion: true, ink_by_color: true, stable_job_id: true },
    note: 'DEMO 样例机台，不是现场设备。',
  },
  {
    ...entity('DEMO-M02', SEED_CREATED),
    code: 'UV-02',
    name: 'UV 平板机 2 号',
    brand: 'Honson',
    model: 'HS-2513G',
    ink_material: 'hard',
    admin_status: 'normal',
    runtime_status: 'idle',
    freshness: 'fresh',
    last_heartbeat_at: at(SAMPLE_BUSINESS_DATE, '14:17'),
    current_task_name: null,
    progress_pct: null,
    connector_id: 'DEMO-CONN-A1',
    connector_mode: 'PrintExp',
    capabilities: { progress: true, exact_completion: true, ink_by_color: true, stable_job_id: true },
    note: 'DEMO 样例机台，不是现场设备。',
  },
  {
    ...entity('DEMO-M03', SEED_CREATED),
    code: 'UV-03',
    name: 'UV 卷材机',
    brand: 'Hoson',
    model: 'HR-320',
    ink_material: 'soft',
    admin_status: 'normal',
    runtime_status: 'error',
    freshness: 'fresh',
    last_heartbeat_at: at(SAMPLE_BUSINESS_DATE, '14:18'),
    current_task_name: 'DEMO-8802-标牌',
    progress_pct: null,
    connector_id: 'DEMO-CONN-A2',
    connector_mode: 'PrintMon',
    capabilities: { progress: false, exact_completion: false, ink_by_color: true, stable_job_id: true },
    note: '适配器不能提供准确进度与可信完工信号，运行时序留空。',
  },
  {
    ...entity('DEMO-M04', SEED_CREATED),
    code: 'UV-04',
    name: 'UV 平板机 4 号',
    brand: 'SLJet',
    model: 'SL-6090',
    ink_material: 'hard',
    admin_status: 'maintenance',
    runtime_status: 'offline',
    freshness: 'stale',
    last_heartbeat_at: at(SAMPLE_BUSINESS_DATE, '11:52'),
    current_task_name: null,
    progress_pct: null,
    connector_id: 'DEMO-CONN-A2',
    connector_mode: 'SLJet',
    capabilities: { progress: true, exact_completion: true, ink_by_color: false, stable_job_id: true },
    note: 'DEMO 维修中机台，行政状态与遥测状态分别维护。',
  },
  {
    ...entity('DEMO-M05', SEED_CREATED),
    code: 'UV-05',
    name: 'UV 平板机 5 号',
    brand: 'QYVision',
    model: 'QY-1310',
    ink_material: 'soft',
    admin_status: 'disabled',
    runtime_status: 'unknown',
    freshness: 'never_seen',
    last_heartbeat_at: null,
    current_task_name: null,
    progress_pct: null,
    connector_id: null,
    connector_mode: null,
    capabilities: { progress: false, exact_completion: false, ink_by_color: false, stable_job_id: false },
    note: '从未连接过的停用机台，不因为从未连接就当作停机事实。',
  },
  {
    ...entity('DEMO-M06', SEED_CREATED),
    code: 'UV-06',
    name: 'UV 打样机',
    brand: 'QYVision',
    model: 'QY-0606',
    ink_material: 'other',
    admin_status: 'normal',
    runtime_status: 'idle',
    freshness: 'fresh',
    last_heartbeat_at: at(SAMPLE_BUSINESS_DATE, '14:16'),
    current_task_name: null,
    progress_pct: null,
    connector_id: 'DEMO-CONN-A3',
    connector_mode: 'QYVision',
    capabilities: { progress: true, exact_completion: false, ink_by_color: false, stable_job_id: false },
    note: 'DEMO 打样机，没有生效计件工价，用于「未定价不是零工资」。',
  },
]

/* ------------------------------------------------------------------ *
 * 产品与工艺版本
 * ------------------------------------------------------------------ */

function processVersion(
  id: string,
  productId: string,
  input: Partial<UvProcessVersion> & { version_label: string; effective_from: BusinessDate },
): UvProcessVersion {
  return {
    ...entity(id, SEED_CREATED),
    product_id: productId,
    version_label: input.version_label,
    effective_from: input.effective_from,
    material: input.material ?? 'ABS',
    pieces_per_board: input.pieces_per_board ?? null,
    board_seconds: input.board_seconds ?? null,
    width_cm: input.width_cm ?? null,
    length_cm: input.length_cm ?? null,
    pricing_area_cm2: input.pricing_area_cm2 ?? null,
    machine_area_m2: input.machine_area_m2 ?? null,
    ink_reference_ml: input.ink_reference_ml ?? null,
    is_active: input.is_active ?? true,
  }
}

export const sampleProducts: UvProduct[] = [
  {
    ...entity('DEMO-P-0001', SEED_CREATED),
    product_no: 'DEMO-0001',
    name: '面板外壳 A',
    customer_name: 'DEMO 客户甲',
    external_ref: 'DEMO-PO-000123',
    external_ref_kind: 'order',
    aliases: ['面板A', 'PANEL-A'],
    is_active: true,
    process_versions: [
      processVersion('DEMO-PV-0001', 'DEMO-P-0001', {
        version_label: 'v1',
        effective_from: '2026-08-01',
        material: 'ABS',
        pieces_per_board: 20,
        board_seconds: 1800,
        width_cm: '30',
        length_cm: '20',
        pricing_area_cm2: '600',
        machine_area_m2: '0.72',
        ink_reference_ml: '4.5',
      }),
    ],
  },
  {
    ...entity('DEMO-P-0002', SEED_CREATED),
    product_no: 'DEMO-0002',
    name: '面板外壳 A',
    customer_name: 'DEMO 客户乙',
    external_ref: 'DEMO-PO-000124',
    external_ref_kind: 'order',
    aliases: ['面板A（乙）'],
    is_active: true,
    process_versions: [
      processVersion('DEMO-PV-0002', 'DEMO-P-0002', {
        version_label: 'v1',
        effective_from: '2026-08-01',
        material: 'ABS',
        pieces_per_board: 12,
        board_seconds: 1500,
        width_cm: '26',
        length_cm: '18',
        pricing_area_cm2: '468',
        machine_area_m2: '0.55',
        ink_reference_ml: '3.8',
      }),
    ],
  },
  {
    ...entity('DEMO-P-0003', SEED_CREATED),
    product_no: 'DEMO-0042',
    name: '控制面板盖',
    customer_name: 'DEMO 客户甲',
    external_ref: null,
    external_ref_kind: 'none',
    aliases: [],
    is_active: true,
    process_versions: [
      processVersion('DEMO-PV-0003', 'DEMO-P-0003', {
        version_label: 'v1',
        effective_from: '2026-08-15',
        material: 'PC',
        pieces_per_board: 8,
        board_seconds: 900,
        width_cm: '40',
        length_cm: '25',
        pricing_area_cm2: '1000',
        machine_area_m2: '1.1',
        ink_reference_ml: '6.2',
      }),
    ],
  },
  {
    ...entity('DEMO-P-0004', SEED_CREATED),
    product_no: 'DEMO-0007',
    name: '按键铭牌',
    customer_name: 'DEMO 客户丙',
    external_ref: 'DEMO-QT-0009',
    external_ref_kind: 'quotation',
    aliases: ['铭牌'],
    is_active: true,
    process_versions: [
      processVersion('DEMO-PV-0004', 'DEMO-P-0004', {
        version_label: 'v1',
        effective_from: '2026-07-01',
        material: 'PET',
        pieces_per_board: 48,
        board_seconds: 600,
        width_cm: '12',
        length_cm: '8',
        pricing_area_cm2: '96',
        machine_area_m2: '0.12',
        ink_reference_ml: '1.1',
      }),
    ],
  },
  {
    ...entity('DEMO-P-0005', SEED_CREATED),
    product_no: 'DEMO-0100',
    name: '灯箱片',
    customer_name: 'DEMO 客户丁',
    external_ref: null,
    external_ref_kind: 'none',
    aliases: [],
    is_active: true,
    process_versions: [
      processVersion('DEMO-PV-0005', 'DEMO-P-0005', {
        version_label: 'v1',
        effective_from: '2026-08-20',
        material: 'PVC',
        pieces_per_board: null,
        board_seconds: null,
        width_cm: '60',
        length_cm: '90',
        pricing_area_cm2: '5400',
        machine_area_m2: '0.58',
        ink_reference_ml: null,
      }),
    ],
  },
  {
    ...entity('DEMO-P-0006', SEED_CREATED),
    product_no: 'DEMO-0315',
    name: '尾板试打件',
    customer_name: 'DEMO 客户甲',
    external_ref: null,
    external_ref_kind: 'none',
    aliases: [],
    is_active: true,
    process_versions: [
      processVersion('DEMO-PV-0006', 'DEMO-P-0006', {
        version_label: 'v1',
        effective_from: '2026-09-01',
        material: 'ABS',
        pieces_per_board: 20,
        board_seconds: 1800,
        width_cm: '30',
        length_cm: '20',
        pricing_area_cm2: '600',
        machine_area_m2: '0.72',
        ink_reference_ml: '4.5',
      }),
    ],
  },
]

/* ------------------------------------------------------------------ *
 * 价规版本：商业执行价 / 计件工价 / 面积费率
 * ------------------------------------------------------------------ */

function rateVersion(
  id: string,
  input: Omit<UvRateVersion, keyof UvEntity | 'factory_id'> & { id: string },
): UvRateVersion {
  return { ...entity(id, SEED_CREATED), ...input }
}

export const sampleRateVersions: UvRateVersion[] = [
  rateVersion('DEMO-RV-C-0001', {
    id: 'DEMO-RV-C-0001',
    rate_kind: 'commercial',
    product_id: 'DEMO-P-0001',
    process_version_id: 'DEMO-PV-0001',
    machine_id: null,
    price_group: null,
    currency: SAMPLE_CURRENCY,
    unit_price: '1.000000',
    effective_from: '2026-08-01',
    effective_to: null,
    note: 'DEMO 标准商业执行价。',
  }),
  rateVersion('DEMO-RV-C-0001-M01', {
    id: 'DEMO-RV-C-0001-M01',
    rate_kind: 'commercial',
    product_id: 'DEMO-P-0001',
    process_version_id: 'DEMO-PV-0001',
    machine_id: 'DEMO-M01',
    price_group: null,
    currency: SAMPLE_CURRENCY,
    unit_price: '1.200000',
    effective_from: '2026-08-01',
    effective_to: null,
    note: 'DEMO 精确机台覆盖，优先于标准价。',
  }),
  rateVersion('DEMO-RV-C-0002', {
    id: 'DEMO-RV-C-0002',
    rate_kind: 'commercial',
    product_id: 'DEMO-P-0002',
    process_version_id: 'DEMO-PV-0002',
    machine_id: null,
    price_group: null,
    currency: SAMPLE_CURRENCY,
    unit_price: '0.850000',
    effective_from: '2026-08-01',
    effective_to: null,
    note: 'DEMO 同名不同货号，价格不同。',
  }),
  rateVersion('DEMO-RV-C-0003', {
    id: 'DEMO-RV-C-0003',
    rate_kind: 'commercial',
    product_id: 'DEMO-P-0003',
    process_version_id: 'DEMO-PV-0003',
    machine_id: null,
    price_group: null,
    currency: SAMPLE_CURRENCY,
    unit_price: '2.400000',
    effective_from: '2026-08-15',
    effective_to: null,
    note: 'DEMO 控制面板盖执行价。',
  }),
  rateVersion('DEMO-RV-C-0005', {
    id: 'DEMO-RV-C-0005',
    rate_kind: 'commercial',
    product_id: 'DEMO-P-0005',
    process_version_id: 'DEMO-PV-0005',
    machine_id: null,
    price_group: null,
    currency: SAMPLE_CURRENCY,
    unit_price: '0.000000',
    effective_from: '2026-08-20',
    effective_to: null,
    note: 'DEMO 显式零价：零价与缺价不同，报表不能把零价当未定价。',
  }),
  rateVersion('DEMO-RV-W-0001', {
    id: 'DEMO-RV-W-0001',
    rate_kind: 'piece_wage',
    product_id: 'DEMO-P-0001',
    process_version_id: 'DEMO-PV-0001',
    machine_id: null,
    price_group: null,
    currency: SAMPLE_CURRENCY,
    unit_price: '0.200000',
    effective_from: '2026-08-01',
    effective_to: null,
    note: 'DEMO 计件工价，与商业执行价严格分开。',
  }),
  rateVersion('DEMO-RV-W-0002', {
    id: 'DEMO-RV-W-0002',
    rate_kind: 'piece_wage',
    product_id: 'DEMO-P-0002',
    process_version_id: 'DEMO-PV-0002',
    machine_id: null,
    price_group: null,
    currency: SAMPLE_CURRENCY,
    unit_price: '0.150000',
    effective_from: '2026-08-01',
    effective_to: null,
    note: 'DEMO 计件工价。',
  }),
  rateVersion('DEMO-RV-W-0003', {
    id: 'DEMO-RV-W-0003',
    rate_kind: 'piece_wage',
    product_id: 'DEMO-P-0003',
    process_version_id: 'DEMO-PV-0003',
    machine_id: null,
    price_group: null,
    currency: SAMPLE_CURRENCY,
    unit_price: '0.350000',
    effective_from: '2026-08-15',
    effective_to: null,
    note: 'DEMO 计件工价。',
  }),
  rateVersion('DEMO-RV-A-0001', {
    id: 'DEMO-RV-A-0001',
    rate_kind: 'area',
    product_id: 'DEMO-P-0001',
    process_version_id: 'DEMO-PV-0001',
    machine_id: null,
    price_group: null,
    currency: SAMPLE_CURRENCY,
    unit_price: '0.010000',
    effective_from: '2026-08-01',
    effective_to: null,
    note: 'DEMO 面积费率（每 cm²），只作独立参考产值，不与按件产值相加。',
  }),
]

/* ------------------------------------------------------------------ *
 * 采集作业
 * ------------------------------------------------------------------ */

function job(
  id: string,
  input: Omit<UvPrintJob, keyof UvEntity | 'factory_id' | 'candidates' | 'ink_by_color'> & {
    candidates?: UvPrintJob['candidates']
    ink_by_color?: UvPrintJob['ink_by_color']
  },
): UvPrintJob {
  const { candidates, ink_by_color: inkByColor, ...rest } = input
  return {
    ...entity(id, at(input.started_at ? input.started_at.slice(0, 10) : SAMPLE_BUSINESS_DATE, '08:00')),
    ...rest,
    id,
    candidates: candidates ?? [],
    ink_by_color: inkByColor ?? [],
  }
}

export const sampleJobs: UvPrintJob[] = [
  job('DEMO-J-1001', {
    machine_id: 'DEMO-M01',
    source_job_id: 'DEMO-SRC-1001',
    source_event_id: 'DEMO-EVT-1001-END',
    connector_id: 'DEMO-CONN-A1',
    generation: 'g1',
    raw_task_name: 'DEMO-8801-面板',
    raw_product_name: '面板外壳 A',
    product_id: 'DEMO-P-0001',
    process_version_id: 'DEMO-PV-0001',
    candidates: [{ product_id: 'DEMO-P-0001', reason: '任务名与货号规则一致', confidence: 0.92 }],
    state: 'completed',
    reconciliation: 'ready',
    reconcile_note: '',
    started_at: at(SAMPLE_BUSINESS_DATE, '09:10'),
    completed_at: at(SAMPLE_BUSINESS_DATE, '09:40'),
    time_evidence: 'observed',
    raw_count: '2',
    raw_unit: 'board',
    suggested_piece_qty: 40,
    available_piece_qty: 40,
    print_time_seconds: 1800,
    print_area_m2: '1.44',
    ink_total_ml: '9.0',
    ink_by_color: [
      { color: '白', ml: '5.0' },
      { color: '青', ml: '4.0' },
    ],
    resolution: '1440x2880',
    color_count: 4,
    duplicate_suspect: false,
  }),
  job('DEMO-J-1002', {
    machine_id: 'DEMO-M01',
    source_job_id: 'DEMO-SRC-1002',
    source_event_id: 'DEMO-EVT-1002-END',
    connector_id: 'DEMO-CONN-A1',
    generation: 'g1',
    raw_task_name: 'DEMO-8801-面板',
    raw_product_name: '面板外壳 A',
    product_id: 'DEMO-P-0001',
    process_version_id: 'DEMO-PV-0001',
    candidates: [{ product_id: 'DEMO-P-0001', reason: '任务名与货号规则一致', confidence: 0.9 }],
    state: 'completed',
    reconciliation: 'ready',
    reconcile_note: '',
    started_at: at(SAMPLE_BUSINESS_DATE, '09:41'),
    completed_at: at(SAMPLE_BUSINESS_DATE, '10:11'),
    time_evidence: 'observed',
    raw_count: '2',
    raw_unit: 'board',
    suggested_piece_qty: 40,
    available_piece_qty: 40,
    print_time_seconds: 1800,
    print_area_m2: '1.44',
    ink_total_ml: '8.6',
    ink_by_color: [{ color: '白', ml: '8.6' }],
    resolution: '1440x2880',
    color_count: 4,
    duplicate_suspect: true,
  }),
  job('DEMO-J-1003', {
    machine_id: 'DEMO-M02',
    source_job_id: 'DEMO-SRC-1003',
    source_event_id: 'DEMO-EVT-1003-END',
    connector_id: 'DEMO-CONN-A1',
    generation: 'g1',
    raw_task_name: 'DEMO-0042-控制面板盖',
    raw_product_name: '控制面板盖',
    product_id: 'DEMO-P-0003',
    process_version_id: 'DEMO-PV-0003',
    candidates: [{ product_id: 'DEMO-P-0003', reason: '任务名精确匹配', confidence: 0.97 }],
    state: 'completed',
    reconciliation: 'partially_allocated',
    reconcile_note: '',
    started_at: at(SAMPLE_BUSINESS_DATE, '08:05'),
    completed_at: at(SAMPLE_BUSINESS_DATE, '08:35'),
    time_evidence: 'observed',
    raw_count: '1',
    raw_unit: 'board',
    suggested_piece_qty: 8,
    available_piece_qty: 0,
    print_time_seconds: 1800,
    print_area_m2: '0.55',
    ink_total_ml: '6.2',
    ink_by_color: [{ color: '白', ml: '4.0' }, { color: '品红', ml: '2.2' }],
    resolution: '720x1440',
    color_count: 4,
    duplicate_suspect: false,
  }),
  job('DEMO-J-1004', {
    machine_id: 'DEMO-M03',
    source_job_id: 'DEMO-SRC-1004',
    source_event_id: 'DEMO-EVT-1004-END',
    connector_id: 'DEMO-CONN-A2',
    generation: 'g1',
    raw_task_name: 'DEMO-8802-标牌',
    raw_product_name: null,
    product_id: null,
    process_version_id: null,
    candidates: [
      { product_id: 'DEMO-P-0004', reason: '任务名包含「铭牌」别名', confidence: 0.61 },
      { product_id: 'DEMO-P-0002', reason: '原始产品名与客户乙历史记录相近', confidence: 0.44 },
    ],
    state: 'completed',
    reconciliation: 'unmatched',
    reconcile_note: '两条候选产品都需要人工确认，不能自动过账。',
    started_at: at(SAMPLE_BUSINESS_DATE, '10:02'),
    completed_at: at(SAMPLE_BUSINESS_DATE, '10:42'),
    time_evidence: 'observed',
    raw_count: '3',
    raw_unit: 'cycle',
    suggested_piece_qty: null,
    available_piece_qty: null,
    print_time_seconds: 2400,
    print_area_m2: '0.36',
    ink_total_ml: '3.3',
    ink_by_color: [{ color: '白', ml: '3.3' }],
    resolution: null,
    color_count: null,
    duplicate_suspect: false,
  }),
  job('DEMO-J-1005', {
    machine_id: 'DEMO-M01',
    source_job_id: 'DEMO-SRC-1005',
    source_event_id: 'DEMO-EVT-1005-END',
    connector_id: 'DEMO-CONN-A1',
    generation: 'g1',
    raw_task_name: 'DEMO-8803-未知单位',
    raw_product_name: '按键铭牌',
    product_id: 'DEMO-P-0004',
    process_version_id: 'DEMO-PV-0004',
    candidates: [{ product_id: 'DEMO-P-0004', reason: '原始产品名精确匹配', confidence: 0.88 }],
    state: 'completed',
    reconciliation: 'needs_unit',
    reconcile_note: '适配器未声明单位，raw_count=10 不能自动当 10 件，也不盲乘每板件数。',
    started_at: at(SAMPLE_BUSINESS_DATE, '11:00'),
    completed_at: at(SAMPLE_BUSINESS_DATE, '11:12'),
    time_evidence: 'inferred',
    raw_count: '10',
    raw_unit: 'unknown',
    suggested_piece_qty: null,
    available_piece_qty: null,
    print_time_seconds: 720,
    print_area_m2: '0.12',
    ink_total_ml: '1.1',
    ink_by_color: [],
    resolution: null,
    color_count: 4,
    duplicate_suspect: false,
  }),
  job('DEMO-J-1006', {
    machine_id: 'DEMO-M02',
    source_job_id: 'DEMO-SRC-1006',
    source_event_id: 'DEMO-EVT-1006-END',
    connector_id: 'DEMO-CONN-A1',
    generation: 'g1',
    raw_task_name: 'DEMO-8804-尾板',
    raw_product_name: '尾板试打件',
    product_id: 'DEMO-P-0006',
    process_version_id: 'DEMO-PV-0006',
    candidates: [{ product_id: 'DEMO-P-0006', reason: '任务名精确匹配', confidence: 0.95 }],
    state: 'completed',
    reconciliation: 'ready',
    reconcile_note: '2 完整板 × 20 件 + 尾板确认 7 件 = 47 件建议量。',
    started_at: at(SAMPLE_BUSINESS_DATE, '13:00'),
    completed_at: at(SAMPLE_BUSINESS_DATE, '13:30'),
    time_evidence: 'observed',
    raw_count: '2',
    raw_unit: 'board',
    suggested_piece_qty: 47,
    available_piece_qty: 47,
    print_time_seconds: 1800,
    print_area_m2: '1.44',
    ink_total_ml: '9.4',
    ink_by_color: [{ color: '白', ml: '9.4' }],
    resolution: '1440x2880',
    color_count: 4,
    duplicate_suspect: false,
  }),
  job('DEMO-J-1007', {
    machine_id: 'DEMO-M01',
    source_job_id: 'DEMO-SRC-1007',
    source_event_id: 'DEMO-EVT-1007-END',
    connector_id: 'DEMO-CONN-A1',
    generation: 'g1',
    raw_task_name: 'DEMO-8805-跨班次',
    raw_product_name: '面板外壳 A',
    product_id: 'DEMO-P-0001',
    process_version_id: 'DEMO-PV-0001',
    candidates: [{ product_id: 'DEMO-P-0001', reason: '任务名精确匹配', confidence: 0.93 }],
    state: 'completed',
    reconciliation: 'ready',
    reconcile_note: '结束时间落在夜班，产量默认归完成时所在班次，运行时长按班次区间拆分。',
    started_at: at(SAMPLE_BUSINESS_DATE, '20:30'),
    completed_at: at(SAMPLE_BUSINESS_DATE, '22:00'),
    time_evidence: 'observed',
    raw_count: '1',
    raw_unit: 'board',
    suggested_piece_qty: 20,
    available_piece_qty: 20,
    print_time_seconds: 5400,
    print_area_m2: '0.72',
    ink_total_ml: '4.8',
    ink_by_color: [{ color: '白', ml: '4.8' }],
    resolution: '1440x2880',
    color_count: 4,
    duplicate_suspect: false,
  }),
  job('DEMO-J-1008', {
    machine_id: 'DEMO-M02',
    source_job_id: 'DEMO-SRC-1008',
    source_event_id: 'DEMO-EVT-1008-END',
    connector_id: 'DEMO-CONN-A1',
    generation: 'g1',
    raw_task_name: 'DEMO-8806-跨午夜',
    raw_product_name: '控制面板盖',
    product_id: 'DEMO-P-0003',
    process_version_id: 'DEMO-PV-0003',
    candidates: [{ product_id: 'DEMO-P-0003', reason: '任务名精确匹配', confidence: 0.94 }],
    state: 'completed',
    reconciliation: 'ready',
    reconcile_note: '夜班跨自然日，业务日期仍是班次开始日。',
    started_at: at('2026-09-12', '23:30'),
    completed_at: at(SAMPLE_BUSINESS_DATE, '00:30'),
    time_evidence: 'observed',
    raw_count: '2',
    raw_unit: 'board',
    suggested_piece_qty: 16,
    available_piece_qty: 16,
    print_time_seconds: 3600,
    print_area_m2: '1.1',
    ink_total_ml: '12.4',
    ink_by_color: [{ color: '白', ml: '8.0' }, { color: '青', ml: '4.4' }],
    resolution: '720x1440',
    color_count: 4,
    duplicate_suspect: false,
  }),
  job('DEMO-J-1009', {
    machine_id: 'DEMO-M03',
    source_job_id: 'DEMO-SRC-1009',
    source_event_id: 'DEMO-EVT-1009-CANCEL',
    connector_id: 'DEMO-CONN-A2',
    generation: 'g1',
    raw_task_name: 'DEMO-8807-取消',
    raw_product_name: '灯箱片',
    product_id: 'DEMO-P-0005',
    process_version_id: 'DEMO-PV-0005',
    candidates: [{ product_id: 'DEMO-P-0005', reason: '任务名精确匹配', confidence: 0.9 }],
    state: 'cancelled',
    reconciliation: 'ignored',
    reconcile_note: '现场在软件内取消，未产生合格品。',
    started_at: at(SAMPLE_BUSINESS_DATE, '12:10'),
    completed_at: at(SAMPLE_BUSINESS_DATE, '12:14'),
    time_evidence: 'observed',
    raw_count: '1',
    raw_unit: 'board',
    suggested_piece_qty: null,
    available_piece_qty: 0,
    print_time_seconds: 240,
    print_area_m2: '0.58',
    ink_total_ml: '0.4',
    ink_by_color: [{ color: '白', ml: '0.4' }],
    resolution: null,
    color_count: null,
    duplicate_suspect: false,
  }),
  job('DEMO-J-1010', {
    machine_id: 'DEMO-M01',
    source_job_id: 'DEMO-SRC-1010',
    source_event_id: 'DEMO-EVT-1010-END',
    connector_id: 'DEMO-CONN-A1',
    generation: 'g2',
    raw_task_name: 'DEMO-8808-完工不确定',
    raw_product_name: '按键铭牌',
    product_id: 'DEMO-P-0004',
    process_version_id: 'DEMO-PV-0004',
    candidates: [{ product_id: 'DEMO-P-0004', reason: '原始产品名精确匹配', confidence: 0.86 }],
    state: 'uncertain',
    reconciliation: 'ready',
    reconcile_note: '连续三次读不到软件 UI，属于不确定结束，不自动判定合格完工。',
    started_at: at(SAMPLE_BUSINESS_DATE, '13:40'),
    completed_at: null,
    time_evidence: 'unknown',
    raw_count: null,
    raw_unit: 'unknown',
    suggested_piece_qty: null,
    available_piece_qty: null,
    print_time_seconds: null,
    print_area_m2: null,
    ink_total_ml: null,
    ink_by_color: [],
    resolution: null,
    color_count: null,
    duplicate_suspect: false,
  }),
  job('DEMO-J-1011', {
    machine_id: 'DEMO-M02',
    source_job_id: 'DEMO-SRC-1011',
    source_event_id: 'DEMO-EVT-1011-END',
    connector_id: 'DEMO-CONN-A1',
    generation: 'g1',
    raw_task_name: 'DEMO-8809-已分配',
    raw_product_name: '按键铭牌',
    product_id: 'DEMO-P-0004',
    process_version_id: 'DEMO-PV-0004',
    candidates: [{ product_id: 'DEMO-P-0004', reason: '任务名精确匹配', confidence: 0.91 }],
    state: 'completed',
    reconciliation: 'allocated',
    reconcile_note: '',
    started_at: at(SAMPLE_BUSINESS_DATE, '07:50'),
    completed_at: at(SAMPLE_BUSINESS_DATE, '08:00'),
    time_evidence: 'observed',
    raw_count: '1',
    raw_unit: 'board',
    suggested_piece_qty: 48,
    available_piece_qty: 0,
    print_time_seconds: 600,
    print_area_m2: '0.12',
    ink_total_ml: '1.2',
    ink_by_color: [{ color: '白', ml: '1.2' }],
    resolution: '1440x1440',
    color_count: 4,
    duplicate_suspect: false,
  }),
  job('DEMO-J-1012', {
    machine_id: 'DEMO-M02',
    source_job_id: 'DEMO-SRC-1012',
    source_event_id: 'DEMO-EVT-1012-END',
    connector_id: 'DEMO-CONN-A1',
    generation: 'g1',
    raw_task_name: 'DEMO-8810-周日计划外',
    raw_product_name: '面板外壳 A（乙）',
    product_id: 'DEMO-P-0002',
    process_version_id: 'DEMO-PV-0002',
    candidates: [{ product_id: 'DEMO-P-0002', reason: '原始产品名精确匹配', confidence: 0.9 }],
    state: 'completed',
    reconciliation: 'ready',
    reconcile_note: '周日仍存在真实报工，保留产量并标记计划外作业。',
    started_at: at('2026-09-13', '08:20'),
    completed_at: at('2026-09-13', '08:50'),
    time_evidence: 'observed',
    raw_count: '2',
    raw_unit: 'board',
    suggested_piece_qty: 24,
    available_piece_qty: 24,
    print_time_seconds: 1800,
    print_area_m2: '0.9',
    ink_total_ml: '7.6',
    ink_by_color: [{ color: '白', ml: '7.6' }],
    resolution: '720x1440',
    color_count: 4,
    duplicate_suspect: false,
  }),
]

/* ------------------------------------------------------------------ *
 * 人员名册（报工样例需要先解析姓名，故声明在报工之前）
 * ------------------------------------------------------------------ */

export const sampleWorkers: UvWorkerRef[] = [
  {
    ...entity('DEMO-W-001', SEED_CREATED),
    employee_profile_id: null,
    employee_no: 'DEMO-E001',
    display_name: 'DEMO 操作员甲',
    role: 'operator',
    employ_state: 'active',
    left_on: null,
    note: '现场未开户工人，独立劳动名册映射，不伪造系统账号。',
  },
  {
    ...entity('DEMO-W-002', SEED_CREATED),
    employee_profile_id: null,
    employee_no: 'DEMO-E002',
    display_name: 'DEMO 操作员乙',
    role: 'operator',
    employ_state: 'active',
    left_on: null,
    note: '',
  },
  {
    ...entity('DEMO-W-003', SEED_CREATED),
    employee_profile_id: null,
    employee_no: 'DEMO-E003',
    display_name: 'DEMO 管工丙',
    role: 'foreman',
    employ_state: 'active',
    left_on: null,
    note: '跨机兼岗：同时安排在两台机，按份额核对工作批次。',
  },
  {
    ...entity('DEMO-W-004', SEED_CREATED),
    employee_profile_id: null,
    employee_no: 'DEMO-E004',
    display_name: 'DEMO 师傅丁',
    role: 'master',
    employ_state: 'active',
    left_on: null,
    note: '',
  },
  {
    ...entity('DEMO-W-005', SEED_CREATED),
    employee_profile_id: null,
    employee_no: 'DEMO-E005',
    display_name: 'DEMO 操作员戊',
    role: 'operator',
    employ_state: 'active',
    left_on: null,
    note: '',
  },
  {
    ...entity('DEMO-W-006', SEED_CREATED),
    employee_profile_id: null,
    employee_no: 'DEMO-E006',
    display_name: 'DEMO 操作员己',
    role: 'operator',
    employ_state: 'active',
    left_on: null,
    note: '',
  },
  {
    ...entity('DEMO-W-007', SEED_CREATED),
    employee_profile_id: null,
    employee_no: 'DEMO-E007',
    display_name: 'DEMO 离职师傅庚',
    role: 'master',
    employ_state: 'left',
    left_on: '2026-08-31',
    note: '已离职，历史排班与工资快照保留。',
  },
]

/* ------------------------------------------------------------------ *
 * 业务报工
 * ------------------------------------------------------------------ */

interface ReportSeed extends Partial<UvReport> {
  id: string
  business_date: BusinessDate
  shift: ShiftCode
  machine_id: Id
  product_id: Id
  source_kind: UvReport['source_kind']
  status: UvReport['status']
  quality: UvQuality
  worker_ids: Id[]
  notes?: string
  replaces_report_id?: Id | null
  correction_reason?: string
  allocation_total?: number
}

function seedReport(seed: ReportSeed): UvReport {
  const product = sampleProducts.find((candidate) => candidate.id === seed.product_id)
  const processVersion = product?.process_versions[0]
  const workers = seed.worker_ids
    .map((workerId) => sampleWorkers.find((worker) => worker.id === workerId))
    .filter((worker): worker is UvWorkerRef => Boolean(worker))
  const qualityStatus = seed.quality.pending_qty === seed.quality.reported_qty && seed.quality.reported_qty > 0
    ? 'pending'
    : seed.quality.pending_qty > 0 || seed.quality.semi_finished_qty > 0
      ? 'partial'
      : 'complete'

  return {
    ...entity(seed.id, at(seed.business_date, '07:00'), seed.status === 'corrected' ? 2 : 1),
    business_date: seed.business_date,
    shift: seed.shift,
    shift_template_version_id: DEFAULT_SHIFT_TEMPLATES[seed.shift].versionId,
    machine_id: seed.machine_id,
    product_id: seed.product_id,
    process_version_id: processVersion?.id ?? '',
    product_no: product?.product_no ?? '',
    product_name: product?.name ?? '',
    reported_qty: seed.quality.reported_qty,
    good_qty: seed.quality.good_qty,
    defective_qty: seed.quality.defective_qty,
    pending_qty: seed.quality.pending_qty,
    semi_finished_qty: seed.quality.semi_finished_qty,
    source_kind: seed.source_kind,
    status: seed.status,
    quality_status: qualityStatus,
    worker_ids: seed.worker_ids,
    worker_names: workers.map((worker) => worker.display_name),
    notes: seed.notes ?? '',
    replaces_report_id: seed.replaces_report_id ?? null,
    correction_reason: seed.correction_reason ?? '',
    allocation_total: seed.allocation_total ?? 0,
  }
}

export const sampleReports: UvReport[] = [
  seedReport({
    id: 'DEMO-R-2001',
    business_date: SAMPLE_BUSINESS_DATE,
    shift: 'day',
    machine_id: 'DEMO-M01',
    product_id: 'DEMO-P-0001',
    source_kind: 'manual',
    status: 'draft',
    quality: { reported_qty: 40, good_qty: 0, defective_qty: 0, pending_qty: 40, semi_finished_qty: 0 },
    worker_ids: ['DEMO-W-001', 'DEMO-W-002', 'DEMO-W-003'],
    notes: '全部待判：现场先记录数量，质量由 QC 复核。',
  }),
  seedReport({
    id: 'DEMO-R-2002',
    business_date: SAMPLE_BUSINESS_DATE,
    shift: 'day',
    machine_id: 'DEMO-M02',
    product_id: 'DEMO-P-0003',
    source_kind: 'mixed',
    status: 'confirmed',
    quality: { reported_qty: 8, good_qty: 8, defective_qty: 0, pending_qty: 0, semi_finished_qty: 0 },
    worker_ids: ['DEMO-W-002'],
    notes: '关联 DEMO-J-1003，全部合格。',
    allocation_total: 8,
  }),
  seedReport({
    id: 'DEMO-R-2003',
    business_date: SAMPLE_BUSINESS_DATE,
    shift: 'day',
    machine_id: 'DEMO-M01',
    product_id: 'DEMO-P-0004',
    source_kind: 'device',
    status: 'confirmed',
    quality: { reported_qty: 48, good_qty: 45, defective_qty: 2, pending_qty: 1, semi_finished_qty: 0 },
    worker_ids: ['DEMO-W-004'],
    notes: '关联 DEMO-J-1011，部分不良与待判。',
    allocation_total: 48,
  }),
  seedReport({
    id: 'DEMO-R-2004',
    business_date: '2026-09-12',
    shift: 'night',
    machine_id: 'DEMO-M02',
    product_id: 'DEMO-P-0003',
    source_kind: 'device',
    status: 'confirmed',
    quality: { reported_qty: 16, good_qty: 14, defective_qty: 1, pending_qty: 0, semi_finished_qty: 1 },
    worker_ids: ['DEMO-W-005'],
    notes: '跨午夜夜班作业，业务日期归 09-12。',
    allocation_total: 16,
  }),
  seedReport({
    id: 'DEMO-R-2005',
    business_date: SAMPLE_BUSINESS_DATE,
    shift: 'day',
    machine_id: 'DEMO-M06',
    product_id: 'DEMO-P-0005',
    source_kind: 'manual',
    status: 'confirmed',
    quality: { reported_qty: 30, good_qty: 30, defective_qty: 0, pending_qty: 0, semi_finished_qty: 0 },
    worker_ids: [],
    notes: '灯箱片没有生效计件工价（只有商业价），也没有排班人员：显示未定价 + 未排班，不给 0 工资。',
  }),
  seedReport({
    id: 'DEMO-R-2006',
    business_date: '2026-09-11',
    shift: 'day',
    machine_id: 'DEMO-M01',
    product_id: 'DEMO-P-0001',
    source_kind: 'manual',
    status: 'corrected',
    quality: { reported_qty: 100, good_qty: 92, defective_qty: 6, pending_qty: 0, semi_finished_qty: 2 },
    worker_ids: ['DEMO-W-001', 'DEMO-W-002'],
    notes: '已更正报工的当前有效修订，原记录与新记录都保留。',
    correction_reason: '入库核数发现 5 件外观不良，追加不良并保留原记录。',
  }),
  seedReport({
    id: 'DEMO-R-2007',
    business_date: '2026-09-11',
    shift: 'day',
    machine_id: 'DEMO-M01',
    product_id: 'DEMO-P-0001',
    source_kind: 'manual',
    status: 'voided',
    quality: { reported_qty: 100, good_qty: 95, defective_qty: 5, pending_qty: 0, semi_finished_qty: 0 },
    worker_ids: ['DEMO-W-001', 'DEMO-W-002'],
    notes: '被更正的原记录，保留为审计证据，不覆盖。',
  }),
  seedReport({
    id: 'DEMO-R-2008',
    business_date: '2026-09-13',
    shift: 'day',
    machine_id: 'DEMO-M02',
    product_id: 'DEMO-P-0002',
    source_kind: 'device',
    status: 'confirmed',
    quality: { reported_qty: 24, good_qty: 22, defective_qty: 2, pending_qty: 0, semi_finished_qty: 0 },
    worker_ids: ['DEMO-W-006'],
    notes: '周日计划外作业：保留真实产量并标注计划外。',
    allocation_total: 24,
  }),
]

export const sampleAllocations: UvSourceAllocation[] = [
  {
    ...entity('DEMO-SA-3001', at(SAMPLE_BUSINESS_DATE, '10:00')),
    job_id: 'DEMO-J-1003',
    report_id: 'DEMO-R-2002',
    piece_qty: 8,
    reversed: false,
  },
  {
    ...entity('DEMO-SA-3002', at(SAMPLE_BUSINESS_DATE, '08:10')),
    job_id: 'DEMO-J-1011',
    report_id: 'DEMO-R-2003',
    piece_qty: 48,
    reversed: false,
  },
  {
    ...entity('DEMO-SA-3003', at(SAMPLE_BUSINESS_DATE, '00:45')),
    job_id: 'DEMO-J-1008',
    report_id: 'DEMO-R-2004',
    piece_qty: 16,
    reversed: false,
  },
  {
    ...entity('DEMO-SA-3004', at(SAMPLE_BUSINESS_DATE, '09:30')),
    job_id: 'DEMO-J-1007',
    report_id: 'DEMO-R-2008',
    piece_qty: 20,
    reversed: false,
  },
]

/* ------------------------------------------------------------------ *
 * 入库核数 / 交接记录
 * ------------------------------------------------------------------ */

export const sampleHandovers: UvHandoverRecord[] = [
  {
    ...entity('DEMO-H-4001', at(SAMPLE_BUSINESS_DATE, '10:20')),
    business_date: SAMPLE_BUSINESS_DATE,
    product_id: 'DEMO-P-0003',
    product_no: 'DEMO-0042',
    product_name: '控制面板盖',
    report_id: 'DEMO-R-2002',
    reported_qty: 8,
    received_qty: 8,
    difference_qty: 0,
    state: 'reconciled',
    receiver: 'DEMO 仓管甲',
    note: '核数一致；本记录不代表 PMC 仓库已入账。',
  },
  {
    ...entity('DEMO-H-4002', at(SAMPLE_BUSINESS_DATE, '11:05')),
    business_date: SAMPLE_BUSINESS_DATE,
    product_id: 'DEMO-P-0004',
    product_no: 'DEMO-0007',
    product_name: '按键铭牌',
    report_id: 'DEMO-R-2003',
    reported_qty: 48,
    received_qty: 45,
    difference_qty: -3,
    state: 'difference',
    receiver: 'DEMO 仓管乙',
    note: '差异 3 件，报工原值不覆盖。',
  },
  {
    ...entity('DEMO-H-4003', at(SAMPLE_BUSINESS_DATE, '14:00')),
    business_date: SAMPLE_BUSINESS_DATE,
    product_id: 'DEMO-P-0005',
    product_no: 'DEMO-0100',
    product_name: '灯箱片',
    report_id: 'DEMO-R-2005',
    reported_qty: 30,
    received_qty: 0,
    difference_qty: -30,
    state: 'pending',
    receiver: '',
    note: '等待接收方确认。',
  },
]

/* ------------------------------------------------------------------ *
 * 墨水
 * ------------------------------------------------------------------ */

export const sampleInkSkus: UvInkSku[] = [
  {
    ...entity('DEMO-SKU-01', SEED_CREATED),
    supplier: 'DEMO 供应商 A',
    material: 'hard',
    color: '白',
    color_aliases: ['白墨', 'White', 'W'],
    package_ml: '1000',
    location: 'UV 仓',
    threshold_ml: '800',
    unit_cost: '0.320000',
    currency: SAMPLE_CURRENCY,
    is_active: true,
  },
  {
    ...entity('DEMO-SKU-02', SEED_CREATED),
    supplier: 'DEMO 供应商 B',
    material: 'hard',
    color: '白',
    color_aliases: ['白墨', 'White'],
    package_ml: '1000',
    location: 'UV 仓',
    threshold_ml: '500',
    unit_cost: '0.295000',
    currency: SAMPLE_CURRENCY,
    is_active: true,
  },
  {
    ...entity('DEMO-SKU-03', SEED_CREATED),
    supplier: 'DEMO 供应商 A',
    material: 'soft',
    color: '白',
    color_aliases: ['白墨'],
    package_ml: '500',
    location: 'UV 仓',
    threshold_ml: '400',
    unit_cost: '0.410000',
    currency: SAMPLE_CURRENCY,
    is_active: true,
  },
  {
    ...entity('DEMO-SKU-04', SEED_CREATED),
    supplier: 'DEMO 供应商 A',
    material: 'hard',
    color: '青',
    color_aliases: ['青墨', 'Cyan', 'C'],
    package_ml: '1000',
    location: 'UV 仓',
    threshold_ml: '600',
    unit_cost: '0.380000',
    currency: SAMPLE_CURRENCY,
    is_active: true,
  },
  {
    ...entity('DEMO-SKU-05', SEED_CREATED),
    supplier: 'DEMO 供应商 B',
    material: 'hard',
    color: '品红',
    color_aliases: ['红墨', 'Magenta', 'M'],
    package_ml: '1000',
    location: 'UV 仓',
    threshold_ml: '600',
    unit_cost: null,
    currency: null,
    is_active: true,
  },
  {
    ...entity('DEMO-SKU-06', SEED_CREATED),
    supplier: 'DEMO 供应商 C',
    material: 'hard',
    color: '黄',
    color_aliases: ['黄墨', 'Yellow', 'Y'],
    package_ml: '1000',
    location: 'UV 仓',
    threshold_ml: '400',
    unit_cost: '0.210000',
    currency: SAMPLE_CURRENCY,
    is_active: true,
  },
]

type InkMovementSeed = Pick<
  UvInkMovement,
  'id' | 'sku_id' | 'sku_label' | 'kind' | 'occurred_on' | 'quantity_ml' | 'signed_ml' | 'balance_after_ml'
> &
  Partial<Omit<UvInkMovement, keyof UvEntity | 'factory_id'>>

function inkMovement(id: string, input: InkMovementSeed): UvInkMovement {
  return {
    ...entity(id, at(input.occurred_on, '08:00')),
    amount: null,
    cost_pending: false,
    bottle_input: null,
    unit_cost: null,
    machine_id: null,
    purpose: '',
    source_doc: '',
    evidence: '',
    created_by_name: 'DEMO 仓管',
    posted_on: input.occurred_on,
    reverses_movement_id: null,
    reversed_by_id: null,
    ...input,
  }
}

export const sampleInkMovements: UvInkMovement[] = [
  inkMovement('DEMO-IM-5001', {
    id: 'DEMO-IM-5001',
    sku_id: 'DEMO-SKU-01',
    sku_label: 'DEMO 供应商 A · 硬墨 · 白',
    kind: 'opening',
    occurred_on: '2026-09-01',
    quantity_ml: '2000',
    signed_ml: '2000',
    balance_after_ml: '2000',
    unit_cost: '0.320000',
    amount: { currency: SAMPLE_CURRENCY, amount: '640.00' },
    purpose: '期初库存，不计入本期采购',
    evidence: 'DEMO 期初盘点表',
  }),
  inkMovement('DEMO-IM-5002', {
    id: 'DEMO-IM-5002',
    sku_id: 'DEMO-SKU-02',
    sku_label: 'DEMO 供应商 B · 硬墨 · 白',
    kind: 'opening',
    occurred_on: '2026-09-01',
    quantity_ml: '1000',
    signed_ml: '1000',
    balance_after_ml: '1000',
    unit_cost: '0.295000',
    amount: { currency: SAMPLE_CURRENCY, amount: '295.00' },
    purpose: '期初库存',
    evidence: 'DEMO 期初盘点表',
  }),
  inkMovement('DEMO-IM-5003', {
    id: 'DEMO-IM-5003',
    sku_id: 'DEMO-SKU-03',
    sku_label: 'DEMO 供应商 A · 软墨 · 白（500ml 包装）',
    kind: 'opening',
    occurred_on: '2026-09-01',
    quantity_ml: '1000',
    signed_ml: '1000',
    balance_after_ml: '1000',
    bottle_input: '2',
    unit_cost: '0.410000',
    amount: { currency: SAMPLE_CURRENCY, amount: '410.00' },
    purpose: '期初库存，2 瓶 × 500ml',
    evidence: 'DEMO 期初盘点表',
  }),
  inkMovement('DEMO-IM-5004', {
    id: 'DEMO-IM-5004',
    sku_id: 'DEMO-SKU-04',
    sku_label: 'DEMO 供应商 A · 硬墨 · 青',
    kind: 'opening',
    occurred_on: '2026-09-01',
    quantity_ml: '1500',
    signed_ml: '1500',
    balance_after_ml: '1500',
    unit_cost: '0.380000',
    amount: { currency: SAMPLE_CURRENCY, amount: '570.00' },
    purpose: '期初库存',
    evidence: 'DEMO 期初盘点表',
  }),
  inkMovement('DEMO-IM-5005', {
    id: 'DEMO-IM-5005',
    sku_id: 'DEMO-SKU-05',
    sku_label: 'DEMO 供应商 B · 硬墨 · 品红',
    kind: 'opening',
    occurred_on: '2026-09-01',
    quantity_ml: '900',
    signed_ml: '900',
    balance_after_ml: '900',
    cost_pending: true,
    purpose: '期初库存，缺单价：数量可用但成本待核',
    evidence: 'DEMO 期初盘点表',
  }),
  inkMovement('DEMO-IM-5006', {
    id: 'DEMO-IM-5006',
    sku_id: 'DEMO-SKU-06',
    sku_label: 'DEMO 供应商 C · 硬墨 · 黄',
    kind: 'opening',
    occurred_on: '2026-09-01',
    quantity_ml: '300',
    signed_ml: '300',
    balance_after_ml: '300',
    unit_cost: '0.210000',
    amount: { currency: SAMPLE_CURRENCY, amount: '63.00' },
    purpose: '期初库存，低于阈值',
    evidence: 'DEMO 期初盘点表',
  }),
  inkMovement('DEMO-IM-5007', {
    id: 'DEMO-IM-5007',
    sku_id: 'DEMO-SKU-01',
    sku_label: 'DEMO 供应商 A · 硬墨 · 白',
    kind: 'purchase_in',
    occurred_on: '2026-09-10',
    quantity_ml: '1000',
    signed_ml: '1000',
    balance_after_ml: '3000',
    bottle_input: '1',
    unit_cost: '0.320000',
    amount: { currency: SAMPLE_CURRENCY, amount: '320.00' },
    source_doc: 'DEMO-PO-9001',
    evidence: 'DEMO 送货单',
    purpose: '采购入库',
  }),
  inkMovement('DEMO-IM-5008', {
    id: 'DEMO-IM-5008',
    sku_id: 'DEMO-SKU-01',
    sku_label: 'DEMO 供应商 A · 硬墨 · 白',
    kind: 'issue_out',
    occurred_on: '2026-09-13',
    quantity_ml: '2200',
    signed_ml: '-2200',
    balance_after_ml: '800',
    bottle_input: '2.2',
    unit_cost: '0.320000',
    amount: { currency: SAMPLE_CURRENCY, amount: '704.00' },
    machine_id: 'DEMO-M01',
    purpose: '生产领用',
    source_doc: 'DEMO-ISS-7001',
    created_by_name: 'DEMO 仓管甲',
  }),
  inkMovement('DEMO-IM-5009', {
    id: 'DEMO-IM-5009',
    sku_id: 'DEMO-SKU-02',
    sku_label: 'DEMO 供应商 B · 硬墨 · 白',
    kind: 'issue_out',
    occurred_on: '2026-09-13',
    quantity_ml: '600',
    signed_ml: '-600',
    balance_after_ml: '400',
    bottle_input: '0.6',
    unit_cost: '0.295000',
    amount: { currency: SAMPLE_CURRENCY, amount: '177.00' },
    machine_id: 'DEMO-M02',
    purpose: '生产领用',
    source_doc: 'DEMO-ISS-7002',
    created_by_name: 'DEMO 仓管乙',
  }),
  inkMovement('DEMO-IM-5010', {
    id: 'DEMO-IM-5010',
    sku_id: 'DEMO-SKU-04',
    sku_label: 'DEMO 供应商 A · 硬墨 · 青',
    kind: 'issue_out',
    occurred_on: '2026-09-13',
    quantity_ml: '700',
    signed_ml: '-700',
    balance_after_ml: '800',
    bottle_input: '0.7',
    unit_cost: '0.380000',
    amount: { currency: SAMPLE_CURRENCY, amount: '266.00' },
    machine_id: 'DEMO-M01',
    purpose: '生产领用',
    source_doc: 'DEMO-ISS-7003',
    created_by_name: 'DEMO 仓管甲',
  }),
  inkMovement('DEMO-IM-5011', {
    id: 'DEMO-IM-5011',
    sku_id: 'DEMO-SKU-03',
    sku_label: 'DEMO 供应商 A · 软墨 · 白（500ml 包装）',
    kind: 'issue_out',
    occurred_on: '2026-09-12',
    quantity_ml: '1000',
    signed_ml: '-1000',
    balance_after_ml: '0',
    bottle_input: '2',
    unit_cost: '0.410000',
    amount: { currency: SAMPLE_CURRENCY, amount: '410.00' },
    machine_id: 'DEMO-M03',
    purpose: '生产领用，2 瓶 × 500ml = 1000ml',
    source_doc: 'DEMO-ISS-7004',
    created_by_name: 'DEMO 仓管甲',
  }),
  inkMovement('DEMO-IM-5012', {
    id: 'DEMO-IM-5012',
    sku_id: 'DEMO-SKU-05',
    sku_label: 'DEMO 供应商 B · 硬墨 · 品红',
    kind: 'issue_out',
    occurred_on: '2026-09-13',
    quantity_ml: '300',
    signed_ml: '-300',
    balance_after_ml: '600',
    bottle_input: '0.3',
    cost_pending: true,
    machine_id: 'DEMO-M03',
    purpose: '生产领用，缺单价：数量已扣，成本待核',
    source_doc: 'DEMO-ISS-7005',
  }),
  inkMovement('DEMO-IM-5013', {
    id: 'DEMO-IM-5013',
    sku_id: 'DEMO-SKU-06',
    sku_label: 'DEMO 供应商 C · 硬墨 · 黄',
    kind: 'stocktake',
    occurred_on: '2026-09-12',
    quantity_ml: '120',
    signed_ml: '120',
    balance_after_ml: '420',
    unit_cost: '0.210000',
    amount: { currency: SAMPLE_CURRENCY, amount: '25.20' },
    purpose: '盘盈：现场实测比账面多 120ml',
    evidence: 'DEMO 盘点单 09-12',
  }),
  inkMovement('DEMO-IM-5014', {
    id: 'DEMO-IM-5014',
    sku_id: 'DEMO-SKU-02',
    sku_label: 'DEMO 供应商 B · 硬墨 · 白',
    kind: 'reversal',
    occurred_on: '2026-09-13',
    quantity_ml: '100',
    signed_ml: '100',
    balance_after_ml: '500',
    unit_cost: '0.295000',
    amount: { currency: SAMPLE_CURRENCY, amount: '29.50' },
    purpose: '冲销：领用登记错误，原流水保留',
    reverses_movement_id: 'DEMO-IM-5009',
    source_doc: 'DEMO-ISS-7002',
  }),
]

/* ------------------------------------------------------------------ *
 * 班次模板、排班
 * ------------------------------------------------------------------ */

export const sampleShiftTemplates: UvShiftTemplate[] = [
  {
    ...entity('DEMO-ST-DAY', SEED_CREATED),
    label: '白班 07:40–21:00',
    shift: 'day',
    start_local: '07:40',
    end_local: '21:00',
    effective_from: '2026-08-01',
    effective_to: null,
    break_minutes: 60,
    note: '班次跨度不是净工作时间；休息与停工需要明确记录。',
  },
  {
    ...entity('DEMO-ST-NIGHT', SEED_CREATED),
    label: '夜班 21:00–次日 07:40',
    shift: 'night',
    start_local: '21:00',
    end_local: '07:40',
    effective_from: '2026-08-01',
    effective_to: null,
    break_minutes: 60,
    note: '夜班跨自然日与跨月时，业务日期仍是班次开始日。',
  },
]

export const sampleAssignments: UvAssignment[] = [
  {
    ...entity('DEMO-AS-6001', at(SAMPLE_BUSINESS_DATE, '07:30')),
    business_date: SAMPLE_BUSINESS_DATE,
    shift: 'day',
    machine_id: 'DEMO-M01',
    worker_id: 'DEMO-W-001',
    share: 1,
    work_batch: 'DEMO-B-0913-M01-D',
    note: '',
  },
  {
    ...entity('DEMO-AS-6002', at(SAMPLE_BUSINESS_DATE, '07:30')),
    business_date: SAMPLE_BUSINESS_DATE,
    shift: 'day',
    machine_id: 'DEMO-M01',
    worker_id: 'DEMO-W-002',
    share: 1,
    work_batch: 'DEMO-B-0913-M01-D',
    note: '',
  },
  {
    ...entity('DEMO-AS-6003', at(SAMPLE_BUSINESS_DATE, '07:30')),
    business_date: SAMPLE_BUSINESS_DATE,
    shift: 'day',
    machine_id: 'DEMO-M01',
    worker_id: 'DEMO-W-003',
    share: 1,
    work_batch: 'DEMO-B-0913-M01-D',
    note: '同时兼顾 M02，按份额核对。',
  },
  {
    ...entity('DEMO-AS-6004', at(SAMPLE_BUSINESS_DATE, '07:30')),
    business_date: SAMPLE_BUSINESS_DATE,
    shift: 'day',
    machine_id: 'DEMO-M02',
    worker_id: 'DEMO-W-003',
    share: 0.5,
    work_batch: 'DEMO-B-0913-M02-D',
    note: '跨机兼岗，份额 0.5。',
  },
  {
    ...entity('DEMO-AS-6005', at(SAMPLE_BUSINESS_DATE, '07:30')),
    business_date: SAMPLE_BUSINESS_DATE,
    shift: 'day',
    machine_id: 'DEMO-M02',
    worker_id: 'DEMO-W-004',
    share: 1,
    work_batch: 'DEMO-B-0913-M02-D',
    note: '',
  },
  {
    ...entity('DEMO-AS-6006', at('2026-09-12', '20:40')),
    business_date: '2026-09-12',
    shift: 'night',
    machine_id: 'DEMO-M02',
    worker_id: 'DEMO-W-005',
    share: 1,
    work_batch: 'DEMO-B-0912-M02-N',
    note: '',
  },
  {
    ...entity('DEMO-AS-6007', at('2026-09-12', '20:40')),
    business_date: '2026-09-12',
    shift: 'night',
    machine_id: 'DEMO-M02',
    worker_id: 'DEMO-W-007',
    share: 1,
    work_batch: 'DEMO-B-0912-M02-N',
    note: '离职员工的历史排班快照。',
  },
  {
    ...entity('DEMO-AS-6008', at(SAMPLE_BUSINESS_DATE, '07:30')),
    business_date: SAMPLE_BUSINESS_DATE,
    shift: 'day',
    machine_id: 'DEMO-M01',
    worker_id: 'DEMO-W-006',
    share: 1,
    work_batch: 'DEMO-B-0913-M01-D',
    note: '',
  },
]

/* ------------------------------------------------------------------ *
 * 费用与月参数
 * ------------------------------------------------------------------ */

function expense(
  id: string,
  category: UvExpense['category'],
  occurredOn: BusinessDate,
  amount: string,
  input: Partial<UvExpense> = {},
): UvExpense {
  return {
    ...entity(id, at(occurredOn, '09:00')),
    category,
    occurred_on: occurredOn,
    period: occurredOn.slice(0, 7),
    amount: { currency: SAMPLE_CURRENCY, amount },
    machine_id: null,
    evidence: 'DEMO 凭证',
    source: 'manual',
    note: '',
    reverses_expense_id: null,
    ...input,
  }
}

export const sampleExpenses: UvExpense[] = [
  expense('DEMO-EX-8001', 'equipment', '2026-09-02', '120000.00', {
    note: '设备投资整笔扣减是旧管理口径，UI 不得标成经营毛利。',
  }),
  expense('DEMO-EX-8002', 'tooling', '2026-09-03', '1800.00'),
  expense('DEMO-EX-8003', 'material', '2026-09-05', '2400.00'),
  expense('DEMO-EX-8004', 'sundry', '2026-09-06', '360.00'),
  expense('DEMO-EX-8005', 'maintenance', '2026-09-08', '920.00', { machine_id: 'DEMO-M04' }),
  expense('DEMO-EX-8006', 'processing', '2026-09-09', '1500.00'),
  expense('DEMO-EX-8007', 'night_subsidy', '2026-09-12', '180.00'),
  expense('DEMO-EX-8008', 'recoverable_wage', '2026-09-12', '260.00', {
    note: '经营调整项，不等同员工实际扣薪。',
  }),
  expense('DEMO-EX-8009', 'recoverable_paint', '2026-09-13', '140.00'),
  expense('DEMO-EX-8010', 'rent', '2026-09-01', '3900.00', {
    note: '月租按选择的工作日集合分摊，分摊合计必须等于配置额。',
  }),
  expense('DEMO-EX-8011', 'utilities', '2026-09-01', '1560.00'),
  expense('DEMO-EX-8012', 'management_wage', '2026-09-01', '4200.00'),
  expense('DEMO-EX-8013', 'rent', '2026-09-01', '100.00', {
    note: '演示分摊舍入：100.00 分到 3 个日期，合计仍为 100.00。',
  }),
]

export const sampleMonthlyPolicy: UvMonthlyPolicy = {
  ...entity('DEMO-MP-9001', at('2026-09-01', '08:00'), 3),
  month: SAMPLE_MONTH,
  working_days: [
    '2026-09-01',
    '2026-09-02',
    '2026-09-03',
    '2026-09-04',
    '2026-09-05',
    '2026-09-07',
    '2026-09-08',
    '2026-09-09',
    '2026-09-10',
    '2026-09-11',
    '2026-09-12',
    '2026-09-13',
    '2026-09-14',
  ],
  allocation_method: 'working_days',
  rent: { currency: SAMPLE_CURRENCY, amount: '3900.00' },
  utilities: { currency: SAMPLE_CURRENCY, amount: '1560.00' },
  management_wage: { currency: SAMPLE_CURRENCY, amount: '4200.00' },
  note: '工作日集合由用户明确选择，不采用 26/26/21 默认值作为制度。',
}

/* ------------------------------------------------------------------ *
 * 定价测算样例
 * ------------------------------------------------------------------ */

export const samplePricingQuotes: UvPricingQuote[] = [
  {
    ...entity('DEMO-PQ-9101', at('2026-09-10', '10:00')),
    label: 'DEMO 面板外壳 A 成本加成测算',
    input: defaultPricingInput(SAMPLE_CURRENCY),
    result: computePricing(defaultPricingInput(SAMPLE_CURRENCY)),
    product_id: 'DEMO-P-0001',
    adopted_rate_version_id: null,
    created_by_name: 'DEMO 成本员',
    note: '10 小时 / 每板 0.5 小时 / 每板 20 件 / 人工 200 / 油墨 80。',
  },
]

/* ------------------------------------------------------------------ *
 * 报工草稿构造与跨天样例
 * ------------------------------------------------------------------ */

export const SAMPLE_DATES: BusinessDate[] = [
  '2026-09-01',
  '2026-09-02',
  '2026-09-03',
  '2026-09-04',
  '2026-09-05',
  '2026-09-06',
  '2026-09-07',
  '2026-09-08',
  '2026-09-09',
  '2026-09-10',
  '2026-09-11',
  '2026-09-12',
  '2026-09-13',
]

export const SAMPLE_MONTHS: string[] = ['2026-07', '2026-08', '2026-09']

export function sampleDraftTemplate(): CreateUvReport {
  return {
    factory_id: SAMPLE_FACTORY_ID,
    operation_id: '',
    expected_version: 0,
    business_date: SAMPLE_BUSINESS_DATE,
    shift: 'day',
    shift_template_version_id: DEFAULT_SHIFT_TEMPLATES.day.versionId,
    machine_id: 'DEMO-M01',
    product_id: 'DEMO-P-0001',
    process_version_id: 'DEMO-PV-0001',
    ...emptyQuality(0),
    worker_ids: ['DEMO-W-001'],
    notes: '',
    source_allocations: [],
    evidence_job_ids: [],
  }
}

/** 报表使用的稳定错开日期，用于构造按日聚合。 */
export function sampleOffsetDate(offset: number): BusinessDate {
  const base = SAMPLE_BUSINESS_DATE
  const [year, month, day] = base.split('-').map(Number)
  const date = new Date(Date.UTC(year, (month ?? 1) - 1, day ?? 1))
  date.setUTCDate(date.getUTCDate() + offset)
  const month2 = String(date.getUTCMonth() + 1).padStart(2, '0')
  const day2 = String(date.getUTCDate()).padStart(2, '0')
  return `${date.getUTCFullYear()}-${month2}-${day2}`
}
