<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { Calculator, Download, RefreshCw, ShieldCheck } from '@lucide/vue'
import { createRandomUuid } from '@/lib/randomUuid'
import { entities, num, object, str, today, UV_BASE, type Entity } from '../contracts'
import { useUvPage } from '../usePage'
import UvTable from '../components/UvTable.vue'
import UvActionDialog from '../components/UvActionDialog.vue'
import CollectionFooter from '../components/CollectionFooter.vue'
const p=useUvPage(()=>[...(p.w.can('cost_read')?['pricing-policies','expenses','run-costs','reference-efficiency']:[]),...(p.w.can('payroll_read')?['wages','wage-policies','wage-allocations']:[]),...(p.w.can('cost_read')&&p.w.can('payroll_read')?['periods','report-snapshots',...(p.w.can('audit_read')?['late-events']:[])]:[])]),w=p.w
const machineTime=ref<Entity|null>(null)
const start=ref(today().slice(0,7)+'-01'),end=ref(today()),report=ref<Entity|null>(null),loading=ref(false),error=ref(''),tab=ref('report'),quoteOpen=ref(false),quoteResult=ref<Entity|null>(null)
const quote=reactive({available_seconds:'32400',cycle_seconds:'100',pieces_per_board:12,cost_amount:'1000',pricing_mode:'markup',ratio:'0.2',currency:'CNY'})
const totals=computed(()=>object(report.value?.totals)),coverage=computed(()=>object(report.value?.coverage)),money=computed(()=>Object.entries(object(report.value?.cost_by_currency)).map(([currency,value])=>({...object(value),id:currency,version:0,currency})))
const amountText=(value:unknown)=>value==null?'待补':String(value).replace(/(\.\d*?[1-9])0+$|\.0+$/,'$1')
const missingLabels:Record<string,string>={missing_price:'缺少价格快照',missing_payroll:'本班工资未核准',missing_cost_evidence:'缺少成本凭证'}
async function refresh(){loading.value=true;error.value='';try{report.value=(await w.request<Entity>('reports',{}, {start_date:start.value,end_date:end.value})).data;machineTime.value=(await w.request<Entity>('machine-time',{}, {start_date:start.value,end_date:end.value})).data}catch(cause){error.value=w.explain(cause)}finally{loading.value=false}}
async function calculate(){error.value='';try{quoteResult.value=(await w.request<Entity>('quotes/calculate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({factory_id:'huakang-a',operation_id:createRandomUuid(),...quote})})).data}catch(cause){error.value=w.explain(cause)}}
watch(w.contextVersion,()=>{report.value=null;machineTime.value=null;quoteResult.value=null})
onMounted(refresh)
</script>
<template><div class="uv-page-heading"><div><span class="uv-eyebrow">OPERATING REVIEW</span><h2>效益与核算</h2><p>先核对数据覆盖，再看良率、产值与经营结果。</p></div><div class="uv-heading-actions"><button v-if="w.can('cost_read')" class="uv-button" @click="quoteOpen=!quoteOpen"><Calculator :size="16"/>报价测算</button><RouterLink class="uv-button" :to="{path:UV_BASE+'/imports',query:{factory:'huakang-a'}}"><Download :size="16"/>导出报表</RouterLink></div></div><form class="uv-filterbar" @submit.prevent="refresh"><label>开始<input v-model="start" type="date" required/></label><label>结束<input v-model="end" type="date" required/></label><button class="uv-button" :disabled="loading"><RefreshCw :size="16"/>{{loading?'计算中…':'核对区间'}}</button></form><p v-if="error||p.error.value" class="uv-error" role="alert">{{error||p.error.value}}</p>
<div v-if="report" class="uv-coverage" :data-complete="coverage.state==='complete'"><ShieldCheck :size="24"/><div><strong>{{coverage.state==='complete'?'区间资料完整':'资料待补齐 · 暂不能作为完整经营结论'}}</strong><p>未匹配运行 {{coverage.unmatched_runs??'—'}} · 待检 {{coverage.unconfirmed_output??'—'}} pcs <template v-if="w.can('cost_read')">· 核算缺项 {{coverage.missing_cost_records??'—'}}</template></p></div><span class="uv-badge">{{report.start_date}} — {{report.end_date}}</span></div>
<div v-if="report" class="uv-summary-strip"><div><small>加工次数（含返工）</small><strong>{{totals.processed}} <small>pcs</small></strong></div><div><small>最终良品</small><strong>{{totals.good}} <small>pcs</small></strong></div><div><small>最终报废</small><strong>{{totals.scrap}} <small>pcs</small></strong></div><div><small>已判定良率</small><strong>{{report.yield_ratio===null?'—':(Number(report.yield_ratio)*100).toFixed(2)+'%'}}</strong><small>良品 ÷（良品 + 报废）</small></div></div>
<section v-if="quoteOpen&&w.can('cost_read')" class="uv-section uv-page-section"><div class="uv-section-heading"><h3>报价测算</h3><span class="uv-muted">测算不写入价格政策</span></div><form class="uv-panel-body uv-form-grid" @submit.prevent="calculate"><label>可用时间（秒）<input v-model="quote.available_seconds" inputmode="decimal" required/></label><label>单板节拍（秒）<input v-model="quote.cycle_seconds" inputmode="decimal" required/></label><label>每板件数<input v-model.number="quote.pieces_per_board" type="number" min="1" required/></label><label>区间成本<input v-model="quote.cost_amount" inputmode="decimal" required/></label><label>计算口径<select v-model="quote.pricing_mode"><option value="markup">成本加成率</option><option value="margin">目标毛利率</option></select></label><label>比例（0.2 表示 20%）<input v-model="quote.ratio" inputmode="decimal" required/></label><label>币种<select v-model="quote.currency"><option>CNY</option><option>HKD</option><option>USD</option></select></label><button class="uv-button primary">计算报价</button><div v-if="quoteResult" class="uv-form-wide uv-notice"><p>理论产能 {{str(quoteResult,'theoretical_quantity')}} pcs · 整板可达 {{str(quoteResult,'quantity')}} pcs</p><p>理论单位成本 {{str(quoteResult,'cost_unit')}} · 整板单位成本 {{str(quoteResult,'achievable_cost_unit')}}</p><strong>建议单位报价 {{str(quoteResult,'quoted_unit_rate')}} {{quoteResult.currency}}</strong></div></form></section>
<div class="uv-tabs uv-page-section" role="tablist" aria-label="核算视图"><button v-for="[key,title] in [['report','区间报表'],...(w.can('cost_read')?[['prices','价格与费用']]:[]),...(w.can('payroll_read')?[['payroll','工资核准']]:[]),...(w.can('cost_read')&&w.can('payroll_read')?[['periods','账期封存']]:[])]" :key="key" role="tab" :aria-selected="tab===key" @click="tab=key!">{{title}}</button></div>
<section v-if="tab==='report'" class="uv-section uv-page-section"><div class="uv-section-heading"><h3>任务区间明细</h3><span class="uv-muted">待检 / 返工为期末结余</span></div><UvTable :rows="entities(report?.details).map(row=>({...row,id:String(row.task_id),cost_revenue:amountText(row.cost_revenue)}))" :columns="[{key:'task_code',label:'任务'},{key:'processed',label:'加工 pcs'},{key:'good',label:'良品 pcs'},{key:'scrap',label:'报废 pcs'},{key:'pending',label:'待检 pcs'},{key:'rework',label:'返工 pcs'},...(w.can('cost_read')?[{key:'cost_revenue',label:'确认产值'},{key:'currency',label:'币种'}]:[])]" selectable @select="w.selectedTaskId.value=$event.id"/><template v-if="w.can('cost_read')"><div class="uv-section-heading"><h3>按币种核算</h3><span class="uv-muted">缺项期间的结果仅供核对</span></div><UvTable :rows="money" :columns="[{key:'currency',label:'币种'},{key:'cost_revenue',label:'产值'},{key:'cost_amount',label:'材料与费用'},...(w.can('payroll_read')?[{key:'payroll_total',label:'人工工资'},{key:'cost_total',label:'总成本'},{key:'cost_margin',label:'毛利率（比例）'}]:[])]"/><div v-if="entities(report?.cost_missing).length" class="uv-panel-body"><h3>待补核算依据</h3><div v-for="(item,index) in entities(report?.cost_missing)" :key="index" class="uv-list-row"><span>{{missingLabels[String(item.code)]??item.code}}</span><button class="uv-link" @click="w.selectedTaskId.value=String(item.task_id)">核对任务 {{String(item.task_id).slice(0,8)}}</button></div></div></template><p v-for="warning in (report?.warnings as string[]??[])" :key="warning" class="uv-notice">{{warning}}</p></section>
<section v-else-if="tab==='prices'" class="uv-section uv-page-section"><div class="uv-section-heading"><h3>价格政策版本</h3><button class="uv-button" :disabled="!w.can('cost_write')" @click="p.open('price')">新增价格版本</button></div><UvTable :rows="w.items('pricing-policies')" :columns="[{key:'product_id',label:'产品 ID'},{key:'basis',label:'计价口径'},{key:'rate',label:'单价'},{key:'currency',label:'币种'},{key:'evidence',label:'确认依据'}]"/><CollectionFooter name="pricing-policies"/><div class="uv-section-heading"><h3>费用凭证</h3><button class="uv-button" :disabled="!w.can('cost_write')" @click="p.open('expense')">登记费用</button></div><UvTable :rows="w.items('expenses')" :columns="[{key:'business_date',label:'起始日期'},{key:'allocation_end',label:'分摊结束'},{key:'category',label:'性质'},{key:'cost_amount',label:'金额'},{key:'currency',label:'币种'},{key:'evidence',label:'依据'}]"><template #actions="{row}"><button v-if="w.can('cost_write')" class="uv-link" @click="p.open('reverseExpense',row)">撤销纠错</button></template></UvTable><CollectionFooter name="expenses"/><div class="uv-section-heading"><h3>拼版运行成本池</h3><button class="uv-button" :disabled="!w.can('cost_write')" @click="p.open('runCost')">登记运行成本</button></div><UvTable :rows="w.items('run-costs')" :columns="[{key:'run_id',label:'运行 ID'},{key:'cost_amount',label:'原始成本池'},{key:'currency',label:'币种'},{key:'business_date',label:'业务日期'}]"><template #actions="{row}"><button v-if="w.can('cost_write')" class="uv-link" @click="p.open('reverseRunCost',row)">撤销纠错</button></template></UvTable><CollectionFooter name="run-costs"/></section>
<section v-else-if="tab==='payroll'" class="uv-section uv-page-section"><div class="uv-section-heading"><h3>工资核准记录</h3><div class="uv-heading-actions"><button class="uv-button" :disabled="!w.can('payroll_write')" @click="p.open('wagePolicy')">新增规则</button><button class="uv-button primary" :disabled="!w.can('payroll_write')" @click="p.open('wage')">核准任务工资</button></div></div><UvTable :rows="w.items('wages')" :columns="[{key:'business_date',label:'业务日期'},{key:'task_id',label:'任务 ID'},{key:'payroll_amount',label:'核准金额'},{key:'currency',label:'币种'}]"><template #actions="{row}"><button v-if="w.can('payroll_write')" class="uv-link" @click="p.open('reverseWage',row)">撤销纠错</button></template></UvTable><CollectionFooter name="wages"/><div class="uv-section-heading"><h3>员工分配</h3><span class="uv-muted">分配后总额与工资凭证一致</span></div><UvTable :rows="w.items('wage-allocations')" :columns="[{key:'employee_id',label:'员工 ID'},{key:'payroll_amount',label:'分配金额'},{key:'payroll_weight_seconds',label:'计薪权重（秒）'}]"/><CollectionFooter name="wage-allocations"/></section>
<section v-else class="uv-section uv-page-section"><div class="uv-section-heading"><h3>月度账期</h3><span class="uv-muted">封账后保留不可变报表快照</span></div><UvTable :rows="w.items('periods')" :columns="[{key:'period',label:'账期'},{key:'status',label:'状态',state:true},{key:'close_reason',label:'封账说明'},{key:'version',label:'版本'}]"><template #actions="{row}"><button class="uv-link" :disabled="!w.can('close_period')" @click="p.open(row.status==='closed'?'reopenPeriod':'closePeriod',row)">{{row.status==='closed'?'重开账期':'封存账期'}}</button></template></UvTable><CollectionFooter name="periods"/><div class="uv-section-heading"><h3>已保存快照</h3></div><UvTable :rows="w.items('report-snapshots').map(x=>({...x,window:`${object(x.report).start_date} — ${object(x.report).end_date}`,good:object(object(x.report).totals).good}))" :columns="[{key:'window',label:'区间'},{key:'good',label:'冻结良品 pcs'},{key:'ledger_revision',label:'账本版本'},{key:'created_at',label:'封存时间'}]"/><CollectionFooter name="report-snapshots"/><template v-if="w.can('audit_read')"><div class="uv-section-heading"><h3>封账后迟到证据</h3></div><UvTable :rows="w.items('late-events')" :columns="[{key:'observed_at',label:'设备时间'},{key:'received_at',label:'到达时间'},{key:'kind',label:'证据类型'},{key:'resolved_by',label:'核对人'}]"><template #actions="{row}"><button v-if="!row.resolved_by&&w.can('close_period')" class="uv-link" @click="p.open('lateAcknowledge',row)">登记核对结论</button></template></UvTable><CollectionFooter name="late-events"/></template></section><section v-if="tab==='report'&&machineTime" class="uv-section"><div class="uv-section-heading"><h3>自然日机台时间</h3><span class="uv-muted">跨零点切段 · 重叠区间取并集 · 不计人工工资</span></div><UvTable :rows="entities(machineTime.by_day).map((row,i)=>({...row,id:String(i)}))" :columns="[{key:'machine_id',label:'机台 ID'},{key:'business_date',label:'自然日'},{key:'machine_seconds',label:'已确认运行秒数'}]"/><p v-if="(machineTime.incomplete_runs as unknown[])?.length" class="uv-notice">{{(machineTime.incomplete_runs as unknown[]).length}} 条运行缺少明确结束证据，未计入完整时长。</p></section><UvActionDialog :action="p.action.value" :target="p.target.value" :preset="p.preset.value" @close="p.action.value=null" @saved="p.reload();refresh()"/></template>
