<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { Download, FileSpreadsheet, Upload, RefreshCw } from '@lucide/vue'
import { useRoute, useRouter } from 'vue-router'
import { createRandomUuid } from '@/lib/randomUuid'
import { entities, str, today, type Entity } from '../contracts'
import { useUvWorkspace, UvError } from '../workspace'
import UvTable from '../components/UvTable.vue'
const route=useRoute(),router=useRouter(),mapping=ref(''),unitsConfirmed=ref(false),exportUncertain=ref(false)
const w=useUvWorkspace(),templates=ref<Record<string,{fields:string[];permissions:string[]}>>({}),template=ref(''),file=ref<File|null>(null),preview=ref<Entity|null>(null),error=ref(''),busy=ref(false),uncertain=ref(false),exporting=ref(false),jobs=ref<Entity[]>([])
const kind=ref('production'),start=ref(today().slice(0,7)+'-01'),end=ref(today()),selection=ref(''),scope=ref('filtered')
let importOperation=createRandomUuid(),exportOperation=createRandomUuid(),timer:ReturnType<typeof setTimeout>|undefined,exportBody:Record<string,unknown>|null=null
const templateNames:Record<string,string>={'products-v1':'产品基础资料 v1','processes-v1':'工艺版本 v1','demands-v1':'生产需求 v1','manual-production-v1':'人工核数 v1','expenses-v1':'费用凭证 v1','reference-efficiency-v1':'参考效率 v1'}
const errors=computed(()=>entities(preview.value?.errors).map((x,index)=>({...x,id:String(index)})))
const previewRows=computed(()=>entities(preview.value?.preview).map(x=>({...x,id:String(x.identity),summary:JSON.stringify(x.values)})))
async function initialize(){error.value='';try{if(w.can('import')){templates.value=(await w.request<typeof templates.value>('imports/templates')).data;template.value=Object.keys(templates.value)[0]??''}if(typeof route.query.import_job==='string')preview.value=(await w.request<Entity>('imports/'+route.query.import_job)).data;if(w.can('export'))await refreshJobs();else schedulePoll()}catch(cause){error.value=w.explain(cause)}}
function downloadTemplate(){const fields=templates.value[template.value]?.fields??[],url=URL.createObjectURL(new Blob(['\ufeff'+fields.join(',')+'\r\n'],{type:'text/csv;charset=utf-8'})),anchor=document.createElement('a');anchor.href=url;anchor.download=template.value+'.csv';anchor.click();URL.revokeObjectURL(url)}
async function upload(){if(!file.value)return;busy.value=true;error.value='';preview.value=null;try{const body=new FormData();body.set('factory_id','huakang-a');body.set('template',template.value);body.set('file',file.value);body.set('field_mapping',JSON.stringify(Object.fromEntries(mapping.value.split(/\r?\n/).filter(line=>line.trim()).map(line=>{const i=line.indexOf('=');if(i<1)throw new Error('映射每行使用 模板字段=原表头');return [line.slice(0,i).trim(),line.slice(i+1).trim()]}))));body.set('units_confirmed',String(unitsConfirmed.value));preview.value=(await w.request<Entity>('imports/preview',{method:'POST',body})).data;importOperation=createRandomUuid();uncertain.value=false;await router.replace({query:{...route.query,import_job:preview.value.id}});schedulePoll()}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
async function commit(){if(!preview.value)return;busy.value=true;error.value='';try{const result=await w.command<Entity>('imports/'+preview.value.id+'/commit',{expected_version:preview.value.version},importOperation);preview.value={...preview.value,...result};uncertain.value=false;w.notification.value=`已导入 ${result.imported} 行，跳过重复 ${result.duplicates} 行`}catch(cause){error.value=w.explain(cause);uncertain.value=!(cause instanceof UvError)||cause.status>=500;if(!uncertain.value)importOperation=createRandomUuid()}finally{busy.value=false}}
async function refreshJobs(){clearTimeout(timer);try{jobs.value=(await w.request<Entity[]>('exports')).data}catch(cause){error.value=w.explain(cause)}schedulePoll()}
async function createExport(){exporting.value=true;error.value='';try{if(!exportUncertain.value)exportBody={kind:kind.value,start_date:start.value,end_date:end.value,selected_ids:scope.value==='selected'?selection.value.split(/[,，\s]+/).filter(Boolean):[]};if(scope.value==='selected'&&!(exportBody!.selected_ids as string[]).length)throw new Error('请选择或填写至少一个记录 ID');await w.command('exports',exportBody!,exportOperation);exportUncertain.value=false;exportOperation=createRandomUuid();await refreshJobs()}catch(cause){error.value=w.explain(cause);exportUncertain.value=!(cause instanceof UvError)||cause.status>=500;if(!exportUncertain.value)exportOperation=createRandomUuid()}finally{exporting.value=false}}
async function retry(row:Entity){try{await w.command('exports/'+row.id+'/retry',{expected_version:row.version});await refreshJobs()}catch(cause){error.value=w.explain(cause)}}
function schedulePoll(){clearTimeout(timer);if(!document.hidden&&(jobs.value.some(x=>['queued','running'].includes(String(x.status)))||['queued','processing'].includes(String(preview.value?.status))))timer=setTimeout(poll,3000)}
async function poll(){try{if(preview.value&&['queued','processing'].includes(String(preview.value.status)))preview.value=(await w.request<Entity>('imports/'+preview.value.id)).data;if(w.can('export'))await refreshJobs()}catch(cause){error.value=w.explain(cause)}finally{schedulePoll()}}
async function revalidate(){if(!preview.value)return;busy.value=true;try{preview.value=await w.command<Entity>('imports/'+preview.value.id+'/revalidate',{expected_version:preview.value.version});importOperation=createRandomUuid();schedulePoll()}catch(cause){error.value=w.explain(cause)}finally{busy.value=false}}
function visibility(){if(document.hidden)clearTimeout(timer);else void poll()}
watch(kind,()=>{if(['daily','monthly'].includes(kind.value)){scope.value='filtered';selection.value=''}})
watch(w.contextVersion,()=>{clearTimeout(timer);preview.value=null;jobs.value=[];file.value=null})
onMounted(()=>{void initialize();document.addEventListener('visibilitychange',visibility)})
onBeforeUnmount(()=>{clearTimeout(timer);document.removeEventListener('visibilitychange',visibility)})
</script>
<template><div class="uv-page-heading"><div><span class="uv-eyebrow">IMPORT & EXPORT</span><h2>导入与导出</h2><p>导入先预览、后确认；导出从完整数据库范围生成。</p></div></div><p v-if="error" class="uv-error" role="alert">{{error}}</p>
<section v-if="w.can('import')" class="uv-section"><div class="uv-section-heading"><h3><Upload :size="18"/>业务导入</h3><span class="uv-badge">CSV / XLSX · 最大 16 MB</span></div><form class="uv-panel-body" @submit.prevent="upload"><div class="uv-form-grid"><label>模板版本<select v-model="template" :disabled="busy||uncertain" required @change="preview=null"><option v-for="(_,key) in templates" :key="key" :value="key">{{templateNames[key]??key}}</option></select></label><label>业务文件<input type="file" accept=".csv,.xlsx" :disabled="busy||uncertain" required @change="file=($event.target as HTMLInputElement).files?.[0]??null;preview=null"/></label></div><label class="uv-block-label">可选字段映射（每行 模板字段=原表头；标准模板留空）<textarea v-model="mapping" rows="3" :disabled="busy||uncertain" placeholder="code=产品编号&#10;name=产品名称"/></label><label class="uv-check-label"><input v-model="unitsConfirmed" type="checkbox" required :disabled="busy||uncertain"/>已确认模板单位：件 pcs、长度 mm、时间秒、金额明确币种；日期时间含时区。</label><div class="uv-heading-actions uv-page-section"><button class="uv-button" type="button" @click="downloadTemplate"><Download :size="15"/>下载表头模板</button><button class="uv-button primary" :disabled="busy||uncertain"><FileSpreadsheet :size="16"/>{{busy?'正在处理…':'生成预览'}}</button></div><p class="uv-muted uv-page-section">每批最多 10000 行。产品、工艺和核数使用稳定 ID；不得用显示名称代替关联编号。Excel 公式只读取缓存值。</p></form>
<div v-if="preview"><p v-if="['queued','processing'].includes(String(preview.status))" class="uv-notice" role="status">文件已保存，后台正在生成预览。可保留本页地址稍后恢复。</p><p v-if="preview.status==='adjustment_required'" class="uv-notice">文件包含封账期间记录，已保留为待调整草稿。经授权重开账期后重新校验，当前没有写入正式账本。</p><div class="uv-section-heading"><h3>{{preview.status==='committed'?'导入已完成':'导入预览'}}</h3><span>共 {{preview.row_count}} 行 · 有效 {{preview.valid_count}} · 错误 {{errors.length}}</span></div><p v-for="warning in (preview.warnings as string[]??[])" :key="warning" class="uv-notice">{{warning}}</p><UvTable v-if="errors.length" :rows="errors" :columns="[{key:'sheet',label:'工作表'},{key:'row',label:'行号'},{key:'message',label:'错误'},{key:'fields',label:'字段'}]"/><UvTable v-else :rows="previewRows" :columns="[{key:'sheet',label:'工作表'},{key:'row',label:'行号'},{key:'summary',label:'字段预览'}]"/><p v-if="preview.preview_truncated" class="uv-panel-body uv-muted">页面展示前 20 行；确认时会处理全部 {{preview.valid_count}} 行。</p><div v-if="['preview','adjustment_required','failed'].includes(String(preview.status))" class="uv-panel-body"><button class="uv-button" :disabled="busy||uncertain" @click="revalidate">按最新业务重新校验</button></div><UvTable v-if="preview.status==='committed'" :rows="entities(preview.results).map((row,i)=>({...row,id:String(i)}))" :columns="[{key:'sheet',label:'工作表'},{key:'row',label:'原始行'},{key:'status',label:'结果'},{key:'entity_id',label:'业务记录 ID'}]"/><div v-if="preview.status==='preview'" class="uv-panel-body"><button class="uv-button primary" :disabled="busy||errors.length>0||!preview.valid_count" @click="commit">{{busy?'提交中…':uncertain?'重试同一导入':'确认导入全部有效行'}}</button><p v-if="errors.length" class="uv-muted">存在错误时不允许提交，请修正后重新生成预览。</p><p v-if="uncertain" class="uv-notice">结果不确定，已锁定本次文件。重试不会重复入账。</p></div></div></section>
<section v-if="w.can('export')" class="uv-section"><div class="uv-section-heading"><h3><Download :size="18"/>导出完整记录</h3><span class="uv-muted">异步任务 · 离开页面后继续生成</span></div><form class="uv-panel-body" @submit.prevent="createExport"><fieldset class="uv-form-grid" :disabled="exporting||exportUncertain"><label>导出内容<select v-model="kind"><option v-for="[key,title] in [['tasks','任务'],['schedule','排程'],['production','生产核数'],['handovers','下工序交接'],['ink','墨水流水'],...(w.can('payroll_read')?[['wages','工资']]:[]),...(w.can('cost_read')&&w.can('payroll_read')?[['daily','日报'],['monthly','月报']]:[])]" :key="key" :value="key">{{title}}</option></select></label><label>范围<select v-model="scope"><option value="filtered">日期范围内全部记录</option><option v-if="!['daily','monthly'].includes(kind)" value="selected">明确选中的记录 ID</option></select></label><label>开始日期<input v-model="start" type="date" required/></label><label>结束日期<input v-model="end" type="date" required/></label><label v-if="scope==='selected'" class="uv-form-wide">记录 ID（逗号或换行分隔，最多 10000 条）<textarea v-model="selection" rows="3" required/></label></fieldset><div class="uv-heading-actions uv-page-section"><button class="uv-button primary" :disabled="exporting">{{exporting?'创建任务中…':exportUncertain?'重试同一导出任务':'创建导出任务'}}</button><span class="uv-muted">不受页面分页影响。金额为数值单元格，编号保留文本。</span></div></form><div class="uv-section-heading"><h3>我的导出任务（最近 100 条）</h3><button class="uv-button small" @click="refreshJobs"><RefreshCw :size="15"/>刷新任务</button></div><UvTable :rows="jobs" :columns="[{key:'kind',label:'内容'},{key:'status',label:'状态',state:true},{key:'row_count',label:'记录数'},{key:'created_at',label:'创建时间'},{key:'error',label:'失败原因'}]"><template #actions="{row}"><a v-if="row.status==='ready'" class="uv-link" :href="'/api/uv-operations/exports/'+row.id+'/download?factory_id=huakang-a'">下载 XLSX</a><button v-if="row.status==='failed'" class="uv-link" @click="retry(row)">重试生成</button></template></UvTable></section><p v-if="!w.can('import')&&!w.can('export')" class="uv-notice">当前账号没有导入或导出权限。</p></template>
