<script setup lang="ts">
import { computed, ref } from 'vue'
import { Droplets, Plus, RefreshCw, Wrench } from '@lucide/vue'
import { num, str } from '../contracts'
import { useUvPage } from '../usePage'
import UvActionDialog from '../components/UvActionDialog.vue'
import UvTable from '../components/UvTable.vue'
import CollectionFooter from '../components/CollectionFooter.vue'
const p=useUvPage(()=>['ink/skus','ink/balances','ink/movements','machines']),w=p.w,tab=ref('balances')
const skus=computed(()=>w.items('ink/skus')),skuName=(id:unknown)=>str(skus.value.find(x=>x.id===id),'code',String(id))
const balances=computed(()=>w.items('ink/balances').map(row=>({...row,sku:skuName(row.sku_id)})))
const movements=computed(()=>w.items('ink/movements').map(row=>{const balance=w.items('ink/balances').find(x=>x.id===row.balance_id);return {...row,sku:skuName(balance?.sku_id),location:balance?.location}}))
</script>
<template><div class="uv-page-heading"><div><span class="uv-eyebrow">MATERIALS & EQUIPMENT</span><h2>材料与设备</h2><p>按 SKU、批号和库位管理库存；耗用独立确认。</p></div><div class="uv-heading-actions"><button class="uv-button" @click="p.reload"><RefreshCw :size="16"/>刷新</button><button class="uv-button" :disabled="!w.can('inventory_write')" @click="p.open('inkSku')"><Plus :size="16"/>新增墨水 SKU</button><button class="uv-button primary" :disabled="!w.can('inventory_write')||!w.can('cost_write')||!w.can('cost_read')" @click="p.open('ink')"><Droplets :size="16"/>登记流水</button></div></div><p v-if="p.error.value" class="uv-error" role="alert">{{p.error.value}}</p>
<div class="uv-summary-strip"><div><small>墨水 SKU</small><strong>{{w.pagination['ink/skus']?.total??skus.length}}</strong></div><div><small>已加载库位余额</small><strong>{{balances.length}}</strong></div><div><small>当前可见库存（ml）</small><strong>{{balances.reduce((sum,row)=>sum+num(row,'quantity_ml'),0).toLocaleString('zh-CN',{maximumFractionDigits:3})}}</strong></div><div><small>维护中机台</small><strong>{{w.items('machines').filter(x=>x.maintenance).length}}</strong></div></div>
<div class="uv-tabs" role="tablist" aria-label="材料视图"><button v-for="[key,title] in [['balances','库存余额'],['movements','不可变流水'],['skus','墨水资料'],['machines','机台能力']]" :key="key" role="tab" :aria-selected="tab===key" @click="tab=key!">{{title}}</button></div><section class="uv-section uv-page-section">
<template v-if="tab==='balances'"><UvTable :rows="balances" :columns="[{key:'sku',label:'墨水 SKU'},{key:'lot',label:'批号'},{key:'location',label:'库位'},{key:'quantity_ml',label:'库存 ml'},...(w.can('cost_read')?[{key:'cost_value',label:'库存价值'},{key:'currency',label:'币种'}]:[])]"/><CollectionFooter name="ink/balances"/></template>
<template v-else-if="tab==='movements'"><UvTable :rows="movements" :columns="[{key:'business_date',label:'业务日期'},{key:'sku',label:'墨水 SKU'},{key:'location',label:'库位'},{key:'kind',label:'类型',state:true},{key:'quantity_ml',label:'数量 ml'},...(w.can('cost_read')?[{key:'cost_value',label:'原成本金额'},{key:'currency',label:'币种'}]:[]),{key:'evidence',label:'依据'}]"/><CollectionFooter name="ink/movements"/></template>
<template v-else-if="tab==='skus'"><UvTable :rows="skus" :columns="[{key:'code',label:'SKU 编号'},{key:'supplier',label:'供应商'},{key:'model',label:'型号'},{key:'ink_family',label:'墨材类别'},{key:'color',label:'颜色 / 通道'},{key:'capacity_ml',label:'包装 ml'}]"/><CollectionFooter name="ink/skus"/></template>
<template v-else><div class="uv-section-heading"><h3><Wrench :size="18"/>机台与维护</h3><button class="uv-button" :disabled="!w.can('master_write')" @click="p.open('machine')">新增机台</button></div><UvTable :rows="w.items('machines').map(x=>({...x,maintenance_label:x.maintenance?'维护中':'可用',size:x.width_mm&&x.height_mm?`${x.width_mm} × ${x.height_mm} mm`:'能力未知'}))" :columns="[{key:'code',label:'编号'},{key:'name',label:'机台'},{key:'size',label:'有效尺寸'},{key:'ink_family',label:'兼容墨材'},{key:'maintenance_label',label:'维护'}]"><template #actions="{row}"><button class="uv-link" :disabled="!w.can('master_write')" @click="p.open('machineEdit',row,row)">编辑能力与维护</button></template></UvTable><CollectionFooter name="machines"/></template></section><p class="uv-inline-note">移库、领料与设备遥测不会自动计入消耗成本。未知用墨量保持空值；冲销沿用原流水成本。</p><UvActionDialog :action="p.action.value" :target="p.target.value" :preset="p.preset.value" @close="p.action.value=null" @saved="p.reload"/></template>
