<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { onBeforeRouteLeave } from 'vue-router'
import { CalendarDays, Plus, RefreshCw, ShieldAlert, X, Check, Sparkles } from '@lucide/vue'
import { createRandomUuid } from '@/lib/randomUuid'
import { displayTime, entities, label, num, object, str, today, utcInput, type Entity } from '../contracts'
import { useUvPage } from '../usePage'
import { UvError } from '../workspace'
import UvTable from '../components/UvTable.vue'
import UvActionDialog from '../components/UvActionDialog.vue'
import CollectionFooter from '../components/CollectionFooter.vue'
const p=useUvPage(()=>['demands','tasks','machines','fixtures','batches','executions']),w=p.w
const tab=ref('timeline'),start=ref(today()),days=ref(1),mobileList=ref(false),scrollTop=ref(0)
const form=reactive({task_id:'',batch_id:'',machine_id:'',fixture_id:'',fixture_evidence:'',start_at:today()+'T08:00',end_at:today()+'T09:00',fixed:false,manual_minutes:'',estimate_reason:''})
const taskDetail=ref<Entity|null>(null),windowRows=ref<Entity[]>([]),suggestions=ref<Entity[]>([]),proposed=ref<Entity|null>(null)
const detailLoading=ref(false)
const error=ref(''),working=ref(false),uncertain=ref(false),windowLoading=ref(false),windowTotal=ref(0),chosenPlan=ref<Entity|null>(null)
const ghost=ref<{machine:string;start:number;duration:number}|null>(null)
let operationId='',body:Record<string,unknown>|null=null,windowVersion=0,detailVersion=0
const dragBlock=ref<Entity|null>(null)
const windowStart=computed(()=>new Date(start.value+'T00:00:00+08:00').valueOf()),windowEnd=computed(()=>windowStart.value+days.value*86400000)
const taskOptions=computed(()=>{const rows=[...w.items('tasks')];if(taskDetail.value&&!rows.some(x=>x.id===taskDetail.value!.id))rows.unshift(taskDetail.value);return rows.filter(x=>!['cancelled','completed'].includes(String(x.status)))})
const selectedTask=computed(()=>taskDetail.value?.id===form.task_id?taskDetail.value:taskOptions.value.find(x=>x.id===form.task_id))
const batches=computed(()=>entities(selectedTask.value?.batches)),selectedBatch=computed(()=>batches.value.find(x=>x.id===form.batch_id))
const process=computed(()=>object(selectedTask.value?.process_snapshot)),manual=computed(()=>selectedTask.value&&process.value.cycle_seconds==null)
const rowHeight=100,firstMachine=computed(()=>Math.max(0,Math.floor(scrollTop.value/rowHeight)-2)),visibleMachines=computed(()=>w.items('machines').slice(firstMachine.value,firstMachine.value+12))
const ticks=computed(()=>Array.from({length:days.value*12+1},(_,i)=>i*2))
const taskName=(row:Entity)=>str(row,'task_code',str(taskOptions.value.find(x=>x.id===row.task_id),'code',String(row.task_id)))
const batchName=(row:Entity)=>row.batch_id?String(row.batch_id).slice(0,8):'旧整任务计划'
const local=(value:unknown)=>new Date(new Date(String(value)).valueOf()+8*3600000).toISOString().slice(0,16)
function blockStyle(row:Entity){const a=Math.max(windowStart.value,new Date(String(row.start_at)).valueOf()),b=Math.min(windowEnd.value,new Date(String(row.end_at)).valueOf());return {left:((a-windowStart.value)/(windowEnd.value-windowStart.value)*100)+'%',width:((b-a)/(windowEnd.value-windowStart.value)*100)+'%'}}
function clearPreview(){if(!uncertain.value){proposed.value=null;body=null;suggestions.value=[]}}
async function loadWindow(){const version=++windowVersion;windowLoading.value=true;try{let cursor='',rows:Entity[]=[];do{const result=await w.request<Entity[]>('schedule/window',{}, {start_at:new Date(windowStart.value).toISOString(),end_at:new Date(windowEnd.value).toISOString(),cursor,limit:'500'});if(version!==windowVersion)return;rows.push(...result.data);windowTotal.value=result.pagination?.total??rows.length;cursor=result.pagination?.next_cursor??''}while(cursor);windowRows.value=rows}catch(cause){if(version===windowVersion)error.value=w.explain(cause)}finally{if(version===windowVersion)windowLoading.value=false}}
watch([start,days,w.contextVersion],()=>{windowRows.value=[];void loadWindow()},{immediate:true})
watch(w.contextVersion,()=>{detailVersion++;taskDetail.value=null;chosenPlan.value=null;proposed.value=null;body=null;form.task_id='';form.batch_id='';suggestions.value=[];uncertain.value=false})
async function selectTask(id=form.task_id){const version=++detailVersion;clearPreview();chosenPlan.value=null;taskDetail.value=null;form.batch_id='';detailLoading.value=true;try{if(!id)return;const task=(await w.request<Entity>('tasks/'+id)).data;if(version!==detailVersion)return false;taskDetail.value=task;form.fixture_id=String(object(task.process_snapshot).fixture_id??'');form.fixture_evidence='';form.manual_minutes='';form.estimate_reason='';const values=entities(task.batches);if(values.length===1)form.batch_id=values[0]!.id;return true}catch(cause){error.value=w.explain(cause);return false}finally{if(version===detailVersion)detailLoading.value=false}}
async function choose(row:Entity){if(working.value||uncertain.value)return;form.task_id=String(row.task_id);if(!await selectTask(form.task_id))return false;chosenPlan.value=row;form.batch_id=String(row.batch_id??(batches.value.length===1?batches.value[0]!.id:''));form.machine_id=String(row.machine_id);form.fixture_id=String(row.fixture_id??process.value.fixture_id??'');form.fixture_evidence=String(row.fixture_evidence??'');form.start_at=local(row.start_at);form.end_at=local(row.end_at);form.fixed=!!row.fixed;form.manual_minutes=row.estimate_basis==='manual'?String(Number(row.estimated_seconds)/60):'';form.estimate_reason=String(row.estimate_reason??'');return true}
function dragOver(event:DragEvent,machine:Entity){if(!dragBlock.value)return;const rect=(event.currentTarget as HTMLElement).getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width));ghost.value={machine:machine.id,start:Math.round((windowStart.value+ratio*days.value*86400000)/900000)*900000,duration:new Date(String(dragBlock.value.end_at)).valueOf()-new Date(String(dragBlock.value.start_at)).valueOf()}}
async function dropped(event:DragEvent,machine:Entity){if(working.value||uncertain.value||!dragBlock.value)return;dragOver(event,machine);const moved=dragBlock.value,target=ghost.value!;ghost.value=null;if(!await choose(moved))return;form.machine_id=machine.id;form.start_at=local(new Date(target.start).toISOString());form.end_at=local(new Date(target.start+target.duration).toISOString());await preview()}
function manualSeconds(){return manual.value&&form.manual_minutes?String(Math.round(Number(form.manual_minutes)*60)):null}
async function preview(){error.value='';working.value=true;proposed.value=null;try{const task=selectedTask.value,machine=w.items('machines').find(x=>x.id===form.machine_id),batch=selectedBatch.value,fixture=w.items('fixtures').find(x=>x.id===form.fixture_id);if(!task||!machine||!batch)throw new Error('请先选择任务、实体批次与机台');const old=entities(task.schedule).find(x=>x.batch_id===batch.id)??entities(task.schedule).find(x=>!x.batch_id&&x.status!=='cancelled');operationId=createRandomUuid();body={blocks:[{task_id:task.id,batch_id:batch.id,batch_version:batch.version,machine_id:machine.id,fixture_id:form.fixture_id||null,fixture_version:fixture?.version??null,fixture_evidence:form.fixture_evidence||null,start_at:utcInput(form.start_at),end_at:utcInput(form.end_at),fixed:form.fixed,manual_estimated_seconds:manualSeconds(),estimate_reason:form.estimate_reason||null,task_version:task.version,machine_version:machine.version,block_version:old?.version??0}]};proposed.value=(await w.request<Entity>('schedule/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({factory_id:'huakang-a',operation_id:operationId,expected_version:0,...body})})).data}catch(cause){error.value=w.explain(cause)}finally{working.value=false}}
async function recommend(){error.value='';working.value=true;try{if(!form.batch_id)throw new Error('请先选择实体批次');suggestions.value=(await w.request<Entity[]>('schedule/recommendations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({factory_id:'huakang-a',task_id:form.task_id,batch_id:form.batch_id,earliest_at:utcInput(form.start_at),manual_estimated_seconds:manualSeconds()})})).data;if(!suggestions.value.length)error.value='未知节拍请先填人工估时，再获取建议'}catch(cause){error.value=w.explain(cause)}finally{working.value=false}}
async function useSuggestion(row:Entity){form.machine_id=String(row.machine_id);form.fixture_id=String(process.value.fixture_id);form.fixture_evidence='';form.start_at=local(row.start_at);form.end_at=local(new Date(Math.ceil(new Date(String(row.end_at)).valueOf()/60000)*60000).toISOString());await preview()}
async function reload(){await p.reload();await loadWindow();if(form.task_id){const task=(await w.request<Entity>('tasks/'+form.task_id)).data;taskDetail.value=task;if(!entities(task.batches).some(x=>x.id===form.batch_id))form.batch_id=''}}
async function commit(){if(!body)return;working.value=true;error.value='';try{await w.command('schedule/commit',body,operationId);proposed.value=null;uncertain.value=false;body=null;await reload()}catch(cause){error.value=w.explain(cause);uncertain.value=!(cause instanceof UvError)||cause.status>=500;if(!uncertain.value){proposed.value=null;await reload()}}finally{working.value=false}}
onBeforeRouteLeave(()=>!proposed.value||window.confirm('排程预览尚未提交，确认离开并放弃草案？'))
</script>
<template>
<div class="uv-page-heading"><div><span class="uv-eyebrow">PLAN WITH CONFIDENCE</span><h2>任务与排程</h2><p>按实体批次分配机台，核对治具与时间，再确认计划。</p></div><div class="uv-heading-actions"><button class="uv-button" @click="reload"><RefreshCw :size="16"/>刷新</button><button class="uv-button" :disabled="!w.can('plan_write')" @click="p.open('demand')"><Plus :size="16"/>新建需求</button><button class="uv-button primary" :disabled="!w.can('plan_write')" @click="p.open('task')"><Plus :size="16"/>新建任务</button></div></div>
<p v-if="p.error.value||error" class="uv-error" role="alert">{{p.error.value||error}}</p>
<div class="uv-tabs" role="tablist" aria-label="计划视图"><button v-for="[key,title] in [['timeline','资源时间轴'],['tasks','任务清单'],['demands','生产需求']]" :key="key" role="tab" :aria-selected="tab===key" @click="tab=key!">{{title}}</button></div>
<section v-if="tab==='timeline'" class="uv-section uv-page-section">
<div class="uv-section-heading"><h3><CalendarDays :size="18"/>机台与治具资源</h3><div class="uv-filterbar"><label>起始日期<input v-model="start" type="date"/></label><label>视野<select v-model.number="days"><option :value="1">1 天</option><option :value="3">3 天</option><option :value="30">30 天</option></select></label><button class="uv-button small" @click="mobileList=!mobileList">{{mobileList?'时间轴':'列表视图'}}</button></div></div>
<p class="uv-section-description" aria-live="polite">{{windowLoading?'正在加载该时间窗口…':`本窗口 ${windowRows.length} / ${windowTotal} 条计划`}} · 拖动只生成预览；短计划以细条显示，可悬停查看或切换列表。</p>
<div v-if="!mobileList" class="uv-timeline-scroll" @scroll="scrollTop=($event.target as HTMLElement).scrollTop" tabindex="0" aria-label="资源时间轴，可横向滚动；也可使用下方表单排程"><div class="uv-timeline" :style="{minWidth:days*800+'px'}"><div class="uv-timeline-header"><span>机台 / 计划时间</span><div><span v-for="hour in ticks" :key="hour" :style="{left:hour/(24*days)*100+'%'}">{{hour===24*days?'':hour%24===0?`${Math.floor(hour/24)+1} 日 00:00`:`${String(hour%24).padStart(2,'0')}:00`}}</span></div></div>
<div :style="{height:firstMachine*rowHeight+'px'}" aria-hidden="true"/><div v-for="machine in visibleMachines" :key="machine.id" class="uv-timeline-row"><strong>{{str(machine,'code')}}<small>{{str(machine,'name')}}</small></strong><div class="uv-timeline-track" :data-machine="machine.id" @dragover.prevent="dragOver($event,machine)" @drop.prevent="dropped($event,machine)"><span v-for="hour in ticks" :key="hour" class="uv-timeline-gridline" :style="{left:hour/(24*days)*100+'%'}"/><button v-for="block in windowRows.filter(row=>row.machine_id===machine.id)" :key="block.id" class="uv-plan-block" :class="{fixed:block.fixed,actual:block.started,manual:block.estimate_basis==='manual',compact:(new Date(String(block.end_at)).valueOf()-new Date(String(block.start_at)).valueOf())/86400000*800<60}" :data-plan="block.id" :style="blockStyle(block)" :title="`${taskName(block)} · ${batchName(block)} · ${displayTime(block.start_at)} — ${displayTime(block.end_at)}`" :aria-label="`${taskName(block)} · ${batchName(block)} · ${displayTime(block.start_at)} — ${displayTime(block.end_at)}`" :draggable="!block.fixed&&!block.started&&w.can('plan_write')" @dragstart="dragBlock=block" @dragend="dragBlock=null;ghost=null" @click="choose(block)">{{taskName(block)}}<small>{{batchName(block)}} · {{block.estimate_basis==='manual'?'人工估时':block.fixed?'已固定':'标准节拍'}}</small></button><div v-if="ghost?.machine===machine.id" class="uv-plan-ghost" :style="blockStyle({id:'ghost',version:0,start_at:new Date(ghost.start).toISOString(),end_at:new Date(ghost.start+ghost.duration).toISOString()} as Entity)">放下后核验冲突</div></div></div><div :style="{height:Math.max(0,w.items('machines').length-firstMachine-visibleMachines.length)*rowHeight+'px'}" aria-hidden="true"/><p v-if="!w.items('machines').length" class="uv-empty-inline">请先配置机台。</p></div></div>
<UvTable v-else :rows="windowRows.map(x=>({...x,task:taskName(x),batch:batchName(x),start:displayTime(x.start_at),end:displayTime(x.end_at)}))" :columns="[{key:'task',label:'任务'},{key:'batch',label:'实体批次'},{key:'start',label:'开始'},{key:'end',label:'结束'}]"><template #actions="{row}"><button class="uv-link" @click="choose(row)">调整计划</button></template></UvTable>
<form class="uv-plan-form" @submit.prevent="preview"><fieldset :disabled="working||uncertain||detailLoading||!w.can('plan_write')">
<label>待排任务<select v-model="form.task_id" required @change="selectTask()"><option value="">选择任务</option><option v-for="task in taskOptions" :key="task.id" :value="task.id">{{str(task,'code')}} · {{label(task.status)}}</option></select></label>
<label>实体批次<select v-model="form.batch_id" required @change="clearPreview"><option value="">选择批次</option><option v-for="batch in batches" :key="batch.id" :value="batch.id">{{batch.id.slice(0,8)}} · {{batch.quantity}} 件 · 待加工 {{batch.remaining}}</option></select></label>
<label>机台<select v-model="form.machine_id" required @change="clearPreview"><option value="">选择机台</option><option v-for="machine in w.items('machines')" :key="machine.id" :value="machine.id">{{str(machine,'code')}}</option></select></label>
<label>实体治具<select v-model="form.fixture_id" required @change="clearPreview"><option v-for="fixture in w.items('fixtures')" :key="fixture.id" :value="fixture.id">{{str(fixture,'code')}} · V{{fixture.revision}}</option></select></label>
<label v-if="form.fixture_id&&form.fixture_id!==process.fixture_id">替代治具确认依据<input v-model="form.fixture_evidence" required minlength="5" @input="clearPreview"/></label>
<label>开始<input v-model="form.start_at" type="datetime-local" required @input="clearPreview"/></label><label>结束<input v-model="form.end_at" type="datetime-local" required @input="clearPreview"/></label>
<template v-if="manual"><label>人工估时（分钟）<input v-model="form.manual_minutes" type="number" min="1" step="1" required @input="clearPreview"/></label><label>估时依据<input v-model="form.estimate_reason" required minlength="5" placeholder="例如按首件试做与装卸用时估计" @input="clearPreview"/></label></template>
<label class="uv-check-label"><input v-model="form.fixed" type="checkbox" @change="clearPreview"/>固定计划</label><button class="uv-button" type="button" :disabled="!form.batch_id" @click="recommend"><Sparkles :size="15"/>推荐可用窗口</button><button class="uv-button primary" type="submit">预览排程</button>
</fieldset></form>
<div class="uv-plan-tools"><span v-if="manual" class="uv-notice">工艺节拍未知：人工估时仅用于本次计划，不改写工艺、不代表设备实际进度。</span><button v-if="selectedBatch&&w.can('plan_write')" class="uv-link" @click="p.open('splitBatch',selectedBatch)">拆分所选批次</button><button v-if="chosenPlan?.fixed&&w.can('plan_write')" class="uv-link" @click="p.open('unlockPlan',chosenPlan)">说明原因并解锁</button><button v-if="chosenPlan&&w.can('plan_write')" class="uv-link" @click="p.open('cancelPlan',chosenPlan)">撤销所选计划</button><button v-if="w.pagination.tasks?.has_more" class="uv-link" @click="w.load(['tasks'],true)">加载更多任务</button></div>
<div class="uv-plan-tools"><button v-if="chosenPlan&&w.can('production_write')&&!w.items('executions').some(x=>x.schedule_id===chosenPlan!.id)" class="uv-button" @click="p.open('startExecution',chosenPlan)">登记所选批次开工</button></div>
<UvTable v-if="w.items('executions').length" :rows="w.items('executions').map(x=>({...x,task:taskName(x),start:displayTime(x.started_at),end:displayTime(x.ended_at)}))" :columns="[{key:'task',label:'实际执行任务'},{key:'batch_id',label:'实体批次'},{key:'start',label:'实际开工'},{key:'end',label:'实际完工'}]"><template #actions="{row}"><button v-if="!row.ended_at&&w.can('production_write')" class="uv-link" @click="p.open('finishExecution',row)">登记完工</button></template></UvTable><CollectionFooter v-if="w.items('executions').length" name="executions"/>
<div v-if="suggestions.length" class="uv-plan-preview"><h3>可用机台建议</h3><div v-for="item in suggestions" :key="String(item.machine_id)" class="uv-list-row"><div><strong>{{str(w.items('machines').find(x=>x.id===item.machine_id),'code')}}</strong><small>{{displayTime(item.start_at)}} — {{displayTime(item.end_at)}} · {{item.reason}}{{num(item,'delay_seconds')>0?' · 存在交期风险':''}}</small></div><button class="uv-button small" :disabled="!item.compatible||working" @click="useSuggestion(item)">采用并预览</button></div></div>
<div v-if="proposed" class="uv-plan-preview" :class="{conflict:!proposed.can_commit}" aria-live="polite"><h3><component :is="proposed.can_commit?Check:ShieldAlert" :size="19"/>{{proposed.can_commit?'资源校验通过，等待确认':'排程冲突，需要调整'}}</h3><ul v-if="!proposed.can_commit"><li v-for="(conflict,index) in (proposed.conflicts as {reasons:string[]}[])" :key="index">{{conflict.reasons.join('；')}}</li></ul><p>{{str(proposed,'rationale')}}</p><p v-for="warning in (proposed.warnings as string[]??[])" :key="warning" class="uv-notice">{{warning}}</p><p v-for="change in entities(proposed.changes)" :key="String(change.batch_id)">原计划：{{displayTime(change.previous_start_at)}} — {{displayTime(change.previous_end_at)}}；交期：{{displayTime(change.due_at)}}；{{num(change,'delay_seconds')>0?`预计延迟 ${Math.ceil(num(change,'delay_seconds')/60)} 分钟`:'未超过交期'}}</p><div class="uv-heading-actions"><button class="uv-button" :disabled="working||uncertain" @click="clearPreview"><X :size="15"/>取消预览</button><button v-if="proposed.can_commit" class="uv-button primary" :disabled="working" @click="commit">{{working?'提交中…':uncertain?'重试同一操作':'确认排程'}}</button></div></div>
</section>
<section v-else class="uv-section uv-page-section"><UvTable v-if="tab==='tasks'" :rows="w.items('tasks')" :columns="[{key:'code',label:'任务编号'},{key:'product_snapshot',label:'产品'},{key:'quantity',label:'目标 pcs'},{key:'status',label:'状态',state:true}]" selectable @select="w.selectedTaskId.value=$event.id"><template #actions="{row}"><button v-if="!row.parent_task_id&&w.can('plan_write')&&((w.can('cost_write')&&!row.cost_price_snapshot)||(w.can('payroll_write')&&!row.payroll_policy_snapshot))" class="uv-link" @click.stop="p.open('completeAccounting',row)">补齐核算</button><button v-if="['ready','planned'].includes(String(row.status))&&w.can('plan_write')" class="uv-link" @click.stop="p.open(row.parent_task_id?'cancelRework':'cancelTask',row)">取消未开工任务</button></template></UvTable><UvTable v-else :rows="w.items('demands')" :columns="[{key:'code',label:'需求编号'},{key:'product_snapshot',label:'产品'},{key:'quantity',label:'需求 pcs'},{key:'allocated',label:'已分配 pcs'},{key:'cancelled',label:'已取消 pcs'},{key:'due_at',label:'交期'}]"><template #actions="{row}"><button v-if="num(row,'quantity')>num(row,'allocated')+num(row,'cancelled')&&w.can('plan_write')" class="uv-link" @click="p.open('cancelDemand',row)">取消未分配数量</button></template></UvTable><CollectionFooter :name="tab"/></section>
<UvActionDialog :action="p.action.value" :target="p.target.value" :preset="p.preset.value" @close="p.action.value=null" @saved="reload"/>
</template>
