<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { CalendarDays, Plus, RefreshCw, ShieldAlert, X, Check } from '@lucide/vue'
import { createRandomUuid } from '@/lib/randomUuid'
import { displayTime, label, num, str, today, utcInput, type Entity } from '../contracts'
import { useUvPage } from '../usePage'
import { UvError } from '../workspace'
import UvTable from '../components/UvTable.vue'
import UvActionDialog from '../components/UvActionDialog.vue'
import CollectionFooter from '../components/CollectionFooter.vue'
const p=useUvPage(()=>['demands','tasks','machines','schedule']),w=p.w,tab=ref('timeline'),start=ref(today()),days=ref(1),mobileList=ref(false)
const form=reactive({task_id:'',machine_id:'',start_at:today()+'T08:00',end_at:today()+'T09:00',fixed:false})
const proposed=ref<Entity|null>(null),error=ref(''),working=ref(false),uncertain=ref(false)
let operationId=createRandomUuid(),body:Record<string,unknown>|null=null,dragTask=''
const scrollTop=ref(0),rowHeight=100
const firstMachine=computed(()=>Math.max(0,Math.floor((scrollTop.value-48)/rowHeight)-3))
const visibleMachines=computed(()=>w.items('machines').slice(firstMachine.value,firstMachine.value+16))
const windowStart=computed(()=>new Date(start.value+'T00:00:00+08:00').valueOf()),windowEnd=computed(()=>windowStart.value+days.value*86400000)
const ticks=computed(()=>Array.from({length:days.value*4+1},(_,index)=>index*6))
const blocks=computed(()=>w.items('schedule').filter(row=>row.status!=='cancelled'&&new Date(String(row.start_at)).valueOf()<windowEnd.value&&new Date(String(row.end_at)).valueOf()>windowStart.value))
const taskName=(id:unknown)=>str(w.items('tasks').find(row=>row.id===id),'code',String(id))
function blockStyle(row:Entity){const a=Math.max(windowStart.value,new Date(String(row.start_at)).valueOf()),b=Math.min(windowEnd.value,new Date(String(row.end_at)).valueOf());return {left:((a-windowStart.value)/(windowEnd.value-windowStart.value)*100)+'%',width:Math.max(.4,(b-a)/(windowEnd.value-windowStart.value)*100)+'%'}}
function choose(row:Entity){if(working.value||uncertain.value)return;form.task_id=String(row.task_id);form.machine_id=String(row.machine_id);form.start_at=local(row.start_at);form.end_at=local(row.end_at);form.fixed=!!row.fixed;proposed.value=null}
function local(value:unknown){return new Date(new Date(String(value)).valueOf()+8*3600000).toISOString().slice(0,16)}
function dropped(event:DragEvent,machine:Entity){if(working.value||uncertain.value||!dragTask)return;const bounds=(event.currentTarget as HTMLElement).getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-bounds.left)/bounds.width)),time=Math.round((windowStart.value+ratio*days.value*86400000)/900000)*900000;form.task_id=dragTask;form.machine_id=machine.id;form.start_at=local(new Date(time).toISOString());form.end_at=local(new Date(time+3600000).toISOString());proposed.value=null;void preview()}
async function preview(){error.value='';working.value=true;proposed.value=null;const task=w.items('tasks').find(x=>x.id===form.task_id),machine=w.items('machines').find(x=>x.id===form.machine_id),old=w.items('schedule').find(x=>x.task_id===form.task_id);try{if(!task||!machine)throw new Error('请先选择任务与机台');operationId=createRandomUuid();body={blocks:[{...form,start_at:utcInput(form.start_at),end_at:utcInput(form.end_at),task_version:task.version,machine_version:machine.version,block_version:old?.version??0}]};const result=await w.request<Entity>('schedule/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({factory_id:'huakang-a',operation_id:operationId,expected_version:0,...body})});proposed.value=result.data}catch(cause){error.value=w.explain(cause)}finally{working.value=false}}
async function commit(){if(!body)return;working.value=true;error.value='';try{await w.command('schedule/commit',body,operationId);proposed.value=null;uncertain.value=false;await p.reload()}catch(cause){error.value=w.explain(cause);uncertain.value=!(cause instanceof UvError)||cause.status>=500;if(!uncertain.value){proposed.value=null;await p.reload()}}finally{working.value=false}}
</script>
<template><div class="uv-page-heading"><div><span class="uv-eyebrow">PLAN WITH CONFIDENCE</span><h2>任务与排程</h2><p>冻结任务版本，预览资源冲突，再确认计划。</p></div><div class="uv-heading-actions"><button class="uv-button" @click="p.reload"><RefreshCw :size="16"/>刷新</button><button class="uv-button" :disabled="!w.can('plan_write')" @click="p.open('demand')"><Plus :size="16"/>新建需求</button><button class="uv-button primary" :disabled="!w.can('plan_write')" @click="p.open('task')"><Plus :size="16"/>新建任务</button></div></div>
<p v-if="p.error.value" class="uv-error" role="alert">{{p.error.value}}</p><div class="uv-tabs" role="tablist" aria-label="计划视图"><button v-for="[key,title] in [['timeline','资源时间轴'],['tasks','任务清单'],['demands','生产需求']]" :key="key" role="tab" :aria-selected="tab===key" @click="tab=key!">{{title}}</button></div>
<section v-if="tab==='timeline'" class="uv-section uv-page-section"><div class="uv-section-heading"><h3><CalendarDays :size="18"/>机台与治具资源</h3><div class="uv-filterbar"><label>起始日期<input v-model="start" type="date"/></label><label>视野<select v-model.number="days"><option :value="1">1 天</option><option :value="3">3 天</option></select></label><button class="uv-button small" @click="mobileList=!mobileList">{{mobileList?'时间轴':'列表视图'}}</button></div></div>
<div v-if="!mobileList" class="uv-timeline-scroll" @scroll="scrollTop=($event.target as HTMLElement).scrollTop" tabindex="0" aria-label="资源时间轴，可横向滚动；也可使用下方表单排程"><div class="uv-timeline" :style="{minWidth:days*800+'px'}"><div class="uv-timeline-header"><span>机台 / 计划时间</span><div><span v-for="hour in ticks" :key="hour" :style="{left:hour/(24*days)*100+'%'}">{{hour===24*days?'':hour%24===0?`${Math.floor(hour/24)+1} 日 00:00`:`${String(hour%24).padStart(2,'0')}:00`}}</span></div></div><div :style="{height:firstMachine*rowHeight+'px'}" aria-hidden="true"/><div v-for="machine in visibleMachines" :key="machine.id" class="uv-timeline-row"><strong>{{str(machine,'code')}}<small>{{str(machine,'name')}}</small></strong><div class="uv-timeline-track" @dragover.prevent @drop.prevent="dropped($event,machine)"><span v-for="hour in ticks" :key="hour" class="uv-timeline-gridline" :style="{left:hour/(24*days)*100+'%'}"/><button v-for="block in blocks.filter(row=>row.machine_id===machine.id)" :key="block.id" class="uv-plan-block" :class="{fixed:block.fixed,actual:w.items('tasks').find(x=>x.id===block.task_id)?.status==='in_progress'}" :style="blockStyle(block)" :title="`${taskName(block.task_id)} · ${displayTime(block.start_at)} — ${displayTime(block.end_at)}`" :draggable="!block.fixed&&w.can('plan_write')" @dragstart="dragTask=String(block.task_id)" @dragend="dragTask=''" @click="choose(block)">{{taskName(block.task_id)}}<small>{{block.fixed?'已固定':'计划'}} · {{displayTime(block.start_at)}}</small></button></div></div><div :style="{height:Math.max(0,w.items('machines').length-firstMachine-visibleMachines.length)*rowHeight+'px'}" aria-hidden="true"/><p v-if="!w.items('machines').length" class="uv-empty-inline">请先配置机台。</p></div></div>
<UvTable v-else :rows="blocks.map(x=>({...x,task:taskName(x.task_id),start:displayTime(x.start_at),end:displayTime(x.end_at)}))" :columns="[{key:'task',label:'任务'},{key:'start',label:'开始'},{key:'end',label:'结束'}]"><template #actions="{row}"><button class="uv-link" @click="choose(row)">调整计划</button></template></UvTable>
<div class="uv-timeline-legend"><span>实线：计划</span><span>斜纹：固定</span><span>深色：执行中</span><span>拖动后只生成预览，也可用下方表单操作。</span></div><CollectionFooter name="schedule"/>
<form class="uv-plan-form" @submit.prevent="preview"><fieldset :disabled="working||uncertain||!w.can('plan_write')"><label>待排任务<select v-model="form.task_id" required @change="proposed=null"><option value="">选择任务</option><option v-for="task in w.items('tasks')" :key="task.id" :value="task.id">{{str(task,'code')}} · {{label(task.status)}}</option></select></label><label>机台<select v-model="form.machine_id" required @change="proposed=null"><option value="">选择机台</option><option v-for="machine in w.items('machines')" :key="machine.id" :value="machine.id">{{str(machine,'code')}}</option></select></label><label>开始<input v-model="form.start_at" type="datetime-local" required @input="proposed=null"/></label><label>结束<input v-model="form.end_at" type="datetime-local" required @input="proposed=null"/></label><label class="uv-check-label"><input v-model="form.fixed" type="checkbox" @change="proposed=null"/>固定计划</label><button class="uv-button" :disabled="working">预览排程</button></fieldset></form>
<div v-if="proposed" class="uv-plan-preview" :class="{conflict:!proposed.can_commit}"><h3><component :is="proposed.can_commit?Check:ShieldAlert" :size="19"/>{{proposed.can_commit?'资源校验通过，等待确认':'排程冲突，需要调整'}}</h3><ul v-if="!proposed.can_commit"><li v-for="(conflict,index) in (proposed.conflicts as {task_id:string;reasons:string[]}[])" :key="index">{{taskName(conflict.task_id)}}：{{conflict.reasons.join('；')}}</li></ul><p>{{str(proposed,'rationale')}}</p><div class="uv-heading-actions"><button class="uv-button" :disabled="working||uncertain" @click="proposed=null;body=null"><X :size="15"/>取消预览</button><button v-if="proposed.can_commit" class="uv-button primary" :disabled="working" @click="commit">{{working?'提交中…':uncertain?'重试同一操作':'确认排程'}}</button></div></div><p v-if="error" class="uv-error" role="alert">{{error}}</p></section>
<section v-else class="uv-section uv-page-section"><UvTable v-if="tab==='tasks'" :rows="w.items('tasks')" :columns="[{key:'code',label:'任务编号'},{key:'product_snapshot',label:'产品'},{key:'quantity',label:'目标 pcs'},{key:'status',label:'状态',state:true}]" selectable @select="w.selectedTaskId.value=$event.id"><template #actions="{row}"><button v-if="!row.parent_task_id&&w.can('plan_write')&&((w.can('cost_write')&&!row.cost_price_snapshot)||(w.can('payroll_write')&&!row.payroll_policy_snapshot))" class="uv-link" @click.stop="p.open('completeAccounting',row)">补齐核算</button><button v-if="row.parent_task_id&&row.status==='ready'&&w.can('quality_write')" class="uv-link" @click.stop="p.open('cancelRework',row)">取消返工</button></template></UvTable><UvTable v-else :rows="w.items('demands')" :columns="[{key:'code',label:'需求编号'},{key:'product_snapshot',label:'产品'},{key:'quantity',label:'需求 pcs'},{key:'allocated',label:'已分配 pcs'},{key:'cancelled',label:'已取消 pcs'},{key:'due_at',label:'交期'}]"/><CollectionFooter :name="tab"/></section><UvActionDialog :action="p.action.value" :target="p.target.value" :preset="p.preset.value" @close="p.action.value=null" @saved="p.reload"/></template>
