<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { FileUp, KeyRound, Link2, Plus, Printer, RefreshCw, Shield, Wifi } from '@lucide/vue'
import { createRandomUuid } from '@/lib/randomUuid'
import { displayTime, label, object, str, type Entity } from '../contracts'
import { useUvPage } from '../usePage'
import { useUvWorkspace, UvError } from '../workspace'
import UvTable from '../components/UvTable.vue'
import UvActionDialog from '../components/UvActionDialog.vue'
import CollectionFooter from '../components/CollectionFooter.vue'
const w=useUvWorkspace(),p=useUvPage(()=>['machines','fixtures','products','process-versions','file-versions',...(w.can('agent_manage')?['agents','sources']:[]),...(w.can('audit_read')?['audit']:[])])
const tab=ref('masters'),master=ref('products'),uploadOpen=ref(false),file=ref<File|null>(null),processId=ref(''),role=ref('production'),uploading=ref(false),error=ref(''),uncertain=ref(false)
let operationId=createRandomUuid(),submitted:FormData|null=null
const catalogs:Record<string,{title:string;action:string;columns:{key:string;label:string}[]}>= {
  products:{title:'产品',action:'product',columns:[{key:'code',label:'产品编号'},{key:'name',label:'名称'},{key:'customer',label:'客户'}]},
  fixtures:{title:'治具',action:'fixture',columns:[{key:'code',label:'治具编号'},{key:'revision',label:'版本'},{key:'slots',label:'槽位'},{key:'width_mm',label:'宽 mm'},{key:'height_mm',label:'高 mm'}]},
  'process-versions':{title:'工艺',action:'process',columns:[{key:'name',label:'工艺'},{key:'revision',label:'版本'},{key:'pieces_per_board',label:'件 / 板'},{key:'cycle_seconds',label:'秒 / 板 / 遍'},{key:'passes',label:'遍数'},{key:'ink_family',label:'兼容墨材'}]},
  machines:{title:'机台',action:'machine',columns:[{key:'code',label:'编号'},{key:'name',label:'名称'},{key:'model',label:'型号'},{key:'capability_evidence',label:'能力依据'}]},
}
const selectedCatalog=computed(()=>catalogs[master.value]!)
async function upload(){if(!file.value||!processId.value)return;uploading.value=true;error.value='';try{if(!uncertain.value){submitted=new FormData();submitted.set('factory_id','huakang-a');submitted.set('operation_id',operationId);submitted.set('process_version_id',processId.value);submitted.set('role',role.value);submitted.set('file',file.value)}await w.request<Entity>('files',{method:'POST',body:submitted});uploadOpen.value=false;file.value=null;uncertain.value=false;operationId=createRandomUuid();await p.reload();w.notification.value='文件已保存，请核对文件版本并完成首件确认'}catch(cause){error.value=w.explain(cause);uncertain.value=!(cause instanceof UvError)||cause.status>=500;if(!uncertain.value)operationId=createRandomUuid()}finally{uploading.value=false}}
watch(w.contextVersion,()=>{file.value=null;submitted=null;uploadOpen.value=false})
</script>
<template><div class="uv-page-heading"><div><span class="uv-eyebrow">FOUNDATIONS</span><h2>基础设置</h2><p>把产品、工艺、文件与现场采集连接到同一条追溯链。</p></div><button class="uv-button" @click="p.reload"><RefreshCw :size="16"/>刷新</button></div><p v-if="p.error.value||error" class="uv-error" role="alert">{{p.error.value||error}}</p><div class="uv-tabs" role="tablist" aria-label="设置类别"><button v-for="[key,title] in [['masters','基础资料'],['files','文件与首件'],...(w.can('agent_manage')?[['agents','现场代理']]:[]),...(w.can('audit_read')?[['audit','操作审计']]:[])]" :key="key" role="tab" :aria-selected="tab===key" @click="tab=key!">{{title}}</button></div>
<section v-if="tab==='masters'" class="uv-section uv-page-section"><div class="uv-section-heading"><div class="uv-chip-group"><button v-for="(catalog,key) in catalogs" :key="key" class="uv-button small" :class="{primary:master===key}" @click="master=String(key)">{{catalog.title}}</button></div><button class="uv-button" :disabled="!w.can('master_write')" @click="p.open(selectedCatalog.action)"><Plus :size="16"/>新增{{selectedCatalog.title}}{{['fixtures','process-versions'].includes(master)?'版本':''}}</button></div><UvTable :rows="w.items(master)" :columns="selectedCatalog.columns"><template v-if="master==='machines'" #actions="{row}"><button class="uv-link" :disabled="!w.can('master_write')" @click="p.open('machineEdit',row,row)">编辑</button></template></UvTable><CollectionFooter :name="master"/><p class="uv-panel-body uv-muted">治具、工艺和已确认文件采用新版本；已有任务保留创建时的快照。</p></section>
<section v-else-if="tab==='files'" class="uv-section uv-page-section"><div class="uv-section-heading"><h3>文件版本与首件</h3><button class="uv-button primary" :disabled="!w.can('master_write')" @click="uploadOpen=!uploadOpen"><FileUp :size="16"/>上传文件</button></div><form v-if="uploadOpen" class="uv-panel-body uv-form-grid" @submit.prevent="upload"><fieldset class="uv-form-grid uv-form-wide" :disabled="uploading||uncertain"><label>关联工艺版本<select v-model="processId" required><option value="">选择工艺</option><option v-for="process in w.items('process-versions')" :key="process.id" :value="process.id">{{str(process,'name')}} · V{{process.revision}}</option></select></label><label>文件角色<select v-model="role"><option value="production">生产文件（只存储，不执行）</option><option value="preview">预览图（PNG / JPEG / WebP）</option></select></label><label class="uv-form-wide">文件（最大 32 MB）<input type="file" required :accept="role==='preview'?'.png,.jpg,.jpeg,.webp':'.png,.jpg,.jpeg,.webp,.pdf,.prn,.prnx,.prt,.rip'" @change="file=($event.target as HTMLInputElement).files?.[0]??null"/></label></fieldset><p v-if="uncertain" class="uv-notice uv-form-wide">结果不确定，重试会使用同一文件及操作编号。</p><button class="uv-button primary" :disabled="uploading">{{uploading?'上传中…':uncertain?'重试同一上传':'保存文件版本'}}</button></form><UvTable :rows="w.items('file-versions').map(x=>({...x,role_label:x.role==='production'?'生产文件':'预览文件',confirmed:x.confirmed_at?'已确认':'待确认'}))" :columns="[{key:'name',label:'文件名'},{key:'role_label',label:'角色'},{key:'sha256',label:'SHA-256'},{key:'confirmed',label:'首件状态'},{key:'first_article_evidence',label:'首件依据'}]"><template #actions="{row}"><a class="uv-link" :href="'/api/uv-operations/files/'+row.id+'/download?factory_id=huakang-a'" target="_blank" rel="noopener">{{row.role==='preview'?'查看':'下载'}}</a><button v-if="!row.confirmed_at&&row.role==='production'" class="uv-link" :disabled="!w.can('master_write')" @click="p.open('fileConfirm',row)">确认首件</button></template></UvTable><CollectionFooter name="file-versions"/></section>
<template v-else-if="tab==='agents'"><section class="uv-section uv-page-section"><div class="uv-section-heading"><h3><Wifi :size="18"/>现场代理接入</h3><span class="uv-badge">只读采集</span></div><ol class="uv-onboarding"><li><span>1</span><div><strong>安装与诊断</strong><p>在现场电脑运行已打包的 Windows 服务；确认日志目录、时区和计量单位。</p></div></li><li><span>2</span><div><strong>一次性配对</strong><p>创建代理身份，将 15 分钟有效配对码输入现场代理。</p><button class="uv-button small" @click="p.open('agent')"><KeyRound :size="15"/>创建配对码</button></div></li><li><span>3</span><div><strong>绑定主采集源</strong><p>将代理本地的来源 ID 绑定到机台。每台机只保留一个有效主源。</p><button class="uv-button small" @click="p.open('source')"><Link2 :size="15"/>绑定采集源</button></div></li></ol><div class="uv-inline-note"><Shield :size="18"/>不会向设备发送开始、暂停或取消打印命令。通用日志适配器需现场验证，模拟器始终标识为合成来源。</div></section>
<section class="uv-section"><div class="uv-section-heading"><h3>代理健康与身份</h3></div><article v-for="agent in w.items('agents')" :key="agent.id" class="uv-agent-card"><div><span class="uv-machine-icon"><Wifi :size="23"/></span><h3>{{str(agent,'name')}}</h3><span class="uv-badge" :data-state="agent.revoked?'offline':agent.last_seen_at&&Date.now()-Date.parse(String(agent.last_seen_at))<120000?'fresh':'stale'">{{agent.revoked?'已撤销':agent.last_seen_at&&Date.now()-Date.parse(String(agent.last_seen_at))<120000?'心跳正常':agent.last_seen_at?'心跳已过期':'等待配对 / 心跳'}}</span><button class="uv-link" :disabled="!!agent.revoked" @click="p.open('revoke',agent)">撤销凭据</button></div><dl class="uv-definition"><dt>最近心跳</dt><dd>{{displayTime(agent.last_seen_at)}}</dd><dt>待发送队列</dt><dd>{{object(agent.diagnostics).queue_count??'未知'}}</dd><dt>最早未确认（秒）</dt><dd>{{object(agent.diagnostics).oldest_age_seconds??'未知'}}</dd><dt>采集错误</dt><dd>{{object(agent.diagnostics).last_error_code??'未提供'}}</dd></dl></article><p v-if="!w.items('agents').length" class="uv-empty-inline">还没有现场代理，请从一次性配对开始。</p><CollectionFooter name="agents"/></section>
<section class="uv-section"><div class="uv-section-heading"><h3><Printer :size="18"/>采集源版本</h3></div><UvTable :rows="w.items('sources').map(x=>({...x,active:x.active_key?'当前主源':'历史版本',adapter:label(x.adapter_type)}))" :columns="[{key:'source_id',label:'来源 ID'},{key:'adapter',label:'适配器'},{key:'binding_version',label:'绑定版本'},{key:'active',label:'状态'},{key:'machine_id',label:'机台 ID'}]"><template #actions="{row}"><button v-if="row.active_key" class="uv-link" @click="p.open('unbind',row)">解除绑定</button></template></UvTable><CollectionFooter name="sources"/></section></template>
<section v-else class="uv-section uv-page-section"><UvTable :rows="w.items('audit')" :columns="[{key:'created_at',label:'时间'},{key:'actor_id',label:'操作人'},{key:'action',label:'操作'},{key:'operation_id',label:'操作编号'},{key:'reason',label:'理由'}]"/><CollectionFooter name="audit"/></section><UvActionDialog :action="p.action.value" :target="p.target.value" :preset="p.preset.value" @close="p.action.value=null" @saved="p.reload"/></template>
