<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useRoute, onBeforeRouteLeave } from 'vue-router'
import { Plus, ClipboardCheck, RefreshCw, Check, Trash2, X } from '@lucide/vue'
import { createRandomUuid } from '@/lib/randomUuid'
import { displayTime, label, num, object, str, type Entity } from '../contracts'
import { useUvPage } from '../usePage'
import { UvError } from '../workspace'
import { pasteQuantities, quantityError, quantityFields, type Quantities } from '../reconciliation'
import UvActionDialog from '../components/UvActionDialog.vue'
import RunMatchDialog from '../components/RunMatchDialog.vue'
import UvTable from '../components/UvTable.vue'
import CollectionFooter from '../components/CollectionFooter.vue'
const p=useUvPage(()=>['shifts','tasks','batches','production','participations','quality','handovers','runs']),w=p.w,route=useRoute()
const shiftId=ref(String(route.query.shift??'')),tab=ref(['reconcile','quality','handovers','runs'].includes(String(route.query.tab))?String(route.query.tab):'reconcile'),gaps=ref<Entity|null>(null),matching=ref<Entity|null>(null),paste=ref(''),pasteOpen=ref(false),saving=ref(false),globalError=ref('')
interface Draft extends Quantities {key:string;task_id:string;batch_id:string;evidence:string;state:'draft'|'saving'|'saved'|'uncertain'|'error';error:string;operationId:string;submitted:Record<string,unknown>|null}
const drafts=reactive<Draft[]>([])
const selected=computed(()=>w.items('shifts').find(x=>x.id===shiftId.value)),preview=computed(()=>paste.value.trim()?pasteQuantities(paste.value):[])
const currentEntries=computed(()=>w.items('production').filter(x=>x.shift_id===shiftId.value))
const totals=computed(()=>object(gaps.value?.totals))
const gapLabels:Record<string,string>={missing_participation:'报产缺参与工时',pending_quality:'待检批次',unmatched_runs:'未匹配运行',running_runs:'未结束设备运行',running_executions:'跨班在制执行',incomplete_batches:'未完加工批次',unreported_plans:'计划缺报产',participation_without_output:'参与工时缺报产',outstanding_handovers:'未结清交接'}
const quantityLabels={processed:'加工',good:'良品',rework:'返工',scrap:'报废',pending:'待检'}
watch(()=>w.items('shifts'),rows=>{if(!shiftId.value&&rows.length)shiftId.value=rows.find(row=>row.status==='open')?.id??rows[0]!.id})
watch(()=>[shiftId.value,w.meta.value?.view_revision],async()=>{const id=shiftId.value;try {if(id){const value=(await w.request<Entity>('shifts/'+id+'/gaps')).data;if(id===shiftId.value)gaps.value=value}}catch(cause){globalError.value=w.explain(cause)}},{immediate:true})
const dirty=computed(()=>drafts.some(x=>x.state!=='saved'&&(x.task_id||x.processed)))
onBeforeRouteLeave(()=>!dirty.value||window.confirm('核数草稿尚未全部确认。离开将丢弃这些未提交输入，是否继续？'))
watch(w.contextVersion,()=>{drafts.splice(0);gaps.value=null;paste.value='';matching.value=null})
function add(values?:Quantities){drafts.push({key:createRandomUuid(),task_id:String(route.query.task??''),batch_id:'',processed:0,good:0,rework:0,scrap:0,pending:0,...values,evidence:'',state:'draft',error:'',operationId:createRandomUuid(),submitted:null})}
function batches(row:Draft){const task=w.items('tasks').find(x=>x.id===row.task_id);return w.items('batches').filter(x=>x.task_id===(task?.parent_task_id||row.task_id))}
function validation(row:Draft){return !selected.value?'请选择班次':selected.value.status!=='open'?'当前班次已关闭':!row.task_id||!row.batch_id?'请选择任务和实体批次':quantityError(row)||(!row.evidence.trim()?'请填写核数依据':'')}
async function save(row:Draft){if(row.state==='saved'||saving.value)return;const problem=validation(row);if(problem){row.error=problem;return}const batch=w.items('batches').find(x=>x.id===row.batch_id),task=w.items('tasks').find(x=>x.id===row.task_id);if(!batch||!task)return;row.error='';const retry=row.state==='uncertain';row.state='saving';try{if(!retry)row.submitted={shift_id:shiftId.value,task_id:row.task_id,batch_id:row.batch_id,pass_index:num(batch,'pass_index'),source_bucket:task.parent_task_id?'rework':'remaining',expected_version:batch.version,evidence:row.evidence,...Object.fromEntries(quantityFields.map(key=>[key,row[key]]))};await w.command('production/confirm',row.submitted!,row.operationId);row.state='saved';await w.load(['batches','production','tasks'])}catch(cause){row.error=w.explain(cause);row.state=!(cause instanceof UvError)||cause.status>=500?'uncertain':'error';if(row.state==='error')row.operationId=createRandomUuid()}}
async function saveValid(){for(const row of drafts){if(row.state!=='saved'&&row.state!=='saving'&&!validation(row))await save(row)}}
function applyPaste(){for(const item of preview.value){if(!item.error)add(item.values)}pasteOpen.value=false;paste.value=''}
function enter(event:KeyboardEvent){const target=event.target as HTMLElement;if(target.tagName!=='INPUT')return;event.preventDefault();const fields=Array.from(target.closest('tbody')?.querySelectorAll<HTMLInputElement>('input:not(:disabled),select:not(:disabled),button[data-confirm]:not(:disabled)')??[]),index=fields.indexOf(target as HTMLInputElement);fields[index+1]?.focus()}
function taskName(id:unknown){return str(w.items('tasks').find(x=>x.id===id),'code',String(id))}
</script>
<template><div class="uv-page-heading"><div><span class="uv-eyebrow">SHIFT & QUALITY</span><h2>班次与品质</h2><p>加工数量逐行守恒，品质处置和交接全程留据。</p></div><div class="uv-heading-actions"><button class="uv-button" @click="p.reload"><RefreshCw :size="16"/>刷新</button><button class="uv-button primary" :disabled="!w.can('shift_write')" @click="p.open('shift')"><Plus :size="16"/>新建班次</button></div></div>
<div class="uv-filterbar"><label>当前班次<select v-model="shiftId" :disabled="dirty"><option value="">请选择班次</option><option v-for="shift in w.items('shifts')" :key="shift.id" :value="shift.id">{{str(shift,'business_date')}} · {{str(shift,'name')}} · {{label(shift.status)}}</option></select></label><span v-if="selected" class="uv-muted">{{displayTime(selected.start_at)}} — {{displayTime(selected.end_at)}}</span><button v-if="selected" class="uv-button small" :disabled="!w.can('shift_write')||dirty" @click="p.open(selected.status==='closed'?'reopenShift':'closeShift',selected)">{{selected.status==='closed'?'重开班次':'核对并结班'}}</button></div><p v-if="dirty" class="uv-notice">本班有未确认草稿，班次选择已锁定。确认或删除草稿后可切换。</p>
<p v-if="p.error.value||globalError" class="uv-error" role="alert">{{p.error.value||globalError}}</p><div class="uv-summary-strip"><div><small>本班累计加工（含返工）</small><strong>{{totals.processed??'—'}} <small>pcs</small></strong></div><div><small>确认合格（按工序）</small><strong>{{totals.good??'—'}} <small>pcs</small></strong></div><div><small>报废</small><strong>{{totals.scrap??'—'}} <small>pcs</small></strong></div><div><small>待检录入</small><strong>{{totals.pending??'—'}} <small>pcs</small></strong></div></div>
<div v-if="gaps" class="uv-panel-body" aria-label="结班待核对事项"><span v-for="(title,key) in gapLabels" :key="key" class="uv-badge">{{title}} {{Array.isArray(gaps[key])?(gaps[key] as unknown[]).length:0}}</span></div><div class="uv-tabs" role="tablist" aria-label="班次业务"><button v-for="[key,title] in [['reconcile','班次核数'],['quality','品质与返工'],['handovers','下工序交接'],['runs','运行匹配'],['participants','参与工时']]" :key="key" role="tab" :aria-selected="tab===key" @click="tab=key!">{{title}}</button></div>
<section v-if="tab==='reconcile'" class="uv-section uv-page-section"><div class="uv-section-heading"><h3><ClipboardCheck :size="18"/>核数工作表</h3><div class="uv-heading-actions"><button class="uv-button small" :disabled="!w.can('production_write')||selected?.status!=='open'" @click="pasteOpen=!pasteOpen">粘贴数量</button><button class="uv-button small" :disabled="!w.can('production_write')||selected?.status!=='open'" @click="add()"><Plus :size="15"/>添加核数行</button><button class="uv-button primary small" :disabled="!drafts.some(x=>x.state!=='saved'&&!validation(x))||drafts.some(x=>x.state==='saving')" @click="saveValid">确认有效行</button></div></div>
<div v-if="pasteOpen" class="uv-panel-body"><label class="uv-block-label">粘贴加工 / 良品 / 返工 / 报废 / 待检五列数量（Tab 或逗号分隔）<textarea v-model="paste" rows="4"/></label><div v-if="preview.length" class="uv-paste-preview"><p v-for="(item,index) in preview" :key="index" :class="{'uv-field-error':item.error}">第 {{index+1}} 行：{{item.error||`守恒通过 · 加工 ${item.values.processed} pcs`}}</p></div><button class="uv-button" :disabled="!preview.some(x=>!x.error)" @click="applyPaste">将有效行加入草稿</button><small>只加入预览通过的行；任务、批次和核数依据仍需填写。最多 200 行。</small></div>
<div class="uv-table-scroll" tabindex="0" aria-label="核数输入表格，可横向滚动"><table class="uv-table uv-reconcile-table"><thead><tr><th>任务 / 批次</th><th v-for="title in ['加工','良品','返工','报废','待检']" :key="title">{{title}} pcs</th><th>核数依据</th><th>确认</th></tr></thead><tbody @keydown.enter="enter"><tr v-for="row in drafts" :key="row.key" :data-row-state="row.state"><td><select v-model="row.task_id" aria-label="核数任务" :disabled="['saving','saved','uncertain'].includes(row.state)" @change="row.batch_id='' "><option value="">选择任务</option><option v-for="task in w.items('tasks')" :key="task.id" :value="task.id">{{str(task,'code')}}</option></select><select v-model="row.batch_id" aria-label="实体批次" :disabled="['saving','saved','uncertain'].includes(row.state)"><option value="">选择批次</option><option v-for="batch in batches(row)" :key="batch.id" :value="batch.id">{{batch.id.slice(0,8)}} · 第 {{batch.pass_index}} 遍 · 余 {{batch.remaining}} / 返 {{batch.rework}}</option></select></td><td v-for="key in quantityFields" :key="key"><input v-model.number="row[key]" :aria-label="quantityLabels[key]+'数量'" type="number" min="0" step="1" :disabled="['saving','saved','uncertain'].includes(row.state)"/></td><td><input v-model="row.evidence" aria-label="核数依据" class="uv-evidence-input" :disabled="['saving','saved','uncertain'].includes(row.state)"/></td><td><div class="uv-row-actions"><span v-if="row.state==='saved'" class="uv-badge" data-state="completed"><Check :size="14"/>已确认</span><button v-else data-confirm class="uv-button small" :disabled="row.state==='saving'||!w.can('production_write')" @click="save(row)">{{row.state==='saving'?'保存中…':row.state==='uncertain'?'原操作重试':'确认'}}</button><button v-if="!['saving','uncertain'].includes(row.state)" class="uv-icon-button" aria-label="移除草稿行" @click="drafts.splice(drafts.indexOf(row),1)"><Trash2 :size="15"/></button></div><small v-if="row.error" class="uv-field-error" role="alert">{{row.error}}</small><small v-else-if="row.processed&&quantityError(row)" class="uv-field-error">{{quantityError(row)}}</small></td></tr><tr v-if="!drafts.length"><td colspan="8" class="uv-empty-inline">选择进行中的班次后，添加核数行。支持 Tab / Enter 在输入项之间移动。</td></tr></tbody></table></div>
<div class="uv-section-heading"><h3>已确认记录</h3><span class="uv-muted">只能冲销，不能直接修改</span></div><UvTable :rows="currentEntries.map(row=>({...row,task:taskName(row.task_id)}))" :columns="[{key:'task',label:'任务'},{key:'pass_index',label:'遍次'},{key:'processed',label:'加工 pcs'},{key:'good',label:'合格 pcs'},{key:'rework',label:'返工 pcs'},{key:'scrap',label:'报废 pcs'},{key:'pending',label:'待检 pcs'},{key:'direction',label:'凭证方向'}]"><template #actions="{row}"><button v-if="row.direction===1" class="uv-link" :disabled="!w.can('production_write')" @click="p.open('reverse',row)">冲销</button></template></UvTable><p class="uv-panel-body uv-muted">当前班次已加载 {{currentEntries.length}} 条；以下加载进度覆盖全部班次。</p><CollectionFooter name="production"/>
</section>
<section v-else-if="tab==='quality'" class="uv-section uv-page-section"><div class="uv-section-heading"><h3>实体品质分桶</h3><div class="uv-heading-actions"><button class="uv-button" :disabled="!w.can('quality_write')" @click="p.open('quality',null,{shift_id:shiftId})">处置待检</button><button class="uv-button" :disabled="!w.can('quality_write')||!w.can('plan_write')" @click="p.open('rework')">建立返工任务</button></div></div><UvTable :rows="w.items('batches').map(row=>({...row,task:taskName(row.task_id)}))" :columns="[{key:'task',label:'任务'},{key:'quantity',label:'实体 pcs'},{key:'pass_index',label:'当前遍次'},{key:'remaining',label:'待加工'},{key:'intermediate',label:'中间合格'},{key:'good',label:'最终良品'},{key:'rework',label:'返工'},{key:'scrap',label:'报废'},{key:'pending',label:'待检'}]"><template #actions="{row}"><button v-if="row.remaining===row.quantity&&row.pass_index===1" class="uv-link" :disabled="!w.can('plan_write')" @click="p.open('splitBatch',row)">拆批</button><button v-if="row.remaining===row.quantity&&row.pass_index===1" class="uv-link" :disabled="!w.can('plan_write')" @click="p.open('mergeBatch',row)">合批</button><button class="uv-link" :disabled="!w.can('production_write')" @click="p.open('advance',row)">进入下一遍</button></template></UvTable><CollectionFooter name="batches"/><div class="uv-section-heading"><h3>品质处置凭证</h3></div><UvTable :rows="w.items('quality')" :columns="[{key:'business_date',label:'业务日期'},{key:'batch_id',label:'批次'},{key:'disposition',label:'结论'},{key:'quantity',label:'件数'},{key:'evidence',label:'依据'}]"><template #actions="{row}"><button v-if="w.can('quality_write')" class="uv-link" @click="p.open('reverseQuality',row)">撤销纠错</button></template></UvTable><CollectionFooter name="quality"/></section>
<section v-else-if="tab==='handovers'" class="uv-section uv-page-section"><div class="uv-section-heading"><h3>良品交接</h3><button class="uv-button primary" :disabled="!w.can('handover_write')" @click="p.open('handover')">发起交接</button></div><UvTable :rows="w.items('handovers')" :columns="[{key:'target',label:'收方 / 下工序'},{key:'quantity',label:'交接 pcs'},{key:'received',label:'已签收'},{key:'rejected',label:'已拒收'},{key:'returned',label:'已退回'},{key:'status',label:'状态',state:true}]"><template #actions="{row}"><button v-for="[key,title] in [['receive','签收'],['reject','拒收'],['return','退回'],['cancelHandover','取消预留']]" :key="key" class="uv-link" :disabled="!w.can('handover_write')" @click="p.open(key!,row)">{{title}}</button></template></UvTable><CollectionFooter name="handovers"/></section>
<section v-else-if="tab==='runs'" class="uv-section uv-page-section"><div class="uv-section-heading"><h3>原始运行证据</h3><span class="uv-muted">运行完成不等于产量确认</span></div><UvTable :rows="w.items('runs')" :columns="[{key:'native_job_id',label:'原生作业'},{key:'state',label:'状态',state:true},{key:'raw_count',label:'原始计数'},{key:'count_unit',label:'计量单位'},{key:'counter_mode',label:'计数语义'},{key:'started_at',label:'开始时间'}]"><template #actions="{row}"><span v-if="row.match_evidence" class="uv-badge" data-state="completed">已核对归属</span><button v-else class="uv-link" :disabled="!w.can('production_write')" @click="matching=row">核对归属</button></template></UvTable><CollectionFooter name="runs"/></section>
<section v-else class="uv-section uv-page-section"><div class="uv-section-heading"><h3>参与工时</h3><button class="uv-button primary" :disabled="!w.can('shift_write')" @click="p.open('participation',null,{shift_id:shiftId})">登记参与</button></div><UvTable :rows="w.items('participations').filter(row=>row.shift_id===shiftId).map(row=>({...row,task:taskName(row.task_id)}))" :columns="[{key:'employee_name',label:'员工'},{key:'task',label:'任务'},{key:'start_at',label:'开始'},{key:'end_at',label:'结束'},{key:'role_coefficient',label:'角色系数'}]"><template #actions="{row}"><button v-if="w.can('shift_write')" class="uv-link" @click="p.open('reverseParticipation',row)">撤销纠错</button></template></UvTable><CollectionFooter name="participations"/></section>
<div v-if="gaps" class="uv-inline-note">结班待核对：参与记录 {{(gaps.missing_participation as unknown[]).length}} 项 · 待检批次 {{(gaps.pending_quality as unknown[]).length}} 项 · 未匹配运行 {{(gaps.unmatched_runs as unknown[]).length}} 项</div>
<UvActionDialog :action="p.action.value" :target="p.target.value" :preset="p.preset.value" @close="p.action.value=null" @saved="p.reload"/><RunMatchDialog :run="matching" @close="matching=null" @saved="matching=null;p.reload()"/>
</template>
